### ISSUE TITLE
Clarify Browser Build Options

### ISSUE THREAD

**Issue by EisenbergEffect** [zloirock/core-js#10]
This project looks amazing :smile: After skimming the document, it wasn't clear to me what the difference is between the browser "default" build and the "shim only" build. Does the default include the dictionary extensions but shim only includes standards shims? Can you confirm?

**Comment by zloirock** [comment]
@EisenbergEffect "shim only" builds contains only standard shims - ES5 (only browser builds - required for IE8-), ES6, ES7, `set(Timeout|Interval)` (only browser builds - required for IE9-), `setImmediate`, array generics, console cap (only browser builds). "default" build contains all features.

**Comment by EisenbergEffect** [comment]
Ok. That's what I thought but wanted to be sure. I'll be trying out replacing es6-shim with the shim only build of core-js today in combination with updating my 6to5 build. So, we'll see how it all goes. Looks like an excellent piece of work.

**Comment by zloirock** [comment]
Thanks :smile:
