### ISSUE TITLE
core-js-compat@3.18.3 updated to 3.19.0 Object is not a function

### ISSUE THREAD

**Issue by shanruo** [zloirock/core-js#1002]
Through investigation, it was found that it was an error after editing and building after the latest change and upgrade. Latest submission([WIP] Changes from October 2021 TC39 meeting
#1001)：https://github.com/zloirock/core-js/pull/1001/files
The screenshot of the error message is as follows:
![issue](https://user-images.githubusercontent.com/7478617/139671332-308dc0c2-c185-4064-821d-e6e0d832cf2c.png)

**Comment by shanruo** [comment]
The core changes are here：https://github.com/zloirock/core-js/commit/6123ff17d26eddf3ba8d456feb97decab3a9e9f6
core-js-pure@3.18.3->@3.19.0,But this package depends on core-js-compat,The reproducible example is not easy to show, the scene is applied in a small program, and the downstream relies on this package,No error will be reported when running the previous version, and an error will be reported in the new version.Now I took the lock package to temporarily solve the problem in the application.
![issue2](https://user-images.githubusercontent.com/7478617/139679862-4519a8c7-a023-4de3-a0b7-b39650ff865c.png)

**Comment by zloirock** [comment]
So what about the environment?

**Comment by zloirock** [comment]
All changes in `core-js-compat` `3.18.3` -> `3.19.0` are in adding compat data mapping for NodeJS 17, Electron 16, Opera Android 65, so it CAN'T be related.

**Comment by zloirock** [comment]
Without a reproducible example, I can't say more, so I'm waiting for it.

**Comment by shanruo** [comment]
I have found the cause of the problem. This version upgrade triggered my application environment bug.The main point of change is "var Object = global.Object",There is no Object in my application environment window，So I need to polyfill window.Object = Object，thanks，that's all. ღ( ´･ᴗ･` )

**Comment by shanruo** [comment]
Add a screenshot
![issue3](https://user-images.githubusercontent.com/7478617/139822878-5ab418ba-67af-4b0c-aefc-8779c66f242f.png)
