### ISSUE TITLE
PromiseRejectionEvent does not exist in older browsers

### ISSUE THREAD

**Issue by chenyulun** [zloirock/core-js#1005]
Download the source code, after the compilation:
copy `packages/core-js-bundle/minified.js` to `tests/compat`
`tests/compat/index.html`
```diff
+  <script src='./minified.js'></script>
<script src='./tests.js'></script>
<script src='./browsers-runner.js'></script>
```
```shell
cd tests/compat
http-server -c-0
```
Safari in ios9.3 accesses static servers
```js
var PROMISES_SUPPORT = function () {
  var promise = new Promise(function (resolve) { resolve(1); });
  var empty = function () { /* empty */ };
  var FakePromise = (promise.constructor = {})[Symbol.species] = function (exec) {
    exec(empty, empty);
  };

  return promise.then(empty) instanceof FakePromise
    && V8_VERSION !== 66
    && (IS_NODE || typeof PromiseRejectionEvent == 'function'); // PromiseRejectionEvent does not exist in older browsers
};
```
PromiseRejectionEvent does not exist in older browsers

![image](https://user-images.githubusercontent.com/15979948/140268027-9e9aae48-cbe6-48ba-a349-eeb014a2ad00.png)

**Comment by zloirock** [comment]
Yes, it's expected. `core-js` polyfill `Promise` rejection tracking.

`core-js` does not polyfill `PromiseRejectionEvent`, so compat data tests not passes even after loading `core-js`, but it's not `core-js` feature detection - it's simplified version of it. `core-js` feature detection contains this line:
```js
var GLOBAL_CORE_JS_PROMISE = PROMISE_CONSTRUCTOR_SOURCE !== String(PromiseConstructor);
```
and does not replace `core-js` `Promise` implementation if it's not required, even without `PromiseRejectionEvent`.

**Comment by chenyulun** [comment]
When will this case be fixed？

**Comment by chenyulun** [comment]
by the way: Browsers that support 'string.at' can't seem to change it anymore, can they?
![image](https://user-images.githubusercontent.com/15979948/140275339-124852be-2d5e-4c83-87f1-aec36c25825e.png)
- UA: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4678.0 Safari/537.36'

**Comment by zloirock** [comment]
What do you mean? It works as expected, see above.

**Comment by zloirock** [comment]
It should not be fixed, it works as expected, see above.

> by the way

Old `esnext.string.at` proposal is incompatible with `es.string.at-alternative`. When you load a full `core-js` bundle with stage-0 proposals, you overwrite the native `String.prototype.at`. So this test is not passed. Old `esnext.string.at` will be removed only in `core-js@4`. Usage of stage-0 proposals is not recommended and is dangerous.

**Comment by chenyulun** [comment]
It is suggested to add other colors in the table to indicate partial support，
The function does not only return true/false, it can return supported levels such as 1, 2, and 3

**Comment by zloirock** [comment]
At this moment, it's used only for checking / generating `core-js-compat` data. However, in case if in the future it will be extended for something else - for example, generation a table where will be shown the requirement of modules for different engines, something like that makes sense. Thanks for the proposal.
