### ISSUE TITLE
Uint8Array performance IE10

### ISSUE THREAD

**Issue by olegmanby** [zloirock/core-js#1014]
After migration to directly using core-js@3 I noticed that Uint8Array performance in the IE10 very low. IE11 works well.

`var createTypedArrayConstructor = __webpack_require__("./node_modules/core-js/internals/typed-array-constructor.js");

// `Uint8Array` constructor
// https://tc39.es/ecma262/#sec-typedarray-objects
createTypedArrayConstructor('Uint8', function (init) {
  return function Uint8Array(data, byteOffset, length) {
    return init(this, data, byteOffset, length);
  };
});`

Previous version from @babel/polyfill works well...

`__webpack_require__("./node_modules/@babel/polyfill/node_modules/core-js/modules/_typed-array.js")('Uint8', 1, function (init) {
  return function Uint8Array(data, byteOffset, length) {
    return init(this, data, byteOffset, length);
  };
});`

**Comment by zloirock** [comment]
Yes, it's expected. In IE11, `core-js` just fixed native typed arrays, but since IE10 contains not all types of typed arrays and not all cases of IE10 typed array problems can be fixed, `core-js` completely replaces typed arrays to polyfills. Slower but correct better than faster but buggy. If you don't need it, you can don't include `core-js` typed arrays polyfills and include only features required for you.

**Comment by olegmanby** [comment]
> Slower but correct better than faster but buggy.
But version of typed array core-js@2 works properly)

> If you don't need it, you can don't include core-js typed arrays polyfills and include only features required for you.
I guess using babel with "useBuiltIns": 'entry' isn't easy

**Comment by zloirock** [comment]
> But version of typed array core-js@2 works properly)

Works, but with some limitations and problems. 

> I guess using babel with "useBuiltIns": 'entry' isn't easy

Why? `exclude` option works with all `useBuiltIns` modes. With `useBuiltIns: entry` even that is not required.

**Comment by olegmanby** [comment]
> core-js/internals/typed-array-constructor.

"exclude": [
            /core-js\/stable\/features\/es.typed-array.uint8-array/
          ]

right?

**Comment by olegmanby** [comment]
from babel docs

exclude
Array<string|RegExp>, defaults to [].
An array of plugins to always exclude/remove.

I think it's not my case

**Comment by zloirock** [comment]
```js
"exclude": [
  /es\.typed-array/
]
```

**Comment by olegmanby** [comment]
> ```js
> "exclude": [
>   /es\.typed-array/
> ]
> ```

It doesn't work))) Typed array is used from core-js) As I mentioned it will be not easy))

**Comment by zloirock** [comment]
This option should accept an array of string or regex patterns of babel plugins or `core-js` modules, so that or something like that should work. If it does not work, it's a babel issue. I don't think that something can depend on `targets` here.

**Comment by olegmanby** [comment]
I think need to reconsider the concept. Polyfills is created to support new features in old browsers like IE. But we cannot use core-js@3 polyfills because we have a broken app after updating. Reasonable question why core-js contains polyfills that doesn't work in old browser properly and we have to get rid of it...

**Comment by zloirock** [comment]
Your issue is the first issue about typed arrays polyfill performance in `core-js@3` for 2.5 years. But it's used on the most popular internet websites. I proposed an option for you. One more time, maximal correctness has more priority than performance.
