### ISSUE TITLE
Object.define & Object.make Symbol awareness

### ISSUE THREAD

**Issue by dmail** [zloirock/core-js#102]
What do you think of making Object.define & Object.make Symbol aware?

```javascript
var a = {};
var b = {};
var fooSymbol = Symbol('foo');
a[fooSymbol] = 'bar';

Object.define(b, a);
b[fooSymbol] === 'bar'; // currently it's false because Object.define ignore symbols
```

**Comment by zloirock** [comment]
In wich version / envieronment? `Object.define` and `Object.make` supports symbols and this example should return `true`.

**Comment by dmail** [comment]
By reading the source code, I was thinking they defined only enumerable keys.
Sorry for the useless issue and thank you for this amazing work :)
