### ISSUE TITLE
TypeError: Failed to resolve module specifier "core-js/modules/es.array.concat.js". Relative references must start with either "/", "./", or "../".

### ISSUE THREAD

**Issue by wansiedler** [zloirock/core-js#1021]
TypeError: Failed to resolve module specifier "core-js/modules/es.array.concat.js". Relative references must start with either "/", "./", or "../".

**Comment by zloirock** [comment]
Why do you think that it's a `core-js` issue? It's an issue with your module loading / resolving process.
