### ISSUE TITLE
Support for ariaExpanded an similars

### ISSUE THREAD

**Issue by alexander-schranz** [zloirock/core-js#1022]
I could not find anything about it but it looks like core-js has not yet support for ariaExpanded and the other aria attributes:

https://developer.mozilla.org/en-US/docs/Web/API/Element/ariaExpanded#examples

Think that would be great.

**Comment by zloirock** [comment]
At this moment, `core-js` contains only polyfills for ECMAScript and closely related features from web standards. In the future, I think to extend it to other web standards features, but `ariaExpanded` is too far from features that `core-js` provide at this moment. So will see in the future.
