### ISSUE TITLE
How to contribute or add suggested methods

### ISSUE THREAD

**Issue by brandonmcconnell** [zloirock/core-js#1028]
If I want to contribute or propose new methods, what is the best way to get started? Should I fork this repo, write up the spec, then create a PR? What is the correct process for new method proposals?

**Comment by zloirock** [comment]
What do you want to contribute? `core-js` provide polyfills for standard ECMAScript features, ECMAScript proposals and some related web standards. If it's a standard feature - yes, you should fork the repo and create a PR. See some basic recommendations in [`CONTRIBUTING.md`](https://github.com/zloirock/core-js/blob/master/CONTRIBUTING.md). If it's not an official proposal see [the TC39 process documents](https://tc39.es/process-document/). If it's an official ES proposal or extension of the `core-js` API it's better at first open an issue.
