### ISSUE TITLE
IE8 hacks included in output, despite Internet Explorer is not a target

### ISSUE THREAD

**Issue by dilyanpalauzov** [zloirock/core-js#1031]
My target are recent-browsers: `browserslist 'edge > 84, firefox > 79, chrome > 84, safari > 13.1'` does not print Internet Explorer.  I bundle using [@rollup/plugin-babel](https://github.com/rollup/plugins/tree/master/packages/babel):
```javascript
babel.default({
    skipPreflightCheck: false,
    babelHelpers: 'bundled',
    exclude: 'node_modules/core-js/**',
    presets: [
        ['@babel/preset-env', {
            bugfixes: true,
            useBuiltIns: 'usage',
            corejs: 3,
            targets: 'edge > 84, firefox > 79, chrome > 84, safari > 13.1'
        }]
    ],
    compact: false,
})
```
The output contains:
```javascript
// Detect IE8's incomplete defineProperty implementation
var descriptors = !fails$9(function () {
  // eslint-disable-next-line es/no-object-defineproperty -- required for testing
  return Object.defineProperty({}, 1, { get: function () { return 7; } })[1] != 7;
});

var objectDefineProperty = {};

var DESCRIPTORS$6 = descriptors;
var fails$8 = fails$c;
var createElement = documentCreateElement$2;

// Thank's IE8 for his funny defineProperty
var ie8DomDefine = !DESCRIPTORS$6 && !fails$8(function () {
  // eslint-disable-next-line es/no-object-defineproperty -- required for testing
  return Object.defineProperty(createElement('div'), 'a', {
    get: function () { return 7; }
  }).a != 7;
});
```
from core-js/packages/core-js/internals/ie8-dom-define.js and core-js/packages/core-js/internals/descriptors.js.

* IE8 code shall not be included in the output, since IE8 is out of scope.
* In “Thank's IE8 for his funny defineProperty” the apostrophe shall be removed.

**Comment by zloirock** [comment]
Thanks for the issue. Yes, it's a known issue, but now, with the current architecture, it can't be *properly* fixed.

`core-js` contains thousands of cases of specific features detection. Now, `core-js` contains ~600 internal and external modules, moving all such cases of features detection to separate files will increase this number to some thousands. It will make mappings of modules almost unsupportable and will increase the size of any significant bundles by tens of percent.

In `core-js@4`, ES3 / IE8 support will be removed, some cases of such workarounds will be moved to entry points and it will significantly reduce such dead code in bundles.

**Comment by zloirock** [comment]
> In “Thank's IE8 for his funny defineProperty” the apostrophe shall be removed.

Thanks, good catch.
