### ISSUE TITLE
Is there plan to polyfill `Atomics`?

### ISSUE THREAD

**Issue by aleen42** [zloirock/core-js#1037]
I have found no documentation around whether we should implement [`Atomics`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics) in `core-js`, and is there any plan for this? I thought some operations like `Atomics.wait` and `Atomics.notify` can be excluded because they are restricted on shared `Int32Array` only. Performances of polyfills should be another factor to consider.

**Comment by zloirock** [comment]
I'm considering `Atomics` as a set of features useful only in combination with `SharedArrayBuffer`, so, since `SharedArrayBuffer` can be properly polyfilled, I don't see any sense in polyfilling of `Atomics`. Could you show any use cases where `Atomics` could be useful without `SharedArrayBuffer`?

**Comment by aleen42** [comment]
Some simple operations like `Atomics.{add, sub, and, or, xor}` can be use with `ArrayBuffer`.

**Comment by zloirock** [comment]
They can be used with `ArrayBuffer`, but any sense to use them instead of usual operations on non-shared data?

**Comment by aleen42** [comment]
😆 No sense.
