### ISSUE TITLE
NodeList.prototype.forEach is not polyfilled with core-js-pure

### ISSUE THREAD

**Issue by fire332** [zloirock/core-js#1038]
The below code is not polyfilled when core-js-pure is used, either through `@babel/plugin-transform-runtime` or `babel-plugin-polyfill-corejs3` with `usage-pure`.

```js
document.body.childNodes.forEach(node => {
  node;
})
```

However, the below line is correctly polyfilled using the same configuration.

```js
[1].includes(1)
```

`babel.config.js`:
```js
module.exports = (api) => {
  api.cache.never();

  return {
    sourceType: 'unambiguous',
    plugins: [
      // [
      //   'polyfill-corejs3',
      //   {
      //     method: 'usage-pure'
      //   }
      // ],
      [
        "@babel/plugin-transform-runtime",
        {
          "corejs": 3,
          "version": require('./package.json').dependencies['@babel/runtime-corejs3']
        }
      ]
    ]
  };
};
```

**Comment by zloirock** [comment]
In what engine?

**Comment by zloirock** [comment]
I can't reproduce it. Could you create a repo with a reproducible example and write in what concert version of the browser it does not work?

**Comment by fire332** [comment]
[polyfill-test.zip](https://github.com/zloirock/core-js/files/7848646/polyfill-test.zip)

Just run `npm i && npx webpack`. There are no polyfills used at all compared to `usage-global` which correctly polyfills.

**Comment by zloirock** [comment]
Thanks, I was able to reproduce it. It's a Babel issue, please open it in their repo.
