### ISSUE TITLE
`structuredClone` throws on Functions

### ISSUE THREAD

**Issue by muuvmuuv** [zloirock/core-js#1044]
> https://replit.com/@muuvmuuv/core-js-structured-clone-func#index.js

I don't know much about the spec of `structuredClone`, but Functions are very common in Objects so I guess this has just been forgotten while implementing?

**Comment by zloirock** [comment]
It works by [the structured clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm), so this is expected behavior.
