### ISSUE TITLE
Why core-js didn't provide polyfill for "getRootNode"

### ISSUE THREAD

**Issue by gaoyuan1223m** [zloirock/core-js#1045]
I am sorry I didn't find the polyfill for "getRootNode" from "Node.prototype", which is not available below iOS10.2

Could you please provide me some ways to solve this?

![image](https://user-images.githubusercontent.com/40973672/152975162-2b6f25b4-6700-4af9-a140-c3d2da5240ab.png)

**Comment by zloirock** [comment]
At this moment, `core-js` provide polyfills only for ECMAScript and related cross-platform web standards, so `getRootNode` is out of `core-js` scope. Maybe, in the future, `core-js` will be extended to such standards, but not soon.

**Comment by gaoyuan1223m** [comment]
> At this moment, `core-js` provide polyfills only for ECMAScript and closely related cross-platform web standards, so `getRootNode` is out of `core-js` scope. Maybe, in the future, `core-js` will be extended to such standards, but not soon.

Understood! Thanks, Zloirock

**Comment by oyar99** [comment]
is this still something we don't want to support in `core-js`?

**Comment by zloirock** [comment]
At this moment not. Maybe later, after adding web standards that are closer to ES.
