### ISSUE TITLE
npm fails on core js 

### ISSUE THREAD

**Issue by DLS60** [zloirock/core-js#1047]
npm ERR! node v16.14.0
NOTE THIS:  npm ERR! npm  v2.15.12  ==> my versiion of npm is PS C:\Users\OR0244124\dev> npm -v
8.4.1 I have no clue why the script report the old version I cleaned the cash in and flushed all the temp files"
npm ERR! file C:\WINDOWS\system32\cmd.exe
npm ERR! path C:\WINDOWS\system32\cmd.exe
npm ERR! code ELIFECYCLE
npm ERR! errno -4058
npm ERR! syscall spawn C:\WINDOWS\system32\cmd.exe

npm ERR! core-js@2.6.12 postinstall: `node -e "try{require('./postinstall')}catch(e){}"`
npm ERR! spawn C:\WINDOWS\system32\cmd.exe ENOENT
npm ERR! 
npm ERR! Failed at the core-js@2.6.12 postinstall script 'node -e "try{require('./postinstall')}catch(e){}"'.
npm ERR! This is most likely a problem with the core-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node -e "try{require('./postinstall')}catch(e){}"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs core-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls core-js

npm ERR! Please include the following file with any support request:     
[npm-debug.log](https://github.com/zloirock/core-js/files/8050643/npm-debug.log)

error log attached

**Comment by zloirock** [comment]
Make sure that `node` is available in your path. Check access rights.

**Comment by DLS60** [comment]
Setting the path and permissions fixed it. ;-) Thank you

Dan
