### ISSUE TITLE
Object Expected Error IE11 in to-object.js

### ISSUE THREAD

**Issue by SgiobairOg** [zloirock/core-js#1049]
Seeing an issue in IE11 with the to-object script. Using version 3.21.1. 

SCRIPT5007: Object expected

Debugger points at line 9 `return Object(requireObjectCoercible(argument));`

If relevant we are using Webpack 5 and had to begin to transpile node_modules in order to support another library, one that doesn't transpile itself.

**Comment by zloirock** [comment]
Logically, this line should throw an error if passed `null` or `undefined`, so most likely the error on your side.

If you don't think so, please add a reproducible example.

**Comment by SgiobairOg** [comment]
I think it may have ended up having more to do with us running core-js through Babel, all fixed now in either case. 

Thanks for the response and sorry for the goose chase.
