### ISSUE TITLE
interface ArrayLike seems to be missing from 1.1.4

### ISSUE THREAD

**Issue by gregoryagu** [zloirock/core-js#105]
After nugetting the latest vesion, Visual Studio 15 gives me numerous errors: Cannot find name 'ArrayLike'

When I dropped back to an older version, it no longer gave this errror.

**Comment by zloirock** [comment]
No ideas. Problem with `TypeScript`? Which steps I should reproduce for getting this problem?

**Comment by zloirock** [comment]
Anyway, the problem in the type definition, not in `core-js`.

\cc @rbuckton

**Comment by zloirock** [comment]
I close it because I don't see any clarifications.

**Comment by rbuckton** [comment]
@gregoryagu Are you using the typings from DefinitelyTyped? The current version of core-js.d.ts on DefinitelyTyped defines `ArrayLike`.

**Comment by gregoryagu** [comment]
Sorry for the delay on answering.  Yes, this seems to be a Typescript issue, not core-js.js.  Yes, I am using typings from Definitely Typed.  I just got the latest .0.0.4 version from nuget, and it still don't not define ArrayLike.  I have searched the file for it, and it is used, but not defined.  I also just searched the github version, and don't see it in there either.
