### ISSUE TITLE
structuredClone argument validation does not match browser implementations

### ISSUE THREAD

**Issue by mc-alt** [zloirock/core-js#1056]
The structuredClone polyfill uses the `arguments` variable to count the number of arguments, and if there is more than one argument it validates that the second argument is an object.

I encountered an issue where Mozilla's pdf-js uses this function, but in some circumstances the 2nd argument can be `undefined`.

In both Firefox and Chrome there is no issue when you do this.

In the core-js polyfill this will trigger a type error.

I think it is reasonable to assume developers could pass `undefined` as a value to the 2nd argument (it is quite common to assume that any trailing undefined arguments should be treated as if they were never supplied)

**Comment by zloirock** [comment]
I can't find it in the WebIDL spec, however, since it's the behavior of implementations from all engines, let it be.

**Comment by mc-alt** [comment]
thanks @zloirock, sorry for leaving you hanging there, I was offline due to a combination of holiday and illness. I really appreciate you looking into this one

**Comment by ZhangJianChengZzz** [comment]
I also had this problem with the latest version of Mozilla's PDF-JS, passing arguments[1] as undefined when using structuredClone will not work properly

**Comment by zloirock** [comment]
@dogedogezzz make sure that you use `core-js@^3.22`.
