### ISSUE TITLE
 Error: Cannot find module 'core-js/modules/es.object.define-property.js'

### ISSUE THREAD

**Issue by ktisakib** [zloirock/core-js#1058]
is this issue related to corejs

E:\Jibonvai\Pixer-Laravel\admin\node_modules\next-i18next\dist\commonjs\index.js
E:\Jibonvai\Pixer-Laravel\admin.next\server\pages_document.js
E:\Jibonvai\Pixer-Laravel\admin\node_modules\next\dist\server\require.js
E:\Jibonvai\Pixer-Laravel\admin\node_modules\next\dist\server\load-components.js
E:\Jibonvai\Pixer-Laravel\admin\node_modules\next\dist\build\utils.js
E:\Jibonvai\Pixer-Laravel\admin\node_modules\next\dist\build\output\store.js
E:\Jibonvai\Pixer-Laravel\admin\node_modules\next\dist\build\output\index.js
E:\Jibonvai\Pixer-Laravel\admin\node_modules\next\dist\cli\next-dev.js
E:\Jibonvai\Pixer-Laravel\admin\node_modules\next\dist\bin\next Error: Cannot find module 'core-js/modules/es.object.define-property.js' Require stack:
E:\Jibonvai\Pixer-Laravel\admin\node_modules\next-i18next\dist\commonjs\index.js
E:\Jibonvai\Pixer-Laravel\admin.next\server\pages_document.js
E:\Jibonvai\Pixer-Laravel\admin\node_modules\next\dist\server\require.js
E:\Jibonvai\Pixer-Laravel\admin\node_modules\next\dist\server\load-components.js
E:\Jibonvai\Pixer-Laravel\admin\node_modules\next\dist\build\utils.js
E:\Jibonvai\Pixer-Laravel\admin\node_modules\next\dist\build\output\store.js
E:\Jibonvai\Pixer-Laravel\admin\node_modules\next\dist\build\output\index.js
E:\Jibonvai\Pixer-Laravel\admin\node_modules\next\dist\cli\next-dev.js
E:\Jibonvai\Pixer-Laravel\admin\node_modules\next\dist\bin\next at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15) at Function.mod._resolveFilename (E:\Jibonvai\Pixer-Laravel\admin\node_modules\next\dist\build\webpack\require-hook.js:171:28) at Function.Module._load (node:internal/modules/cjs/loader:778:27) at Module.require (node:internal/modules/cjs/loader:1005:19) at require (node:internal/modules/cjs/helpers:102:18) at Object. (E:\Jibonvai\Pixer-Laravel\admin\node_modules\next-i18next\dist\commonjs\index.js:3:1) at Module._compile (node:internal/modules/cjs/loader:1103:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10) at Module.load (node:internal/modules/cjs/loader:981:32) at Function.Module._load (node:internal/modules/cjs/loader:822:12) { code: 'MODULE_NOT_FOUND', requireStack: [ 'E:\Jibonvai\Pixer-Laravel\admin\node_modules\next-i18next\dist\commonjs\index.js', 'E:\Jibonvai\Pixer-Laravel\admin\.next\server\pages\_document.js', 'E:\Jibonvai\Pixer-Laravel\admin\node_modules\next\dist\server\require.js', 'E:\Jibonvai\Pixer-Laravel\admin\node_modules\next\dist\server\load-components.js', 'E:\Jibonvai\Pixer-Laravel\admin\node_modules\next\dist\build\utils.js', 'E:\Jibonvai\Pixer-Laravel\admin\node_modules\next\dist\build\output\store.js', 'E:\Jibonvai\Pixer-Laravel\admin\node_modules\next\dist\build\output\index.js', 'E:\Jibonvai\Pixer-Laravel\admin\node_modules\next\dist\cli\next-dev.js', 'E:\Jibonvai\Pixer-Laravel\admin\node_modules\next\dist\bin\next' ] }

**Comment by zloirock** [comment]
This module [is available](https://unpkg.com/browse/core-js@3.21.1/modules/es.object.define-property.js) in the actual version of `core-js` package, so this is not related to `core-js`. Make sure that you have installed a proper version of `core-js` dependency.
