### ISSUE TITLE
TypeArray iOS supported version

### ISSUE THREAD

**Issue by skychx** [zloirock/core-js#1062]
From caniuse's data, type-array (e.g. [Int8Array](https://caniuse.com/?search=Int8Array)) has been supported since iOS Safari 4.2, why does corejs think it's only supported since iOS14? Is it because there is a bug in the iOS implementation?

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/24872439/159458853-550e83e0-ea32-4aac-aeb1-0f56cbd3204e.png">

https://github.com/zloirock/core-js/blob/25f86b698807048390932e1a8252558e7b8af4e8/packages/core-js-compat/src/data.mjs#L1310-L1350

**Comment by zloirock** [comment]
Because `core-js` also contains bug fixes and changes by the actual standards. [This test](https://github.com/zloirock/core-js/blob/54f8800ac63ca2a0584ea11b1fad873856661d59/tests/compat/tests.js#L160-L183) is not passed till Safari 14.0.

**Comment by skychx** [comment]
> Because `core-js` also contains bug fixes and changes by the actual standards. [This test](https://github.com/zloirock/core-js/blob/54f8800ac63ca2a0584ea11b1fad873856661d59/tests/compat/tests.js#L160-L183) is not passed till Safari 14.0.

THX
