### ISSUE TITLE
Is there a way to get a list of applied polyfills?

### ISSUE THREAD

**Issue by ondrasak** [zloirock/core-js#1063]
Would be great to have the ability to get this data... for tracking and future optimization purposes

Thanks!

**Comment by aladdin-add** [comment]
but how? IMHO, seems core-js does not know what and how it's being imported. if you are something like babel, you'll need to file the issue in that repo.

**Comment by zloirock** [comment]
Depends on what do you want.

If you know the engine, the version of `core-js` and the list of imported modules, you can use `core-js-compat` for know applied modules:
```js
require('core-js-compat')({ targets: { safari: '14.0'}, filter: /^(es|web)\./ }).list;
/*
[
  'es.error.cause',
  'es.aggregate-error.cause',
  'es.array.at',
  'es.object.has-own',
  'es.string.at-alternative',
  'es.typed-array.at',
  'es.typed-array.set',
  'es.typed-array.sort',
  'web.dom-exception.stack',
  'web.immediate',
  'web.structured-clone'
]
*/
```

But if you wanna know what features are applied and the concrete reason - it's problematical. Each module can contain some polyfills and they are can be applied for many different reason. I wanted to add a registry and add features and reasons on polyfilling for debugging, buе it was too expensive (for example, a serious increase in size), so I abandoned this idea.
