### ISSUE TITLE
WTF

### ISSUE THREAD

**Issue by us-maksym** [zloirock/core-js#1069]
@zloirock why should I see these links and information that you need a job???

![Screenshot from 2022-04-11 19-06-59](https://user-images.githubusercontent.com/19506391/162783980-8c0d11ea-360b-4c52-a279-83137bbe1393.png)

**Comment by zloirock** [comment]
You should see it because you use my software. If you don't like it - you could just stop to use it.

**Comment by us-maksym** [comment]
@zloirock 
At first, do not tell me what I should do if you are a well-mannered person, but not an animal
At second, it is an open-source package and it's bullshit to see these notes of the beggar using this package
Do you have any problems because of the war that your country started in Ukraine? Why do you beg money?

**Comment by artptr** [comment]
>  Do you have any problems because of the war that your country started in Ukraine? Why do you beg money?

Are you so lazy to lookup through history of the project to find the earliest commit https://github.com/zloirock/core-js/commit/abdaeb8759e98cc01d9372aa21c48e1602fa8423 on 18th May 2019?
