### ISSUE TITLE
Promise should report stack trace on unhandled promise rejection

### ISSUE THREAD

**Issue by LPGhatguy** [zloirock/core-js#107]
Because of issue #78, native promises aren't used in V8 -- but this hampers debugging in V8.

On an unhandled promise rejection, core-js should outputed a console trace using something like `console.trace`, otherwise errors are masked completely.

**Comment by zloirock** [comment]
I have no ideas how implement it with current microtask implementation. If you have - you can add PR or propose here. For more convenient debugging in next version will be available #106.

**Comment by zloirock** [comment]
Close this because I don't see any proposals how to implement this with low price. If someone have any ideas - welcome.

**Comment by benjamingr** [comment]
Sure, you already have unhandled rejection tracking. You can just log to the console on errors. 

Note that in Node the default behavior is a silence failure unless a handler is added.
