### ISSUE TITLE
Cannot find module: '../modules/es.array.iterator'

### ISSUE THREAD

**Issue by sasilevi** [zloirock/core-js#1071]
we are having build issues since last version with error:

./node_modules/core-js/modules/web.dom-collections.iterator.js 
Cannot find module: '../modules/es.array.iterator'

**Comment by zloirock** [comment]
This module [is available](https://unpkg.com/browse/core-js@3.22.1/modules/es.array.iterator.js) on NPM, so it's not a `core-js` issue.
