### ISSUE TITLE
Why does "yarn add - D core-js" always fail to install

### ISSUE THREAD

**Issue by bcbnbxy** [zloirock/core-js#1074]
![image](https://user-images.githubusercontent.com/24733062/165323823-0befb695-d6ab-4f50-bcea-81e0c988b045.png)

**Comment by zloirock** [comment]
Not always.

![image](https://user-images.githubusercontent.com/2213682/165338294-0b58a515-3011-423d-b601-ee6fb6024f35.png)

It's not a `core-js` issue, it a problem of your installing process.
