### ISSUE TITLE
Remove PhantomJS dependency

### ISSUE THREAD

**Issue by sandstrom** [zloirock/core-js#1076]
Would it be possible to somehow get rid of the PhantomJS dependency? (`phantomjs-prebuilt`)

That package is deprecated, and doesn't work with ARM.

Since it's part of CoreJS, any node or browser project on ARM, where core-js is part of the dependency tree, will fail due to this package.

PhantomJS doesn't seem to be used for anything except the tests, and phantomJS itself was archived/deprecated 4 years ago (https://github.com/ariya/phantomjs/issues/15344). Maybe it's time to cut the cord?

![image](https://user-images.githubusercontent.com/122287/166249391-967f28f5-1313-48c3-ade6-87bcde0fd29d.png)

https://www.npmjs.com/package/phantomjs-prebuilt

**Comment by zloirock** [comment]
No, it's not possible. It's used for automatic testing of very old versions of WebKit. However, I can't understand how it can cause any problems - it's the dependency of the root of the monorepo, it's not a dependency of any published packages.

**Comment by zloirock** [comment]
Also, at this moment I'm on an ARM laptop - and PhantomJS works fine.

**Comment by sandstrom** [comment]
Thanks for answering @zloirock and those are valid points!

PhantomJS works on our Darwin ARM machine, but not on our Linux ARM machine.

**Comment by jtsoi** [comment]
@zloirock to help you to understand how this can cause a problem:

Popular frameworks like Vue, Ember, React, define their "runtime/browser" deps in dependencies, and build time dependencies in devDependencies.
- https://github.com/ember-cli/ember-new-output/blob/master/package.json
- https://github.com/sharmasourabh/vue-starter-template/blob/master/package.json
- https://github.com/react-boilerplate/react-boilerplate/blob/master/package.json
This seems to be a common practice:
https://betterprogramming.pub/package-jsons-dependencies-in-depth-a1f0637a3129

I might be wrong about this, but installing with `npm ci` ir `npm install` will pull in **all** devDependencies in the dependency tree. 
And as @sandstrom wrote, `phantomjs-prebuilt` does not have a `linux/arm64` binary, thus installation fails.

With popularity of arm64 cpus on the rise, (AWS linux/arm64 offer is compelling) and phantomjs is no longer maintained, if phantomjs is only needed for testing, may I suggest moving it into `optionalDependencies`?

**Comment by zloirock** [comment]
@jtsoi sorry, I can't understand what do you mean - `phantomjs-prebuilt` is not a dependency of **any** `core-js` package. It's used only in the top level monorepo `package.json` for CI - and dependencies should not have the monorepo in dependencies.

**Comment by jtsoi** [comment]
@zloirock Ah, yes, sorry, you are right.
Its only an issue with older version of `core-js` (v2) 
https://github.com/zloirock/core-js/blob/v2/package.json

That unfortunately `ember-cli-babel` still depends on `core-js` (v2)  via `babel-polyfill`
https://github.com/babel/ember-cli-babel/blob/master/package.json
https://github.com/babel/babel/blob/v7.11.5/packages/babel-polyfill/package.json

**Comment by zloirock** [comment]
So maybe it's time to update your dependencies? `core-js@2` is no longer supported for many years and have many critical issues - you should see at least the deprecation message:

> core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

**Comment by jtsoi** [comment]
@zloirock Agreed.
