### ISSUE TITLE
Line 9 number !== number || number === 0 , what does that do

### ISSUE THREAD

**Issue by heweixiang** [zloirock/core-js#1080]
![image](https://user-images.githubusercontent.com/49872030/168340980-18489843-c3a4-460a-8782-23df3ecc9e7b.png)
Line 9 number !== number || number === 0 , what does that do

**Comment by zloirock** [comment]
It's check on `NaN`  / `+0` / `-0`.

**Comment by heweixiang** [comment]
> 这是检查`NaN` / `+0`/ `-0`。

Thank you, Epiphany
