### ISSUE TITLE
Syntax error when compiling in IDE.

### ISSUE THREAD

**Issue by brennaharden** [zloirock/core-js#1081]
While I am certain this could have to do with other dependencies/issues in our project, I thought I would reach out on the chance that this is familiar to someone here...

I'm running core-js v. 2.6.12 as a dependency of a private library, which is connected locally to my microservice via npm link... I'm getting this error when compiling:

```
core-js/internals/wrap-error-constructor-with-cause.js:37
var result = IS_AGGREGATE_ERROR ? new OriginalError(a) : new OriginalError();

Syntax Error
```

<img width="916" alt="Screen Shot 2022-05-19 at 3 32 22 PM" src="https://user-images.githubusercontent.com/67924219/169408326-70e863cf-c736-40a5-ae90-443a9aacb675.png">

Any leads/ideas would be greatly appreciated!

**Comment by brennaharden** [comment]
Thanks for replying so quickly, the only other files explicitly listed in the error are from the @babel/parser package.
<img width="927" alt="Screen Shot 2022-05-19 at 4 20 06 PM" src="https://user-images.githubusercontent.com/67924219/169414224-d78bc62a-d885-4ab1-aba5-92cc52bd53ef.png">

**Comment by zloirock** [comment]
So seems it's the place where the error is thrown.
