### ISSUE TITLE
core-js es.array.iterator with Chrome53 error

### ISSUE THREAD

**Issue by daoerche** [zloirock/core-js#1083]
Hi, I found this issue while building polyfills with vite, and it seems to be a core-js issue after discussion.
reproducible: https://gist.github.com/sapphi-red/c1c02a1df86fbd0df9526f2d0f5e6e6a
vite issues: https://github.com/vitejs/vite/issues/8287

**Comment by zloirock** [comment]
Thanks.

**Comment by zloirock** [comment]
Added a workaround in [3.22.7](https://github.com/zloirock/core-js/releases/tag/v3.22.7).

**Comment by daoerche** [comment]
> Added a workaround in [3.22.7](https://github.com/zloirock/core-js/releases/tag/v3.22.7).

This is so fast, thank you so much~
