### ISSUE TITLE
why no globalThis in core-js/stable?

### ISSUE THREAD

**Issue by taoliujun** [zloirock/core-js#1089]
env: `core-js: 3.22.7`

I read document about `globalThis` below.

`Finished (stage 4) proposals already marked in core-js as stable ECMAScript, they are available in core-js/stable and core-js/es namespace`

And it said `globalThis is not defined` in android7 when import `core-js/stable`, but it worked fine when import `core-js` or `core-js/full`.

**Comment by zloirock** [comment]
[It's present in `core-js/es` -> `core-js/stable`](https://unpkg.com/browse/core-js@3.22.7/es/index.js) and tested in this envieronment. Could you add a reproducible example?

**Comment by taoliujun** [comment]
> [It's present in `core-js/es` -> `core-js/stable`](https://unpkg.com/browse/core-js@3.22.7/es/index.js) and tested in this envieronment. Could you add a reproducible example?

I used `useBuiltIns: 'usage'` to load core-js. and search `global-this` in treemap after webpack build with analyze , strange appearance like below.

1. If use `import 'core-js/stable'` and console log `globalThis`.  `globalThis` is appear in treemap.
2. If use `import 'core-js/stable'` and no `globalThis` in code. `globalThis` is not appear in treemap.
3. If use `import 'core-js/full'` and console log `globalThis`.  `globalThis` is appear in treemap.
4. If use `import 'core-js/full'` and no `globalThis` in code. `globalThis` is **still** appear in treemap.

I think that no `globalThis` appeared in treemap if no `globalThis` in code was expected. But why it still appeard when use `core-js/full`
6.

**Comment by zloirock** [comment]
If you use `useBuiltIns: 'usage'`, you should not import `core-js` by yourself. If you import it by yourself, use `useBuiltIns: 'entry'`. You should use `corejs: '3.22'` instead of `corejs: 3` in the `babel` config. `core-js-compat` version in the `babel` dependencies should be actual.
