### ISSUE TITLE
logger not found in es6.promise.js of core-js

### ISSUE THREAD

**Issue by shreychaturvedi123** [zloirock/core-js#109]
At line 96 , I did a hack
} catch(err){
if(console){
console.log(err);
}
react.rej(err);
}
but if i use logger.log then it says logger is not defined and i am using winston logger globally and in catch also it is getting error that "logger is not defined".
[ReferenceError: logger is not defined]

**Comment by zloirock** [comment]
So... `logger` defined before `core-js`?

**Comment by shreychaturvedi123** [comment]
yeah , i have raised this issue in core-js.

**Comment by zloirock** [comment]
@shreychaturvedi123 I don't see a reproducible example. Or you already solved this problem?

**Comment by shreychaturvedi123** [comment]
I am trying to give a reproducable example, btw where does react.rej(err) goes to.

**Comment by zloirock** [comment]
Close this because I don't see a reproducible example.
