### ISSUE TITLE
at core-js 3.23.0 version, throw error Cannot redefine property: DEG_PER_RAD。

### ISSUE THREAD

**Issue by Nowitzki41** [zloirock/core-js#1091]
![image](https://user-images.githubusercontent.com/22088253/173571734-3cc747ed-9cc7-4f90-a564-d8322d718ff2.png)
we can see the change,  why do this?

**Comment by zloirock** [comment]
Because it should be non-writable non-configurable.

It seems you load multiple copies of `core-js` - I don't know why it's required.

I forgot about this case, thanks for the report, I'll add a workaround.

**Comment by zloirock** [comment]
Fixed in `3.23.1`.

**Comment by Nowitzki41** [comment]
> Because it should be non-writable non-configurable.
> 
> It seems you load multiple copies of `core-js` - I don't know why it's required.
> 
> I forgot about this case, thanks for the report, I'll add a workaround.

Our project uses a micro front-end framework, so there are multiple project resources running the scene at the same time, thanks for your reply
