### ISSUE TITLE
Array.prototype.push has extra "prototype" property

### ISSUE THREAD

**Issue by Jack-Works** [zloirock/core-js#1092]
Native version:

![image](https://user-images.githubusercontent.com/5390719/174231501-cbc69e3d-262a-4668-9b20-a493e54c009d.png)

Core-js version:

![image](https://user-images.githubusercontent.com/5390719/174231523-e31601bc-a43b-4a3c-aa26-6077935ee752.png)

This cause the following error in our environment:

![image](https://user-images.githubusercontent.com/5390719/174231593-e25a17c0-efc0-459b-9e18-8ef3ee93ea7d.png)

**Comment by zloirock** [comment]
Could you add a reproducible example?

`core-js` polyfills should work everywhere - even in ES3 - and simple function definition (instead of an arrow or a method shorthand) is the only way to define a method. Functions defined via `function` have a `.prototype` property - and it can't be completely deleted - we overwrite it to `undefined` and can't do more.

**Comment by zloirock** [comment]
If you just walk over built-ins tree and `delete` anything unexpected - it's strange, since, if you use polyfills, sooner or later will be added (maybe to polyfills, maybe to a new engine version) something non-writable non-configurable that can't be deleted, like in this case.

**Comment by Jack-Works** [comment]
I'm using ses (https://github.com/endojs/endo/tree/master/packages/ses).

I run core-js first, then freeze all built-ins by `lockdown` provided by ses. SES maintains a whitelist of built-in intrinsic and removes all non-standard items.

Maybe I need to cc @erights, @kriskowal and @naugtur? I believe they can explain better why this is necessary.

**Comment by Jack-Works** [comment]
> if you use polyfills or even not, sooner or later will be added (maybe to polyfills, maybe to a new engine version) something non-writable non-configurable that can't be deleted

yes, ses maintains a list of intrinsic and update them when they're stage 3 or 4. Usually, new APIs in JavaScript are configurable so removing them is usually OK (Some exceptions are new well-known symbols).

By the way, I also see these things on TypedArrays. I'm wondering what are those new properties? Does removing them cause something in core-js breaks?

![image](https://user-images.githubusercontent.com/5390719/174286210-9bb7d44c-5fbe-4847-8a8e-d778c5a8aff3.png)

**Comment by zloirock** [comment]
> I'm using ses

That's what I assumed.

I think that for the reason specified above, it's better to fix it on the `endo` side.

> Does removing them cause something in core-js breaks?

It will break new `%TypedArray%` methods. However, I wanted to rewrite this case with another approach in some months.

**Comment by Jack-Works** [comment]
> and simple function definition (instead of an arrow or a method shorthand) is the only way to define a method. Functions defined via function have a .prototype property - and it can't be completely deleted - we overwrite it to undefined and can't do more.

Now I understand, this is interesting. Maybe it is possible to patch `Object.getPropertyDescriptors` as well like the `[native code]` hack? ...Or use Proxy when possible? But it does not sound like a good idea.

**Comment by Jack-Works** [comment]
Oh! When you define the method in object literal, it will not have a `"prototype"` property and you can still use `this`! But is that viable for core-js?

![image](https://user-images.githubusercontent.com/5390719/174287721-0e0018c7-396f-4532-93a0-9a0be4f2a497.png)

**Comment by zloirock** [comment]
As I wrote, one source code should work everywhere - methods shorthands do not work in ES5, and creation of that via `Function` constructor or `eval` will break CSP.

**Comment by zloirock** [comment]
In case it was a method that does not handle `this` internally, in most browsers that have native `.bind` and allow redefinition on functions `.name`, it's possible to wrap it with `.bind` - bound functions have not `.prototype` - but `.push` is not this case.

**Comment by Jack-Works** [comment]
I agree. Looks like there isn't anything core-js can do. Thanks for your reply!

**Comment by zloirock** [comment]
All that I can recommend it's taking this case into account on `endo` side or excluding `es.array.push` from your bundle - however, over time, the list of such modules will be changed...

Maybe, in the future, `core-js` will be transpilable, and, in this case, will be used methods shorthand that will be transpiled to usual functions if ES5 support will be required - but it will be not soon.

**Comment by zloirock** [comment]
> > if you use polyfills or even not, sooner or later will be added (maybe to polyfills, maybe to a new engine version) something non-writable non-configurable that can't be deleted
> 
> yes, ses maintains a list of intrinsic and update them when they're stage 3 or 4. Usually, new APIs in JavaScript are configurable so removing them is usually OK (Some exceptions are new well-known symbols).
> 
> By the way, I also see these things on TypedArrays. I'm wondering what are those new properties? Does removing them cause something in core-js breaks?
> 
> ![image](https://user-images.githubusercontent.com/5390719/174286210-9bb7d44c-5fbe-4847-8a8e-d778c5a8aff3.png)

In the next patch release, new `%TypedArray%` methods will work without those properties.

**Comment by erights** [comment]
> As I wrote, one source code should work everywhere - methods shorthands do not work in ES5, and creation of that via `Function` constructor or `eval` will break CSP.

Is ES5 still practically important? What actual targets do you still support that do not implement concise method syntax?

**Comment by zloirock** [comment]
@erights even ES3 is practically important. `core-js` support even IE8- and embedded engines. In `core-js@4`, ES3 support will be removed - but only ES3, definitely not ES5.

**Comment by erights** [comment]
Thanks for the clarification. I will explore addressing this from the SES side.

**Comment by erights** [comment]
@zloirock @Jack-Works @ljharb ,

Please see https://github.com/endojs/endo/pull/1221 . Would love feedback. Thanks!
