### ISSUE TITLE
TypeError: Cannot redefine property: DEG_PER_RAD after upgrading to v3.23.0

### ISSUE THREAD

**Issue by JennyZeiser** [zloirock/core-js#1094]
After updating to v3.23.0, we get the following error: `Uncaught TypeError: Cannot redefine property: DEG_PER_RAD`, assumingly due to the following commit: https://github.com/zloirock/core-js/commit/c0508b57fd118c394231c0c3d087176a6f15db34

**Comment by zloirock** [comment]
It was fixed in 3.23.1. Duplicate of #1091
