### ISSUE TITLE
Serialization of JSON bodies containing a Map

### ISSUE THREAD

**Issue by jlavadoww** [zloirock/core-js#1096]
Hi there! This is not an issue but I would like to understand something. I have recently upgraded from `2.6.5` to `3.22.5` version and this upgrade gave me one error. 

On the `2.6.5` version I am able to send Map objects through an Angular HTTP request with no problems. But in the `3.22.5`, the Map object is sent as <u>empty</u>. 

I tried reading the release notes but couldn't find something explaining this behavior. Could someone explain to me why is this happening here, please? 

Example of an interface being sent through the request:

```
export interface MyObject {
  name: string;
  description: string;
  labels?: Map<string, string>;
}
```

In the version `2.6.5`, the `labels` property is being sent properly as a JSON. But in the `3.22.5` is being sent as an **empty object**.

Note: Could this be related to @types/core-js?

Thanks!

**Comment by zloirock** [comment]
In `core-js@2` was implemented [`Map.prototype.toJSON` proposal](https://github.com/DavidBruant/Map-Set.prototype.toJSON), however it was rejected by TC39, so it was removed from `core-js@3`.
