### ISSUE TITLE
Enable CSP support

### ISSUE THREAD

**Issue by Ralt** [zloirock/core-js#11]
Hi,

A reroll of https://github.com/6to5/6to5/issues/427

Basically, this line is the offending one: https://github.com/zloirock/core-js/blob/master/index.js#L2084

See the angular link for more info: https://docs.angularjs.org/api/ng/directive/ngCsp

I'm not sure how this should be handled. Maybe a global variable could be used as an option setting?

**Comment by sebmck** [comment]
Shouldn't this be opened as an issue on the `core-js` repo?

**Comment by Ralt** [comment]
@sebmck look where we are :-)

**Comment by sebmck** [comment]
@Ralt I'm an idiot haha, sorry!

**Comment by zloirock** [comment]
@Ralt I can get rid of the `Function` constructor in this case, but not all, for example, [here](https://github.com/zloirock/core-js/blob/master/src/immediate.js#L14).

**Comment by Ralt** [comment]
In which occasion is `setImmediate` called with a string argument? ES6
standard allows this?

**Comment by Ralt** [comment]
In any case, if this can't be fixed, then it has to be advised that core-js (and by extension, 6to5-polyfill) can't work on CSP environments.

**Comment by benjamingr** [comment]
Someone performing a setImmediate with a string is _explicitly_ saying they're interested in invoking a CSP violating as it is a function constructor.

If you can optionally remove `Function` from all places it is not used for exactly that it would definitely suffice as `setImmediate` with a string argument is a CSP violation _anyway_.

**Comment by zloirock** [comment]
@Ralt core-js is not only ES6 shim. `setImmediate` is not a pert of ES6.

@benjamingr Ok, i will remove `Function` constructor where it is not needed.

**Comment by benjamingr** [comment]
@zloirock note that if you're using for `Function` for performance optimization it's worth opt-ing out of `Function`, especially since in Node where the CSP is not an issue the performance difference is important. Great work on the library by the way.

**Comment by Ralt** [comment]
It works! Thanks a lot :)

**Comment by zloirock** [comment]
Thanks. Available as 0.4.4.
