### ISSUE TITLE
Object.values and Object.entries polyfill

### ISSUE THREAD

**Issue by roman01la** [zloirock/core-js#110]
Looks like this ES7 proposal just got to stage 2 and there are a couple of polyfills already, see: https://twitter.com/ljharb/status/646838312087326721

Can we have it in core-js?

**Comment by zloirock** [comment]
We have it from the first versions.

**Comment by roman01la** [comment]
That is great! Sorry then.

**Comment by delaaxe** [comment]
This is not in the latest non-beta release though? Couldn't find it in v2 docs

**Comment by zloirock** [comment]
@delaaxe https://github.com/zloirock/core-js/tree/v2#stage-4-proposals
