### ISSUE TITLE
web.structured-clone test will always fail

### ISSUE THREAD

**Issue by Pyrolistical** [zloirock/core-js#1106]
https://github.com/zloirock/core-js/blob/bba906efe9db8f6922bac12678d99405b3509a53/tests/compat/tests.js#L1863

The bug in the test
```js
var error = new Error();
var test = structuredClone({ a: error, b: error });
if (!(... && test.stack === error.stack)) return false;
```

`test.stack` will always be `undefined` and `error.stack` will always be an array.

I think the test intended use `test.a.stack`? But I am not sure as it would seem that `test.a === error` would be a better test.

**Comment by Pyrolistical** [comment]
Like copypasta from https://github.com/zloirock/core-js/blob/bba906efe9db8f6922bac12678d99405b3509a53/packages/core-js/modules/web.structured-clone.js#L72

**Comment by Pyrolistical** [comment]
This was previously gated by https://bugs.chromium.org/p/v8/issues/detail?id=12542 but has been fixed

**Comment by Pyrolistical** [comment]
Ah according to this https://github.com/zloirock/core-js/commit/e41db12061534e0af3a2a636a87ec56714088013#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR4

I believe the intended code is `test.a.stack === error.stack`

**Comment by zloirock** [comment]
Yes, thanks, you are right, it's a typo. Anyway, no one of the current native implementations still does work as expected - FF implementation is the closest and left [the final issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1777321).
