### ISSUE TITLE
some questions in using Function.bind  polyfill 

### ISSUE THREAD

**Issue by shareluck** [zloirock/core-js#1107]
```js
Function.prototype.myBind = function(target) {
    var _fn = this
    var args = [...arguments].slice(1) 
    var bridge = function() {} 
    var fnBound = function() { 
        var _this = this instanceof fnBound ? this : target
        return _fn.apply(_this, args.concat([...arguments]))
    }
    if (this.prototype) {
        bridge.prototype = this.prototype;
        fnBound.prototype = new bridge();
    }
    return fnBound;
}

function Fn(){
   
    console.log(this.a)

}
let obj = {
a:1
}
let fnMyBind = Fn.myBind(obj)
let fnBind = Fn.bind(obj)

let myBindInstance = new fnMyBind()
let bindInstance = new fnBind()

myBindInstance.fn = fnMyBind
bindInstance.fn = fnBind

myBindInstance.fn ()  //  undefined
bindInstance.fn ()     // 1
```

**Comment by zloirock** [comment]
Yes, it's impossible to write 100% correct `Function.prototype.bind` polyfill. It's one of **many** issues with this polyfill. Theoretically, this case can be worked around by adding a protection field on a construct. However, I'm not sure that this is a real-life case and it's required.

**Comment by shareluck** [comment]
i also see&nbsp;[[BoundThis]]&nbsp;in the browser, maybe it works .&nbsp; thank you .&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zloirock/core-js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月16日(星期六) 晚上6:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zloirock/core-js] some questions in using Function.bind  polyfill  (Issue #1107)





 
Yes, it's impossible to write 100% correct Function.prototype.bind polyfill. It's one of many issues with this polyfill. Theoretically, this case can be worked around by adding a protection field on a construct. However, I'm not sure that this is a real-life case and it's required.

**Comment by zloirock** [comment]
`[[BoundThis]]` at first is not something that can be accessed in userland, at second it's a full equal of `target` that is stored in the closure. It's absolutely not related to this case.

I think that the only possible workaround for this (with a field installed to initialized instances) will cause more problems than this issue.

Thanks for reporting, however, let it be not fixed - anyway, it will be removed soon with IE8- support.
