### ISSUE TITLE
Watta heck: postinstall script fails?!

### ISSUE THREAD

**Issue by bricss** [zloirock/core-js#1108]
```bash
npm ERR! code 127
npm ERR! path C:\Users\<Username>\Documents\Workspace\<Omited>\node_modules\core-js
npm ERR! command failed
npm ERR! command C:\Program Files\git\bin\bash.exe -c 'C:\Users\<Username>\AppData\Local\Temp\postinstall65825929496.sh'
npm ERR! /usr/bin/bash: C:Users<Username>AppDataLocalTemppostinstall65825929496.sh: command not found
```
Can anyone explain this?

**Comment by zloirock** [comment]
`core-js` haven't [any postinstall `.sh` files](https://unpkg.com/browse/core-js@3.23.5/), so it comes not from that.

`core-js` have a [`postinstall.js`](https://unpkg.com/browse/core-js@3.23.5/postinstall.js) file that can show a banner and it can fail only if you haven't `node` in your path or you haven't access to a temp directory.

**Comment by bricss** [comment]
I still have the same error even when I run clean install w/o of `package-lock.json`  
And at least can you explain how/why its trying to execute `sh` script?
Does it mean that release version got compromised?
