### ISSUE TITLE
Closure Compiler Compatibility with Safari 8 and IE9 Minifying Array.from

### ISSUE THREAD

**Issue by jacobangel** [zloirock/core-js#111]
We ran into an issue where Array.from was minifying incorrectly. 

[Google Closure Output on es6.array.js](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A'use%2520strict'%253B%250Avar%2520ctx%2520%2520%2520%2520%2520%2520%2520%2520%2520%253D%2520require('.%252F%2524.ctx')%250A%2520%2520%252C%2520%2524def%2520%2520%2520%2520%2520%2520%2520%2520%253D%2520require('.%252F%2524.def')%250A%2520%2520%252C%2520toObject%2520%2520%2520%2520%253D%2520require('.%252F%2524.to-object')%250A%2520%2520%252C%2520call%2520%2520%2520%2520%2520%2520%2520%2520%253D%2520require('.%252F%2524.iter-call')%250A%2520%2520%252C%2520isArrayIter%2520%253D%2520require('.%252F%2524.is-array-iter')%250A%2520%2520%252C%2520toLength%2520%2520%2520%2520%253D%2520require('.%252F%2524.to-length')%250A%2520%2520%252C%2520getIterFn%2520%2520%2520%253D%2520require('.%252Fcore.get-iterator-method')%253B%250A%2524def(%2524def.S%2520%252B%2520%2524def.F%2520*%2520!require('.%252F%2524.iter-detect')(function(iter)%257B%2520Array.from(iter)%253B%2520%257D)%252C%2520'Array'%252C%2520%257B%250A%2520%2520%252F%252F%252022.1.2.1%2520Array.from(arrayLike%252C%2520mapfn%2520%253D%2520undefined%252C%2520thisArg%2520%253D%2520undefined)%250A%2520%2520from%253A%2520function%2520from(arrayLike%252F*%252C%2520mapfn%2520%253D%2520undefined%252C%2520thisArg%2520%253D%2520undefined*%252F)%257B%250A%2520%2520%2520%2520var%2520O%2520%2520%2520%2520%2520%2520%2520%253D%2520toObject(arrayLike)%250A%2520%2520%2520%2520%2520%2520%252C%2520C%2520%2520%2520%2520%2520%2520%2520%253D%2520typeof%2520this%2520%253D%253D%2520'function'%2520%253F%2520this%2520%253A%2520Array%250A%2520%2520%2520%2520%2520%2520%252C%2520mapfn%2520%2520%2520%253D%2520arguments%255B1%255D%250A%2520%2520%2520%2520%2520%2520%252C%2520mapping%2520%253D%2520mapfn%2520!%253D%253D%2520undefined%250A%2520%2520%2520%2520%2520%2520%252C%2520index%2520%2520%2520%253D%25200%250A%2520%2520%2520%2520%2520%2520%252C%2520iterFn%2520%2520%253D%2520getIterFn(O)%250A%2520%2520%2520%2520%2520%2520%252C%2520length%252C%2520result%252C%2520step%252C%2520iterator%253B%250A%2520%2520%2520%2520if(mapping)mapfn%2520%253D%2520ctx(mapfn%252C%2520arguments%255B2%255D%252C%25202)%253B%250A%2520%2520%2520%2520%252F%252F%2520if%2520object%2520isn't%2520iterable%2520or%2520it's%2520array%2520with%2520default%2520iterator%2520-%2520use%2520simple%2520case%250A%2520%2520%2520%2520if(iterFn%2520!%253D%2520undefined%2520%2526%2526%2520!(C%2520%253D%253D%2520Array%2520%2526%2526%2520isArrayIter(iterFn)))%257B%250A%2520%2520%2520%2520%2520%2520for(iterator%2520%253D%2520iterFn.call(O)%252C%2520result%2520%253D%2520new%2520C%253B%2520!(step%2520%253D%2520iterator.next()).done%253B%2520index%252B%252B)%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520result%255Bindex%255D%2520%253D%2520mapping%2520%253F%2520call(iterator%252C%2520mapfn%252C%2520%255Bstep.value%252C%2520index%255D%252C%2520true)%2520%253A%2520step.value%253B%250A%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%257D%2520else%2520%257B%250A%2520%2520%2520%2520%2520%2520for(result%2520%253D%2520new%2520C(length%2520%253D%2520toLength(O.length))%253B%2520length%2520%253E%2520index%253B%2520index%252B%252B)%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520result%255Bindex%255D%2520%253D%2520mapping%2520%253F%2520mapfn(O%255Bindex%255D%252C%2520index)%2520%253A%2520O%255Bindex%255D%253B%250A%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520result.length%2520%253D%2520index%253B%250A%2520%2520%2520%2520return%2520result%253B%250A%2520%2520%257D%250A%257D)%253B)

The bad line is: 

```js
// es6.array.js line 26
      for(result = new C(length = toLength(O.length)); length > index; index++){
```
which minifies to:
```js
for (e = new c(c = toLength(b.length));c > a;a++) {
```

What is counterintuitive, is that Safari will run the code fine when it is run from the top context, but breaks when run in a function context. Here is an example of the offending pattern in action:

```js
function runTheSameCode() {
  var ctor = Array;
  var newInstance = new ctor(ctor=1);
  return newInstance;
}

var ctor = Array;
var newInstance = new ctor(ctor=1);
console.log('now watch this...', newInstance);

try {
  var c = runTheSameCode();
  console.log('here is the value of the function:', c);
} catch (e) {
  console.log('I caught an error: %s', e.message);
}
``` 

### Safari 8.0.8
![screen shot 2015-09-24 at 10 48 05 am](https://cloud.githubusercontent.com/assets/169159/10076484/ce58eb7c-62a9-11e5-8c5d-5f3016328959.png)

### Chrome
![screen shot 2015-09-24 at 10 49 02 am](https://cloud.githubusercontent.com/assets/169159/10076521/f39c3a7e-62a9-11e5-94a2-3878889dd4f0.png)

This is stemming from closure compiler inferring this it can save a variable reference. Simply moving the length assignment outside of the new Array should [fix this issue](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A'use%2520strict'%253B%250Avar%2520ctx%2520%2520%2520%2520%2520%2520%2520%2520%2520%253D%2520require('.%252F%2524.ctx')%250A%2520%2520%252C%2520%2524def%2520%2520%2520%2520%2520%2520%2520%2520%253D%2520require('.%252F%2524.def')%250A%2520%2520%252C%2520toObject%2520%2520%2520%2520%253D%2520require('.%252F%2524.to-object')%250A%2520%2520%252C%2520call%2520%2520%2520%2520%2520%2520%2520%2520%253D%2520require('.%252F%2524.iter-call')%250A%2520%2520%252C%2520isArrayIter%2520%253D%2520require('.%252F%2524.is-array-iter')%250A%2520%2520%252C%2520toLength%2520%2520%2520%2520%253D%2520require('.%252F%2524.to-length')%250A%2520%2520%252C%2520getIterFn%2520%2520%2520%253D%2520require('.%252Fcore.get-iterator-method')%253B%250A%2524def(%2524def.S%2520%252B%2520%2524def.F%2520*%2520!require('.%252F%2524.iter-detect')(function(iter)%257B%2520Array.from(iter)%253B%2520%257D)%252C%2520'Array'%252C%2520%257B%250A%2520%2520%252F%252F%252022.1.2.1%2520Array.from(arrayLike%252C%2520mapfn%2520%253D%2520undefined%252C%2520thisArg%2520%253D%2520undefined)%250A%2520%2520from%253A%2520function%2520from(arrayLike%252F*%252C%2520mapfn%2520%253D%2520undefined%252C%2520thisArg%2520%253D%2520undefined*%252F)%257B%250A%2520%2520%2520%2520var%2520O%2520%2520%2520%2520%2520%2520%2520%253D%2520toObject(arrayLike)%250A%2520%2520%2520%2520%2520%2520%252C%2520C%2520%2520%2520%2520%2520%2520%2520%253D%2520typeof%2520this%2520%253D%253D%2520'function'%2520%253F%2520this%2520%253A%2520Array%250A%2520%2520%2520%2520%2520%2520%252C%2520mapfn%2520%2520%2520%253D%2520arguments%255B1%255D%250A%2520%2520%2520%2520%2520%2520%252C%2520mapping%2520%253D%2520mapfn%2520!%253D%253D%2520undefined%250A%2520%2520%2520%2520%2520%2520%252C%2520index%2520%2520%2520%253D%25200%250A%2520%2520%2520%2520%2520%2520%252C%2520iterFn%2520%2520%253D%2520getIterFn(O)%250A%2520%2520%2520%2520%2520%2520%252C%2520length%252C%2520result%252C%2520step%252C%2520iterator%253B%250A%2520%2520%2520%2520if(mapping)mapfn%2520%253D%2520ctx(mapfn%252C%2520arguments%255B2%255D%252C%25202)%253B%250A%2520%2520%2520%2520%252F%252F%2520if%2520object%2520isn't%2520iterable%2520or%2520it's%2520array%2520with%2520default%2520iterator%2520-%2520use%2520simple%2520case%250A%2520%2520%2520%2520if(iterFn%2520!%253D%2520undefined%2520%2526%2526%2520!(C%2520%253D%253D%2520Array%2520%2526%2526%2520isArrayIter(iterFn)))%257B%250A%2520%2520%2520%2520%2520%2520for(iterator%2520%253D%2520iterFn.call(O)%252C%2520result%2520%253D%2520new%2520C%253B%2520!(step%2520%253D%2520iterator.next()).done%253B%2520index%252B%252B)%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520result%255Bindex%255D%2520%253D%2520mapping%2520%253F%2520call(iterator%252C%2520mapfn%252C%2520%255Bstep.value%252C%2520index%255D%252C%2520true)%2520%253A%2520step.value%253B%250A%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%257D%2520else%2520%257B%250A%2520%2520%2520%2520%2520%2520length%2520%253D%2520toLength(O.length)%253B%250A%2520%2520%2520%2520%2520%2520for(result%2520%253D%2520new%2520C(length)%253B%2520length%2520%253E%2520index%253B%2520index%252B%252B)%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520result%255Bindex%255D%2520%253D%2520mapping%2520%253F%2520mapfn(O%255Bindex%255D%252C%2520index)%2520%253A%2520O%255Bindex%255D%253B%250A%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520result.length%2520%253D%2520index%253B%250A%2520%2520%2520%2520return%2520result%253B%250A%2520%2520%257D%250A%257D)%253B).

**Comment by sebmck** [comment]
If this bug is with the closure compiler then why not report the bug there and get them to fix it?

**Comment by jacobangel** [comment]
The bug is not with closure compiler, it is with safari 8. The javascript generated is valid, and there is no way to target the safari versions in closure. 

It compiles this way because of the inline assignment, and cannot be avoided without rewriting this code.

**Comment by zloirock** [comment]
Bug in Safari, unsafe optimization in Closure Compiler... I don't think completely correct code should be "fixed" in `core-js`. I don't use Closure Compiler, but, I think, unsafe optimizations can be disabled.

**Comment by jacobangel** [comment]
Unfortunately, I don't believe this is an unsafe optimization, the closure compiler examples I linked to are using basic settings. This is purely a bug in safari8/ie9's interpretation of the javascript.

**Comment by zloirock** [comment]
This optimisation can break code in [many other places](https://github.com/zloirock/core-js/blob/master/modules/es6.number.constructor.js#L16-L17), not only this line. This issue should be in Closure Compiler repo.
