### ISSUE TITLE
Update core-js-compat data

### ISSUE THREAD

**Issue by ScubaDaniel** [zloirock/core-js#1111]
I'm using the babel `preset-env` plugin with the following targets:
```
ie >= 9
chrome >= 42
firefox >= 38
safari >= 12
edge >= 12
```

The `core-js-compat` data states that IE cannot support `es.regexp.test`, yet caniuse.com states otherwise: https://caniuse.com/mdn-javascript_builtins_regexp_test

It also states that IE cannot support `es.string.split`, yet caniuse.com states otherwise: https://caniuse.com/mdn-javascript_builtins_string_split

It also states that IE 9 cannot support `es.json.stringify`, yet caniuse.com states otherwise: https://caniuse.com/mdn-javascript_builtins_json_stringify

It also states that Chrome 49 is the first one to support `es.regexp.sticky`, yet caniuse.com states otherwise: https://caniuse.com/?search=regexp%20constructor

These are only three of the polyfills I've found to be included when they should not, but I'm confident there are even more. I'm trying to minimize the size of my bundles, so this is obviously concerning.

**Comment by zloirock** [comment]
You can run http://zloirock.github.io/core-js/compat/ to make sure that the current results for them are correct. Take a look at  [the tests source](https://github.com/zloirock/core-js/blob/master/tests/compat/tests.js) - it's a little more complex than just the existence of those methods.
