### ISSUE TITLE
`Array.prototype.at` is not polyfilled event set target to "Chrome 87", which is supported after "Chrome 92"

### ISSUE THREAD

**Issue by AndyBoat** [zloirock/core-js#1114]
I'm not sure if I made some mistake,  I will appreciate any response or help 

I'm using `create-react-app` ,  and set polfyill steps according to [official docs](https://create-react-app.dev/docs/supported-browsers-features/)  I fond a compatibility about `Array.prototype.at` API on 360 Browser, which packaged Chrome 86 as its core;

I believe `create-react-app`  uses babel inside to polfyill

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at#browser_compatibility) , The `Array.prototype.at` is available from Chrome 92;  But I realized that I have set browserlist in packages.json to ` > 0.2%` , ant it includes Chrome 87,  so it should polyfil `.at`  API, which it doesn't;

We can take thie [demo project](https://github.com/AndyBoat/polyfill-react-app-js/blob/main/src/index.js) for example

I wonder if it is expected behavoir?  If so, how can I polyfill all features by core-js for Chrome 86? Because I dont want my team-member to check caniuse list  and identify every feature that have issue with Chrome 86; 

Or is there any mistake I made or any step I missed?

**Comment by AndyBoat** [comment]
BTW , the only way I can make polyfill works is to force import like:
```js
import R from "core-js/stable";
import React from "react";
import ReactDOM from "react-dom/client";
import "./index.css";
import App from "./App";
import reportWebVitals from "./reportWebVitals";

// eslint-disable-next-line no-unused-expressions
R;

//...
```

I believe it is quite ugly and not meet the degisned usage

**Comment by zloirock** [comment]
I have no idea how you polyfill it since I can't find this information in this issue. However, since I see something about targets, most likely you use Babel or SWC. The most common issue in this case - you should specify the current minor `core-js` - for example, `corejs: '3.24'` in Babel.

**Comment by AndyBoat** [comment]
@zloirock Thanks for reply!
Yes ,  as I know, the `create-react-app` uses bable inside to do polyfill things ;
I will have a try ~

**Comment by zloirock** [comment]
Also, if `.at` is used inside your dependencies - you should transpile those dependencies by Babel or SWC.

**Comment by AndyBoat** [comment]
Its clearly this is a problem related to @babel/preset-env usage  packaged by `create-react-app`, I will put some workaround under the issue above, and close this issue , thanks!

**Comment by Slava-Ini** [comment]
Had the similar issue, not related to React
`require('core-js/modules/es.array.at.js')` wasn't imported in the result file
Thanks to @zloirock explicitly setting `corejs` minor version solves the issue - I'm using `corejs: 3.32`
Versions are located [here](https://github.com/zloirock/core-js/blob/master/CHANGELOG.md)
