### ISSUE TITLE
Iterator Helpers return value

### ISSUE THREAD

**Issue by 2767mr** [zloirock/core-js#1116]
When using iterator helpers such as `.map` and calling `.return` on them it will return the value of the next result, instead of undefined.

An example:
```js
import 'core-js/proposals/iterator-helpers';

var x = Iterator.from({next() {return {value: 1, done: false}}, return() {return {value: 10, done: false}}}).map(x => x + 100);
x.next();
console.log(x.return()); //Should print { done: true, value: undefined } but prints { done: true, value: 10 }
```

This is probably because of https://github.com/zloirock/core-js/blob/4c9c6d6187b906c14f41b84d3ac992c6d3e2aeb8/packages/core-js/internals/iterator-create-proxy.js#L51 which checks if result (referred to by the spec as `innerResult`) is an object but then returns the result instead of the provided `completion`, which at that point should always be `undefined`.

The spec I am referring to: https://tc39.es/ecma262/#sec-iteratorclose
Core.js version: 3.24.1

**Comment by zloirock** [comment]
Hmm, need to dig here, but now I'm a little busy. Could you specify the complete order of operations why it should return `{ done: true, value: undefined }`?

**Comment by 2767mr** [comment]
IT = Iterator Helpers specification (https://tc39.es/proposal-iterator-helpers/)
ES = https://tc39.es/ecma262/

1. [IT 3.1.4.1.2] %IteratorHelperPrototype%.return: Entrypoint
2. (1.) `C = undefined`
3. (2.) Calls `GeneratorResumeAbrupt(this, C)`
4. [ES 27.5.3.4] GeneratorResumeAbrupt
5. (1.) Calls `Validate()` successfully
6. (2.) Not taken
7. (3.) Not taken
8. (4.-10.) Execute `genContext` until next yield/return and store result in `result`
9. Continues in [IT 3.1.6.2 - 3.a.vi.]
10. (vi.) `completion = return[undefined]`
11. (vii.) `IfAbruptCloseIterator(completion, iterated)` same as `IfAbruptCloseIterator(return[undefined], iterated)`
12. [ES 7.4.8] IfAbruptCloseIterator
13. (2.) If is taken: `return[undefined]` is abrupt
14. [ES 7.4.7] IteratorClose
15. (3.) `innerResult = Completion(iterator.return)`
16. (4.) If is taken: `return` exists
17. (4.a.-c.) `innerResult = Completion(iterator.return())`
18. (5.) Not taken: `completion` is `return`
19. (6.) Not taken: `return` is `normal[{...}]`
20. (7.) Not taken
21. (8.) return `completion` same as `return[undefined]`
22. Continues in [ES 7.4.8 - 2.]: return `return[undefined]`
23. Continues in [ES 27.5.3.1 - 4.b.ii]
24. (4.b.ii.) `result = return[undefined]`
25. (c.-f.) complete generator
26. (g.) Not taken
27. (h.) `resultValue = result.value` = `undefined`
28. (i.) Not taken
29. (j.) return `{done: true, value: resultValue}` = `{done: true, value: undefined}`

I hope it helps

**Comment by zloirock** [comment]
Thanks.
