### ISSUE TITLE
Add `"sideEffects": false` in `package.json` of `core-js-pure` package for proper Webpack tree-shaking

### ISSUE THREAD

**Issue by roshecode** [zloirock/core-js#1117]
If possible please add `"sideEffects": false,` in [`package.json`](https://github.com/zloirock/core-js/blob/master/packages/core-js-pure/package.json#L9) of `core-js-pure` package similar as it was done for [lodash](https://github.com/lodash/lodash/blob/master/package.json#L10) in [this PR](https://github.com/lodash/lodash/pull/3533) to let Webpack to tree-shake code. Webpack by default treats `core-js-pure` as it has side effects, but in reality it's side effect free ("pure"), so adding this flag will instruct Webpack to remove `core-js-pure` imports (in case they are not used further in code because of some conditions) leading to a smaller bundle size.

**Comment by zloirock** [comment]
Hmm, thanks, it could be a great addition. However, I'm not totally sure how it works and that it could be totally safe because of some specific cases. I'll explore it.

**Comment by zloirock** [comment]
It seems `"sideEffects": ["./modules/*.js"]` should work.

**Comment by roshecode** [comment]
It works, thank you!
