### ISSUE TITLE
corejs.version:'3.15' not work with @babel/preset-env

### ISSUE THREAD

**Issue by h1orz** [zloirock/core-js#1126]
```
@babel/preset-env: 7.19.1
core-js: 3.25.2
```
I use `Array.prototype.groupBy` in my code, sometime `@babel/preset-env` not work, `@core-js/proposals/array-grouping` not import automatic. Webpack config like this:
```js
[
  '@babel/preset-env',
  {
    useBuiltIns: 'usage',
    corejs: {
      version: 3, // not work
      // version: '3.0', // not work
      // version: '3.15', // not work
      // version: '3.16', // work
      // version: '3.20', // work
      // version: '3.22', // work
      proposals: true
    },
    modules: false,
  },
]
```
When version >= ’3.15‘, `@babel/preset-env` can't import automatic. Is that some condition in there?

**Comment by zloirock** [comment]
It works fine. Make sure that you use the latest `core-js-compat` and Babel packages like `babel-plugin-polyfill-corejs3`.

**Comment by zloirock** [comment]
BTW the actual name of this method is `Array.prototype.group`, however, the old should work too.

**Comment by zloirock** [comment]
```js
      // version: '3.15', // not work
      // version: '3.16', // work
```

Why

**Comment by h1orz** [comment]
> ```js
>       // version: '3.15', // not work
>       // version: '3.16', // work
> ```
> 
> Why it should work with `corejs: '3.15'` if it was added in [`3.16`](https://github.com/zloirock/core-js/blob/ea7645f83b1df744c687bce222138ff68a42d0dc/packages/core-js-compat/src/modules-by-versions.mjs#L100)?

Got it! I didn't find it. Thx!
