### ISSUE TITLE
Question: stability of symbols

### ISSUE THREAD

**Issue by guybedford** [zloirock/core-js#113]
How much can one rely on Symbol string values of this implementation?

I'm wondering if the following is a suitable shim for `Symbol.toStringTag` without including core-js:

```javascript
// use native Symbol.toStringTag or Core-JS "Symbol(Symbol.toStringTag)" value
var toStringTag = typeof Symbol != 'undefined' && Symbol.toStringTag || 'Symbol(Symbol.toStringTag)';
function getToStringTag(m) {
  return m[toStringTag];
}
```

Would the above be stable with respect to Core-js upgrades? Or is this completely unadvisable?

**Comment by zloirock** [comment]
Sorry, I do not exactly understand this question and example.

`Symbol.toStringTag` is something like `'Symbol(Symbol.toStringTag)_4.09coiy03b47'` for prevent collisions, if you mean this. For use eqaul well-known symbols between instances, `core-js` uses `window["__core-js_shared__"].wks.toStringTag`, but better don't use it - can be changed in the future - and just include `core-js/library/fn/symbol/to-string-tag` for get this key.

**Comment by guybedford** [comment]
Thanks for the quick response. I'm looking to see what the minimal code is to detect if a given JS object is an ECMAScript module namespace exotic object using http://www.ecma-international.org/ecma-262/6.0/#sec-@@tostringtag in a way that can work with CoreJS-base Symbol polyfilling as well as actual ES environments in future.

So the goal is to find the minimal detection without having to explicitly rely on core-js. If it's not possible though then that's fine, but these kinds of detections will likely be needed in future when dealing with module interops.

I did see in the code that there was hashing going on, but in my naive test of checking the string value of `Symbol.toStringTag` in core-js 1.1.4 I didn't actually get the trailing hash value:

```javascript
var symbol = require('core-js/es6/symbol');
console.log(Symbol.toStringTag); // "Symbol(Symbol.toStringTag)"
console.log(symbol.toStringTag);  // "Symbol(Symbol.toStringTag)"
```

Is the hash only sometimes generated, and is it always generated to the same value? If so then this function could be hard-coded as say:

```javascript
function isModule(m) {
  return typeof m == 'object' && m.__esModule || (m[Symbol.toStringTag || 'Symbol(Symbol.toStringTag)_4.09coiy03b47'] == 'Module');
}
```

without a dependence on core-js.

**Comment by zloirock** [comment]
@guybedford `"Symbol(Symbol.toStringTag)_4.09coiy03b47"` - only example, each time it unique. As I saw, you can get it as `global["__core-js_shared__"].wks.toStringTag`, it works from `0.9.12` and in near future it will not be changed. As an alternative, you can use detection like
```js
var keys = (Object.getOwnPropertySymbols ? Object.getOwnPropertySymbols : Object.getOwnPropertyNames)(Math);
var TO_STRING_TAG;
keys.forEach(function(key){
  if(Math[key] === 'Math')TO_STRING_TAG = key;
});
```
but `core-js` modular, it will work only if was included `es6.symbol` module, some tags can be added without this module.

**Comment by guybedford** [comment]
Thank you so much @zloirock for the detailed explanation despite my ignorance! Am I actually being completely dumb here, and the following would just work fine?

```javascript
var toStringTag = typeof Symbol != 'undefined' && Symbol.toStringTag;
function isModule(m) {
  return typeof m == 'object' && (m.__esModule || toStringTag && m[toStringTag]);
}
```

Or is there ever a mode in core-js where symbols are not written globally or could somehow interfere in the above?

**Comment by zloirock** [comment]
It will work only with a completely default version. In `library` version `core-js` does not add global polyfills (for example, `babel` uses it in `runtime`). And, as I said, some tags can be added w/o `es6.symbol` module.

Use something like
```js
var toStringTag = global.Symbol && Symbol.toStringTag
  || global["__core-js_shared__"] && global["__core-js_shared__"].wks
  && global["__core-js_shared__"].wks.toStringTag;
function isModule(m) {
  return typeof m == 'object' && (m.__esModule || toStringTag && m[toStringTag]);
}
```
should work quite correctly.
