### ISSUE TITLE
Saw you are looking for a job.

### ISSUE THREAD

**Issue by AbstractAlao** [zloirock/core-js#1132]
Figured this would be the best place to reach you.  You should consider applying to [Gigster.](https://gigster.com/)

https://jobs.lever.co/ionicpartners/0df8a7db-4773-4a10-badf-923040f8ee83

**Comment by zloirock** [comment]
It's not exactly what I'm looking for. See this post https://github.com/zloirock/core-js/blob/master/docs/2023-02-14-so-whats-next.md
