### ISSUE TITLE
Why can't I find the dependency   (core-js)

### ISSUE THREAD

**Issue by message163** [zloirock/core-js#1139]
![image](https://user-images.githubusercontent.com/32630999/197710427-660b4a3c-d7a1-403a-bc35-358226943bfe.png)
![image](https://user-images.githubusercontent.com/32630999/197710489-914fb3d3-15ab-4f05-804d-462203de5ced.png)

**Comment by zloirock** [comment]
As you can see, [all those modules are available in the package](https://unpkg.com/browse/core-js@3.26.0/modules/). Make sure that the proper `core-js` version is available in your `node_modules`, reinstall your dependencies, clean your NPM cache, etc. It's not a `core-js` issue.
