### ISSUE TITLE
Cannot find module '../internals/a-callable' in 3.26.0

### ISSUE THREAD

**Issue by foray1010** [zloirock/core-js#1140]
I am using core-js 3.26.0, and this bug does not exist in 3.25.5
There is no `internals/a-callable.js`, but it is referred by `internals/get-method.js`

**Comment by zloirock** [comment]
[Those files available in `core-js@3.26.0`](https://unpkg.com/browse/core-js@3.26.0/internals/a-callable.js). Make sure that you have installed `core-js@3.26.0` and if those files missed - clean NPM cache and reinstall dependencies.

**Comment by foray1010** [comment]
Interesting! It works after cleaning the yarn cache, thank you for the prompt response!
