### ISSUE TITLE
Uncaught TypeError: functionToString is not a function at store.inspectSource

### ISSUE THREAD

**Issue by yeli19950109** [zloirock/core-js#1141]
i use tools about under with Microsoft Edge 107.0.1418.26
```
    "core-js": "^3.26.0",
    "@babel/core": "^7.19.6",
    "@vue/cli-plugin-babel": "^5.0.8",
    "@vue/cli-plugin-typescript": "^5.0.8",
    "@vue/cli-service": "^5.0.8",    
    "webpack": "^5.74.0",
```
and got a error
```
Uncaught TypeError: functionToString is not a function
    at store.inspectSource (inspect-source.js?086c:10:1)
    at Function.toString (make-built-in.js?6604:48:1)
    at RegExp.exec (<anonymous>)
    at eval (is-constructor.js?2e30:13:1)
    at ./node_modules/core-js/internals/is-constructor.js (chunk-vendors.js:12574:1)
    at __webpack_require__ (app.js:2930:33)
    at fn (app.js:3233:21)
    at eval (array-species-constructor.js?00b1:2:1)
    at ./node_modules/core-js/internals/array-species-constructor.js (chunk-vendors.js:11765:1)
    at __webpack_require__ (app.js:2930:33)
```
but in google chrome 107.0.5304.88 is everything fine

**Comment by zloirock** [comment]
Please, add a reproducible example and specify the environment in which the error occurs.

**Comment by zloirock** [comment]
Also, please, add a list of **all** used `core-js` versions (`window['__core-js_shared__'].versions`).

**Comment by epmatsw** [comment]
We're seeing this with "3.25.4". No repro yet (working on that).

**Comment by epmatsw** [comment]
Still no repro, but our previous release with 3.25.2 didn't log any of these. Seems likely that it's the `uncurry-this` changes in there?

**Comment by zloirock** [comment]
Yes, see #1128 and #1133. I see that it can be related by the stack from initial comment, but that means that in your env
```js
Object.prototype.toString.call(Function.prototype.toString) !== '[object Function]'
```

**Comment by zloirock** [comment]
So, any news with a repro? Now it looks like a somehow broken environment.

**Comment by zloirock** [comment]
I removed the `classof` check from `uncurryThis` in cases where it's not required and it should be a workaround for cases of broken env like yours - but if you had this issue it's time to think about [what breaks your env](https://github.com/zloirock/core-js/issues/1141#issuecomment-1297545044) because it could break other cases.

**Comment by zloirock** [comment]
https://github.com/zloirock/core-js/releases/tag/v3.26.1
