### ISSUE TITLE
es.array.includes only supported in Firefox >= 102?

### ISSUE THREAD

**Issue by aKzenT** [zloirock/core-js#1147]
I noticed some unexpected Polyfills in my bundle, such as Array.prototype.includes when targetting firefox version 102 or lower. According to MDN and caniuse it should be fully supported from version 43 onwards:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes?retiredLocale=de
https://caniuse.com/array-includes

The compat list however states that it is only supported starting from Firefox 102:
http://zloirock.github.io/core-js/compat/

Is that a bug?

**Comment by zloirock** [comment]
Yes, Firefox 99-101 has a bug and does not handle holes as `undefined`.
```js
Array(5).includes(undefined); // => should be true
```
MDN too often contains incorrect or incomplete data.
