### ISSUE TITLE
Pure version of Number constructor

### ISSUE THREAD

**Issue by trosos** [zloirock/core-js#1154]
Hi,
Is there a technical or philosophical reason not to have a pure version of the `Number` constructor?

I would appreciate it for transpiling things like `Number("0b11")` (using babel-plugin-transform-runtime).

Thank you for a great project!

**Comment by zloirock** [comment]
Hi. It's a technical problem.

It's not a problem to add a pure polyfill for it, it's a problem to make it work with `babel-plugin-transform-runtime` as expected in all cases.

Initially, it was added, but it broke some projects.

For example, someone checks a type like this:

```js
const number = 1;

number.constructor === Number; // => true
```

But with runtime, we could have:

```js
const _Number = require(/* something */);

const number = 1;

number.constructor === _Number; // => false
```

and vice versa.

It can work as expected only in the case of patching built-in prototypes, but it contradicts the pure nature.
