### ISSUE TITLE
Structured cloning sparse arrays do not match browsers

### ISSUE THREAD

**Issue by cyreb7** [zloirock/core-js#1156]
I couldn't find anything in the spec as to how `structuredClone()` should handle sparse arrays, but all browsers I've tested handle them different from Core JS.

Core JS 3.26.1:
```
const sparseArray = structuredClone([,]);
console.log(sparseArray.length); // 0
console.log(0 in sparseArray); // false
```

Latest version of Chrome, FireFox, and Safari:
```
const sparseArray = structuredClone([,]);
console.log(sparseArray.length); // 1
console.log(0 in sparseArray); // false
```

**Comment by zloirock** [comment]
You are right, thanks.

![image](https://user-images.githubusercontent.com/2213682/207485330-3ce10681-ca7b-47b1-8ffd-dc0d68e4f4eb.png)
