### ISSUE TITLE
Remove RegExp.escape

### ISSUE THREAD

**Issue by benjamingr** [zloirock/core-js#116]
Sadly, two months ago my proposal has been rejected by the TC.

The good part is that there is work on a more extensive proposal using a tag that is completely safe. 

In the meanwhile, it might best to remove .escape from the polyfill.

**Comment by zloirock** [comment]
Yes, thanks, I know it.

I think, it should be available as minimum before adding an alternative of this method. It will be moved to the non-standard (`core`) namespace. It's breaking change and I don't know when it will be done.
