### ISSUE TITLE
`Object.keys` / ` Object.entries` from `Map` polyfill returns unusual values in IE11

### ISSUE THREAD

**Issue by mkszepp** [zloirock/core-js#1160]
I'm using [Ember.Js](https://github.com/emberjs/ember.js) as framework, which is using `babel` / `core-js` to get polyfills for old browsers.

The build from my repo works fine, but on IE11 i was running in an error, which is maybe caused from `Map` polyfill.

### Code Example:

```
var x = new Map();
console.log(x.size);
console.log(Object.keys(x));
console.log(Object.entries(x));
```

### Behavier on IE11:
The `console.log` of `size` returns `0`, which is correct.
The `console.log` of `Object.keys` returns maybe internal properties and `length` of `5`.
The `console.log` of `Object.entries` returns an array with `length` of `5` & error `Zeichenfolge erwartet` (maybe in EN `String expected`)

I think the keys `[_t, _i, _f, _l, _s]` are internal from polyfill, because it is unusual.

![grafik](https://user-images.githubusercontent.com/19845290/211489437-025355ff-fa16-40bc-b8bb-fea9ae444317.png)

### Expected behavier (like in FF, Chrome...):
The `console.log` of `size` returns `0`, which is correct.
The `console.log` of `Object.keys` returns `length` of `0` and no keys.
The `console.log` of `Object.entries` returns an array `length` of `0` and no error

![grafik](https://user-images.githubusercontent.com/19845290/211489720-940b6b48-ec38-4c2d-808d-8eda7cb6762e.png)

### Enviroment / Sources:
core-js: 3.27.1
Browser: Internet Explorer 11
Repo, in which i have done the console.log output manually: [build.zip](https://github.com/zloirock/core-js/files/10380060/build.zip)
Ember.js repo: https://github.com/mkszepp/promise-bug-ie11
issue on Ember.js: https://github.com/emberjs/ember.js/issues/20347#issuecomment-1375897594

**Comment by zloirock** [comment]
Those keys are present only in `core-js@2-`, it seems you use some `core-js` copies and some of them are obsolete.

**Comment by zloirock** [comment]
It seems `ember-cli-babel` imports `core-js@2.6.12` since you use the obsolete `includePolyfill` option.

**Comment by mkszepp** [comment]
@zloirock right, thanks for the info
