### ISSUE TITLE
Errors related to btoa/atob in IE11 after upgrading to latest core-js version

### ISSUE THREAD

**Issue by tardiva** [zloirock/core-js#1161]
After upgrading core-js in our app to latest 3.27.1 version we found that the app stopped working in IE11. Seems that the last stable version for us is 3.21.1 and critical changes were made [here](https://github.com/zloirock/core-js/commit/6edcde930736b0ac094fa69d31429629d80c0c51#diff-c1d72cebdf325ffb937cce7bf31e56c56941eb2452cb25646da90e28bf1734f0).

I prepared minimal [example](https://github.com/tardiva/core-js-example) for reproducing the issue.

Run npm start in main branch and note that alert is shown in Chrome but it is not shown in IE11

Then change the [branch](https://github.com/tardiva/core-js-example/tree/core-js-v-21) to use core-js version 3.21.1. Note that alert works as expected in both browsers.

**Comment by zloirock** [comment]
It seems a webpack devserver bug that incorrectly eval code. Usual compiled without `eval` works fine.

**Comment by zloirock** [comment]
Similar to #62

**Comment by zloirock** [comment]
I added a workaround.
