### ISSUE TITLE
main.ts depends on 'core-js/es7/reflect' and Error: Module not found: Error: Can't resolve 'core-js/es/reflect'

### ISSUE THREAD

**Issue by gexleu** [zloirock/core-js#1162]
I'm using Angular 15.0.4 and when I run ng serve -o to launch my app, the app doesn't compile and run, and I get this message:

```
√ Browser application bundle generation complete.

Initial Chunk Files   | Names         |  Raw Size
vendor.js             | vendor        |   3.55 MB |
styles.css, styles.js | styles        | 351.25 kB |
polyfills.js          | polyfills     | 314.27 kB |
main.js               | main          |  72.00 kB |
runtime.js            | runtime       |   6.51 kB |

                      | Initial Total |   4.28 MB

Build at: 2023-01-11T15:32:28.997Z - Hash: 7b4d3ef0affc1690 - Time: 7179ms

Warning: C:\work-temp\angular-example\QuickCBT\src\main.ts depends on 'core-js/es7/reflect'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies



./src/main.ts:4:0-29 - Error: Module not found: Error: Can't resolve 'core-js/es/reflect' in 'C:\work-temp\angular-example\QuickCBT\src'



** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


× Failed to compile.
```
How can I fix this?

I should note that I already installed core-js@2.5.x by running npm install --save core-js@^2.5.0, following the answers of this question: [Error: Can't resolve 'core-js/es7/reflect' in '\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models](https://stackoverflow.com/questions/55398923/error-cant-resolve-core-js-es7-reflect-in-node-modules-angular-devkit-bui)

**Update**: I installed core-js@3 and the second error disappeared, but the first error persists.

Here is the output now:

```
ng serve -o √ Browser application bundle generation complete.

Initial Chunk Files   | Names         |  Raw Size vendor.js            | vendor        |   3.58 MB | styles.css, styles.js | styles        |
351.25 kB | polyfills.js          | polyfills     | 314.27 kB | main.js               | main          |  72.00 kB | runtime.js         | runtime       |   6.51 kB |

                      | Initial Total |   4.30 MB

Build at: 2023-01-11T16:43:11.909Z - Hash: 77cd44828399b547 - Time: 8190ms

Warning: C:\work-temp\angular-example\QuickCBT\src\main.ts depends on 'core-js/es/reflect'. CommonJS or AMD dependencies can cause optimization bailouts. For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies



./src/main.ts:6:0-30 - Error: Module not found: Error: Can't resolve 'core-js/es7/reflect' in 'C:\work-temp\angular-example\QuickCBT\src'



** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


× Failed to compile.
```

**Comment by zloirock** [comment]
It's absolutely different features - [ES2015+ `Reflect` API](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Reflect) and obsolete [`Reflect` metadata proposal](https://github.com/rbuckton/reflect-metadata). `core-js/es/reflect` is present in `core-js@3` and missed in `core-js@2` (here it's `core-js/es6/reflect`). `core-js/es7/reflect` is present in `core-js@2` and missed in `core-js@3` (here you can load all  `Reflect` features as `core-js/full/reflect`). Resolving conflicts of your dependencies is your work.

Make sure that all your imports use one (better - modern) `core-js` version.
