### ISSUE TITLE
update core-js

### ISSUE THREAD

**Issue by ebazhanglang** [zloirock/core-js#1167]
hi!
   I'd like to ask you a question,I have an old project that needs to upgrade core-js. The reason is that the user detected the vulnerability of JavaScript library, so I need to upgrade core-js. However, my old project needs to upgrade from version 2.6.9 to the latest return error and there are many dependencies

The following is a picture of the absence dependence
[Deletion dependence.md](https://github.com/zloirock/core-js/files/10529113/Deletion.dependence.md)

**Comment by zloirock** [comment]
It seems you didn't upload the picture.

**Comment by zloirock** [comment]
See [this old post](https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md). In `core-js@3` the most of modules were renamed.

**Comment by ebazhanglang** [comment]
Hi, I may be stupid, but I still don't understand haha.

**Comment by zloirock** [comment]
If you use Babel or SWC, update your config and specify the latest `core-js@3` minor version. If you use `core-js` manually, just update imported entries manually as specified in the post from the comment above and in the docs.

**Comment by ebazhanglang** [comment]
I'm using babel, I'm also introducing these two in the entry file, the babel file also sets `useBuiltIns `  to  `entry`, and I also have configure `targets ` why am I being told to set `targets ` after I type in the command to run the project

The following is the screenshot.

![3](https://user-images.githubusercontent.com/110316089/215381185-1bc33a25-57e3-443f-9657-59e163be0761.png)

**Comment by ebazhanglang** [comment]
The babel used in the project I introduced these two in the entry file, and the babel also changed the configuration 'useBuiltIns':'entry', also set the version, and I set the ’targets‘. Why do I have to set the ’targets' when I run the code?

![3](https://user-images.githubusercontent.com/110316089/215381738-acdaf822-527f-4684-b80e-e46c0623a0d5.png)

**Comment by zloirock** [comment]
As an option, it could be an obsolete Babel version. You could ask it in their repo.

**Comment by ebazhanglang** [comment]
Ok, thank you for your reply
