### ISSUE TITLE
The proposal polyfill "Array.uniqueBy" does not work in ie11

### ISSUE THREAD

**Issue by limingcan562** [zloirock/core-js#1171]
Hello author, I have a problem, I want to use the proposal polyfill (`Array.uniqueBy`) in ie11 but it doesn't work

## Input code
````js
// Entry document
const data = [
    { id: 1, uid: 10000 },
    { id: 2, uid: 10000 },
    { id: 3, uid: 10001 }
]
const final_data = data.uniqueBy(it => it.uid); 
console.log(final_data);
````
## Configuration
````js
// babel.config.js
const presets = [
    [
        '@babel/preset-env',
        {
            debug: true,
            targets: "ie 11",
            useBuiltIns: "usage",
            corejs: {
                version: '3.27.2',
                proposals: true
            }
        }
    ]
];
module.exports = {presets};

// package.json
"dependencies": {
    "core-js": "^3.27.2"
  },
 "devDependencies": {
    "@babel/cli": "^7.20.7",
    "@babel/core": "^7.20.12",
    "@babel/preset-env": "^7.20.2",
    "babel-loader": "^9.1.2",
    "webpack": "^5.75.0",
    "webpack-cli": "^5.0.1"
 }
````

> **This [repository](https://github.com/limingcan562/babel-use-proposals-problem) allows you to see more configurations and to reproduce problems.**

## Running in ie 11
![error](https://user-images.githubusercontent.com/45028746/216020413-9816e738-ea1d-4a3b-95b7-48538fe86a21.png)

I don't know why this is happening, is there something wrong with my configuration?

**Comment by zloirock** [comment]
On IE11 VM with ful loaded `core-js` it works fine:

![image](https://user-images.githubusercontent.com/2213682/216025218-bca6cc8c-bfb9-4a4f-a727-90309bc976d5.png)

I'll check your repo a little later.

**Comment by zloirock** [comment]
I looked at this. This is a Babel issue. It should also import `Map` polyfill, but it's missing in the bundle. However, it's present' in built-in definitions, https://github.com/babel/babel-polyfills/blob/798db9d4b3e3096fd6fc5b48c2fedd78e948b6b8/packages/babel-plugin-polyfill-corejs3/src/built-in-definitions.ts#L877
