### ISSUE TITLE
How to disable rule to fix core-js wrongly using require where it is undefined?

### ISSUE THREAD

**Issue by Slapbox** [zloirock/core-js#1173]
Specifically we have a [worklet](https://developer.mozilla.org/en-US/docs/Web/API/Worklet) where we use `array.push` and it adds in:

`require("core-js/modules/es.array.push.js");` - which results in `Uncaught ReferenceError: require is not defined`

I tried `const require = () => {}` and `global.require = () => {}` without any luck.

**Comment by Slapbox** [comment]
Our only option to work around it seems to be to use `array.concat` but that's a mess. Is there a recommended way to handle this?

**Comment by zloirock** [comment]
For usage in a worklet, it should be bundled - use, for example, Webpack. If you don't wanna use it - figure out why it's injected - for example, it can be Babel or SWC option for injecting `core-js`.

**Comment by Slapbox** [comment]
Thanks for your reply @zloirock.

We actually are using Webpack and `core-js` never gets wrongly injected into any workers - just this worklet, and actually nor did it get injected with Electron `18.x` but it apparently does with `20.x` - this is true for both `core-js@3.23` and `3.27`.

Specifically it's a [layout worklet](https://github.com/w3c/css-houdini-drafts/blob/main/css-layout-api/EXPLAINER.md#getting-started) which are pretty cutting edge. I don't know if that's making a difference in feature detection?

We had to enable it in Chromium (technically Electron) using [`--enable-experimental-web-platform-features` ](https://peter.sh/experiments/chromium-command-line-switches/)- but that's actually a rather reasonable thing in our case because it is an Electron app and we can control the environment.

Is there anything you can think for us to do?

**Comment by zloirock** [comment]
If you have `Uncaught ReferenceError: require is not defined` - it's just not bundled via Webpack, look for the error here.

**Comment by Slapbox** [comment]
Thanks again for your reply @zloirock.

The file is server by Webpack with a random name on each page refresh and the code is transformed - but I guess that could be just Babel doing it?

Electron has a stricter security model than Chromium - are you sure the above would be true? You can't use `require` in the Electron `renderer` process that spawns the worklet.

Is there a way I can be sure it's not processed by Webpack?

----

But also, it worked in the previous version of Electron so I also have to ask, why is it only suddenly polyfilling now? The code looks identical except for the `require("core-js/modules/es.array.push.js");` that's now inserted at the top. Are you sure there couldn't be a feature detection problem here?

**Comment by zloirock** [comment]
If you have `require("core-js/modules/es.array.push.js")` in the output - it's not bundled via Webpack since Webpack replaces `require` to own helpers.

It's injected since used `.push` - and actual V8 has a bug with `Array#push`.
