### ISSUE TITLE
Очередной идеальный пример, как не надо делать

### ISSUE THREAD

**Issue by Vasiliy-Makogon** [zloirock/core-js#1188]
Далек от мира JS, но ситуация интересная. На самом деле ты не первый, в своё время тему финансирования затронул автор пакета Faker.js и [намеренно сломал своё решение](https://ebanoe-it.ru/2022/01/11/%d0%b0%d0%b2%d1%82%d0%be%d1%80-faker-js-%d0%bd%d0%b0%d0%bc%d0%b5%d1%80%d0%b5%d0%bd%d0%bd%d0%be-%d1%81%d0%bb%d0%be%d0%bc%d0%b0%d0%bb-%d1%81%d0%b2%d0%be%d0%b8-%d0%bf%d0%b0%d0%ba%d0%b5%d1%82%d1%8b-%d0%b8/).  

Все, что происходит - это идеальный пример, как НЕ НАДО делать. А именно - работать бесплатно, вестись на розовые сопли об открытом исходном коде, читать лозунги на Хабре, вестись на красивые призывы "сделаем мир лучше" и тратить тысячи человеко-часов на поддержку кода, за который тебе не платят.  Но ты, будучи специалистом начавшим ещё в 2012, так и не захотел понять, в какой среде ты варишься: 

> Вместо благодарности я вижу только **огромную ненависть со стороны разработчиков**, которым я упрощаю жизнь.

и что именно ты делаешь:

>  Я не думал о десятках тысяч долларов судебных исков, оставшихся после аварии. Я не думал о своем будущем. **Я думал о лучшем будущем Интернета**

Прости, но ты сам себе злобный буратино. О будущем Интернета он думал.. Да, оказывается можно быть в IT и 10 и 20 лет, но оставаться наивным чудаком, играющим в игрушки при наличии потрясающих мозгов. Ты должен был думать не об будущем Интернета, а о своем будущем. 

Есть условный Денис Пушкарев,  а есть условный Павел Дуров (семья Дуровых). Один в итоге сидит без денег, другой долларовый миллиардер. 

Эта история прекрасна во всём. Она показывает, что нет никакого смысла затрачивать в жизни огромные усилия в то, что невозможно монетизировать. Нет никакого смысла делать бесплатно работу для тех, кто потом приходит и пишет в твой адрес гневные комментарии (программисты в основной массе токсичные и мерзкие люди, лично я за 20 лет в IT насмотрелся на них сполна). 

Нужно хотеть денег, нужно желать деньги, всегда нужно получать за свою работу деньги, а не играть в благотворительность.

**Comment by javadev** [comment]
Вроде бы спонсор для библиотеки. Потом почему-то пропал. Теперь новые появятся.

**Comment by Vasiliy-Makogon** [comment]
> Вроде бы спонсор для библиотеки. Потом почему-то пропал. Теперь новые появятся.

Речь кардинально о другом. С наличием мозгов нужно зарабатывать, гребсти бабло нагло и безапелляционно, а не искать "спонсоров". Спонсоров девочки на "мамбе" ищут.

**Comment by javadev** [comment]
> > Вроде бы спонсор для библиотеки. Потом почему-то пропал. Теперь новые появятся.
> 
> Речь кардинально о другом. С наличием мозгов нужно зарабатывать, гребсти бабло нагло и безапелляционно, а не искать "спонсоров". "Спонсоров" ищут девочки на "мамбе".

Могут и на работу принять с договором и ДМС.

**Comment by diimpp** [comment]
![image](https://user-images.githubusercontent.com/870747/218994079-ea4e0347-b169-4d8c-8821-1908e8c0cc5b.png)

- Коммиты пушатся на прямую в мастер
- Неинформативные коммит сообщения уровня джуна/проекта на 3 человека
- Отсутвие issue/pr с объяснением происходящего, в коммит сообщениях развернутого описания нет
- Случайная верификация коммитов через один

Если добавить commit lint, заблокировать прямой пуш в мастер и описывать изменения прежде им их делать, то и меинтейнерам будет проще в проект заходить, и бизнесу обосновывать свои траты, как на стандарт индустрии, а не чей-то пет проект

**Comment by Vasiliy-Makogon** [comment]
> Коммиты пушатся на прямую в мастер
> Неинформативные коммит сообщения уровня джуна/проекта на 3 человека

Ну это и называется **токсичность**. Докопаться до коммитов, до мастера, до лишнего пробела в коде, до чего угодно. Суть только в том, что его пуши в мастер не отменяют значимость его "пет проекта". Если кому-то это не нравится - можете писать свои наработки в строго-академическом стиле. 

> и бизнесу обосновывать свои траты, как на стандарт индустрии

Не будет бизнес ничего ему платить, даже если он форки будет делать и писать длинные человекопонятные сообщения для коммитов. 
Тут подход не верный, благотворительность - зло.

**Comment by javadev** [comment]
> > Коммиты пушатся на прямую в мастер
> > Неинформативные коммит сообщения уровня джуна/проекта на 3 человека
> 
> Ну это и называется **токсичность**. Докопаться до коммитов, до мастера, до лишнего пробела в коде, до чего угодно. Суть только в том, что его пуши в мастер не отменяют значимость его "пет проекта". Если кому-то это не нравится - можете писать свои наработки в строго-академическом стиле.
> 
> > и бизнесу обосновывать свои траты, как на стандарт индустрии
> 
> Не будет бизнес ничего ему платить, даже если он форки будет делать и писать длинные человекопонятные сообщения для коммитов. Тут подход не верный, благотворительность - зло.

Уже платит, не?

![image](https://user-images.githubusercontent.com/348496/219006094-52dc276f-e0f9-4ac4-977a-67a3f64d050f.png)

**Comment by dynamicult** [comment]
> программисты в основной массе токсичные и мерзкие люди

А остальне люди не токсичные в основной своей массе? Давно вы заглядывали в любое сообщество, где сидят не программисты? Ну, какой нибудь паблик вк, одноклассники, реддит, твиттер?

Может дело не в программистах, а  в том, что люди в массе своей таковы в принципе?

То же касается хейта в сторону разработчиков. Откройте любой ресурс публичной поддержки любого коммерческого продукта и вы, возможно. будете поражены тому, что там совершенно нет положительных отзывов о работе какой-либо компании, предоставляемых их услугах или программном обеспечении.  А все потому, что о положительном никто не пишет.

**Comment by zloirock** [comment]
Hey, it's rather should be as a comment to #1179.
