### ISSUE TITLE
Error with Getters and Setters: Object Expected (IE8)

### ISSUE THREAD

**Issue by bmakuh** [zloirock/core-js#119]
Right now I `require('core-js')` via Browserify-rails, but then when I load up the page in IE8, I get an error (Object Expected) on this line:

```js
if('get' in Attributes || 'set' in Attributes)throw TypeError('Accessors not supported!');
```

**Comment by zloirock** [comment]
You uses `Object.defineProperty` / `Object.defineProperties` / `Object.create` with getters / setters. In ES3 is no way to add accessors, IE8 supports it only on DOM objects, so we generate this error.

Duplicate #84, #74.

**Comment by txiaocao** [comment]
i has some problem.how to do?

**Comment by blling** [comment]
What is the solution?  one of a 3rd lib use it :(

**Comment by zloirock** [comment]
@blling there is no solution. You can propose this change to the 3rd library, replace this library to something else or stop support IE8.
