### ISSUE TITLE
Is babel-plugin-polyfill-corejs3 deprecated / production ready?

### ISSUE THREAD

**Issue by NicolasBonduel** [zloirock/core-js#1191]
My understanding is that there are currently three non-deprecated ways to use corejs with babel.

1. For most use-cases, with `@babel/preset-env`. It will create polyfills and pollute the global context. It is possible to target only specific browsers and use a subset of scripts from `core-js`.
2. For libraries, with `@babel/plugin-transform-runtime` and `@babel/runtime-corejs3`. It will use `core-js-pure` and thus create pure polyfills (or ponyfills). It is not possible to target specific browsers with this method.
3. `babel-plugin-polyfill-corejs3` seem to offer the best of both worlds, for use-cases where we have a target list, but also cannot afford to pollute the global context. I cannot find a lot of documentations about it, besides on their github page. It is not mentioned here, or on babel's documentation.

Can I use `corejs` through `babel-plugin-polyfill-corejs3` instead of using `@babel/preset-env` or `@babel/runtime-corejs3` at this time? What do you recommend?

**Comment by zloirock** [comment]
It is production ready (at least the global modes). It's used under the hood of `preset-env`. IIRC there were some possible problems in the `pure` mode. Most likely, such separate plugins will be the preferable way in the future.
