### ISSUE TITLE
You get much hatred – so take some love from me.

### ISSUE THREAD

**Issue by 0unknwn** [zloirock/core-js#1193]
Your story sounds plausible to me. 

So I just wanted to tell you, that I can feel you.

I wish the very best for you and your family and hope that there will be a way to keep on working on your nice project.

**Comment by zloirock** [comment]
Thanks -) However, I'm closing this since #1179 is a better place for this.

**Comment by 0unknwn** [comment]
Thanks for pointing me there. I really love to see all the support there and hope something will really change for you!
