### ISSUE TITLE
About sponsorship channels

### ISSUE THREAD

**Issue by SWHL** [zloirock/core-js#1194]
hello, I saw your posting and it was very emotional. Because we are both a people who like open source.

Since I am in China, I hope you will have Alipay sponsorship channels so that it will be more convenient for us to sponsor you in China.

Attached is a [link](https://mysourcify.com/how-to-register-an-alipay-account-outside-china/) on how to register for an Alipay account. 

[Link](https://github.com/RapidAI/RapidOCR): This is the example of how Alipay is used in the appreciation channel of the project I maintain.

**Comment by a554878526** [comment]
Yes, I also want to help the author

**Comment by immortal-oe** [comment]
Me too.

**Comment by Ale6333499** [comment]
Me too.

**Comment by Ale6333499** [comment]
I think those developers who accuse the author have no conscience and are not worthy of being human. I am also in Beijing. If possible, I would like to ask the author to publish the channels for easy donations in China. Thank you very much.

**Comment by zuisong** [comment]
I want to help the author too.

**Comment by warmthsea** [comment]
可以注册 PayPal

**Comment by selicens** [comment]
> 可以注册 PayPal

作者在俄罗斯，文中有提到PayPal不给他们提供服务

**Comment by KevinMX** [comment]
> opencollective 可以使用贝宝

No.

https://opencollective.com/opencollective/updates/payments-to-individuals-in-russia-and-ukraine1

> Update: Please note that as of 5th of March [PayPal is also suspending its services to Russia](https://opencollective.com/redirect?url=https%3A%2F%2Fwww.reuters.com%2Fbusiness%2Fpaypal-shuts-down-its-services-russia-citing-ukraine-aggression-2022-03-05%2F) meaning that right now there is no effective way for us to support payments to Russian contributors. We will post further updates once this situation changes.

**Comment by zloirock** [comment]
@KevinMX I can withdraw money from OpenCollective, it's not a problem.

**Comment by zloirock** [comment]
I have some minor problems with Alipay. I will try to solve them in the next some days.

**Comment by zloirock** [comment]
I've added Alipay:

![**Alipay**](https://user-images.githubusercontent.com/2213682/219464783-c17ad329-17ce-4795-82a7-f609493345ed.png)

**Comment by rujptw** [comment]
thanks for your contribute @zloirock ,I donate a little,hope you and your family can live well and health
