### ISSUE TITLE
A better testing alternatives which provides IE headless testing down to IE9

### ISSUE THREAD

**Issue by aleen42** [zloirock/core-js#1195]
In the project [core-web](https://github.com/aleen42/core-web), I have figured out a testing alternative where I can test down to IE9 headless within GitHub Actions for the polyfills of Web APIs, and the corresponding configuration is: https://github.com/aleen42/core-web/blob/main/karma.config.js, I hope it can give you a favour.

**Comment by zloirock** [comment]
@aleen42 thanks. I used something like that before on local karma tests. However, emulation mode has a significant difference from real IE. Maybe makes sense to add it to GitHub Actions too, I'll think about it.

**Comment by zloirock** [comment]
I added IE11 with Karma to GitHub actions. Since at this moment, I am mainly working on `core-js@4` that drops IE10- support, I don't think that the rest makes sense.

**Comment by aleen42** [comment]
Good job!
