### ISSUE TITLE
About sponsorship channels（erc20 address）

### ISSUE THREAD

**Issue by anlia260** [zloirock/core-js#1196]
hello, I saw your posting and it was very emotional. Because we are both a people who like open source.

I hope you will have `erc20 address` sponsorship channels so that it will be more convenient for us to sponsor you in web3.

Attached is a [metamask](https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn?hl=zh-CN) on how to register for an eth account.

**Comment by channely** [comment]
Try to transfer token through OpenCollective's [crypto-channel](https://opencollective.com/core-js/donate?interval=oneTime&amount=30) works well. It's just that the author don't get the money in real time. I get a successful notice a day later.
<img src="https://user-images.githubusercontent.com/3193212/219301226-8bd9da58-cff8-4b01-a606-82c1f1fa33dc.jpeg" width="300px">

**Comment by anlia260** [comment]
Nice .
![image](https://user-images.githubusercontent.com/11311553/219308786-3c4f64f9-c5b3-4acc-bc5a-e0fbda87f42c.png)

**Comment by zloirock** [comment]
Absorbed by https://github.com/zloirock/core-js/issues/1209 to avoid duplications.
