### ISSUE TITLE
Can you open an account that supports Alipay? In China, almost everyone has Alipay.

### ISSUE THREAD

**Issue by zhmt** [zloirock/core-js#1199]
We saw your article translated into chinese, I think some of us will support you!

**Comment by GanZiheng** [comment]
How about WeChat pay (doge

**Comment by Thecosy** [comment]
I can pay my all qq coins

**Comment by DreamerKadars** [comment]
I admire your dedication very much and are willing to pay.

**Comment by DreamOfIce** [comment]
Also, in the current situation, using a payment method from China is probably the more reliable option. And Alipay is probably the most widely supported one that qualifies

**Comment by zloirock** [comment]
Could you try it?

![**Alipay**](https://user-images.githubusercontent.com/2213682/219464783-c17ad329-17ce-4795-82a7-f609493345ed.png)

**Comment by zloirock** [comment]
@12189108 yep, thanks -)
