### ISSUE TITLE
Consider debuggable promises

### ISSUE THREAD

**Issue by benjamingr** [zloirock/core-js#12]
Unlike native promises are intended to eventually and unlike promise libraries like when, bluebird and rsvp and like older libraries - the Promise shim does not perform any form of unhandled rejection tracking.

This means that a promise that failed but does not have a `catch` handler attached will perform a silent failure creating debuggability issues since your code would fail but you would not know where.

ES6 does not include any `done` like method to explicitly terminate a chain because modern promise libraries as well as native promises now can in practice detect unhandled rejections pretty well.

Please consider adding unhandled rejection tracking to the promises shim so the promises will no longer silently fail by default.

**Comment by zloirock** [comment]
How do you propose catch and handle them?

**Comment by benjamingr** [comment]
Usually the simple heuristic is "no catch handler has been attached for 2 seconds". Or even "no catch handler has been attached synchronously"

Native promises utilize GC for this which is impossible in our case - in practice the above heuristics work fantastically.

**Comment by gaearon** [comment]
Yes please!

I like what Bluebird is doing: [`onPossiblyUnhandledRejection`](https://github.com/petkaantonov/bluebird/blob/master/API.md#promiseonpossiblyunhandledrejectionfunction-handler---undefined) + [`onUnhandledRejectionHandled`](https://github.com/petkaantonov/bluebird/blob/master/API.md#promiseonunhandledrejectionhandledfunction-handler---undefined).

**Comment by daliwali** [comment]
:-1: I think that core-js should not handle more than what is already in the Promise spec.

**Comment by sebmck** [comment]
Related [v8#3093](https://code.google.com/p/v8/issues/detail?id=3093&sort=priority&colspec=ID%20Type%20Status%20Priority%20Owner%20Summary%20HW%20OS%20Area%20Stars).

**Comment by benjamingr** [comment]
@daliwali wait wat? You _want_ silent failures?

io.js is during a PR
to patch these in core, WhatWG is specifying this and promise libraries are implementing this (I wrote a Q PR last week, when added reporting, bluebird has it, in RSVP it's on the way) but somehow you think the people using core-JS deserve to suffer from an unusable and undebuggable implementation?

**Comment by benjamingr** [comment]
@zloirock the algorithm I used in Q and Petka used in bluebird and io.js is "run after every microtask" basically

**Comment by daliwali** [comment]
@benjamingr just saying that I think it should just have parity with the Promise spec and not do anything unexpected. If tomorrow the spec has fallback error handlers then it's ok.

**Comment by benjamingr** [comment]
@daliwali what spec? The unhandled rejection reporting is specified by the platform (node/browser etc)

I wrote the proposal for node/io.js which Petka implemented and io core staff reviewed - it's going to be discussed at the meeting Wednesday and added to io.js in 1.3 probably making this polyfill the only thing to actually silence errors and make debugging hard in node.

Similarly native promises in Firefox already do this and Chrome team are working on tooling to handle this to.

**Comment by zloirock** [comment]
@benjamingr Ok. More interesting action on such rejection. On node.js / io.js it's your [`process.emit('unhandledRejection', e, promise)`](https://gist.github.com/benjamingr/0237932cee84712951a2), but in browser? Only `console` message?

**Comment by benjamingr** [comment]
In browsers a console message is a good start, emitting window events is better but it requires adding around 100 lines of code to "get right" across browsers unless the infrastructure for firing a custom event cross-browser is already there. Moreover the events are still not as specified in browsers from what I can tell.

The link you posted (The Gist) contains links to the whatwg discussion about this as well as the relevant issues in promise libraries and in node.

**Comment by zloirock** [comment]
@benjamingr Added simple check on reject. What do you think?

**Comment by benjamingr** [comment]
I'm not sure - I'm not familiar with the code base - it needs to run after
everything else that was scheduled so for example the following should not
log anything:

    var p = Promise.reject();
    Promise.resolve().then(function(){
         p.catch(function(){});
    });

**Comment by zloirock** [comment]
@benjamingr Current `Promise` module codebase is spagetti, need fully rewrite it. You are right, such check is not suitable for returned promises, I'll fix it.

**Comment by benjamingr** [comment]
I'd probably go for a bluebird build with all the extra features disabled instead of a re-implementation since it's a very fast library that already does these events but yeah - I agree that the current code base could be nicer :)

**Comment by zloirock** [comment]
Current implementation uses not only microtask, can't simply add check on macrotask. Added check after 1 sec.

**Comment by benjamingr** [comment]
Sounds fun :) Thanks for fixing this!

**Comment by ysmood** [comment]
Here's an article to demonstrate how yaku wins native promise and bluebird on `unhandled expection`: https://github.com/ysmood/yaku/blob/master/docs/debugHelperComparison.md
Besides `unhandled exception`, `long stack trace` is also very important for debug.

Yaku is super lightweight, fast and error friendly, it pass all your unit tests. The gzipped size is 1.5KB, it even supports IE5.5+. Check all the other features on its readme.

@benjamingr @zloirock It meets all your needs. And recently, some of my projects are heavily depends on babel and core-js, we have to hack core-js to use yaku, to do so it hurts. So I start to think why not let yaku become a part of core-js?

**Comment by benjamingr** [comment]
Start by a) making it ES2015 compatible (rather than with non standard APIs and implement the unhandled rejection process events spec and we can talk :)

**Comment by ysmood** [comment]
@benjamingr On, I don't have to, it's already there, for example, we only add serveral lines in core-js, it will meet the process events spec:

```
Yaku.onUnhandledRejection = function (value, promise) {
    var handler, console;
    if(isNode){
      process.emit('unhandledRejection', value, promise);
    } else if(handler = global.onunhandledrejection){
      handler({promise: promise, reason: value});
    } else if((console = global.console) && console.error){
      console.error('Unhandled promise rejection', value);
    }
  };
```

Same works with iterable apis. I have already left the possibilities to end users.

**Comment by ysmood** [comment]
I will make a PR to demo how easily it is to port Yaku to core-js

**Comment by benjamingr** [comment]
You would also have to remove all the APIs that are non-standard as core-js is a shim.

**Comment by ysmood** [comment]
There's nothing like that. All the non-standard apis of Yaku is separated in to another module.

For example, you have to get them by `require('yaku/lib/sleep')`, if you `require('yaku')` you won't get  the `sleep` function.

**Comment by zloirock** [comment]
@ysmood interesting proposal, need to think about it. This issue was opened 9 months ago, too much was changed. Please, open the new issue. Currently, I think about rewriting `Promise` core, but only core - not methods, runtime tests, microtask implementation, etc.

> You would also have to remove all the APIs that are non-standard as core-js is a shim.

It's not required - `core-js` modular, full versions already contains non-standard API. The problem in some non-ES6-compat places. For example, by spec `this` in `Promise` executor should not be `Promise` instance. And main - `core-js` should use enough correct native implementations.

**Comment by ysmood** [comment]
Move this conversation to #115
