### ISSUE TITLE
Manually extract desired polyfill

### ISSUE THREAD

**Issue by OAguinagalde** [zloirock/core-js#1204]
This might a weird question (or an already answered one, couldn't find it) but...

If I wanted to get the polyfill for `Map` (for example) out of `core-js` without using any other tool or framework or whatever, so that I could use `Map` in my `ES5` `js` code, how could I go about it?

I'm not completely familiar with how polyfills work internally, I imagine that when I use a bundler and it "applies" a polyfill (taken out of `core-js`) it will do something like this:

Either my code is literally modified at the source-code level... or an implementation of `Map` is injected (as if I had done something like `require("core-js.Map")`) into my code. Or both?

I tried literally doing that but I'm a bit confused by looking at the source code of `core-js`. And `Babel` is way too big and I have no clue where I could start looking.

**Comment by zloirock** [comment]
It seems you mean `require('core-js/actual/map')`. See the second example a the top [here](https://github.com/zloirock/core-js/blob/master/ORIGINAL_README.md).
