### ISSUE TITLE
Polyfill getComputedStyle for IE8

### ISSUE THREAD

**Issue by SimenB** [zloirock/core-js#121]
Could `window.getComputedStyle` be polyfilled? https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle

It works in IE9

**Comment by zloirock** [comment]
I don't think it should be added. `core-js` adds not only ECMAScript polyfills, but not platform (browser in this case) specific. It can be added only if in the future will be changed this conception.
