### ISSUE TITLE
Delete excessive private debates and take community action on unreasonable people!

### ISSUE THREAD

**Issue by jack9603301** [zloirock/core-js#1218]
STOP NOW! It is suggested that the author delete the Chinese debate including me and keep the English part. What I have said is all facts, so I hope to help you to the greatest extent. However, some low-quality Chinese netizens have made unreasonable accusations on the details of community governance And argue, please take appropriate community governance measures for all unfriendly commenters after deleting the comments!

I hope the author is well, pay attention to the facts, return to the correct open source route, find a job or make money in your country or internationally as a freelancer or other e-commerce status, I hope you have your own job, come on!

This is the last comment and I will stop further debate on unreasonable people! Again, come on, promise

Related PRs

https://github.com/zloirock/core-js/issues/1179

**Comment by zloirock** [comment]
@jack9603301 please, stop spamming, or I will be forced to ban you. A couple of such comments were enough - everyone already understood your opinion.

**Comment by jack9603301** [comment]
@zloirock It's a clean-up request, and it's a comment on the end of the episode. What do you think?

**Comment by zloirock** [comment]
@jack9603301 now I'm trying to read all those debates. Will see.

**Comment by zloirock** [comment]
BTW thanks for your opinion. But it's size... too much -)

**Comment by jack9603301** [comment]
@zloirock Sorry to bother you. These comments are not directed at you. My suggestion to you has already ended in the previous comments. Unfortunately, I have to respond to the criticism of some Chinese netizens. Now, I don't want to argue. I know there is no point in arguing with these people. Clean him up and deal with these people when necessary.

Sorry for the harassment. I know issues are formal.


Apologize again

Sorry.
