### ISSUE TITLE
Let's remove all politics from the repo

### ISSUE THREAD

**Issue by gcruchon** [zloirock/core-js#1219]
In the README.md, stating "I don't want to choose between two kinds of evil" is a clear political statement.

As @zloirock declared in an issue: 
"It's not a place for politics, it's a place for code, goodbye."

_Originally posted by @zloirock in https://github.com/zloirock/core-js/issues/1051#issuecomment-1053487696_

Therefore, I'll send a PR to remove it.

**Comment by zloirock** [comment]
It's not a political statement.

**Comment by gcruchon** [comment]
Saying there are 2 evils is a judgment, it's saying that both side are evil. It's a political position.
It needs to be removed, else you are showing the whole world you are spreading Russian propaganda...

**Comment by zloirock** [comment]
Banned.
