### ISSUE TITLE
ImageData is not a constructor

### ISSUE THREAD

**Issue by victor-wm** [zloirock/core-js#1224]
I believe there is no polyfill for the ImageData built-in, but is there a reason why?

**Comment by zloirock** [comment]
`core-js` is a polyfill of ECMAScript features and features from some other closely related web standards. `ImageData` is not in the scope of `core-js`. Even if the scope will be extended, there are many more closely related to ECMAScript features.

**Comment by victor-wm** [comment]
Understood, thank you! Wasn't aware that there was this difference. Is the scope documented somewhere so myself and other people can just RTFM?

**Comment by zloirock** [comment]
The second sentence in the description:

![image](https://user-images.githubusercontent.com/2213682/226097128-4294c23e-4145-48bf-88f9-8612d3d10cc6.png)

The future options for web standards polyfills see in the roadmap: https://github.com/zloirock/core-js/blob/master/docs/2023-02-14-so-whats-next.md#web-standards-polyfills
