### ISSUE TITLE
DisposableStack is not set to disposed after move

### ISSUE THREAD

**Issue by davbrito** [zloirock/core-js#1226]
https://github.com/zloirock/core-js/blob/446aa802ebc37831c14c5f18be17d01189374bd5/packages/core-js/modules/esnext.disposable-stack.constructor.js#L91-L98

According to [the spec](https://tc39.es/proposal-explicit-resource-management/#sec-disposablestack.prototype.move), the state of the disposable should be set to disposed when moving the disposable:
[![image](https://user-images.githubusercontent.com/39559632/227091574-d7467f8d-1c34-4165-871a-4dcfd221b047.png)](https://tc39.es/proposal-explicit-resource-management/#sec-disposablestack.prototype.move)

**Comment by zloirock** [comment]
It seems you are right, thanks.
