### ISSUE TITLE
[Question] The behaviour of replacer function of `String.prototype.replace()` and `String.prototype.replaceAll()` 

### ISSUE THREAD

**Issue by DreamOfIce** [zloirock/core-js#1229]
For this function, I have found two implementations:

MDN's description(tested chromium and firefox both follow this implementation):
`String.prototype.replace()`: https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String/replace
`String.prototype.replaceAll()`: https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll

ECMAScript standard, core-js polyfill follows this specification:
`String.prototype.replace()`: https://tc39.es/ecma262/multipage/text-processing.html#sec-string.prototype.replace
`String.prototype.replaceAll()`: https://tc39.es/ecma262/multipage/text-processing.html#sec-string.prototype.replaceall

**Comment by DreamOfIce** [comment]
What is the cause of this? Should we add a note about this in the documentation?

**Comment by DreamOfIce** [comment]
Sorry, I missed the `RegExp[Symbol.replace]`, also MDN documentation has some problems.
I think it is necessary to remind the user in the documentation that the polyfill of `string.prototype.replace` (This contains the polyfill for `RegExp[Symbol.replace]`) should be included, otherwise the arguments of the replacer function may not consistent with the specification when searchValue is a regular expression.

**Comment by zloirock** [comment]
If you think so, feel free to improve it.
