### ISSUE TITLE
object.assign hasSymbols fails on `Object#toString`

### ISSUE THREAD

**Issue by ljharb** [zloirock/core-js#123]
When I add `if (Object.prototype.toString.call(Symbol() !== '[object Symbol]') { return false; }` or `if (Object.prototype.toString.call(Object(Symbol()) !== '[object Symbol]') { return false; }` to `hasSymbols`, my `core-js` tests fail. The latest version of `get-own-property-symbols` added support for this [here](https://github.com/WebReflection/get-own-property-symbols/commit/ad5e37dabdce5f8c891965ba8d266eba48b4f68e).

I'll leave the tests commented out for now so that `core-js` continues working - please implement this so I can uncomment them :-)

Thanks!

**Comment by zloirock** [comment]
It should not be passed **only** with `core-js/modules/es6.symbol` module. `module` path is itrernal API. Please, use, for example, `core-js/fn/symbol` and `core-js/fn/symbol/to-string-tag`.

**Comment by ljharb** [comment]
aha, thanks for clarifying - i'll require both of those in my tests.
