### ISSUE TITLE
how can i get the native version of Array.prototype.push ?

### ISSUE THREAD

**Issue by smallst** [zloirock/core-js#1230]
my project requires core-js in many places, and i don't want to get rid of core-js. but core-js makes `Array.prototype.push` to be 
```js
ƒ push(item) {
    var O = toObject(this);
    var len = lengthOfArrayLike(O);
    var argCount = arguments.length;
    doesNotExceedSafeInteger(len + argCount);
    for (var i = 0; i < argCount; i++) …
```  while the default `Array.prototype.push` is `ƒ push() { [native code] }` 
and sadly, `googleapi` uses (i guess) lodash.isNative to check Array.prototype.push which is a regex `/\[ native code \]/`. in core-js push it would breaks googleapi. 

i need googleapi and core-js both. what's the best practice to get native push back or ... other ways to make googleapi works together with core-js?
![image](https://user-images.githubusercontent.com/11417632/229066140-7e0420c0-83ac-4cf3-99a4-4eda2994038e.png)

**Comment by zloirock** [comment]
1. You could use https://github.com/zloirock/core-js#configurable-level-of-aggressiveness
2. You could exclude `Array.prototype.push` from the bundle - that depends on how `core-js` is included - for example, `exclude` option of `preset-env`.
3. You could find out why the reason - both - `core-js` and Google API - are used too often, but I still didn't see a such issue.

**Comment by smallst** [comment]
thank you. i don't know why googleapi and core-js, such common used pacakge would confict in my project. and, i don't know why finally i solve this issue by insert a `const uselessstring = '[native code']` since this line fix that stupid regex test. 😂  
i may try your suggestion later. thanks for replying. 
actually i also want to ask googleapi why they add such test. but i haven't find a way to ask them this question. so i ask here first.

**Comment by zloirock** [comment]
`core-js` have protection from this kind of issue:

https://github.com/zloirock/core-js/blob/v3.29.1/packages/core-js/internals/make-built-in.js#L50-L54

I don't know why it does not work in your case.

**Comment by smallst** [comment]
emm which version introduce this feature? i think some of my packge doesn't use the latest version. maybe i should try to upgrade them

**Comment by zloirock** [comment]
From `core-js@0.9.10` -) However, it can be a conflict of some versions, non-writable `Function.prototype.toString` and many other reasons.

**Comment by smallst** [comment]
okay. much thanks. finally i found one of my dependency install core-js as dependency instead of devDependency, and maybe conflict with my main repo. after change that dependency to dev one, everything goes well

**Comment by zloirock** [comment]
Could you write what was in `window['__core-js_shared__'].versions` before resolving the issue?

**Comment by smallst** [comment]
sure. 
in my dependency. there's only 3.26.1, which push.toString works normal.
![1680304896052](https://user-images.githubusercontent.com/11417632/229249091-6dbac8c7-3c69-4b8a-a43a-c8aedd030bca.jpg)

in my clean project, there's two versions, but push.toString still works normal.
![1680304336336](https://user-images.githubusercontent.com/11417632/229249122-35da6672-b986-4529-b0c8-5199113d0652.jpg)

in buggy project, there's 4 versions, and the push.toString breaks 
![1680304794822](https://user-images.githubusercontent.com/11417632/229249147-951e3667-4189-46ca-abf2-2889a06aa366.jpg)

----
but i also found a version which 4 versions still work:
![image](https://user-images.githubusercontent.com/11417632/229249339-192e7c1e-40bf-4d79-8192-38a5c3c4149a.png)


so i doubt, if the window['__core-js_shared__'].versions[0] is not the latest version, maybe toString breaks?

**Comment by zloirock** [comment]
Thanks. It looks like a problem of some old versions that have already been fixed.
