### ISSUE TITLE
Contact methods

### ISSUE THREAD

**Issue by universalpotato** [zloirock/core-js#1232]
Hi @zloirock,

Is there any way I can get in touch with you? Your email seems to be undeliverable right now.

**Comment by zloirock** [comment]
Hi @universalpotato, sorry for the delayed reply.

A couple of months some guys report that my main mailbox (zloirock@zloirock.ru) shows that it's full - but for the most users it works fine. I changed some settings - but it seems it's still a problem for someone.

You could use my alternative mailboxes - zloirock@ya.ru or zloirock@gmail.com.

Other ways to connect with me you could find here - [zloirock.ru](http://zloirock.ru).
