### ISSUE TITLE
[Solution] Object doesn't support this action

### ISSUE THREAD

**Issue by Taritsyn** [zloirock/core-js#1236]
For quite a long time, I thought that cause of this error was incompatibility of the `core-js` library with the  ActiveScript version of Chakra JavaScript engine (Internet Explorer 9 JavaScript engine), but I was wrong.

During discussion of this error with Denis at Open Source community meetup, it became clear that this problem requires in-depth research. To reproduce this error as cleanly as possible, I created a .NET console application (see the final version in the [TestCoreJsInActiveScriptJsEngine](https://github.com/Taritsyn/TestCoreJsInActiveScriptJsEngine) repository). The error was completely reproduced:

```
Object doesn't support this action
   at TestCoreJsInActiveScriptJsEngine.Resources.es6-polyfills.js:315:7
```

The error was thrown in the following code fragment:

```
…
309  var defineProperty$1 = Object.defineProperty;
310
311  var defineGlobalProperty$3 = function (key, value) {
312    try {
313      defineProperty$1(global$6, key, { value: value, configurable: true, writable: true });
314    } catch (error) {
315      global$6[key] = value;
316    } return value;
317  };
…
```

From the code fragment, it was clear that at some point the global object became read-only. After a series of experiments, I realized that the cause of error is in my C# code, and specifically in the call of `EmbedHostObject` method:

```csharp
…
engine = new MsieJsEngine(settings);
engine.EmbedHostObject("someObj", new SomeClass());
engine.ExecuteResource(polyfillsResourceName, assembly);
engine.Evaluate("var arr = Array.of(3);");
int arrayLength = engine.Evaluate<int>("arr.length;");
…
```

This method is responsible for embedding of .NET object to script and is called before the code of polyfill is executed. Refusing to call of the `EmbedHostObject` method solves this problem, but this way did not suit me.

Internally, this method is implemented as a call of the [`IActiveScript.AddNamedItem`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.debugger.interop.iactivescript.addnameditem) with two flags: `SCRIPTITEM_ISVISIBLE` and `SCRIPTITEM_GLOBALMEMBERS`. Unsetting the `SCRIPTITEM_GLOBALMEMBERS` flag completely solves this problem.

As a result, the cause of error was the incorrect usage of the standard ActiveScript API. Similar problems can also occur on earlier versions of the ActiveScript JavaScript engines (for example, on engines that implemented in the `jscript.dll` library).

Special thanks to Denis for discussing this problem!

**Comment by zloirock** [comment]
Thanks for the discussion and your research, maybe it will help someone else -)
