### ISSUE TITLE
trying to contact Denis P.

### ISSUE THREAD

**Issue by ngounaris** [zloirock/core-js#1244]
Denis,
I have been trying to reach you via Twitter and email, but haven't heard back from you yet; I hope you are well.

I am a professor of law and practicing attorney with over 20 years experience; you can find my professional bio set out on Georgetown Law’s website, as well as UVA Law’s and Washington & Lee’s respective websites. For the past 18 months we have been developing OS.Cash, a new way to license successful open-source projects so the software remains free for all (except Billion Dollar Businesses, who purchase a license for use).

I've read with interest how you continue to maintain and keep Core-JS active, despite personal and financial hardship. From what I have understood, your experience is entirely consistent with what is (painfully, cruelly) inefficient with open-source.

Can you make time for a Zoom call with me tomorrow or the day after to discuss this; I have a proposition that I would like to discuss with you. I'm in Greece now (in terms of time zones); would your afternoon suit?

Sincerely,
Nestor Gounaris
OS.Cash
[www.os.cash](http://www.os.cash/)

**Comment by ngounaris** [comment]
Denis,

I have been trying to reach you via Twitter and email, but haven't heard back from you yet; I hope you are well.

I am a professor of law and practicing attorney with over 20 years experience; you can find my professional bio set out on Georgetown Law’s website, as well as UVA Law’s and Washington & Lee’s respective websites. For the past 18 months we have been developing OS.Cash, a new way to license successful open-source projects so the software remains free for all (except Billion Dollar Businesses, who purchase a license for use).

I've read with interest how you continue to maintain and keep Core-JS active, despite personal and financial hardship. From what I have understood, your experience is entirely consistent with what is (painfully, cruelly) inefficient with open-source.

Can you make time for a Zoom call with me tomorrow or the day after to discuss this; I have a proposition that I would like to discuss with you. I'm in Greece now (in terms of time zones); would your afternoon suit?

Sincerely,

Nestor Gounaris

OS.Cash

[www.os.cash](http://www.os.cash/)

**Comment by ngounaris** [comment]
Denis,
I have been trying to reach you via Twitter and email, but haven't heard back from you yet; I hope you are well.
I am a professor of law and practicing attorney with over 20 years experience; you can find my professional bio set out on Georgetown Law’s website, as well as UVA Law’s and Washington & Lee’s respective websites. For the past 18 months we have been developing OS.Cash, a new way to license successful open-source projects so the software remains free for all (except Billion Dollar Businesses, who purchase a license for use).
I've read with interest how you continue to maintain and keep Core-JS active, despite personal and financial hardship. From what I have understood, your experience is entirely consistent with what is (painfully, cruelly) inefficient with open-source.
Can you make time for a Zoom call with me tomorrow or the day after to discuss this; I have a proposition that I would like to discuss with you. I'm in Greece now (in terms of time zones); would your afternoon suit?
Sincerely,
Nestor Gounaris
OS.Cash
[www.os.cash](http://www.os.cash/)

**Comment by ngounaris** [comment]
My email is Nestor.Gounaris@os.cash.
 The error I've been getting when trying to email you is this:
- <[zloirock@zloirock.ru](mailto:zloirock@zloirock.ru)>: host mx.yandex.ru[77.88.21.249] said: 552 5.2.2 Mailbox
    size limit exceeded 1683196460-GYMX0Z8PG4Y0-tvs8Eka5 (in reply to end of

I would like to setup a video call with you to discuss further.

**Comment by ngounaris** [comment]
> Hey, I don't often check Twitter messages and I don't remember any email from you, it can be a problem with my mailbox. I'll check it. Could you leave your email address here?

Hi Denis, did you have a chance to email me? I would really like a chance to speak with you, and I think it may be a good opportunity for you as well, and certainly worth your time to at least hear me out and consider. 

Kind regards, 
Nestor

**Comment by zloirock** [comment]
Oops, I missed your answer. I'll write you right now.
