### ISSUE TITLE
Not Fount  Relative Modules

### ISSUE THREAD

**Issue by trcat** [zloirock/core-js#1247]
Version: 3.30.2

![image](https://github.com/zloirock/core-js/assets/23648263/519e1641-5774-444d-9b3e-404abf2354eb)

![image](https://github.com/zloirock/core-js/assets/23648263/6bc2f7f2-6d85-4758-a9a6-756c49c659ff)

**Comment by trcat** [comment]
I don't know what happend，and it’s works when I change version to 3.29.1

**Comment by zloirock** [comment]
Those modules are [present](https://unpkg.com/core-js@3.30.2/internals/a-callable.js) in the package, so it's an issue in your environment. Try to clean your `node_modules` and reinstall dependencies, if it will not help - clean the NPM cache.
