### ISSUE TITLE
Update proposal array grouping to use static methods

### ISSUE THREAD

**Issue by jsejcksn** [zloirock/core-js#1249]
The API has been modified. See:
- https://github.com/tc39/proposal-array-grouping/pull/47
- https://github.com/tc39/proposal-array-grouping/issues/54

**Comment by zloirock** [comment]
Thanks, I'm watching this. Sure, it will be updated soon, with [the rest changes from this meeting](https://github.com/babel/proposals/issues/88).

**Comment by jsejcksn** [comment]
> Thanks, I'm watching this. Sure, it will be updated soon, with [the rest changes from this meeting](https://github.com/babel/proposals/issues/88).

👍 Just making sure it's in the backlog.
