### ISSUE TITLE
feat!: use scope package names in v4

### ISSUE THREAD

**Issue by DreamOfIce** [zloirock/core-js#1251]
Currently core-js has 5 packages and should consider using scope

**Comment by zloirock** [comment]
Yes, thanks, [it's planned](https://github.com/zloirock/core-js/blob/master/docs/2023-02-14-so-whats-next.md#new-approaches-to-tooling-are-more-interesting).

![image](https://github.com/zloirock/core-js/assets/2213682/e974ce53-cabe-4653-9bce-26a3bcb70207)
