### ISSUE TITLE
Missing `return` in `AsyncDisposableStack.prototype.adopt` closure

### ISSUE THREAD

**Issue by 0f-0b** [zloirock/core-js#1258]
https://github.com/zloirock/core-js/blob/2db49d1740b391ec907f9dcaa21875212e7b9bc6/packages/core-js/modules/esnext.async-disposable-stack.constructor.js#L97-L99

[Relevant spec section](https://tc39.es/proposal-async-explicit-resource-management/#sec-asyncdisposablestack.prototype.adopt). The return value is eventually [passed to `Promise.resolve`](https://github.com/zloirock/core-js/blob/2db49d1740b391ec907f9dcaa21875212e7b9bc6/packages/core-js/modules/esnext.async-disposable-stack.constructor.js#L77) so it is observable.

**Comment by zloirock** [comment]
Hmm, you are rigth, thanks.
