### ISSUE TITLE
Configurator mishandles `AsyncIteratorPrototype` option

### ISSUE THREAD

**Issue by mhofman** [zloirock/core-js#1268]
https://github.com/zloirock/core-js/blob/d12cd84ffa2be90f67d31310041e82700a67cdc5/packages/core-js/configurator.js#L24

Looks like a typo where the value of the `AsyncIteratorPrototype` option is assigned to the `USE_FUNCTION_CONSTRUCTOR` shared storage.

**Comment by zloirock** [comment]
Yes, thanks, it's a copy-paste bug. Anyway, it's still not documented.
