### ISSUE TITLE
Promise.resolve is not bound to Promise object

### ISSUE THREAD

**Issue by dmail** [zloirock/core-js#127]
```javascript
Promise.resolve.call(null);
```
Running the above line of code throw an error when using core-js.

Using your librabry you get the error : Object is not a function at [line 230](https://github.com/zloirock/core-js/blob/v1.2.5/modules/es6.promise.js#L230)
Using firefox Promise it returns a promise fullfilled with `undefined`

I suggest to bind Promise functions (resolve, reject, race, all) to the constructor.

```javascript
resolve: function resolve(x){
    return isPromise(x) && sameConstructor(x.constructor, this)
      ? x : new this(function(res){ res(x); });
}.bind(PROMISE)
```

**Comment by zloirock** [comment]
It's not very convenient, but it's a correct behavior by the spec and FF bug, [see step 2 and note](http://www.ecma-international.org/ecma-262/6.0/#sec-promise.resolve).

**Comment by dmail** [comment]
I just figured this out when I saw the check useNative with firefox subclassing. Thanks you for the fast answer.

**Comment by medikoo** [comment]
> Binding constructor will break subclassing.

I think It's not really true. It's just `Promise` constructor functions that behave that way, e.g. you won't see that problem with `Array.from`, which you can freely call as `Array.from.call(null, [])`, and Array remains perfectly subclassable.

Still, that's just a side note, as indeed it's how it was specified, but I'm not sure why.

**Comment by zloirock** [comment]
@medikoo it's really true for a *bound*, not *default* constructor, like in `Array.from`. Why `Promise.resolve` by the spec does not use the same logic? No ideas, possible because before [this last-minute change](https://esdiscuss.org/topic/fixing-promise-resolve) it had `@@species` logic. It seems that soon we will have one more review of this logic for `Promise` methods, see [1](https://esdiscuss.org/topic/resolve-reject-on-promise-subclasses-and-species), [2](https://github.com/tc39/ecma262/issues/151), so you can mention current problem there.

**Comment by medikoo** [comment]
>  it's really true for a bound, not default constructor, like in Array.from

Thing is that, when it's _bound_ to `null` or `undefined` it just fallbacks to native, and it's highly expected, thanks to that we can use `from` in stand alone form as e.g. `var from = Array.from; from([]);`

Unfortunately it's not the case with `Promise.resolve` which to me looks as spec issue (it introduced  inconsistency to ECMAScript, as it's first ever case where constructor function needs to be called in context of constructor to not fail, so it's a first ever _"constructor method"_).
Do you have any reference to exact place where it was justified? I browsed links you provided but I didn't find it there.

**Comment by zloirock** [comment]
> Do you have any reference to exact place where it was justified?

...
> No ideas

It's also interesting for me.

@domenic can you explain?

**Comment by stefanpenner** [comment]
It's to make inheritance work, `this` is the inherited constructor for a static method like resolve/reject/race/all etc

**Comment by zloirock** [comment]
@stefanpenner sure, it's my answer from the first comment, question here - why `Promise` methods hasn't fallback for calling without context, like `Array.from` :)

**Comment by stefanpenner** [comment]
@zloirock thats what i get for quickly reading and answering on my phone :P

You are correct, `Array.from` appears to handle this more gracefully [sec-array.from 6.b.i](http://www.ecma-international.org/ecma-262/6.0/#sec-array.from) I suspect this could be added in some future iteration of the spec. Although yes, it would be great to get @domenic's context.
