### ISSUE TITLE
esm.sh importing process library due to core-js/internals/engine-is-node.js

### ISSUE THREAD

**Issue by cdrini** [zloirock/core-js#1277]
This was a strange issue.

Commit https://github.com/zloirock/core-js/commit/25e93739aa8623a47526cc65f2d8e5d68bd3b107 changed some code from `typeof global.process` to `typeof process`. Unfortunately this resulted in some part of esm.sh when transpiling for deno to think that the node library `process` needed to be imported. You can see it on the first line here: https://esm.sh/v130/@internetarchive/bookreader@5.0.0-64/deno/BookReader/BookReader.js . Searching that minified file for `__Process$` shows that it's only used by the code inside core-js/internals/engine-is-node.js . And rolling back to the version before that commit, v3.27.1 , fixes the issue and removes the import.

This import causes problems when used in esbuild, which cannot understand typescript imports out-of-the-box. And also process _shouldn't_ be imported here, because then the browser-side code will think this code is running inside node.

I'm not sure whether this is a bug in esbuild, esm.sh, or core-js, but core-js was the easiest spot to fix it for my project: https://github.com/internetarchive/bookreader/pull/1207 .

Apologies for the confusing problem! Can we revert the style changes of https://github.com/zloirock/core-js/commit/25e93739aa8623a47526cc65f2d8e5d68bd3b107 to go back to using `global` ?

**Comment by zloirock** [comment]
It's not a `core-js` issue, but I agree that it's better to add a workaround on the `core-js` side.

**Comment by cdrini** [comment]
:+1: Yeah that seems correct. Awesome, thank you so much @zloirock !
