### ISSUE TITLE
Suggestion: Modify the repo's branch protection rules to improve PR safety

### ISSUE THREAD

**Issue by santi100a** [zloirock/core-js#1283]
Hi, @zloirock! I hope you're having an awesome day!
I have a nice suggestion for you. It aims to improve the repo's security, since branch protection can prevent force-pushes or
deletion of the trunk codebase. 
I suggest that you:
- Require code review from you and/or your fellow admins
- Add status check requirement for the most essential CI tests

**Comment by santi100a** [comment]
- How to [require certain CI checks](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#require-status-checks-before-merging)
- How to [require code review](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#require-pull-request-reviews-before-merging)

**Comment by zloirock** [comment]
@santi100a thanks for your proposal. I thought about your proposal but decided to leave everything as it is since it will not seriously improve security, but, for example, it may complicate emergency releases, for which the passage of the CI is not required - there were precedents.
