### ISSUE TITLE
"$" symbol in file names

### ISSUE THREAD

**Issue by AStoker** [zloirock/core-js#129]
In the modules library, there are many files that start with `$`. When using TFS to manage projects, this is not allowed, as "$" are invalid characters for file names (https://msdn.microsoft.com/en-us/library/aa980550(v=vs.120).aspx#SourceControl).
What gives? Is there a reason why these files start with a "$"? This is a significant limitation for those who are using TFS (see stackoverflow issue too: http://stackoverflow.com/questions/32081002/team-foundation-error-with-the-in-the-path).

**Comment by zloirock** [comment]
Holy shit... Team Foundation Server limitations... What will be next? Dots in filenames? Oh, wait... [previous issue](https://github.com/rollup/rollup-plugin-commonjs/issues/3).

> What gives? Is there a reason why these files start with a "$"?

`$` is a mark that it's an internal module. Why `$`? It's non-alphabet character allowed in a variable name and in a file system path. Each additional character here - additional 0.5kb for minified code with `browserify` without `bundle-collapser` or with other bundlers which keeps a path, `internal.` instead of `$.` - +3.5kb.

I'll think that can be done.

**Comment by zloirock** [comment]
It's internal API, but too often I see something like [that](https://github.com/ampproject/amphtml/blob/1446675574301/src/custom-core-js-shim.js#L133), so if I'll change this prefix - it will be breaking change for many projects. Makes sense do it only on the next major release.

**Comment by AStoker** [comment]
Yah, TFS is not my favorite for a number of reasons, and this adds to it, but I'm limited to what we're using at the office. 
Thanks for explaining that all to me, I appreciate it. Is that something to look forward to in the next major release? Or is it too soon to tell?

**Comment by zloirock** [comment]
I'll change prefix in the next major release, but I have no ideas when it will be. If will be convenient to add enough breaking changes in the near future - instead of next minor release I'll publish the major release in the end of this or in the next month. Otherwise - only in the next year.

**Comment by mizrachiran** [comment]
@zloirock  Thank you so much for this fix.
I'm blocked on this one, can you publish a minor version to npm?

**Comment by AStoker** [comment]
Or maybe at least a pre-release version, that way dependencies that wrongly use your internal modules won't automatically get a breaking change, but those of us who need the change can manually get the pre-release.

**Comment by zloirock** [comment]
[2.0.0-alpha](https://github.com/zloirock/core-js/releases/tag/v2.0.0-alpha)
