### ISSUE TITLE
globalThis does not work with stable namespace

### ISSUE THREAD

**Issue by yuri-voloshyn** [zloirock/core-js#1290]
globalThis does not work with stable namespace (core-js/stable/global-this), only with full (core-js/full/global-this)

Version:  3.32.2

**Comment by zloirock** [comment]
What do you mean by "does not work"?

[`core-js/full/global-this`](https://github.com/zloirock/core-js/blob/master/packages/core-js/stable/global-this.js) imports [`core-js/es/global-this`](https://github.com/zloirock/core-js/blob/master/packages/core-js/es/global-this.js) that imports [`core-js/modules/es.global-this`](https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/es.global-this.js) that works as expected.

![image](https://github.com/zloirock/core-js/assets/2213682/3cde44a0-1aa6-4bc5-a9ed-ff006fb000c4)

Could you add a reproducible example?

**Comment by yuri-voloshyn** [comment]
Project to reproduce: https://github.com/yuri-voloshyn/core-js-issue-1290

Open build/index.html with Live Server

Open url in Safari 5.1

We will see the following messages in the console: https://github.com/yuri-voloshyn/core-js-issue-1290/blob/main/screenshot.jpg

![screenshot](https://github.com/zloirock/core-js/assets/32106701/689f453a-39bf-46da-b8bb-996c5054eb6a)

**Comment by zloirock** [comment]
In this example, in the bundle, `require("core-js/stable/global-this")` is just removed and not imported:
```js
// ...
!function() {
console.log("stable",window.globalThis);function load_full(){__webpack_require__(6060);}load_full();console.log("full",window.globalThis);
}();
```

I don't wanna dig into the reason, most likely it's related to your targets - anyway it's not a `core-js` issue.

**Comment by yuri-voloshyn** [comment]
Yes, I see that import is not included. But why? We have the same targets for both namespaces.

**Comment by zloirock** [comment]
I don't know how `react-app-rewired` works with polyfills optimization, so at first glance, I can’t determine the reasons. It just removes this import at build. You could ask them.

**Comment by yuri-voloshyn** [comment]
I added `react-app-rewired` to the example just to disable optimization, the same behavior is observed without it.

**Comment by zloirock** [comment]
If it happens with `@babel/preset-env`, ask here: https://github.com/babel/babel-polyfills - I don't know what else could remove this import.

**Comment by zloirock** [comment]
The correct output should be
```js
!function() {
__webpack_require__(9758);console.log("stable",window.globalThis);function load_full(){__webpack_require__(6060);}load_full();console.log("full",window.globalThis);
}();
```
and in this case, everything works fine.
