### ISSUE TITLE
Did finally pass correct value when `onFinally` isn't a function?

### ISSUE THREAD

**Issue by manyuemeiquqi** [zloirock/core-js#1297]
When i view this line [finally](https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/es.promise.finally.js), i confused this case 

```typescript
new Promise((resolve, reject) => {
  resolve("1");
})
  .finally(2)
  .then((res) => {
    console.log("res: ", res);
  });

```
finally should return value or reason whether the `onFinally` is a function or not
---

Should replace 

 ` return promiseResolve(C, onFinally()).then(function () { return x; });
      } : onFinally,`
 with

  ` return this.then(
      isFunction ? function (x) {
        return promiseResolve(C, onFinally()).then(function () { return x; });
      } : x, `

**Comment by zloirock** [comment]
Everything works fine. See the spec:

![image](https://github.com/zloirock/core-js/assets/2213682/cb451575-4416-4271-9d19-cf2f9bc8d842)

The answer to the question "why?" is a little below in the spec:

![image](https://github.com/zloirock/core-js/assets/2213682/15bebe7d-4405-424a-9433-3890610b750a)
