### ISSUE TITLE
Math.cbrt(-1)

### ISSUE THREAD

**Issue by Yaffle** [zloirock/core-js#13]
`Math.cbrt(-x)` should be equal to `-Math.cbrt(x)`

**Comment by zloirock** [comment]
@Yaffle [hmm?](https://github.com/zloirock/core-js/blob/master/src/es6.js#L86-L89)
```javascript
console.log(Math.cbrt(-1)) // => -1
```

**Comment by Yaffle** [comment]
Ah, excuse me, I copied `Math.cbrt` manually, and forgot `sign(x)`, seems.

Also, please look at https://github.com/kangax/compat-table/issues/392

**Comment by zloirock** [comment]
I do not think that this accuracy is needed, especially as it is not defined in the specification.

**Comment by Yaffle** [comment]
@zloirock  I do not think the  specification is needed so.
