### ISSUE TITLE
window.performance support

### ISSUE THREAD

**Issue by rymohr** [zloirock/core-js#130]
Was this intentionally left out? I assumed core-js provided it but we just ran into errors with mobile Safari 8 users.

http://caniuse.com/#search=performance

**Comment by zloirock** [comment]
Thanks for proposal, but it can't be polyfilled - only little part and with serious limitations.

**Comment by rymohr** [comment]
Probably worth mentioning that in the missing polyfills section then.  I was under the impression you didn't need to include other polyfills if you were including core-js but clearly I was wrong.

https://github.com/zloirock/core-js#missing-polyfills

**Comment by zloirock** [comment]
I'm not sure about that. It's a browser-specific API, in this section I made only one exeption for `window.fetch` because it was frequent request.
