### ISSUE TITLE
core.js can not convert Array.prototype.at ES2022

### ISSUE THREAD

**Issue by turtleinspace1** [zloirock/core-js#1300]
Original js
[1, 2, 3].includes(1) 

Using babel 7.3.2 core-js 3.33.1
the Result is not down-level
do latest  core.js support to low-level this API ?

**Comment by zloirock** [comment]
Sorry, I don't understand what do you mean. [See the REPL](https://babeljs.io/repl/#?browsers=defaults%2C%20ie%2011&build=&builtIns=usage&corejs=3.21&spec=false&loose=false&code_lz=NoRgNABATJDMC6A6AlgOwMYBsCuATApgM4AUIAlEA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.23.2&externalPlugins=&assumptions=%7B%7D), everything injected as expected.
