### ISSUE TITLE
How do I set my babelrc to let it not polyfill array.push because I am satisfied with browsers' implementation for array.push

### ISSUE THREAD

**Issue by qiulang** [zloirock/core-js#1311]
Hi, this is a question I don't know whether I should raise to corejs or babeljs.  I don't want babel to polyfill  `array.push`.  But how ?

I have the following .babelrc but I still see `array.push` is injected. 

                        "useBuiltIns": "usage",
                        "shippedProposals": true,
                        "corejs": {
                            "version": 3.33
                            "proposals": false
                        }

After all, this is a [very basic](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array/push) array function I am happy with browsers' (chromium browsers) implementation.

I read the [array.push](https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/es.array.push.js) but it is not clear to me how you implement push function.

**Comment by zloirock** [comment]
[An example of usage `exclude` option.](https://github.com/babel/babel/blob/main/packages/babel-preset-env/test/fixtures/corejs3/exclude-built-ins/options.json)
