### ISSUE TITLE
`writable` values of `Symbol.toStringTag` property of `DOMIterables` are overwritten to `true` 

### ISSUE THREAD

**Issue by canalun** [zloirock/core-js#1312]
Hi, core-js team. Thank you for developing this great library.

### Background
[`packages/core-js-pure/override/modules/web.dom-collections.iterator.js`](https://github.com/zloirock/core-js/blob/master/packages/core-js-pure/override/modules/web.dom-collections.iterator.js) sets `writable` of `Symbol.toStringTag` property of DOM Iterables as true.
That is because [`createNonEnumerableProperty()`](https://github.com/zloirock/core-js/blob/master/packages/core-js/internals/create-non-enumerable-property.js) defines PropertyDescriptor with `writable: true`.

As a result, the presence or absence of core-js affects some systems whose behavior changes depending on the `writable` value. 
For example, [this part of lodash](https://github.com/lodash/lodash/blob/f299b52f39486275a9e6483b60a410e06520c538/lodash.js#L6048-L6066) will be affected.

### Question
1. What is the reason for overwrite of the `writable` value of `Symbol.toStringTag` property of DOM Iterables? (I'm thinking about patching to stop this overwrite on my application using core-js. Of course, if I can help anything, I'd like to contribute to core-js also.)
2. This file, `packages/core-js-pure/override/modules/web.dom-collections.iterator.js`, is in core-js-pure. 
I've thought that core-js will never overwrite prototypes. It's not correct??

**Comment by zloirock** [comment]
Thanks, you are right, they should be non-writable.

Could you show for what collections and in what engines they are defined? With the current logic, they should be defined only in case of lack or inconsistency `@@toStringTag` on DOM collections prototypes.

**Comment by canalun** [comment]
Thanks :)

- Engine: V8 11.9.169.6 (Chrome v119.0.6045.159)
- Collections: as follows
```
CSSRuleList
CSSStyleDeclaration
DOMRectList
DOMStringList
DOMTokenList
DataTransferItemList
FileList
HTMLAllCollection
HTMLCollection
HTMLFormElement
HTMLSelectElement
MediaList
MimeTypeArray
NamedNodeMap
NodeList
Plugin
PluginArray
SVGLengthList
SVGNumberList
SVGPointList
SVGStringList
SVGTransformList
SourceBufferList
StyleSheetList
TextTrackCueList
TextTrackList
TouchList
```

I checked by using the below page.
https://codesandbox.io/p/sandbox/determined-bose-sk7wqw

**Comment by zloirock** [comment]
Ok, thanks here is a wrong condition.

**Comment by zloirock** [comment]
`classof(CollectionPrototype) !== TO_STRING_TAG` instead of `classof(CollectionPrototype) !== COLLECTION_NAME`

**Comment by canalun** [comment]
Got it, thanks :) I'll try to patch it!

**Comment by zloirock** [comment]
Here also required some other changes, I already made them -)

**Comment by canalun** [comment]
wow, really thanks...!!! I'm trying this patch on my environment, now. Thanks!!

**Comment by canalun** [comment]
wow, really thanks...!! I'm trying it on my environment now :)

**Comment by canalun** [comment]
The problem has been resolved, thank you so much for your quick response! ! !
