### ISSUE TITLE
`Array.prototype.at` polyfill works inconsistent with spec.

### ISSUE THREAD

**Issue by minseok-choe** [zloirock/core-js#1318]
The following code works different in node 15 and 16:

```javascript
 const at = require('core-js-pure/actual/array/at');
at({ length: BigInt("-10") }, 0)
```

```
Running node v16.20.2 (npm v8.19.4)
TypeError: Cannot convert a BigInt value to a number
```

```
Running node v15.14.0 (npm v7.7.6)
undefined
```

**Comment by zloirock** [comment]
It's an interesting case, thanks. I'm pretty sure that some other similar edge cases are not good with bigints at least since they were written before bigints were added to the standard -)
