### ISSUE TITLE
Uncaught TypeError: $RegExp is not a function

### ISSUE THREAD

**Issue by DominicBoettger** [zloirock/core-js#133]
I always get this error. Do you know what is going wrong?
I am using Chrome 46 and jspm as loader.

**Comment by zloirock** [comment]
`$RegExp` used only in [`es6.regexp.constructor`](https://github.com/zloirock/core-js/blob/v1.2.6/modules/es6.regexp.constructor.js). Looks on code - by idea it can not be anything other than a function. It's possible only if [`$.global`](https://github.com/zloirock/core-js/blob/v1.2.6/modules/%24.global.js) returns something else than global object. It can't only with an incorrect build process, so it's your config or jspm issue.

**Comment by DominicBoettger** [comment]
The problem was caused by babel 5.8.34. It only works until 5.8.33.

**Comment by zloirock** [comment]
It's definitely not `core-js` issue, so I have no ideas how I can help you.

**Comment by DominicBoettger** [comment]
My comment was just for documentation purposes, cause i think others will run into this problem too. I am pretty sure you can't help :-).
