### ISSUE TITLE
zloirock ！！！ You can go here to receive the airdrop。

### ISSUE THREAD

**Issue by ijilwevsd41** [zloirock/core-js#1334]
Hello, zloirock, this is not an advertisement or a scam. You can go here to receive the airdrop https://provisions.starknet.io/ The current price is 1.95USDT each

**Comment by AlexDev404** [comment]
Yeah, it actually works. But not for US citizens, sadly :/

**Comment by zloirock** [comment]
I'm skeptical about airdrops, but this case of supporting FOSS fundament is good. However, it's not available for Russians. I'll take a look at possible options one more time later, thanks.

**Comment by ijilwevsd41** [comment]
vpn....
