### ISSUE TITLE
Marking the Set proposal as stable

### ISSUE THREAD

**Issue by NMinhNguyen** [zloirock/core-js#1342]
It appears that the Set proposal has advanced to Stage 4 this week (https://x.com/robpalmer2/status/1777777295941386429, https://github.com/tc39/proposals/commit/bda5a6bccbaca183e193f9e680889ea5b5462ce4) - can it be marked as stable in `core-js` now? If so, what is the process to do so?

**Comment by zloirock** [comment]
Sure, https://github.com/zloirock/core-js/pull/1336

**Comment by NMinhNguyen** [comment]
Oh oops, let me close this issue 😅
