### ISSUE TITLE
Question in checkModule of compat.js

### ISSUE THREAD

**Issue by biin** [zloirock/core-js#1344]
In core-js-compat, the version list is retrieved via browserslist in targets-parser.js. For iOS version 15.7.2, browserslist returns the minimum version as 16. Subsequently, the minimum version is set to 16, and the necessary polyfill list is retrieved through checkModule in compat.js.
The problem here is that for cases like es.array.to-sorted, where the minimum version is 16, checkModule uses < for comparison, so the necessary polyfills are not included. Should this be considered an error in browserslist, or is there a need for a separate handling for this version?
Thank you!

**Comment by zloirock** [comment]
Sorry, I don't understand what do you mean. Everything here works as expected and `es.array.to-sorted` marked as required for iOS 15.7.2:

![image](https://github.com/zloirock/core-js/assets/2213682/3c7e3c53-ac47-43e3-969f-e8010b7d423b)

**Comment by biin** [comment]
@zloirock 
This issue can be reproduced by setting the browserslist query to ios >= 15.7.2. 
I have confirmed that when executed as shown in the sample, there is no issue.
 It seems that this issue arises from a difference in the browserslist query.

Thank you.

**Comment by zloirock** [comment]
Clear, I see it:

![image](https://github.com/zloirock/core-js/assets/2213682/d45eb531-e846-43dc-98a6-6fddd989ec95)

In this case, it's not a `core-js` issue that works as expected as I have shown above, it's a `browserslist` issue that `ios >= 15.7.2` query also should include `15.6-15.8`. You could ask it in their repo.

**Comment by zloirock** [comment]
https://github.com/browserslist/browserslist/pull/836
