### ISSUE TITLE
Can we upgrade http to https in url-constructor-detection.js ?

### ISSUE THREAD

**Issue by wChenonly** [zloirock/core-js#1345]
https://github.com/zloirock/core-js/blob/f1303f38bd80474f950cadb3e802db1c2618a2c5/packages/core-js/internals/url-constructor-detection.js#L11

Because core.js, as a dependency of many underlying compilation packages, will appear in chunk-vendors after packaging, but some projects cannot require http, so the packaged code scan will scan out http in url-constructor-detection.js.

http://a
http://a/c%20d?a=1&c=3
...

**Comment by zloirock** [comment]
I don't think that it's good to report this case in such scanners, however, OK, it's not a big deal, so I'll replace `http -> https` here.
