### ISSUE TITLE
es6.object.to-string not working correctly in IE8

### ISSUE THREAD

**Issue by deepsweet** [zloirock/core-js#135]
hi.

```js
Object.prototype.toString.call({})
// [object String Iterator]

Object.prototype.toString.call([])
// [object String Iterator]
```

so it's impossible to determine `[object Object]` or `[object Array]`.

**Comment by deepsweet** [comment]
(I'm trying to use `core-js/es6/symbol` polyfill)

**Comment by zloirock** [comment]
`Object#toString` [tested](https://github.com/zloirock/core-js/blob/master/tests/tests/es6.object.to-string.ls), in the IE8 - too. This behavior possible if you uses an alternative incorrect string iterator polyfill without own prototype.

**Comment by zloirock** [comment]
I can't reproduce it without incorrect alternative string iterator polyfill. If you could not find the conflict - please, write a simple reproducible example.
