### ISSUE TITLE
Polyfill Including Unneeded Modules

### ISSUE THREAD

**Issue by artola** [zloirock/core-js#1353]
Using webpack to build a polyfill file it pulls in `padStart` (and many others) modules that are not required for the target. I am using the latest version possible of any package.

I do follow the instructions in [migration docs](https://github.com/babel/babel-polyfills/blob/main/docs/migration.md).

`webpack.config.js`:

```javascript
'use strict';

module.exports = {
  name: 'polyfills',
  mode: 'production',
  entry: require.resolve('core-js/stable'),
  output: {
    filename: 'polyfills.bundle.js',
  },
  module: {
    rules: [
      {
        test: /\.(mjs|js|jsx)$/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              envName: 'production',
              configFile: false,
              cacheDirectory: false,
              cacheCompression: false,
              targets: {chrome: 125},
              presets: [['@babel/preset-env']],
              plugins: [
                [
                  'polyfill-corejs3',
                  {
                    method: 'entry-global',
                    version: '3.37',
                    debug: true,
                  },
                ],
              ],
            },
          },
        ],
      },
    ],
  },
  optimization: {
    minimize: false,
  },
};
```

What is wrong in such config?

**Comment by zloirock** [comment]
Could you debug and show your input (what `core-js` entries are used in your code, since it's `entry-global` mode) and output (included modules)? And what do you mean by `padStart`? `es.string.pad-start` should not be included with this target. However, a couple of polyfill modules could include a simple internal `string-pad` helper that can't be removed from the output for compatibility reasons before the next major release.

**Comment by zloirock** [comment]
Oops, I see `core-js/stable` as the entry, so you could ignore the question about input.

**Comment by zloirock** [comment]
Specific questions about Babel configurations is better to ask in `babel` / `babel-polyfills` repos.

**Comment by zloirock** [comment]
Also, `core-js` should not be transpiled by itself, it should be ignored in the transpiler config, it could be the reason of this issue. If you wanna just make a polyfills bundle for your target environment, it's better to use [`core-js-builder`](https://github.com/zloirock/core-js/tree/master/packages/core-js-builder).

**Comment by artola** [comment]
Even with `exclude: [/node_modules[\\\/]core-js/]` to avoid the transpiler the size states the same (we have that in a shared config always).
With [core-js-builder](https://github.com/zloirock/core-js/tree/master/packages/core-js-builder) the size is a way smaller.
I would expect to get a similar size to the builder using `@babel/preset-env`, at least from the docs it seems that should be able to pull/strip the correct modules for the target, but I guess that fails to produce the same output of `core-js-compat/compat`.

**Comment by zloirock** [comment]
I'm not sure that the `entry-global` polyfills optimization will be applied in case of your config at all - that does not contain something like `import 'core-js/***` that can be optimized - internal imports in this entry are relative. Instead of that, you could try a file that contains just `import 'core-js/stable'`.

**Comment by artola** [comment]
In my original code, I have a module that only import `import 'core-js/stable'`. It makes no difference in the size.

In theory it should replace that statement with the required by the target: https://babeljs.io/docs/babel-preset-env#usebuiltins-entry

And I would say that it does it, but somehow wrong. There is a difference when I change the targets, but it does not makes sense even when I set `chrome 125`.

I do expect that `@babel/preset-env` injects only the modules for the target as stated in their docs:

> This option enables a new plugin that replaces the import "core-js/stable"; and require("core-js"); statements with individual imports to different core-js entry points based on environment.

I will port this issue to their board. Thanks a lot @zloirock

**Comment by zloirock** [comment]
Note that the optimized output for that entry and target should contain only:
<img width="654" alt="Снимок экрана 2024-07-18 в 02 52 58" src="https://github.com/user-attachments/assets/3257430d-f191-44e8-8ae1-443cf8624ea6">
