### ISSUE TITLE
Use of cryptographically weak pseudo-random number generator (PRNG)

### ISSUE THREAD

**Issue by monicavis** [zloirock/core-js#1358]
Hi,
Ran **Semgrep** scanning for vulnerability. Getting the below-mentioned issue in the node module for core-js
This rule identifies the use of cryptographically weak random number generators.\nUsing cryptographically weak random number generators like crypto.pseudoRandomBytes() \nand Math.random() for security-critical tasks can expose systems to significant \nvulnerabilities. Attackers might predict the generated random numbers, compromising \nthe integrity and confidentiality of cryptographic operations. This could lead to \nbreaches where sensitive data is accessed or manipulated, authentication mechanisms \nare bypassed, or secure communications are intercepted, ultimately undermining the \nsecurity of the entire system or application.\n\nMitigation strategy:\nReplace the use of these cryptographically weak random number generators with \ncrypto.randomBytes(), a method provided by Node.js's crypto module that \ngenerates cryptographically secure random numbers. This method should be used \nfor all operations requiring secure randomness, such as generating keys, tokens, \nor any cryptographic material.\n\nSecure Code Example:\n\nconst crypto = require('crypto');\nconst secureBytes = crypto.randomBytes(256);\nconsole.log(`Secure random bytes: ${secureBytes.toString('hex')}`);\n\n

After the yarn build, getting vulnerable in chunks and points to core-js packages.
Found **Math.random()** in the following

/node_modules/core-js/internals/object-prototype-accessors-forced.js
/node_modules/core-js/internals/uid.js

**Comment by zloirock** [comment]
Those cases are not related to security. It's public data, for example, you can get symbols that's created with `uid` helper with `Object.getOwnPropertySymvols`. `Math.random` here is used for *reducing* the number of possible collisions. Also, `crypto.pseudoRandomBytes` is not available in target environments.

So I think that you should report to Semgrep about the false positive.

**Comment by zloirock** [comment]
Duplicate of https://github.com/zloirock/core-js/issues/779, https://github.com/zloirock/core-js/issues/1315

**Comment by monicavis** [comment]
@zloirock I have reported to **semgrep**, but is there any other alternative for this issue?

**Comment by zloirock** [comment]
What do you mean?

**Comment by monicavis** [comment]
Like is there any other alternative solution to resolve this vulnerable issue

**Comment by zloirock** [comment]
It's not a vulnerability, so I don't know what to say -)

**Comment by monicavis** [comment]
okay thank you
