### ISSUE TITLE
I want to know why push is so slow.

### ISSUE THREAD

**Issue by ForeverCZ** [zloirock/core-js#1360]
**core-js版本：3.30.0，chrome：127.0.6533.100**

**Native code**

![image](https://github.com/user-attachments/assets/7092adf8-ec67-48d8-ac3e-e92760628450)

**Polyfill**
![image](https://github.com/user-attachments/assets/2ccbb73f-9f1e-44c1-85ef-0d70fd3fbe5f)

**Comment by Michaelpalacce** [comment]
"I demand this now" seems like an issue title I'd naturally ignore

**Comment by zloirock** [comment]
At least because it's not a native function and can't so optimized. Anyway, it's fixed from V8 ~ Chrome 122, so it's not an issue.

**Comment by ForeverCZ** [comment]
> "I demand this now" seems like an issue title I'd naturally ignore (from a random nobody that happened to see this).
> 
> Meaning: Phrase your issues better ffs

You are right.
