### ISSUE TITLE
`esnext.json.parse`  will lead to  `Node.ELEMENT_NODE` => undefined

### ISSUE THREAD

**Issue by thinke5** [zloirock/core-js#1369]
before
<img width="226" alt="image" src="https://github.com/user-attachments/assets/65d71f14-51d3-4bb6-9ad5-3366da6e3e9e">

after
<img width="262" alt="image" src="https://github.com/user-attachments/assets/4a9b6eef-105e-44a6-9d45-2b52c6438b93">

**Comment by zloirock** [comment]
It seems this is a problem of your build process.

This module contains a definition of the internal `Node` constructor and it's not exposed to the global scope.

https://github.com/zloirock/core-js/blob/v3.38.1/packages/core-js/modules/esnext.json.parse.js#L86-L91

<img width="421" alt="Снимок экрана 2024-09-25 в 00 04 27" src="https://github.com/user-attachments/assets/401d7adb-2a30-4cda-9e0f-c3b521fdbc5f">

It works fine in any kind of build that I saw:

<img width="643" alt="Снимок экрана 2024-09-25 в 00 05 00" src="https://github.com/user-attachments/assets/820ffbfa-ef3e-4197-83fd-41e49b836cff">

Looks like `core-js` module are not wrapped with closures when you bundle it.
