### ISSUE TITLE
Fix invalid 1.toString() minification in core-js for compatibility with Cloudflare

### ISSUE THREAD

**Issue by nureweb** [zloirock/core-js#1370]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `core-js@3.26.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/core-js/internals/uid.js b/node_modules/core-js/internals/uid.js
index e2230f1..38fb151 100644
--- a/node_modules/core-js/internals/uid.js
+++ b/node_modules/core-js/internals/uid.js
@@ -2,7 +2,7 @@ var uncurryThis = require('../internals/function-uncurry-this');
 
 var id = 0;
 var postfix = Math.random();
-var toString = uncurryThis(1.0.toString);
+var toString = uncurryThis((1).toString);
 
 module.exports = function (key) {
   return 'Symbol(' + (key === undefined ? '' : key) + ')_' + toString(++id + postfix, 36);
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by zloirock** [comment]
https://github.com/zloirock/core-js/pull/1368#discussion_r1773752921
