### ISSUE TITLE
es.object.proto.js and object-set-prototype-of.js depend on each other

### ISSUE THREAD

**Issue by ahaoboy** [zloirock/core-js#1375]
I want to use corejs in mujs, but there is no __proto__ and setPrototypeOf in mujs, and these two APIs depend on each other in corejs, so I can't import any of them.

```js
// mujs 
print(Object.prototype.__proto__) // undefined
print(Object.setPrototypeOf) // undefined
print('__proto__' in {}) // false
```

object-set-prototype-of.js
```js
setter = uncurryThisAccessor(Object.prototype, '__proto__', 'set');
```

es.object.proto.js
```js
var setPrototypeOf = Object.setPrototypeOf;
```

**Comment by zloirock** [comment]
Yes, `Object.setPrototypeOf` (where it's missed) can  be polyfilled only in engines with available `__proto__`,  `__proto__` (where it's missed) - with available `Object.setPrototypeOf`. So, for example, in IE9 you can't polyfill it since in such engines there is no available way set a prototype.

**Comment by zloirock** [comment]
In such engines is possible somehow simulate them, like #459 - but it's not safe, so I don't think that it's a good idea.
