### ISSUE TITLE
es6.promises polyfill breaks Promise.all in Safari and mobile Safari

### ISSUE THREAD

**Issue by jeffbski** [zloirock/core-js#138]
In Safari 8.0.6, when I require es6.promise polyfill, Promise.all breaks, throwing errors when passing in an array. 

```javascript
require('core-js/modules/es6.promise');

Promise.all([1]);  // throws error [1] is not iterable
```

It fails with any array (promises, strings, etc.).

Surprisingly, the Safari native implementation works fine without the polyfill, so the polyfill is somehow breaking things. 

It is also a problem on mobile Safari, confirmed in the IOS simulator.

It doesn't cause any problem in chrome or firefox.

**Comment by zloirock** [comment]
Completely correct. `Promise.all` accepts only iterables. So, you also need `es6.array.iterator`. `modules` path - internal API, please, don't use it.

Use, for example, `core-js/fn/promise` or `core-js/es6/promise` - it will add all required dependencies.

**Comment by jeffbski** [comment]
Thanks. I misunderstood about how to pull in smaller pieces, but I understand now. I appreciate the quick response. Have a great day!

**Comment by neothemachine** [comment]
I just noticed that I also use the /modules/* style for importing parts. Maybe the correct way should be clarified in the readme.

**Comment by zloirock** [comment]
Yep, thanks. IIRC some time ago was a little notice about it in the README, but looks like in was lost. In the README for the next version, it will be described in detail.
