### ISSUE TITLE
The latest version (3.39.0) can't work on IE11

### ISSUE THREAD

**Issue by dindding17** [zloirock/core-js#1385]
The latest version (3.39.0) can't work on IE11, but 3.26.0 works fine.
When using 3.39.0, IE11 throws error like:
`SCRIPT5005:缺少字符串`

**Comment by zloirock** [comment]
It's tested in IE11.

<img width="903" alt="Снимок экрана 2024-12-13 в 09 30 31" src="https://github.com/user-attachments/assets/6a09b74c-627f-4edb-a46a-1e294cce72e4" />

Even CI includes testing in IE11.

Could you add a reproducible example?

**Comment by zloirock** [comment]
Closed as `can't reproduce`.
