### ISSUE TITLE
Don't override console methods that already exist

### ISSUE THREAD

**Issue by gaearon** [zloirock/core-js#14]
It would be nice if methods such as `console.log` weren't overriden in Chrome because this breaks "jump to source" in DevTools.

**Comment by zloirock** [comment]
@gaearon it's not a bug. Reason:
```javascript
// Throwing in FF, Chrome
// Works in Node.js, IE, FireBug
setTimeout(console.log, 1e3, 42);
```
You can build core-js w/o `console` module:
```javascript
npm i -g grunt-cli
npm i core-js
cd node_modules/core-js && npm i
grunt build:new_shim,core,es5,timers --path=custom uglify
```

**Comment by gaearon** [comment]
Yeah I just realized this.

I'll have to stick with `console-shim` for this, I guess. I'd rather not have binding fix than make debugging in Chrome harder.

**Comment by zloirock** [comment]
@gaearon I will think about extracting `console` module in a separate file.

**Comment by gaearon** [comment]
Yeah file's actually not a problem for me. I'm running via Webpack (so using `shim.js` build) and I was considering a custom build to include `console` to cover missing IE10 methods, but since it doesn't work how I want it to, I'll just keep using `console-shim` (and `shim.js` for ES6+).

Thanks for very nice lib btw.
