### ISSUE TITLE
Unhandled rejection tracking and native promises

### ISSUE THREAD

**Issue by zloirock** [zloirock/core-js#140]
Most V8 `Promise` bugs (like [1](https://code.google.com/p/v8/issues/detail?id=4162) or [2](https://code.google.com/p/v8/issues/detail?id=4539)) will be fixed in V8 ~ Chrome 49. Still not fixed V8 bugs are fixed in `core-js` by patching methods. It means [custom unhandled rejection handlers](https://github.com/zloirock/core-js#unhandled-rejection-tracking) will not work in Chrome 49 with `core-js`. The same situation with FF46. Some days ago promise rejection events was added to [ECMAScript](https://github.com/tc39/ecma262/pull/76) and [HTML](https://github.com/whatwg/html/pull/224) drafts.

So the question for the community: replace native `Promise` without support promise rejection events (in this case, in addition to global handlers, add generation custom events in browsers) or not?

Upd.: Ok. Chrome 49 supports unhandled rejection events.

**Comment by danharper** [comment]
Now that they're in the spec, +1 for replacing a native `Promise` which doesn't support the rejection events.

**Comment by zloirock** [comment]
Added to feature detection in [`2.1.1`](https://github.com/zloirock/core-js/releases/tag/v2.1.1).
