### ISSUE TITLE
Custom build with $for function

### ISSUE THREAD

**Issue by MarenkovIgor** [zloirock/core-js#141]
I build custom core-js via npm run npm run grunt build:es6.function.name,es6.array,es6.string -- --blacklist=es6.string.starts-with  --path=../../Resources/Libs/core-js.for-customers-canvas

What build option for $for function?

**Comment by zloirock** [comment]
If you mean the `$for` function from 0.x versions - it was moved to [the separate library](https://github.com/zloirock/forof).
