### ISSUE TITLE
"Out of stack space"  - karma with IE11 and webpack 

### ISSUE THREAD

**Issue by dballance** [zloirock/core-js#143]
Getting the following in IE11 on Windows10 using angular2-webpack-starter and karma-ie-launcher.

```typescript
IE 11.0.0 (Windows 10 0.0.0) ERROR
  Out of stack space
  at C:/angular2-webpack-starter/spec-bundle.js:1064 <- webpack:///~/core-js/modules/es6.symbol.js:54:0
```

Offending lines:
```javascript
 set: function(value){
      if(has(this, HIDDEN) && has(this[HIDDEN], tag))this[HIDDEN][tag] = false;
      setSymbolDesc(this, tag, createDesc(1, value));
 }
```
Removing / commenting the set descriptor function appears to resolve the issue.
```javascript
 set: function(value){
      //if(has(this, HIDDEN) && has(this[HIDDEN], tag))this[HIDDEN][tag] = false;
      //setSymbolDesc(this, tag, createDesc(1, value));
 }
```

PhantomJS and Chrome tests run fine, only IE with this issue. Not sure how to resolve --- it seems to be calling the set method with enough iterations to overflow the stack.

**Comment by dballance** [comment]
Forgot to add -- possibly related to #96 but unsure how to resolve with webpack + Typescript.

**Comment by zloirock** [comment]
Please, write a simple reproducible example.

**Comment by zloirock** [comment]
@dballance any news about a reproducible example? I don't see the problem just in karma + IE11 + webpack, so looks like this problem in your config.

**Comment by dballance** [comment]
I haven't had any time to provide a repro for this. It most likely is in my config - will close and provide a repro if it pops up again and I have time to investigate.

**Comment by webtechy** [comment]
Reproducible here:

https://github.com/webtechy/sp-dev-fx-webparts/tree/master/samples/kendo-simplebutton

Related here:

https://github.com/angular/zone.js/issues/316

**Comment by webtechy** [comment]
Let me know if you want access to a URL to see this issue.
