### ISSUE TITLE
in node 0.10, `Map.prototype.forEach.call({}, function () {})` does not throw

### ISSUE THREAD

**Issue by ljharb** [zloirock/core-js#144]
`Map#forEach` and `Set#forEach` are supposed to throw a `TypeError` if their receiver/"this" value is not an actual Map or Set. In node 0.12 and later, with `core-js` required, it throws as expected, but in node 0.10 and earlier, it does not.

This is preventing [`is-equal`](https://github.com/ljharb/is-equal/issues/4#issuecomment-164171179) and `expect` from working with `core-js` in an environment without native `Map` and `Set`, since it gives false positives for object values.

**Comment by zloirock** [comment]
I saw this issue. I don't think it is a principal behavior for polyfill, but ok, I will add it.

**Comment by ljharb** [comment]
It's the only reliable way to determine if something is a Map or Set, cross-realm (ie, not relying on `instanceof`). Thanks!

**Comment by mjackson** [comment]
:+1: Thanks, @zloirock! This is important for feature detection.

**Comment by ljharb** [comment]
Thanks! Please let me know when you release a v2.0.0

**Comment by ljharb** [comment]
Any update? I'd love to verify that `is-equal` works with `core-js` v2 and higher.

**Comment by zloirock** [comment]
> Any update?

Available `2.0.0-beta.2`, I should stabilize a few more things before the final release.

**Comment by ljharb** [comment]
Great, thanks!

**Comment by zloirock** [comment]
Available in [2.0](https://github.com/zloirock/core-js/releases/tag/v2.0.0).
