### ISSUE TITLE
console.log gets overwritten by nop

### ISSUE THREAD

**Issue by lukescott** [zloirock/core-js#149]
For some reason the default build of core-js is replacing the native version of console.log with an empty function. This was quite surprising because we were using core-js in another project and this wasn't happening.

I read in another issue that the reason for this was because this throws:
```javascript
setTimeout(console.log, ...)
```

Who does this anyway? If this is an issue, why not wrap the function instead?

**Comment by lukescott** [comment]
It seems to be just console.log. console.dir works.

**Comment by zloirock** [comment]
O_o actual versions of `core-js` do not touch `console.log` near a year.

**Comment by lukescott** [comment]
Ok, it looks like it's a combination of https://trackjs.com/ and core-js. tracker.js is being included first, which wraps console.log. And then core-js replaces the wrapped function with an empty one. If I remove tracker.js core-js doesn't replace the method.

Is the solution include core-js first?

**Comment by zloirock** [comment]
> actual versions of `core-js` do not touch `console.log`

What `core-js` version you are using?

**Comment by lukescott** [comment]
1.2.6. We are using webpack to `require('core-js')`.

**Comment by zloirock** [comment]
This version definitely can not do anything with `console.log`. So maybe the problem just in `trackjs`?

**Comment by lukescott** [comment]
Ok, apparently we were using 0.5.x. Our dependency management needs a serious overhaul. We're using both npm and bower, and one of our bower dependencies was pulling an older version of core-js and webpack was giving bower priority over npm.

So, for now, I put core-js in our bower file with a version resolution to force it to pull the newer version until we completely remove bower (which is the plan).
