### ISSUE TITLE
PhantomJS doesn't understand Set

### ISSUE THREAD

**Issue by et** [zloirock/core-js#15]
Please excuse my ignorance for this low level library, but I'm trying to use a native `Set` object with [6to5](https://github.com/6to5/6to5) and have determined that this is probably the library that I should report this issue to.

I have no trouble getting a `Set` to work with Chrome, but PhantomJS reports it can't find `Set`. Unfortunately, I'm not sure how to run the test suite for this library or I'd happily create a test scenario. Any assistance is extremely helpful.

Kind regards

**Comment by sebmck** [comment]
You need to include the [6to5 polyfill](http://6to5.org/docs/usage/polyfill/).

**Comment by et** [comment]
Wowsa. Thank you for your quick and correct response.
