### ISSUE TITLE
Promise polyfill/shim in Chrome appears to swallow unhandled rejections

### ISSUE THREAD

**Issue by mmoss** [zloirock/core-js#151]
**Chrome Native Promise without Rejection Handler:**
![nativepromiserethrownwithoutrejectionhandler](https://cloud.githubusercontent.com/assets/648160/11932701/568d1f8a-a7c5-11e5-9ddd-8ab47063b528.png)

**Transcompiled using Babel without a Rejection Handler in Chrome:**
_No indication that something's gone awry_

![promiseshimwithoutrejectionhandlerswallowserror](https://cloud.githubusercontent.com/assets/648160/11932700/54886e24-a7c5-11e5-962b-93745baa81d0.png)

**Comment by zloirock** [comment]
Looks on result - it's not `core-js` `Promise`, rather `es6-promise` overrides it.

`core-js` replaces native `Promise` in actual Chromium, but instead of `es6-promise` supports unhandled rejection tracking.

**Comment by mmoss** [comment]
So this appears to be an issue with https://github.com/jakearchibald/es6-promise? Sorry for the noise!

**Comment by mmoss** [comment]
For anyone who runs into this, it's been logged here: https://github.com/jakearchibald/es6-promise/issues/70
