### ISSUE TITLE
include Reflect es7 metadata

### ISSUE THREAD

**Issue by gdi2290** [zloirock/core-js#152]
it would be great for angular2 if we only had to include `core-js` rather than `es6-shim`, `es6-promise`, and `reflect-metadata`
https://github.com/rbuckton/ReflectDecorators

**Comment by zloirock** [comment]
I think about it a few months. The problem here - [it's not an official ES proposal](https://github.com/rbuckton/ReflectDecorators/issues/9). It's very simple for implementation, so I think makes sense add it as an experimental feature. Or wait for the next TC39 meeting - IIRC decorator proposal should be updated.

**Comment by gdi2290** [comment]
would it be too crazy to ask for an experimental folder path so all Angular 2 developer could rejoice 
from
```es6
import 'es6-shim';
import 'es6-promise';
import 'es7-reflect-metadata/dist/browser';
import 'zone.js/lib/browser/zone-microtask';
import 'zone.js/lib/browser/long-stack-trace-zone';
```
to
```es6
import 'core-js/experimental';
import 'zone.js/lib/browser/zone-microtask';
import 'zone.js/lib/browser/long-stack-trace-zone';
```
then we only need to update zone.js
```es6
import 'core-js/experimental';
import 'zone.js/lib/browser/zone-microtask';
```
which could live in 
```es6
import 'angular2/polyfills';
```

**Comment by zloirock** [comment]
cc @wycats @rbuckton what do you think about it? Any conflicts with changes in the decorators proposal? Perspectives as an official proposal?

**Comment by gdi2290** [comment]
thanks for adding it as experimental :+1:

**Comment by zloirock** [comment]
@gdi2290 currently I just play with it and explore possibilities.

**Comment by zloirock** [comment]
I can add it right now as pre-strawman feature (it will be available not only in the `'core-js'` entry point - also in `'core-js/shim'` -> `'babel-polyfill'`), but 2 problems confuse me:
- [Fallback for `GetPrototypeOf` in `rbuckton/ReflectDecorators`](https://github.com/rbuckton/ReflectDecorators/blob/3c231b8f73f2827dee0c60d258b5d6d884327b4e/Reflect.js#L705-L731) for non-spec-compliant `TypeScript` (or `Babel` with `proto-to-assign`) classes. Sure, I can add the same fallback, but I don't think it's a good idea - inherited metadata will not work with constructors and statics if it will be implemented natively.
- I don't see any feedback [here](https://github.com/zloirock/core-js/issues/152#issuecomment-167802677) or [in the repo](https://github.com/jonathandturner/decorators/issues/19) [with the spec text](https://github.com/jonathandturner/decorators/issues/20) from champions. Is this proposal alive? One more time: cc @wycats @rbuckton

**Comment by zloirock** [comment]
Ok. In the next minor version (`2.1`) - after some days - it will be enabled by default. If current implementation will cause any problems - it's already not my problems. The questions above, I don't see any answers.

**Comment by gdi2290** [comment]
thanks
