### ISSUE TITLE
Object.assign does not throw when trying to extend sealed object

### ISSUE THREAD

**Issue by StyMaar** [zloirock/core-js#154]
```Js
(function(){
    "use strict";
    let toto = {
        a:1,
        b:2,
        c:3
    }

    let conf = {
        a:undefined,
        b:undefined,
    }

    Object.seal(conf);

    Object.assign(conf,toto);
    console.log(conf);
})();
```

In Firefox the given sample throws because `Object.assign` tries to add a `c` property to the sealed `conf` object.
With Babel-node it works and assign only the attribute `a` and `b`.

I think that the Firefox approach is the expected one.

**Comment by zloirock** [comment]
Fixed in https://github.com/zloirock/core-js/commit/7bf885b119b1db54154c40a3fcf327cf2438e016
