### ISSUE TITLE
promises do not work, USE_NATIVE fails on node native promises

### ISSUE THREAD

**Issue by silkentrance** [zloirock/core-js#155]
See https://phabricator.babeljs.io/T6910 for more information.

**Comment by loganfsmyth** [comment]
Define "promises do not work", there is nothing wrong with `USE_NATIVE` failing in some cases, because the polyfill version should be a perfect substitute.

**Comment by zloirock** [comment]
Native Node.js `Promise` is buggy, see #78, it will be fixed in V8 ~ 4.9. `.finally`is not a part of the spec.
