### ISSUE TITLE
Question - proper way to require just Promise

### ISSUE THREAD

**Issue by plaxdan** [zloirock/core-js#158]
I have tried the following with `"core-js": "^2.0.2"`:

```javascript
delete window.Promise;
var promise = require('core-js/library/fn/promise').Promise;
window.Promise = promise;
```

But `window.Promise` is still undefined. Am I doing this wrong?

**Comment by zloirock** [comment]
~~`var promise = require('core-js/library/fn/promise').Promise`~~
`var promise = require('core-js/library/fn/promise')`

Instead all of your code use just `require('core-js/fn/promise')`.

**Comment by plaxdan** [comment]
Thank you!
