### ISSUE TITLE
about using "UglifyJS2" compression causes problems "function name" lost cause

### ISSUE THREAD

**Issue by LiaoSept** [zloirock/core-js#162]
```
> Number.name
< ""
```
see https://github.com/zloirock/core-js/blob/master/modules/es6.number.constructor.js#L46

**Comment by zloirock** [comment]
By default, `core-js` compressed with [`--keep-fnames`](https://github.com/mishoo/UglifyJS2#usage) flag. You should use the same flag in your config or use default bundles,

**Comment by LiaoSept** [comment]
```
$Number.name = 'Number';
```
Is not it better this way?

**Comment by zloirock** [comment]
It will not work - functions `.name` property non-writable and, in most engines, non-configurable.

**Comment by LiaoSept** [comment]
thx
