### ISSUE TITLE
WeakMap not subclassable

### ISSUE THREAD

**Issue by unional** [zloirock/core-js#164]
```
import WeakMap from 'core-js/es6/weak-map';
class X extends WeakMap {}
let x = new X();
x.get('a'); // throws TypeError
```

Error is: `TypeError: Method WeakMap.prototype.get called on incompatible receiver [object Object]`

**Comment by zloirock** [comment]
Looks like you uses `babel` or something like that. `babel` does not support subclassing native constructors.

**Comment by unional** [comment]
I use typescript. @weswigham, does tsc has the same limitation?

According to http://www.ecma-international.org/ecma-262/6.0/#sec-weakmap-constructor
> The WeakMap constructor is designed to be subclassable. It may be used as the value in an extends clause of a class definition.

**Comment by zloirock** [comment]
> does tsc has the same limitation?

Yep.

**Comment by unional** [comment]
Thank!
