### ISSUE TITLE
core-js not installing correctly.

### ISSUE THREAD

**Issue by azizhk** [zloirock/core-js#171]
I'm getting this error in my production setup.
I am using gulp-babel which has its dependency on babel-core -> babel-runtime -> core-js
```
Error: Cannot find module 'core-js/library/fn/get-iterator'
```
I did a search for any probable reasons:
https://github.com/jspm/jspm-cli/issues/636
https://github.com/Granze/react-starterify/issues/20
https://github.com/iam4x/isomorphic-flux-boilerplate/issues/46
https://github.com/elastic/kibana/issues/5327

Almost everyone suggest deleting node_modules folder or reinstalling node.
Is there any other way.

Sorry if wrong place to ask.

**Comment by zloirock** [comment]
This entry point available in all packages from `1.0.0` version, so I don't think it's a problem with `core-js`. Looks like in a some package specified wrong `core-js` versions range or the problem with the package manager. I don't think I can help here.
