### ISSUE TITLE
Is `listner` a typo?

### ISSUE THREAD

**Issue by JoshMcCullough** [zloirock/core-js#175]
See line ~22: https://github.com/zloirock/core-js/blob/master/modules/_task.js

var listner = function(event){
  run.call(event.data);
};

Should it be "listener"?

**Comment by zloirock** [comment]
Yep, sure, thanks. English is not my best skill. I think, in the source code there are many other similar mistakes.

**Comment by JoshMcCullough** [comment]
No problem. I realize this is super minor! :+1:
