### ISSUE TITLE
ES6 Promise instropection not correctly working

### ISSUE THREAD

**Issue by dendril** [zloirock/core-js#178]
The following code evaluates to false in `Chrome: Version 49.0.2623.75 (64-bit)`

```js
var USE_NATIVE = !!function(){
  try {
    // correct subclassing with @@species support
    var promise     = $Promise.resolve(1)
      , FakePromise = (promise.constructor = {})[require('./_wks')('species')] = function(exec){ exec(empty, empty); };
    // unhandled rejections tracking support, NodeJS Promise without it fails @@species test
    return (isNode || typeof PromiseRejectionEvent == 'function') && promise.then(empty) instanceof FakePromise;
  } catch(e){ /* empty */ }
}();
```

I'm not an expert, but what I can said is, if the environment provides the `fetch API`, we should consider promises available, because any call to fetch() will return a "native" instance instead of a an instance using the polyfill.

Make sense?

**Comment by loganfsmyth** [comment]
@dendril Having `fetch` and having a `Promise` constructor does not mean that the `Promise` implementation is spec compliant. The goal of a polyfill is to ensure spec compliance across the board. I believe it's Chrome 50 or 51 that has the first fully compatible implementation.

**Comment by dendril** [comment]
I completely agree with you, but doesn't make sense to have a fetch API answering something different from what I can instantiate using a call to the Promise constructor.

**Comment by zloirock** [comment]
What can I say... If native promise implementation is incorrect - it should be replaced. Most alternative `Promise` polyfills do the same. Someone just replaces global `Promise`, for example, to Bluebird. So anyway `instanceof` detection for most cases makes no sense. In your code you can just wrap `fetch` and have correct instance:
```js
$fetch = fetch;
window.fetch = (...args) => Promise.resolve($fetch(...args));
```

**Comment by dendril** [comment]
Looks nice, but not implementable. Thanks all for take time to answer :smile:.

**Comment by Yaffle** [comment]
>What can I say... If native promise implementation is incorrect - it should be replaced. 
because it is correct enough for some applications.
This issue is really annoying. Promise#finally polyfills do not work in case core-js is used.

**Comment by loganfsmyth** [comment]
@Yaffle No-one has shown an example of what is actually not working, so if you have one, it would be more helpful to have an example to discuss.

**Comment by zloirock** [comment]
I added a workaround which should fix a big part of cases by patching `.than` and adding `.finally` on / to native `Promise` prototype.

**Comment by testacode** [comment]
I'm having this issue also on Microsoft Edge version 44.17763.831.0 and Firefox version 68.12.0esr (32-bit).
