### ISSUE TITLE
IE11 promise strange behaviour

### ISSUE THREAD

**Issue by MT-PL-SWF-Dev** [zloirock/core-js#179]
We have noticed really strange behaviour in IE11 when starting Aurelia application. It occurs only if it is first time you start app in new window/tab AND mouse cursor is NOT in IE window area (for example program is run from command line with given url - which is important scenario for us). Application then stays on index.html with static content but and nothing happens. Until you move cursor over window... Then magically app continues without any errors and any issues.

After many test we have found out that issue happens while trying to import "core-js" (no problem with other libraries though) and it can be worked around with window.setTimeout with at least 1-2 seconds of waiting.
Below I provide code with this workaround:

`    <script src="jspm_packages/system.js"></script>`
`    <script src="config.js"></script>`
`    <script>`
`        System.import("webcomponents.js/MutationObserver").then(function () {`
`            System.import('core-js').then(function () {`
`                System.import('aurelia-bootstrapper');`
`            });`
`        });`
`        window.setTimeout(function () {}, 2000);`
`    </script>`

Do you have any idea what can do to avoid this unstable solution?
We have also opened similar thread on StackOverflow: [http://stackoverflow.com/questions/35651193/ie11-promise-strange-behaviour](http://stackoverflow.com/questions/35651193/ie11-promise-strange-behaviour)
Problem was also discussed on Aurelia Github:
[https://github.com/aurelia/framework/issues/337](https://github.com/aurelia/framework/issues/337)

**Comment by zloirock** [comment]
Please, write a reproducible example as, for example, a repository, because I don't see any info about version libraries, config, etc.

When a tab is not active event loop behavior changes in many engines. If the problem in `MutationObserver` - it's a serious problem because we haven't any alternative way creation correct microtask.

**Comment by MT-PL-SWF-Dev** [comment]
I created GitHub repository with most basic example that reproduces issue.
[https://github.com/MT-PL-SWF-Dev/promise-strange-behaviour-core-js-179](https://github.com/MT-PL-SWF-Dev/promise-strange-behaviour-core-js-179)

To test it you need to run it on IE11 with mouse cursor out of IE window boundaries in new tab. As soon as mouse is moved over window it finishes promise and shows alert window.

**Comment by zloirock** [comment]
Interesting. It happens even when `core-js` `Promise` is disabled. Looks like JSPM bug. I'll explore it later.

**Comment by zloirock** [comment]
Yep, it's issue SystemJS / JSPM. After replacing `npm:core-js@2.1.3` -> `npm:core-js@2.1.3/client/core.js` in your config (without it, you will load ~300 files) I see the same problem, but after replacing JSPM bundled `client/core.js` file to [standard bundle](https://github.com/zloirock/core-js/blob/master/client/core.js) from GitHub / NPM all works fine. Please, open issue in their repos.
