### ISSUE TITLE
The core-js/library module is setting global.core

### ISSUE THREAD

**Issue by appden** [zloirock/core-js#18]
In order to support creating self-contained libraries with 6to5's `coreAliasing` transform, I believe this module should not be creating a global variable. Thanks!

**Comment by zloirock** [comment]
`core-js/library` is not only for use with a modular systems. There were conflicts, for this reason I left the global object for browsers in the presence of modular systems. I will remove it from the next build, but if conflicts will appear again, I'll return it.
