### ISSUE TITLE
Don't use object as promise constructor

### ISSUE THREAD

**Issue by nuxdie** [zloirock/core-js#183]
during fixing #176 the next code was introduced in commit 9d7e2da467e97af0b2897efff371b66d561d708e:
````js
var promise     = $Promise.resolve(1)
      , FakePromise = (

     promise.constructor = {} // !! at this moment promise.constructor equals new object instance !!

     )[require('./_wks')('species')] = function(exec){ exec(empty, empty); };
    // unhandled rejections tracking support, NodeJS Promise without it fails @@species test
    return (isNode || typeof PromiseRejectionEvent == 'function') && 

     promise.then(empty) // !! here comes .then method which fails with 
                                      // TypeError: object is not a constructor

      instanceof FakePromise;
````
the reason promise.then method fails in V8 is this --V8 creates new Promise every time `.then` method is called: https://github.com/v8/v8/blob/611add52550510b6bc0b79f6ae9278786183405f/src/js/promise.js#L285
and what is especially important, if `promise.constructor !== Promise`, V8 tries to create new promise from whatever thing `promise.constructor` points to ( https://github.com/v8/v8/blob/611add52550510b6bc0b79f6ae9278786183405f/src/js/promise.js#L233 )! which is `{}` in case above! hence we have `object is not a constructor` TypeError.

**Comment by zloirock** [comment]
Yep, it's a V8 bug and it should be fixed in V8 ~ Chrome 51, see  #159.
