### ISSUE TITLE
es6.promise always pause on exception in Canary

### ISSUE THREAD

**Issue by szarouski** [zloirock/core-js#186]
Hi, I can't use pause on exception feature in Canary (51.0.2694.1 canary (64-bit)) because es6.promise causes "Iterator result undefined is not an object" type error. Is there a way to fix that?

![temp](https://cloud.githubusercontent.com/assets/911388/14160561/ff054848-f6aa-11e5-8ac1-3bed74a49646.gif)

Thank you.

**Comment by zloirock** [comment]
Interesting. Looks like exceptions in promises, even with handlers, causes this problem:
```js
new Promise(_ => { throw 42 }).catch(e => console.log(e));
```
It's Chrome dev tools issue, not core-js. I can try to add a fallback for this example, but not sure it's possible.
