### ISSUE TITLE
Creating browser specific builds

### ISSUE THREAD

**Issue by philer** [zloirock/core-js#188]
So the README mentions some way of making custom builds via command line but it's not very elaborate. I'll probably have to read the Gruntfile for more details but before I do that I'd like to ask about a more powerful, automated approach.

My questions are:
1. Which of the following things already exist?
2. Which are too impractical to implement / not worth the effort?
3. Which don't exist because nobody has tried?

First, consider the following use cases:

**A** I'm creating an app targeted at a very specific browser engine. While this is not too common for regular websites it does occur more frequently when engines like webkit are used to provide a GUI for desktop applications ([here's an example](http://blog.linuxmint.com/?p=2327)). I only need a small subset of the entire polyfill.

**B** I'm creating a regular stand-alone web app and I want to server the absolute minimum to individual browser versions. Instead of sending the same monolithic polyfill.js to every browser I want to host specialized bundles. My server side code can then simply parse the client info and include the relevant bundle in a template (with a fallback to the big file for exotic browsers). For example if I access the site with Firefox 45 my templates will include

``` HTML
<script src="https://mysite.com/assets/polyfill-ff45.js"></script>
```

Advantages of this approach:
- Much smaller source needs to be transmitted, especially to modern browsers that already support many of the relevant features natively. This also means less code needs to be executed on each page load.
- Might need even less code since most checks for existing features should no longer be necessary. I already know that browser version X doesn't support feature Y so I can just polyfill it without checking.

I imagine two ways of creating those bundles:
1. Access caniuse.com to determine which features need to be polyfilled in which browsers (similar to postcss's [autoprefix](https://github.com/postcss/autoprefixer)). Even if it's not reliable on a per-function level it might be enough to categorically exclude larger chunks. This would provide an easy way to generate a large set of browser-specific bundles.
2. Create a build-script that can be run directly in any browser and will output a new script containing only those polyfills that were needed. In a sense this is like caching the results of all those little "what do we need" checks in core-js. The result is stored on the server. There are npm packages that simulate browsers so it might still be possible to automate this.
3. Use the same script as in 2. but store the result on the client (localStorage). It can then be loaded from there if it exists (though I'm not sure if that's a potential security hole since any code executed on the site could manipulate that code).

What do you think? Is this a reasonable approach or am I so dreaming?

**Comment by zloirock** [comment]
Sorry, I missed this question.

Sure, this approach makes sense, but it's harder what do you think. It was a part of my specialist's degree work. The main problem - `caniuse.com` is a bad data source about ES features support. `compat-table` much better, but also does not contain all required data.

`polyfill-service` tried to do it, but not successful in ES6+ stuff.

Now I'm working on the project which also can propose something like it, but I'm not sure it will be open source.

**Comment by philer** [comment]
Thanks for your feedback. At least I know now why this doesn't exist yet. I'm guessing that the [difficulties of user agent sniffing](http://webaim.org/blog/user-agent-string-history/) aren't making this any easier.

**Comment by triblondon** [comment]
@philer check out https://cdn.polyfill.io.  This is the service alluded to above.  We accept that we're not comprehensive - no-one is - but we do serve about 400 million polyfills per month just from our free hosted CDN, so some people clearly find it useful.

**Comment by philer** [comment]
@triblondon That looks interesting, thanks for linking it.

**Comment by cletusw** [comment]
Unless I'm mistaken, `babel-preset-env` [now does](https://github.com/babel/babel-preset-env/issues/20) exactly this (at least, use case **A**). If you specify `useBuiltIns`, it will only load the polyfills necessary for your target environment (using `compat-table` data, I believe). Is there anyway to get that functionality into `core-js` itself?

**Comment by zloirock** [comment]
Closed in favour [`babel-preset-env` with `useBuiltIns` option](https://github.com/babel/babel/tree/master/packages/babel-preset-env#usebuiltins).

**Comment by fabb** [comment]
`babel-preset-env` with `useBuiltIns` option has the downside that it does not analyze dependencies needed for the projects node_modules, since those are not processed by babel (by default, and it's not really a good idea to process all of them, which could break stuff).

Also babel does not take advantage of the `nomodule` performance improvement (i.e. load a different set of polyfills for browsers supporting es6 modules and the ones which do not).
