### ISSUE TITLE
x is not an object! in defineProperty

### ISSUE THREAD

**Issue by LeZuse** [zloirock/core-js#189]
Since version 2.2.0 I am getting this error in IE 11:
<img width="1350" alt="screenshot 2016-04-04 22 16 36" src="https://cloud.githubusercontent.com/assets/140393/14261881/106c31da-fab3-11e5-9dc6-d80038c62f5e.png">

Using core-js as a dependency through babel-polyfill

**Comment by zloirock** [comment]
You will have this error if `Object.defineProperty` target is not an object, it's expected behavior and looks like the problem in your code.

Looks on picture `core-js` compiled with usage `babel`, but it should be ignored. Maybe the problem here.

If you can't find the problem - please, add a reproducible example.

**Comment by LeZuse** [comment]
Are you saying I should use the distributed built version or `core-js` and not compile it myself using babel?

**Comment by zloirock** [comment]
Definitely not. I said:
- Your `babel` config should ignore `core-js` or `node_modules`.
- You should not pass to `Object.defineProperty` primitive as the first argument with `core-js` or without.
- If you write an issue, please, add a reproducible example.

**Comment by skozin** [comment]
@zloirock, we're getting the same error in IE 11, on the same line. 2.1.5 was the last version that worked for us. Here is the commit that introduced the error: https://github.com/zloirock/core-js/commit/86fa797f3665ae12864784620fd266367238a85d#diff-cef85cf90f184a55418f175f3c233f2aL229.

It seems that `_hide` tries to define a property (using, through `dP.f`, the `$defineProperty` implementation from `es6.symbol.js`) on `_Symbol.prototype` (polyfill), but `_is-object` returns `false` for `_Symbol.prototype` for some reason, so `_an-object` throws.

So, the call stack is the following:

* https://github.com/zloirock/core-js/blob/v2.2.2/modules/_an-object.js#L3 (throws)
* https://github.com/zloirock/core-js/blob/v2.2.2/modules/es6.symbol.js#L75
* https://github.com/zloirock/core-js/blob/v2.2.2/modules/_hide.js#L4
* https://github.com/zloirock/core-js/blob/v2.2.2/modules/es6.symbol.js#L229

**Comment by zloirock** [comment]
@skozin very strange. Can you write a reproducible example?

**Comment by skozin** [comment]
@zloirock, `_is_object` returns false because `_typeof` returns `"symbol"` for core-js Symbol polyfill, but `_is-object` fails to consider this case.

**Comment by skozin** [comment]
Here is the screenshots of the stack:

<img width="1280" alt="2016-04-14 12 59 53" src="https://cloud.githubusercontent.com/assets/1699593/14524694/44897ae0-0242-11e6-9f16-ce7becea22f7.png">
<img width="1280" alt="2016-04-14 13 00 31" src="https://cloud.githubusercontent.com/assets/1699593/14524698/4fd09082-0242-11e6-9050-c475f6bdefb9.png">
<img width="1280" alt="2016-04-14 13 01 10" src="https://cloud.githubusercontent.com/assets/1699593/14524713/59841306-0242-11e6-83cc-729c298f4c78.png">
<img width="1280" alt="2016-04-14 13 01 23" src="https://cloud.githubusercontent.com/assets/1699593/14524717/5f132bea-0242-11e6-8885-b57f8211f31c.png">

**Comment by skozin** [comment]
To reiterate: `_is-object` returns `false` for core-js' `Symbol` polyfill, because `_typeof` returns `"symbol"` for it, and `_is-object` expects typeof of an object to equal `"object"`.

**Comment by zloirock** [comment]
@skozin as I wrote - `core-js` should not be transformed by `babel`. I'll explore it later, but not sure fixing that makes sense because anyway transpiling `core-js` should cause other problems which can't be fixed.

**Comment by skozin** [comment]
@zloirock, I suppose babel doesn't change anything here, but let me try.

**Comment by zloirock** [comment]
@skozin looks like `babel` transpile `typeof` operator to helper which returns `"symbol"` instead of `"object"` for `Symbol.prototype`.

**Comment by skozin** [comment]
@zloirock, ah, so `_typeof` is not a part of `core-js`? I'll try to debug why it gets inserted, thanks!

**Comment by skozin** [comment]
@zloirock, thanks a lot for your help!

Now I see that [_is-object](https://github.com/zloirock/core-js/blob/v2.2.2/modules/_is-object.js)'s source indeed differs from what I see in the browser, sorry I that missed that in the first place.

It turned out that we used something like `/[/]node_modules[/]/` as Babel exclude RegExp, but it didn't work on Windows where path separator is `\` and where the test build was performed, so `core-js` was indeed processed by Babel.

I can confirm that everything works fine now that we're not processing core-js with Babel anymore.

**Comment by LeZuse** [comment]
Thanks for the investigation @skozin! I also agree on not fixing `core-js` for transpilation purposes, if anything this is a `babel` bug. Just curious, why are you not simply using `/node_modules/`?
