### ISSUE TITLE
Does core-js conditionally apply shims?

### ISSUE THREAD

**Issue by trusktr** [zloirock/core-js#190]
For example, if the browser already supports `Array.prototype.includes`, will core-js ignore setting that shim so that the browser's will take precedence?

**Comment by zloirock** [comment]
Sure. `core-js` replaces only broken implementations.

**Comment by trusktr** [comment]
@zloirock Mind pointing to the conditional check where that happens?

**Comment by zloirock** [comment]
`Array#includes` hasn't any extended feature detection, so it will be added to `Array.prototype` only if it's missed, see `modules/_export.js`. Some other polyfills have it and pass to `modules/_export.js` flag for forced replacement.

**Comment by petermikitsh** [comment]
The conditional application seems pretty inline with Wikipedia's definition of a [polyfill](https://en.wikipedia.org/wiki/Polyfill_(programming)).

> Polyfills allow web developers to use an API regardless of whether or not it is supported by a browser, and usually with minimal overhead. Typically they first check if a browser supports an API, and use it if available, otherwise using their own implementation.
