### ISSUE TITLE
IE11: Cannot define property 'name': object is not extensible

### ISSUE THREAD

**Issue by glortho** [zloirock/core-js#193]
When using es6.function.name (and es6.symbol) in IE11 there appear to be some circumstances where  `dP(this, NAME, createDesc(5, name))` in https://github.com/zloirock/core-js/blob/master/modules/es6.function.name.js#L13 throws the above error, presumably because the object has been frozen or sealed.

One such case where this happens is in certain accesses of `componentClass.name` here: https://github.com/facebook/react/blob/67f8524e88abbf1ac0fd86d38a0477d11fbc7b3e/src/isomorphic/classic/element/ReactElementValidator.js#L237 . 

This approach is a safer alternative, though with some obvious drawbacks by comparison: https://github.com/JamesMGreene/Function.name/blob/master/Function.name.js

**Comment by zloirock** [comment]
Ok, I will add a fallback for frozen functions.
