### ISSUE TITLE
Firefox error: Function.prototype.toString called on incompatible object

### ISSUE THREAD

**Issue by Robinnnnn** [zloirock/core-js#195]
My website fails to load on older versions of Firefox, displaying the following error: `TypeError: Function.prototype.toString called on incompatible object`.

I've traced the error to a collection of babel-related node modules, including but not limited to: `babel-core/browser-polyfill.min.js`, `babel-core/browser.min.js`, `babel-polyfill/browser.js`, etc.

I obviously depend heavily on these libraries to transpile my ES6 code. Is there any other fix / polyfill I can inject specifically for this error?

**Comment by Robinnnnn** [comment]
I've also updated to the latest `lodash` v4.12 and apparently that should [no longer be an issue](https://github.com/gaearon/react-transform-hmr/issues/73)

**Comment by Robinnnnn** [comment]
The browser console complained about this line:
`(Function.prototype,u,function(){return"function"==typeof this&&this[i]||c.call(this)})}`. The error occured at the end, where it tries to attempt `c.call(this)`.

Upon doing some digging it seems that this is the corresponding line in an unminfied version of `browser-polyfill.js`:
```
(Function.prototype, TO_STRING, function toString(){
  return typeof this == 'function' && this[SRC] || $toString.call(this);
})
```
Still at a loss.

**Comment by zloirock** [comment]
`core-js` tested in all FF versions above 4. Please, write a reproducible example, without it I can't say anything.

**Comment by Robinnnnn** [comment]
My issue is in FF v39.0 and below. The stack trace is confusing because it leads back to a minified file, and I never call `toString` in my codebase.

**Comment by Robinnnnn** [comment]
I should emphasize here that the site loads just fine on later versions of FF

**Comment by zloirock** [comment]
> I never call `toString` in my codebase

Then apparently you use a library which calls it, like `lodash` by your link. As I wrote, this code - just wrapper for `Function#toString` and calls original `Function#toString` only when you call `Function#toString` with the same target object.

**Comment by Robinnnnn** [comment]
Thanks, I'll try to find a fix elsewhere.
