### ISSUE TITLE
IE11: es6.symbol.js: toPrimitive -> [object (_Symbol)] ist not an object

### ISSUE THREAD

**Issue by Mischi** [zloirock/core-js#196]
Hi, 
we 're getting an unhandled exception lately while running our internal test suite. The error **[object (_Symbol)] is not an object!** is thrown at https://github.com/zloirock/core-js/blob/master/modules/es6.symbol.js#L75 

The callstack looks like this:
https://github.com/zloirock/core-js/blob/master/modules/es6.symbol.js#L75 
https://github.com/zloirock/core-js/blob/master/modules/_hide.js#L4
https://github.com/zloirock/core-js/blob/master/modules/es6.symbol.js#L229
https://github.com/zloirock/core-js/blob/master/es6/symbol.js#L1

The error shows up in IE11. We have a pretty complicated toolchain and i wasn't able to produce a minimal demo yet. We use Webpack to build our Tests which are written in TypeScript 1.8.10 and go through babel too. Then we run out tests with karma.

We import core-js via `import 'core-js`.

Any ideas what the problem could be?

Cheers,
Fabian

**Comment by zloirock** [comment]
See #189. Babel should not transpile `core-js`.

**Comment by Mischi** [comment]
Thanks!

CC: @davidreher
