### ISSUE TITLE
option to not use es7.string.at with es6.string.iterator

### ISSUE THREAD

**Issue by kevinbarabash** [zloirock/core-js#198]
It would be nice if there was a way to use `es6.string.iterator` without pulling in `es7.string.at`.  We're creating a custom build in order to keep the size of the polyfills down and adding `es6.string.iterator` added approximately 4K which was unexpected.

**Comment by zloirock** [comment]
I don't think that makes sense. `es6.string.iterator` uses [`_string-at`](https://github.com/zloirock/core-js/blob/master/modules/_string-at.js), not `es7.string.at`, it's enough small dependency. If you don't need iteration by code points - you can use `Array` iterator for strings - `String.prototype[Symbol.iterator] = Array.prototype[Symbol.iterator]`.

**Comment by kevinbarabash** [comment]
I'll go with `String.prototype[Symbol.iterator] = Array.prototype[Symbol.iterator]`.  Thanks.
