### ISSUE TITLE
Library versions of Map and Set doesn't implement @@toStringTag

### ISSUE THREAD

**Issue by chicoxyzzy** [zloirock/core-js#199]
```
(new Map()).toString();
(new Set()).toString();
```

expected output:

```
[object Map]
[object Set]
```

actual output:

```
[object Object]
[object Object]
```

I've found this working on https://github.com/facebook/react/pull/6780 (https://github.com/facebook/react/pull/6780#issuecomment-219414511)

**Comment by zloirock** [comment]
Not exactly. `@@toStringTag` here available, but `@@toStringTag` behavior in `Object#toString` implemented only in global polyfill mode - we should not override built-ins in library version. I see only 2 possible solutions - override `Object#toString` in library version too or add own `toString` methods to `Map`, `Set` and other built-in prototypes. Any ideas?

**Comment by chicoxyzzy** [comment]
What do you mean by _own_ `toString` methods?

**Comment by zloirock** [comment]
I mean `toString` methods with `@@toStringTag` logic on `Map`, `Set`, etc prototypes in library version instead of patching `Object#toString`.

**Comment by chicoxyzzy** [comment]
In that case I think this is preferable solution

**Comment by zloirock** [comment]
In `v3` branch, they have own `toString` methods.
