### ISSUE TITLE
core-js@2.4.0 npm install , invalid target

### ISSUE THREAD

**Issue by gtame** [zloirock/core-js#201]
If you execute this command
$ npm install  core-js@2.4.0 --save-dev
The output :
npm ERR! node v6.2.0
npm ERR! npm  v3.8.8

npm ERR! No compatible version found: core-js@2.4.0
npm ERR! Valid install targets:
npm ERR! 2.3.0, 2.2.2, 2.2.1, 2.2.0, 2.1.5, 2.1.4, 2.1.3, 2.1.2, 2.1.1, 2.1.0, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 2.0.0-beta.2, 2.0.0-beta, 2.0.0-alpha, 1.2.6, 1.2.5, 1.2.4, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.1, 1.0.0, 0.9.18, 0.9.17, 0.9.16, 0.9.15, 0.9.14, 0.9.13, 0.9.12, 0.9.11, 0.9.10, 0.9.9, 0.9.8, 0.9.7, 0.9.6, 0.9.5, 0.9.4, 0.9.3, 0.9.2, 0.9.1, 0.9.0, 0.8.4, 0.8.3, 0.8.2, 0.8.1, 0.8.0, 0.7.2, 0.7.1, 0.7.0, 0.6.1, 0.6.0, 0.5.4, 0.5.3, 0.5.2, 0.5.1, 0.5.0, 0.4.10, 0.4.9, 0.4.8, 0.4.7, 0.4.6, 0.4.5, 0.4.4, 0.4.3, 0.4.2, 0.4.1, 0.4.0, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.0.9, 0.0.8, 0.0.7, 0.0.5, 0.0.4, 0.0.3
npm ERR!

There is something wrong in the npm package, https://registry.npmjs.org/core-js . The target core-js@2.4.0 doesn't exists.

**Comment by zloirock** [comment]
`core-js@2.4.0` available on NPM, so it's definitely not `core-js` issue.

![111](https://cloud.githubusercontent.com/assets/2213682/15454887/a56eaeb2-206e-11e6-9ff5-9cc37e5e1950.png)
You can try to clean NPM cache.

**Comment by gtame** [comment]
Sorry, I am a newbie in this technology.
Now, It's working. You a're the man :+1: 
Thanks for your help
