### ISSUE TITLE
Restrictions for contents of script elements (_object-create.js)

### ISSUE THREAD

**Issue by epiloque** [zloirock/core-js#204]
In-lining the `core-js/library/modules/_object-create.js` in html `<script>` tag may theoretically backfire, `_object-create.js` has `<script>` tags in the source.

Should this be adressed ?

> [Restrictions for contents of script elements](https://www.w3.org/TR/html5/scripting-1.html#restrictions-for-contents-of-script-elements)

> The easiest and safest way to avoid the rather strange restrictions described in this section is to always escape "<!--" as "<\!--", "<script" as "<\script", and "</script" as "<\/script" when these sequences appear in literals in scripts (e.g. in strings, regular expressions, or comments), and to avoid writing code that uses such constructs in expressions. Doing so avoids the pitfalls that the restrictions in this section are prone to triggering: namely, that, for historical reasons, parsing of script blocks in HTML is a strange and exotic practice that acts unintuitively in the face of these sequences.

[_object-create.js#L23](https://github.com/zloirock/core-js/blob/e482646353b489e200a5ecccca6af5c01f0b4ef2/library/modules/_object-create.js#L23)

```js

  iframeDocument.open();
  iframeDocument.write('<script>document.F=Object</script' + gt);
  iframeDocument.close();

```

**Comment by zloirock** [comment]
We had a problem with `</script>`, so now it's splitted, but not with `<script>`. Anyway, just in case, I'll fix this issue later.

**Comment by epiloque** [comment]
Would you accept a PR ?

On 06/03, Denis Pushkarev wrote:
> We had a problem with `</script>`, so now it's splitted, but not with `<script>`. Anyway, just in case, I'll fix this issue later.
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/zloirock/core-js/issues/204#issuecomment-223697463

-- 

Mark Milstein

@epiloque
+1-917-719-1790
http://bit.ly/pgp-key-mm

**Comment by zloirock** [comment]
Sure.
