### ISSUE TITLE
Unhandled promise rejections doesn't emit unhandledRejection event in the browser

### ISSUE THREAD

**Issue by thomasguillory** [zloirock/core-js#205]
Using `babel-polyfill`, it seems I'm unable to catch promise rejections with this syntax:

``` javascript
window.addEventListener('unhandledRejection', (event) => {
   ...
})
```

However I'm able to catch them with

``` javascript
window.onunhandledrejection = (event) => {
   ...
}
```

I think it's related to this line:
https://github.com/zloirock/core-js/blob/add384de52cb380ff16118664f2d177302943b1a/library/modules/es6.promise.js#L116

**Comment by zloirock** [comment]
Yep, it still not implemented. I'll add it later. Feel free add a PR.

**Comment by Xanderite** [comment]
Hey, was just going to have a go implementing this, but didn't realise there is no polyfill for event/custom event for the reasons described here https://github.com/zloirock/core-js/issues/354.

So not really sure how to resolve this.

Also it seems like maybe a large refactor to implement, here is my naive attempt with comments on why it wouldn't work:

```js
      if(isUnhandled(promise)){
        if(isNode){
          process.emit('unhandledRejection', value, promise);
        } else {
          // This is required to call onunhandledrejection on any browser except chrome
          // but using in chrome this will cause it to be called twice as it will also be triggered when the event is dispatched on the window.
          if(handler = global.onunhandledrejection){
            handler({promise: promise, reason: value});            
          }

          // This doesn't work in IE11-
          var unhandledRejectionEvent = new Event('unhandledrejection');

          unhandledRejectionEvent.promise = promise;
          unhandledRejectionEvent.reason = value;

          global.dispatchEvent(unhandledRejectionEvent)
        }

      // Also what condition should be used to determine logging like:
      // console.error('Unhandled promise rejection', value);
      } record.a = undefined;
```
I don't really have much experience with older browser quirks, so some help would be appreciated.

**Comment by Kovensky** [comment]
You should be able to use `document.createEvent('Event')` in this case, despite being deprecated.

**Comment by zloirock** [comment]
Added to [v3](https://github.com/zloirock/core-js/pull/325) branch.
