### ISSUE TITLE
Symbol prototype deleted after redefine toString with PhantomJS

### ISSUE THREAD

**Issue by nathancahill** [zloirock/core-js#206]
https://github.com/zloirock/core-js/blob/master/modules/es6.symbol.js#L144

Before this line, `$Symbol[PROTOTYPE]` is defined. After this line, it is `undefined`.

```js
redefine($Symbol[PROTOTYPE], 'toString', function toString(){
    return this._k;
});
```
I went down the rabbit hole: `redefine -> hide -> object-dp` where it seems to be calling `Object.defineProperty`, but I was unable to debug it further.

**Comment by zloirock** [comment]
Are you sure that you don't transpile `core-js`? `babel` should ignore it.

**Comment by zloirock** [comment]
Looks like duplicate #189.

**Comment by nathancahill** [comment]
Thanks @zloirock. Missed that issue, it is a duplicate. Somehow `babel-polyfill` was being included in the build, which I removed.
