### ISSUE TITLE
Chrome 51 always throws if dev tools open using core-js 1.2.6

### ISSUE THREAD

**Issue by Merri** [zloirock/core-js#207]
Using latest Chrome v51 on Windows results in this error with core-js@1.2.6 when developer tools are open:
```
Paused on promise rejection: 'TypeError: Iterator result undefined is not an object'
```
This error happens before any of our client code runs.

As a background we're still stuck with Babel 5.x which prevents from updating as it wants core-js from 1.x range. It is summer time so we don't have the resources to do a Babel upgrade until August. As a workaround I'm adding a temporary patch where browser actually loads core-js 2.4.0 instead and have my fingers crossed that this won't cause any issues.

Also, I'm not sure whether this issue is a bug in Chrome or core-js. Also sent feedback to Chrome linking to this issue.

**Comment by zloirock** [comment]
#186

**Comment by loklaan** [comment]
I've opened a backport request in the form of a pr, #210, so that libs depending on `v1.0.0` can still function in the current stable and future Chrome.

**Comment by gnizhak** [comment]
I had this issue with chrome 51 & core-js 1.2.6 so my colleague suggested that if I clicked the "Restore settings and reload" under Chrome dev tools Settings it might go away. It did. 

So it might have something to do with updating the dev tools settings and some historical property was causing this. Cannot really verify what happened though.

**Comment by craigsh** [comment]
@gnizhak Wow, I spent so much time trying to figure this out. The "Reset defaults and reload" in Chrome dev tools fixed things for me too.

**Comment by loklaan** [comment]
Awesome! Thanks @gnizhak 👍

**Comment by szarouski** [comment]
👎 , restore settings solution works because it disables stop on exception setting from sources tab. Turning it back causes issues. I guess it is time for upgrade for me...

**Comment by zloirock** [comment]
https://github.com/zloirock/core-js/releases/tag/v1.2.7
