### ISSUE TITLE
trim breaks in Phantomjs

### ISSUE THREAD

**Issue by knownasilya** [zloirock/core-js#208]
> TypeError: Can't call method on  null

This fails in PhantomJS 1.9 and 2.1.

Code:

```js
// 1 -> String#trimLeft
// 2 -> String#trimRight
// 3 -> String#trim
var trim = exporter.trim = function(string, TYPE){
  string = String(defined(string)); // <-------- HERE
  if(TYPE & 1)string = string.replace(ltrim, '');
  if(TYPE & 2)string = string.replace(rtrim, '');
  return string;
};
```

Originally filed here:
https://github.com/babel/ember-cli-babel/issues/75

**Comment by zloirock** [comment]
It should be thrown only if you use something like `''.trim.call(null)`. `core-js` tested in PhantomJS, so most likely it's a bug in your code. Without a reproducible example, I can't help here.

**Comment by knownasilya** [comment]
It works in any other browser though. Any ideas on a possible reason for that?

**Comment by zloirock** [comment]
No ideas. I tested it in different versions of PhantomJS just now - all works fine

**Comment by stefanpenner** [comment]
@knownasilya maybe an example demonstrating the Phantom only problem?

**Comment by knownasilya** [comment]
Looks like it's this code:

```js
if (parseInt(ws + '08') !== 8 || parseInt(ws + '0x16') !== 22) {
/* eslint-enable radix */
    /* global parseInt: true */
    parseInt = (function (origParseInt) {
        var hexRegex = /^[\-+]?0[xX]/;
        return function parseInt(str, radix) {
            var string = trim(str);
            var defaultedRadix = $Number(radix) || (hexRegex.test(string) ? 16 : 10);
            return origParseInt(string, defaultedRadix);
        };
    }(parseInt));
}
```

The trim is being executed by Google Maps..

**Comment by zloirock** [comment]
@knownasilya it's not a code from [actual `core-js` version](https://github.com/zloirock/core-js/blob/master/modules/_parse-int.js).

**Comment by knownasilya** [comment]
Found it.. https://github.com/es-shims/es5-shim/blob/master/es5-shim.js#L1977
