### ISSUE TITLE
Object.entries not supported?

### ISSUE THREAD

**Issue by n1ru4l** [zloirock/core-js#209]
I could not find a polyfill for Object.entries()
Please prove me if I am wrong :neutral_face:

https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Object/entries
Polyfill: https://github.com/es-shims/Object.entries

**Comment by loganfsmyth** [comment]
`core-js` does indeed include a polyfill for `Object.entries`, it's listed in the Stage 4 section of the README: https://github.com/zloirock/core-js#stage-4-proposals
