### ISSUE TITLE
Internal modules cannot be checked into Team Foundation Server due to leading $

### ISSUE THREAD

**Issue by awesley** [zloirock/core-js#212]
Hi, realize this is a bit of world-collision but as per https://msdn.microsoft.com/en-us/library/ms245472(v=vs.100).aspx files with $ as a leading character cannot be checked into TFS.

When installing core-js via Node many of these internal modules are included.

**Comment by zloirock** [comment]
[It was fixed a long time ago.](https://github.com/zloirock/core-js/issues/129)
