### ISSUE TITLE
core-js tries but fails to polyfill Safari 9.1.1 Promise

### ISSUE THREAD

**Issue by Kovensky** [zloirock/core-js#214]
I have no idea what is going on. Assigning `out` to `target[key]` gets `out` overwritten instead, somehow. This debugging session (paused just before `if(target)`) is probably the best explanation I can provide:

![](http://puu.sh/pzi1b/f20f00a0e4.png)

**Comment by zloirock** [comment]
I can't understand the problem. After calling `redefine`, `Promise` polyfill (`out`) should look like a native `Promise` constructor, but it's a polyfill, it's expected behavior. All tests passed in Safari 9.1.1.

**Comment by Kovensky** [comment]
I see, I misunderstood the expected behaviour.

I thought this was the ultimate cause of some strange behaviour I had when using a combination of `babel-runtime`, `babel-polyfill` (both using `core-js`) and https://github.com/ljharb/proposal-promise-finally/blob/master/polyfill.js the latter definitely runs after babel-polyfill and core-js, so it should polyfill whatever it is that core-js decided to use, but `babel-runtime/core-js/promise` was seeing core-js's non-polyfilled Promise. This made promises returned by `asyncToGenerator` not be the same Promise as the one that was polyfilled.

It looks like the actual cause is that babel uses "fake" ES6 modules -- patching `window.Promise` does not patch the promise that gets read by `{ "default": require("core-js/library/fn/promise"), __esModule: true }`.
