### ISSUE TITLE
unused variables.

### ISSUE THREAD

**Issue by trusktr** [zloirock/core-js#217]
Seems like https://github.com/zloirock/core-js/blob/master/modules/es6.promise.js#L8 and https://github.com/zloirock/core-js/blob/master/modules/es6.promise.js#L12 are unused variables that Webpack 2 complains about:

![screen shot 2016-06-30 at 5 05 57 pm](https://cloud.githubusercontent.com/assets/297678/16508137/f667c8aa-3ee4-11e6-8840-5e5b5c9c94ca.png)

**Comment by zloirock** [comment]
Thanks.
