### ISSUE TITLE
Breaking in IE11

### ISSUE THREAD

**Issue by danielhusar** [zloirock/core-js#219]
Hey,

Im not sure if Im doing something wrong, but this module is breaking for me in IE11.
Im using the `babel polyfill` together with webpack, but if my js file contains only:

```js
import 'babel-polyfill';
```

it breaks in IE11 with this error:

<img width="508" alt="screen shot 2016-07-12 at 20 37 47" src="https://cloud.githubusercontent.com/assets/1857751/16780927/b5c07f46-4870-11e6-994e-59259d6e0dd2.png">

**Comment by zloirock** [comment]
Looks like duplicate #189.

**Comment by danielhusar** [comment]
thanks!
