### ISSUE TITLE
Ignore the test directory when publishing to npm

### ISSUE THREAD

**Issue by hawkrives** [zloirock/core-js#22]
Unless you preform some sort of sanity checks when npm installs `core-js`, or have a good reason to ship the test out with every copy of `core-js`, would you accept a PR to add an `.npmignore` file?

That way, npm doesn't install 1.1MB of tests into node_modules for every library that uses `core-js`.

(Additionally, it shrinks `6to5` from ~20MB on my machine.)

BTW, great job on this library. It's amazing!

**Comment by zloirock** [comment]
Thanks!
