### ISSUE TITLE
use native check will always fail

### ISSUE THREAD

**Issue by ishowshao** [zloirock/core-js#221]
```
var USE_NATIVE = !!function(){
  try {
    // correct subclassing with @@species support
    var promise     = $Promise.resolve(1)
      , FakePromise = (promise.constructor = {})[require('./_wks')('species')] = function(exec){ exec(empty, empty); };
    // unhandled rejections tracking support, NodeJS Promise without it fails @@species test
    return (isNode || typeof PromiseRejectionEvent == 'function') && promise.then(empty) instanceof FakePromise;
  } catch(e){ /* empty */ }
}();
```
this use native check will always fail because  `promise.then(empty)` will throw error

so it will always use babel's Promise, but babel's Promise has bug in iOS9.3 webview, Promise.resolve not resolving when page scrolling

**Comment by zloirock** [comment]
Native check correctly fails because this promise implementation does not support `@@species` pattern and unhandled rejection tracking. If you have an issue with "babel's Promise bug in iOS9.3 webview" - please, open issue about it, add details and reproducible example.
