### ISSUE TITLE
Why library folders code is repetition with outsize?

### ISSUE THREAD

**Issue by jcs12311** [zloirock/core-js#222]
eg: 
`library/shim.js` and `core-js/shim.js`,
`core-js/library/es7/array.js` and `core-js/es7/array.js`.
these code was totally same.

the release js file was has twice code-js code, it was about 190kb addition code if no using minfiy.

**Comment by zloirock** [comment]
`core-js/shim.js` and `core-js/es7/array.js` use `core-js/modules`, `core-js/library/shim.js ` and `core-js/library/es7/array.js ` - `core-js/library/modules`, modules from those paths have some difference - global mode and without gobal namespace pollution.
