### ISSUE TITLE
Literal object as Map

### ISSUE THREAD

**Issue by bevrard** [zloirock/core-js#223]
Hi,

I've an issue when I try to create an Object as a map:
`let response:Response = <Response> {
    event: {
        descriptions: <Map<string,string>> {
            "en": "test"
        }
 }`

I get the error:
 error TS2352: Neither type '{ "en": string; }' nor type 'Map<string, string>' is assignable to the other.
  Property 'clear' is missing in type '{ "en": string; }'.

I don't understand what's happening.  If I'm doing the following code, it's working:
 let descriptionValues = new Map<string, string>();
        descriptionValues.set('en','description_EN');

`let response:Response = <Response> {
    event: {
        descriptions: descriptionValues 
 }`

I'm using Angular2 RC4 with core-js 2.4.0.

Is it possible to create a literal object as a map?

Thanks in advance,

Benjamin

**Comment by Kovensky** [comment]
Use `Map`'s constructor with an iterable yielding key-value pairs. `Object.entries()` is one such iterable that returns an object's enumerable key-value pairs.

`new Map(Object.entries({ your: 'object' }))` will produce a `Map {"your" => "object"}`.

**Comment by bevrard** [comment]
Ok but when I do it with the _http methods there is no problem:
`this._http.get(URL).map(response=> {
    let findLastAppointmentByClientIdResponse = <FindLastAppointmentByClientIdResponse> {
         event: response.json()
    };
    return findLastAppointmentByClientIdResponse;`
});`      
The Map in the FindLastAppointmentByClientIdResponse Interface is automatically filled.

Is there a special method in _http for this?

**Comment by zloirock** [comment]
Rather it looks like a question for Angular community, @Kovensky answer looks enough about `core-js` / ECMAScript standard library part this question.

**Comment by bevrard** [comment]
Thank you for your answers :)
