### ISSUE TITLE
Add Promise.prototype.finally per tc39 0716

### ISSUE THREAD

**Issue by clavecoder** [zloirock/core-js#225]
Since TC39 moved [`Promise.prototype.finally`](https://github.com/ljharb/proposal-promise-finally) to [Stage 2 in the 07 '16 meeting](https://github.com/tc39/proposals/commit/a6696379bcec50cea8b3a32496dcaa4d00baf636), add to `core.js`. Was requested previously as #70, by others.

**Comment by zloirock** [comment]
Makes sense. Feel free to add a PR.

**Comment by xjamundx** [comment]
Any movement here.

**Comment by zloirock** [comment]
@xjamundx now I have some problems with time, it will be added when I'll be a little freer.

**Comment by clavecoder** [comment]
I'll integrate this weekend, promise!

**Comment by zloirock** [comment]
@clavecoder 👍

**Comment by xjamundx** [comment]
Thanks friends!

**Comment by Kovensky** [comment]
I'd suggest basing it on the proposal's own polyfill at https://github.com/tc39/proposal-promise-finally/blob/master/polyfill.js. It takes one less microtask tick to settle and correctly supports `@@species` (though you may be able to use core-js's `_species-constructor`).

**Comment by clavecoder** [comment]
PR (#238) created, as promised. Tripped up a bit, perhaps, with the reserved word function name and, possibly by the species of `Promise`. Preliminary reviews very welcome!

**Comment by zloirock** [comment]
https://github.com/zloirock/core-js/commit/ed59a9c0822eb1fa3509e06f996f424d8392d0a9, https://github.com/zloirock/core-js/commit/86ed553fbaa2d1e2f380bfe174f158e711e2e51f, https://github.com/zloirock/core-js/commit/fd70e24f8f076177c321b29aa2dc3b4de8592122, https://github.com/zloirock/core-js/commit/0bc7a9ea75fd1a604cc6c99eb755c32a08afda9a

**Comment by clavecoder** [comment]
Thanks for bringing it home!
