### ISSUE TITLE
Consider adding ecma262 Math Extensions Stage 1 per TC39 0716

### ISSUE THREAD

**Issue by clavecoder** [zloirock/core-js#226]
The [Math Extensions](https://github.com/rwaldron/proposal-math-extensions) proposal was [moved to **Stage 1** in the TC39 07 '16 meeting](https://github.com/tc39/proposals/commit/78124021259eae3cde70186534fe32db34fefe7d). Consider adding it to `core.js`
## Details
1. Well-Known Intrinsic Objects
2. Math.clamp ( x, lower, upper )
3. Math.scale ( x, inLow, inHigh, outLow, outHigh )
4. Math.radians ( degrees )
5. Math.degrees ( radians )
6. Math.RAD_PER_DEG
7. Math.DEG_PER_RAD

**Comment by zloirock** [comment]
Makes sense. Feel free to add a PR.

**Comment by clavecoder** [comment]
Working on this one first. Basing off of `umulh` and `epsilon`. Testing now.

**Comment by clavecoder** [comment]
OK. Here's PR #227. Need a little work, but tests pass.

**Comment by zloirock** [comment]
Released in `2.5.0`.
