### ISSUE TITLE
Extraneous throw: Method Number.prototype.toFixed called on incompatible receiver #{Object}

### ISSUE THREAD

**Issue by clavecoder** [zloirock/core-js#228]
While debugging with breakpoints for "All Exceptions", i get an extraneous exception in core.js. It would be great if it could be avoided.

_I'm using WebPack 2/Babel 6 on a TypeScript 2/NodeJS 6 app..._

When loading an NodeJS app, while loading `es6.number.to-fixed.js` the following `TypeError` is thrown at the [line](https://github.com/zloirock/core-js/commit/d49f1031155afadc5967684f73efa7ba8fa5bd08#diff-ae6eec9e4bffb3540eb91fe128540fcaR64)

``` javascript
  // V8 ~ Android 4.3-
  $toFixed.call({});
```

however, the app loads and runs successfully.

> "TypeError: Method Number.prototype.toFixed called on incompatible receiver #<Object>\n    at Object.toFixed (native)\n    at ...\node_modules\core-js\modules\es6.number.to-fixed.js:64:12\n    at module.exports (...\node_modules\core-js\modules_fails.js:3:14)\n    at Object.<anonymous> (...\node_modules\core-js\modules\es6.number.to-fixed.js:62:26)\n    at Module._compile (module.js:541:32)\n    at Object.Module._extensions..js (module.js:550:10)\n    at Module.load (module.js:458:32)\n    at tryModuleLoad (module.js:417:12)\n    at Function.Module._load (module.js:409:3)\n    at Module.require (module.js:468:17)"

**Comment by kidandcat** [comment]
Same here +1

**Comment by ayozebarrera** [comment]
Someone noticed why was this happening? I'm having the same issue at the moment, can't figure out why

**Comment by ValeriiMal** [comment]
The same on Safari. It crashes only in Safari. Browser just become reload the page

**Comment by ValeriiMal** [comment]
Possible slution:
conditions: Safari and Angular; page reloads after clicking on button that nested to the form element. If there is no [ngSubmit] attribute on the form element try strictly specify the type of the button like <button type="button">

**Comment by zloirock** [comment]
`core-js` works as should polyfills work - it uses feature detection with possible throwing and catching errors. I don't think that I can't do anything here, it can be improved / fixed only on the side of your engine / debugger.
