### ISSUE TITLE
Add EventSource polyfill

### ISSUE THREAD

**Issue by ming-codes** [zloirock/core-js#229]
This is feature request for [EventSource](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events) polyfill. [There are numerous existing implementations](https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-Browser-Polyfills#eventsource), but I think it should be included in core-js.

All of the major browsers already supports it natively. IE is the only one that does not supports this.

**Comment by zloirock** [comment]
Sorry, but I'm not sure that it is in the scope of `core-js`...

**Comment by ming-codes** [comment]
How is this out of scope? Isn't polyfill missing browser features the scope?

**Comment by zloirock** [comment]
`core-js` contains mainly ECMAScript polyfills and polyfills for some related cross-platform features (`setImmediate`, iterators...). `EventSource` isn't cross-platform feature and not so close to ECMAScript.

**Comment by ming-codes** [comment]
Hm, if by cross-platform feature, you mean if there's a spec for it, then yes it does https://html.spec.whatwg.org/multipage/comms.html#server-sent-events

**Comment by zloirock** [comment]
@ming-codes we can implement it for browsers or for Node, but, for example, not for specific JS engines which does not know anything about the network or works here differently.
