### ISSUE TITLE
Circular dependency with Promise and microtask

### ISSUE THREAD

**Issue by b123400** [zloirock/core-js#231]
Here, Promise depends on microtask:
https://github.com/zloirock/core-js/blob/630378ea75326f2bc9cd12027dd6af37e45b1198/modules/es6.promise.js#L68

Here, microtask depends on Promise:
https://github.com/zloirock/core-js/blob/aa0c05d0b0ae5e60d944a22db8519eaff9b8cb38/library/modules/_microtask.js#L43

This bug makes Promise never resolve, on environment like [Pebble.js](https://developer.pebble.com/guides/communication/using-pebblekit-js/).

It can be reproduced easily with the following script:

```javascript
Promise.resolve().then(function(){
  console.log('thank you');
});
```

**Comment by zloirock** [comment]
Global `Promise` in microtask implementation used before polyfilling `Promise`, so it should not cause a circular dependency. Most likely you doing something wrong. Can you add a reproducible example?

**Comment by b123400** [comment]
Confirmed this is an issue with pebble.js, sorry for the mistake
