### ISSUE TITLE
Forced replacement prototype accessors methods fails Android 4.0

### ISSUE THREAD

**Issue by ikhilko** [zloirock/core-js#232]
We are using `babel-polyfill` in our code, and it loads core-js as dependency.
Unfortunately `core-js` fails application for Android 4.0. After some investigation i found the problem place, but have no idea why problem occurred here:

```
// Forced replacement prototype accessors methods
module.exports = require('./_library')|| !require('./_fails')(function(){
  var K = Math.random();
  // In FF throws only define methods
  __defineSetter__.call(null, K, function(){ /* empty */});
  delete require('./_global')[K];
});
```

Browser's engine raised "Uncaught illegal access" exception that for some magic reasons doesn't catched by `try/catch` while execution line:

```
__defineSetter__.call(null, K, function(){ /* empty */});
```

I have tried to replace this line with:

```
var obj = {};
__defineSetter__.call(obj, K, function(){ /* empty */});
delete obj[K];
```

and this fixed the problem, but i'm not sure that this is a right solution. So can anyone help me to solve this problem?

**Comment by lnwu** [comment]
Same issue in ios 10.3 iphone7 simulator

`__defineSetter__.call(null, "test", function () { /* empty */ });`
will cause error
`TypeError: null is not an object (evaluating '__defineSetter__.call(null, "test", function () { /* empty */ })')`
