### ISSUE TITLE
Safari failing USE_NATIVE test for Promises

### ISSUE THREAD

**Issue by Andarist** [zloirock/core-js#233]
https://github.com/zloirock/core-js/blob/master/modules/es6.promise.js#L23

Is this intended that Safari's native Promises failing this test? Does it mean that they are in some way buggy in Safari?

**Comment by Kovensky** [comment]
Safari 9 doesn't support `@@species`, Safari 10 will pass it.

**Comment by Andarist** [comment]
I've encountered really weird bug when this polyfill `Promise` would not resolve cause of depending on `MutationObserver` and `flush` which runs queued microtasks was not called. Had that for quite some time during a debug, but later it got 'fixed' without me doing anything about it. 

Maybe something has changed in the mean time, I dont know. Safari is a weird thing...

**Comment by zloirock** [comment]
Safari really fails some `USE_NATIVE` tests, you can check it. If you have an issue with `MutationObserver` - please, create a new issue and add a reproducible example.

**Comment by mvayngrib** [comment]
@Andarist @zloirock hit this issue as well, where in the console i'm typing `Promise.resolve('hey').then(console.log)` and it never resolves, the flush function never getting hit, while in the next tab it prints 'hey' like no one's business. Unfortunately i haven't figured out yet how to cause this issue on purpose.
