### ISSUE TITLE
Symbol.iterator not working?

### ISSUE THREAD

**Issue by trusktr** [zloirock/core-js#234]
Hello, I am getting

```
TypeError: undefined is not a function (evaluating 'this.attributes[Symbol.iterator]()')
```

in Safari, and thought maybe I can use core-js to fix this to add Symbol.iterator, but I tried core.min.js with no luck. Does core-js polyfill Symbol.iterator?

**Comment by loganfsmyth** [comment]
Looks like `NamedNodeMap` would need to be added to this list that's repeated in a few places: https://github.com/zloirock/core-js/blob/master/modules/web.dom.iterable.js#L11

Though from what I can see in the DOM spec (https://dom.spec.whatwg.org/#interface-namednodemap)  only `NodeList` and `DOMTokenList` are marked iterable, though it seems like Chrome has made a few other things iterable.

**Comment by trusktr** [comment]
That seems to be the problem! Where can I report this problem (i.e. request for it to be officially iterable)? Is there any disadvantage or reason why we would not want to make it iterable?

**Comment by trusktr** [comment]
Or, maybe a better question: Is there a generic and recommended way to make a non-iterable iterable at runtime?

**Comment by trusktr** [comment]
So for now, I'm using a small helper,

```js
function makeIterable(arrayLike) {
    return Array.prototype.slice.call(arrayLike)
}
```

so code becomes

```js
for (let attr of makeIterable(this.attributes))
```

Would you recommend any other way that may be better?

**Comment by loganfsmyth** [comment]
Sounds like you want `Array.from()` :)

**Comment by zloirock** [comment]
`NamedNodeMap` is iterable in `core-js@2.5`, thanks to @loganfsmyth.
