### ISSUE TITLE
Including Object.assign - Not working for me

### ISSUE THREAD

**Issue by dschinkel** [zloirock/core-js#239]
Am I not doing this right?  In my top level React component I tried the following:

```
import assign from 'core-js/library/fn/object/assign';
```

also tried this

```
require('core-js/library/fn/object/assign');
```

doesn't seem to be working.  When I test in IE still getting:

```
Error: Object doesn't support property or method 'assign'
```

**Comment by zloirock** [comment]
If you wanna global polyfill - use it without `library`.

**Comment by dschinkel** [comment]
what's the difference?  what just take out '/library' in that path?

**Comment by zloirock** [comment]
Yep.

**Comment by dschinkel** [comment]
thanks....
