### ISSUE TITLE
FF 24 TypeError

### ISSUE THREAD

**Issue by dmvjs** [zloirock/core-js#24]
[11:40:02.146] TypeError: inst[FOR_EACH] is not a function 

isWeak || inst[FOR_EACH](function(val, key){

**Comment by dmvjs** [comment]
isWeak || typeof inst[FOR_EACH] === 'function' && inst[FOR_EACH](function(val, key)

seems to work

**Comment by zloirock** [comment]
Thanks! Seems like FF20-24 problem, i check `{Map, Set}#entries`, but removed check `{Map, Set}#forEach`.

**Comment by zloirock** [comment]
Fixed as 0.4.9, https://github.com/zloirock/core-js/commit/d87ce9b8bb35eb9b7fa3f86d3fbb1884bf51e843

**Comment by dmvjs** [comment]
Thank you!
