### ISSUE TITLE
acosh crash on node

### ISSUE THREAD

**Issue by amitport** [zloirock/core-js#244]
https://github.com/zloirock/core-js/blob/master/modules/es6.math.acosh.js#L9

running `$acosh(Number.MAX_VALUE)` crash the process with exit code `-1073741795 (0xC000001D)`

node v6.6.0
win 7 pro

**Comment by zloirock** [comment]
Sorry, I can't reproduce it:

![2016-09-21_22-21-32](https://cloud.githubusercontent.com/assets/2213682/18717419/00ce732e-804a-11e6-914f-f40c6a3ee891.png)
(the same on Windows). Make sure that you don't load any incorrect implementation before.

**Comment by zloirock** [comment]
Googling by exit code returns some strange results - maybe you have some problems with your environment.
