### ISSUE TITLE
Importing only Symbol.iterator in typescript

### ISSUE THREAD

**Issue by flyon** [zloirock/core-js#245]
This works in typescript and results in working code in IE11: 
`import "core-js/es6/symbol"`, 

But it will bundle code for all Symbol functionality. What if I just want to include the code for Symbol.iterator?

I've tried: `import "core-js/library/fn/symbol/iterator";`
and  `import "core-js/library/fn/symbol/iterator";`

But both result in an error in IE11, `Symbol is undefined`

**Comment by zloirock** [comment]
For global polyfills version, you can't import only `Symbol.iterator`. But you can do it for the version without global namespace pollution which used, for example in `babel-runtime`. `core-js/library/fn/symbol/iterator` is a version without global namespace pollution. It does not create  global `Symbol` or `Symbol.iterator` property, but returns a key which can be used as it and adds iterators to arrays, strings, etc. For TypeScript it would be better load `Symbol` global polyfill and completely (`import "core-js/fn/symbol";`).
