### ISSUE TITLE
IE8 exception thrown and not caught

### ISSUE THREAD

**Issue by loliparra80** [zloirock/core-js#250]
When I try to open my website in a internet explorer ie8, doesn't work. While in IE11 I have no problems.

When I debug the error is: "Exception thrown and not caught" shim.js, line 595 character 50. It seems like don't recognize the "throw" on "throw TypeError(...".

What can I do?
Thanks.

**Comment by zloirock** [comment]
Most likely you doing something wrong. Can you add a reproducible example?

**Comment by continuata** [comment]
I have the exact same error in IE8 (same line and character)

**Comment by loliparra80** [comment]
Ok, give some days and I will try to put an example on plunker. Thanks

**Comment by colangiuli** [comment]
I have the same error.
i'm using ie11 emulating ie8

**Comment by loganfsmyth** [comment]
A reproducible example would be a big help.

**Comment by zloirock** [comment]
![cxbe_t7wmaau1q8](https://cloud.githubusercontent.com/assets/2213682/20005075/9924cd18-a2c2-11e6-96b0-4ddbfc8df21c.gif)
