### ISSUE TITLE
Relationship between `_library` and `USE_NATIVE` in es6.promise.js

### ISSUE THREAD

**Issue by taylor1791** [zloirock/core-js#251]
I was debugging some of our code and noticed that some files had the native `Promise.resolve` and others had the implementation in `es6.promise.js`. Furthermore, `Promise.reject` was the native implementation in both places. An investigation led me to find this bit of code.

```
$export($export.S + $export.F * !USE_NATIVE, PROMISE, {
  // 25.4.4.5 Promise.reject(r)
  ...
});
$export($export.S + $export.F * (LIBRARY || !USE_NATIVE), PROMISE, {
  // 25.4.4.6 Promise.resolve(x)
  ...
});
```

Specifically, it appears that `Promise.resolve` is always polyfilled regardless of the USE_NATIVE flag since `LIBRARY` is always true. This was unexpected to me.

What is the motivation to always polyfill `resolve`, but not necessarily `reject`?

**Comment by ebrentnelson** [comment]
+1

**Comment by zloirock** [comment]
`LIBRARY` is a flag that it's the version without global namespace pollution, native `Promise.resolve` will not work correctly because in this version `Promise` constructor wrapped, so in this version `Promise.resolve` should be always replaced.

**Comment by ebrentnelson** [comment]
I don't get it. Why would `Promise.resolve` not work if native `Promise` is available? I have replaced this manually and everything works (but better because I get native resolve function rather than a shimmed one). Where is a use case where it breaks when native promises are available? Also, as OP mentioned, why only `resolve` and not also `reject`? 

Seems broken to me.

**Comment by zloirock** [comment]
`library` is a version without global namespace pollution, `require('core-js/library/fn/promise') !== global.Promise` anyway. It's wrapper for preventing pollution and internally uses native `Promise` if it's enough correctly. Why will it not work as expected and why not `Promise.reject`? See the third step of http://www.ecma-international.org/ecma-262/7.0/#sec-promise.resolve

**Comment by zloirock** [comment]
Example:
```js
const $Promise = require('core-js/library/fn/promise');
const promise = $Promise.resolve(42);
console.log($Promise.resolve(promise) === promise); // -> true
$Promise.resolve = Promise.resolve;
console.log($Promise.resolve(promise) === promise); // -> false
```
