### ISSUE TITLE
NS_ERROR_XPC_BAD_OP_ON_WN_PROTO on old Firefox

### ISSUE THREAD

**Issue by PRR24** [zloirock/core-js#254]
Loading core-js/client/shim.min.js in Firefox 22 (well, need to support it still) results
NS_ERROR_XPC_BAD_OP_ON_WN_PROTO: Illegal operation on WrappedNative prototype object
Error happens on load time.

**Comment by PRR24** [comment]
Just in case -- Priority: low.

**Comment by loganfsmyth** [comment]
If you load the non-minified version, what line is throwing the error?

**Comment by PRR24** [comment]
Line 342: var D = gOPD(it, key); // function getOwnPropertyDescriptor(it, key)

**Comment by zloirock** [comment]
Sorry, I can't reproduce it - `core-js` tested in all FF versions from FF4 on Saucelabs. Please, add a reproducible example.

**Comment by PRR24** [comment]
The easiest way to repro the issue is using Angular 2 quickstart example https://angular.io/resources/live-examples/quickstart/ts/plnkr.html

But I think I was wrong while stating it happens on core-js at load time. I did use the same link for testing and removed all other js files from index to validate and it did, but...
Re-testing the same thing today, I can track that zone.js causes the error to apprean in the shim.
Aplogies, if it turns out zone.js issue :(

**Comment by zloirock** [comment]
It seems so.

**Comment by boom235** [comment]
I am having the same Problem @PRR24  Did you solve the issue? I need to support a very old Firefox, too -.-
which version of zone.js are you using? 0.6.21 still has that issue. I have been trying for days now to downgrade all depencies -.-

**Comment by cb03037** [comment]
Any luck anyone?
Same thing for me with brand new angular4 app, zone.js is 0.8.14 (latest).

**Comment by nickbar86** [comment]
I have the same issue

**Comment by nickbar86** [comment]
Basically the error is thrown by babel-polyfill.
I don't know if i should post it here or in babel but i assume that both should cooperate to be solved.
Specs Firefox v.20, babel-polyfill 6.26.0 
i know it might not concern you but just in case you can help, cause it is a blocking issue.
The error is thrown by core.js in file es6.symbol.js at line
10583: var D = gOPD(it, key);
```
var $getOwnPropertyDescriptor = function getOwnPropertyDescriptor(it, key) {
  it = toIObject(it);
  key = toPrimitive(key, true);
  if (it === ObjectProto && has(AllSymbols, key) && !has(OPSymbols, key)) return;
  var D = gOPD(it, key);
  if (D && has(AllSymbols, key) && !(has(it, HIDDEN) && it[HIDDEN][key])) D.enumerable = true;
  return D;
};
```

**Comment by zloirock** [comment]
> `var D = gOPD(it, key);`

That means that it's an issue with native `Object.getOwnPropertyDescriptor`, you see this line in the stack because `core-js` wraps this method.

As I wrote, please, add a simple reproducible example - `Object.getOwnPropertyDescriptor` with passed arguments, maybe it will help.

**Comment by nickbar86** [comment]
Well, i tried to reproduce it but the only thinnk i can get is that
` var D = gOPD(it, key);`
is called with params 
`it: [object XPC_WN_ModsAllowed_NoCall_Proto_JSClass], key:value`
