### ISSUE TITLE
wrong documentation for findIndex

### ISSUE THREAD

**Issue by OleksiiZubko** [zloirock/core-js#255]
As we got in PR https://github.com/zloirock/core-js/pull/253 , we have some error in documentation, the method returns -1, not undefined as we see in doc.

**Comment by zloirock** [comment]
If you meant the error in comments for type definition - it's not a correct place for this issue. It's  created by @rbuckton and a part of https://github.com/DefinitelyTyped/DefinitelyTyped repo.
