### ISSUE TITLE
HowTo import core-js Map into angular-cli webpack generated application

### ISSUE THREAD

**Issue by st-clair-clarke** [zloirock/core-js#256]
I logged an issue at [http://stackoverflow.com/questions/38814049/howto-import-core-js-map-into-angular-cli-webpack-generated-application](http://stackoverflow.com/questions/38814049/howto-import-core-js-map-into-angular-cli-webpack-generated-application). Could you please take a look at it form me.

Thanks

**Comment by zloirock** [comment]
I don't use TypeScript, so I don't know. Default type definitions available only for `core-js@0.9.7` - it's ~2 years old version. I think you can ask the author of those type definitions, cc @rbuckton. You can use `import 'core-js/es6/map';`, global `Map` and standard ES6 type definitions.

**Comment by aluanhaddad** [comment]
@st-clair-clarke Please see my answer to your stackoverflow question. @zloirock if you like I can post it here as well in case others have trouble.

**Comment by zloirock** [comment]
@aluanhaddad thanks. Feel free to add it if it could be useful for someone.

**Comment by aluanhaddad** [comment]
Apparently the fix didn't work for @st-clair-clarke but I have no idea as to why. The error is very specific.

**Comment by aluanhaddad** [comment]
I still believe this is the correct fix unless there's a bug and TypeScript.

The issue you are having is that the type definitions for core-js redeclare many of the types in .d.ts files automatically provided by TypeScript, but they are not as actively maintained and contain some divergent declarations.

core-js aims to polyfill the current and future specifications of the ECMAScript standard library. TypeScript aims to describe the types of those same current and future specifications. The type definitions available for core-js overlap.

You have a few solid options that you can use:

In tsconfig.json specify "noLib": true under "compilerOptions" telling TypeScript to refrain from automatically including its built in standard library declarations to the compilation context.
In tsconfig.json specify the "lib" option which gives you more granular control over which standard library declarations are included. For example you might specify "lib": ["es2017.symbol.wellknown", "dom"].
Uninstall the @types/core-js package and simply use TypeScript's built in declaration files as above by specifying "lib": ["es2017", "dom"]. You will continue to use core-js, but you will be using TypeScript's own well-maintained definitions to type the implementation.
After spending some time going back and forth between these options myself, I find that option 3 is the easiest to maintain.

Please note that the declaration files automatically included by TypeScript depend on the the "target" property in tsconfig
