### ISSUE TITLE
Observable#subscribe w/ callbacks

### ISSUE THREAD

**Issue by arcanis** [zloirock/core-js#257]
The [current Observable proposal](https://github.com/tc39/proposal-observable) allows two different ways to call `subscribe`: with an observer object, or via callbacks. The later doesn't seem to be supported by Core-js.

```
// Subscribes to the sequence with an observer
subscribe(observer : Observer) : Subscription;

// Subscribes to the sequence with callbacks
subscribe(onNext : Function, onError? : Function, onComplete? : Function) : Subscription;
```

**Comment by zloirock** [comment]
Some months ago `Observable` proposal was updated with some breaking changes. But we can't update it in `core-js` right now - it's breaking changes. It will be updated in next major version.

**Comment by fbuecklers** [comment]
Is that really API breaking changes? I See it more like an API addition. 
I have currently patched the core-js implementation with the following code:

```js
var sub = Observable.prototype.subscribe;
Observable.prototype.subscribe = function(onNext, onError, onComplete) {
  if (onNext instanceof Function) {
    return sub.call(this, {
      next: onNext,
      error: onError,
      complete: onComplete
    });
  } else {
    return sub.call(this, onNext);
  }
};
```
Or do im miss somthing here right now?

**Comment by zloirock** [comment]
For example, in `Observable#forEach` - it's just removed.

**Comment by zloirock** [comment]
Added to [v3](https://github.com/zloirock/core-js/pull/325) branch.
