### ISSUE TITLE
Math.log10(1000) should be 3

### ISSUE THREAD

**Issue by hakatashi** [zloirock/core-js#259]
Now ([Notebook](https://runkit.com/hakatashi/math-log10-1000-isnt-3)):

```js
var log10 = require('core-js/library/fn/math/log10');
console.log(log10(1000)); //=> 2.9999999999999996
console.log(log10(1000) === 3); //=> false
```

Though [the spec](http://www.ecma-international.org/ecma-262/6.0/#sec-math.log10) states this function is implementation-dependent, the base 10 logarithm of 1000 is obviously 3, and I think Math.log10(1000) should return 3.

Other implementations:

| Browser       | Result |
|---------------|--------|
| Edge 14       | 3      |
| Firefox 49    | 3      |
| Chrome 54     | 3      |
| Node.js 7.0.0 | 3      |

**Comment by Yaffle** [comment]
@hakatashi , if your use case is for integers only then you could use the next trick:
```
Math.floor(Math.log10(n + 0.5))
```

**Comment by zloirock** [comment]
I'll fix it today or tomorrow as `Math.log(n) * Math.LOG10E`.
