### ISSUE TITLE
ie11 out of memory issue with symbols

### ISSUE THREAD

**Issue by david-gang** [zloirock/core-js#260]
Put this in ie11.

```html
<head>
<script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>
<script>
for(var i=0; i<1000000; i++) {
Symbol(i)
}
</script>

</head>
<body>
</body>
```

It will give you out of memory

SCRIPT2344: Out of memory at line: 1

**Comment by david-gang** [comment]
this may be connected to https://github.com/zloirock/core-js/issues/143

**Comment by zloirock** [comment]
Yes, it's a known problem, but it can't be completely fixed, see the [caveats](https://github.com/zloirock/core-js#caveats-when-using-symbol-polyfill).

**Comment by david-gang** [comment]
Wow @zloirock . This is interesting. So maybe there should be a clear description not to use Symbols in ie11. My case was that i used https://github.com/ngUpgraders/ng-forward and after a couple of time the browser crashed. Is it a problem in the localstorage of ie11? Could it also make problems in other projects, like in angular2? Thanks for your quick reply.

**Comment by zloirock** [comment]
I thought that actual description is enough. Feel free to improve it. Now I haven't time to explore your library. In your example the third option from the caveats - uncontrolled creation symbols in the loop. For each symbol, we have a pair of accessors on `Object.prototype` for preventing enumerability in `for-in` and for some other specific behaviour. In JS, garbage collection is unobservable, so we can't delete those accessors after collection symbols. It's bad, but it's better than alternatives. You can disable this behaviour as `Symbol.useSimple()`. `core-js` have ~85000000 downloads and I don't see many issues about it. IIRC, `angular@2` does not use symbols internally.

**Comment by david-gang** [comment]
Thanks for your extensive explaination,
David
