### ISSUE TITLE
Stage 1 cancellable promise support?

### ISSUE THREAD

**Issue by isiahmeadows** [zloirock/core-js#263]
The [cancellable promise proposal](https://github.com/tc39/proposal-cancelable-promises) is stage 1, and could definitely use some people experimenting with it in the wild IMHO. Could it be added?

**Comment by Kovensky** [comment]
I have written a Cancel + CancelToken implementation that I could adapt to core-js; but integrating it with Promise could be a big performance hit.

The Cancel support has to change Promise internals, so this would result in core-js _always_ polyfilling, even when the feature it not used...

**Comment by isiahmeadows** [comment]
Are you sure? I thought it only needed to add a few extra methods, since
cancels are only a special type of rejection. I didn't think it would've
required modifying `then` or `catch`.

What specifically requires internal hackery?

On Sat, Dec 10, 2016, 21:25 Diogo Franco <notifications@github.com> wrote:

I have written a Cancel + CancelToken implementation that I could adapt to
core-js; but integrating it with Promise could be a big performance hit.

The Cancel support has to change Promise internals, so this would result in
core-js *always* polyfilling, even when the feature it not used...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zloirock/core-js/issues/263#issuecomment-266256327>,
or mute
the thread

**Comment by Kovensky** [comment]
@isiahmeadows the things related to the `HostPromiseRejectionTracker`

The case where the user does not add their own `catch` can be worked around by replacing `then` with `then (...args) { const ret = this.then(...args); ret.catch(e => e instanceof Cancel || throw e); return ret }`; but if the user _does_ attach their own `catch` handler, this would instead generate spurious promise rejection errors.

**Comment by isiahmeadows** [comment]
Oh. That will complicate things majorly...

I'll go file an issue on that proposal's repo.

**Comment by zloirock** [comment]
This proposal has been withdrawn, see the repo.
