### ISSUE TITLE
Interactive documentation

### ISSUE THREAD

**Issue by viebel** [zloirock/core-js#265]
Would you be interested by an interactive documentation/blog post like this ones:

- http://blog.klipse.tech/javascript/2016/12/19/es2017-sleep.html
- http://blog.klipse.tech/javascript/2016/12/19/es2017-entries.html

Disclaimer: I'm the author of the [klipse plugin](github.com/viebel/klipse).

**Comment by zloirock** [comment]
Sorry, I don't know why I missed this issue. Looks awesome -) When I'll need something like that, I'll try `klipse`.

**Comment by viebel** [comment]
Never too late!
