### ISSUE TITLE
"Clean up" npm distribution

### ISSUE THREAD

**Issue by ficristo** [zloirock/core-js#266]
I've installed react through npm and noticed that the node_modules folder takes 7.4 MB of which 4.4 are about this module.
Is it possible to reduce the size of the distribution?
We are trying to leverage to npm and, since we embed the results in a desktop application, size can matter.
(Probably there are tools like webpack or other that could help, but we are not there yet)

**Comment by Siilwyn** [comment]
The size seems absurd... For me the module takes a whopping 18.3MB!
I'm not sure what the file structure is but to me it looks like there is duplication in the files: the root and the files in `libraries`. :thinking:

**Comment by HugoDF** [comment]
`core-js` seems to only be used in the fixtures for the React package https://github.com/facebook/react/search?utf8=%E2%9C%93&q=import+%27core-js&type=, you could run a `postinstall` or `prebuild` script that removes it from node_modules (in your package.json "scripts" add `"postinstall": "rm -rf node_modules/core-js"`). Ideally you want to be packaging up your app though, your dev and transitive dependencies shouldn't be affecting your final build size so much.

**Comment by zloirock** [comment]
I don't know where you found 18.3 or 4.4 MB - `core-js@2.5.1` size on NPM is ~2 MB. Almost all what can be removed from the package already removed. [In the next major release](https://github.com/zloirock/core-js/pull/325) from the package will be removed 2 bundled versions and it will reduce the size twice.
