### ISSUE TITLE
Importing minified core|library|shim breaks Traceur build with a 'read-only' error.

### ISSUE THREAD

**Issue by lancemonotone** [zloirock/core-js#268]
I am on Windows 10, using PhpStorm v2016.3.2, and core-js v2.4.1 installed and updated via npm. 

I have set up a file watcher in PhpStorm to run Traceur automatically. If I import core-js into my main ES6 app like this `import '../node_modules/core-js/client/core.js';` the Traceur build works as expected. However if I attempt to use the minified version `import '../node_modules/core-js/client/core.min.js';` the build breaks with this error in the PhpStorm Run console:

```
cmd.exe /D /C call <path>/node_modules/.bin/traceur.cmd <path>\assets\js\src\<project>\<project>.es6 --out <path>\assets\js\src/<project>.js
<path>/node_modules/core-js/client/shim.min.js:7:28849: D is read-only
<path>/node_modules/core-js/client/shim.min.js:7:28854: G is read-only
```

D and G are both found in this section of minified code:
`C && F && F.name !== r && (D = !0, G = function values() {return F.call(this)})`

Which appears to refer to this block in core.js:2730.
```
// fix Array#{values, @@iterator}.name in V8 / FF
if(DEF_VALUES && $native && $native.name !== VALUES){
	VALUES_BUG = true;
	$default = function values(){ return $native.call(this); };
}
```

**Comment by zloirock** [comment]
It does not look like a `core-js` or `uglifyjs` (it's used for minification) issue - it's a correct code, so seems it's a problem of `traceur`.
