### ISSUE TITLE
Release Tagging

### ISSUE THREAD

**Issue by felixbuenemann** [zloirock/core-js#27]
Please add git tags in the form of `<major>.<minor>.<patch>` e.g `0.4.10` for each released version, so it's possible for bower to resolve the package version.

If you already have tags locally then `git push --tags` should push them to github.

**Comment by zloirock** [comment]
I'll do it when the time appears.

**Comment by felixbuenemann** [comment]
Thanks, it would already be great if you could just add a tag for the current release. I'm trying to create packages through https://rails-assets.org and it fails due to the missing tags.

Alternatively you could give me commit access for a short time and I'd be happy to look through the git history and add all the missing tags.
