### ISSUE TITLE
In node 0.10, Map/Set size don't throw on Set/Map, respectively

### ISSUE THREAD

**Issue by ljharb** [zloirock/core-js#272]
```js
var setSize = Object.getOwnPropertyDescriptor(Set.prototype, 'size').get;
var mapSize = Object.getOwnPropertyDescriptor(Map.prototype, 'size').get;

setSize.call(new Set()); // 0
mapSize.call(new Map()); // 0

assert.throws(function () { setSize.call(new Map()); }); // should throw but does not
assert.throws(function () { mapSize.call(new Set()); }); // should throw but does not
```

This code passes on es6-shim, and in any engine with native `Map`/`Set`.

**Comment by ljharb** [comment]
This is blocking `expect` and `object-inspect`, which affect a number of downstream projects. Any chance this could be looked at soon?

**Comment by ljharb** [comment]
Thanks! What version will this be released in?

**Comment by zloirock** [comment]
@ljharb sorry for the delay. I wanna fix some more issues and test it, so seems `2.5.0` will be released after some days.

**Comment by ljharb** [comment]
Sounds good, thanks! I'll keep an eye out for it.
