### ISSUE TITLE
Observable: Subscription and SubscriptionObserver prototypes lack a `closed` getter.

### ISSUE THREAD

**Issue by jasmith79** [zloirock/core-js#276]
Per the proposal both of the following `console.log`s should work (simplified example):

```javascript
let obs = new Observable(observer => { console.log(observer.closed); }); // undefined
let subs = obs.subscribe({});
console.log(subs.closed);  // undefined

console.log("closed" in subs); // false
```

This is part of the [test conformance suite](https://github.com/tc39/proposal-observable/search?utf8=%E2%9C%93&q=closed) and it should return `false` or `true` depending. Looking through the source code it doesn't seem implemented. Seems like a trivial PR if you'd like me to do it.

**Comment by zloirock** [comment]
I'll try to add it to `core-js@3` because actual `Observable` has many breaking changes.

**Comment by zloirock** [comment]
Added to [v3](https://github.com/zloirock/core-js/pull/325) branch.
