### ISSUE TITLE
Object.prototype.toString.call([]) returns incorrect result

### ISSUE THREAD

**Issue by Rhionin** [zloirock/core-js#278]
The [MDN-recommended way](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray#Polyfill) to check `isArray` is:

`// Without Core-js`
`Object.prototype.toString.call([]) === '[object Array]'; // true`

Core-js is replacing the array tag to be "Array Iterator" instead of "Array", which is breaking default behaviors which depend on it.

`// With Core-js`
`Object.prototype.toString.call([]) === '[object Array]'; // false`
`Object.prototype.toString.call([]) === '[object Array Iterator]'; // true`

In my case, core-js and [CKEditor](http://ckeditor.com/) don't get along because CKEditor isn't even trying to use `Array.isArray` before using their own polyfill (see [here](https://github.com/ckeditor/ckeditor-dev/blob/master/core/tools.js#L272-L274)). Note that I'm reporting to CKEditor that they should attempt to use Array.isArray before their polyfill, as that would make these compatible, but I still believe this is a concern as core-js is clobbering a default behavior.

**Comment by Rhionin** [comment]
Closing this. Turns out it was a combination of core-js and an older version of prototype.js (1.7.0), which is fixed when updating to 1.7.3. Y'all are great!

**Comment by RENSAAS** [comment]
results in [object Array]
Object.prototype.toString.call([])
