### ISSUE TITLE
TypedArray.from() error in Safari

### ISSUE THREAD

**Issue by ynishiza** [zloirock/core-js#285]
Hello, thanks for the great library.
As in the title, calling something like
```Uint8Array.from([1,2])```
raises this error in Safari:
```TypeError: TypedArray.from requires its this argument subclass a TypedArray constructor```

Safari version: 10.0.3
core-js version: 2.4.1

**Comment by arabold** [comment]
I run into the exact same problem and had to rewrite our code to use `new Uint8Array()` instead.

**Comment by cbush06** [comment]
This is still a problem

**Comment by zloirock** [comment]
@cbush06 make sure that you use the latest `core-js` version and in this case, please, create a new issue with a reproducible example.

**Comment by cbush06** [comment]
Will do. Thanks.
