### ISSUE TITLE
Object.getPrototypeOf doesn't work in IE 8

### ISSUE THREAD

**Issue by lukescott** [zloirock/core-js#29]
Sample code:
```html
var foo = function() {};
foo.prototype.foo = "foo";
var bar = function() {};
bar.prototype = Object.create(foo.prototype);
bar.prototype.constructor = bar;
alert(Object.getPrototypeOf(bar.prototype).foo);
```
This should output "foo", but instead gives "undefined". I know that it won't work in every situation, but where the constructor is correct `.constructor.prototype` [should return the correct value](http://ejohn.org/blog/objectgetprototypeof/). This works with [es5-sham](https://github.com/es-shims/es5-shim/blob/master/es5-sham.js).

**Comment by zloirock** [comment]
It's `Object.create` issue. This is by design, so as not to add extra enumerable properties and, where possible, to use the `constructor` property in `Object.getPrototypeOf`. I will fix it, but it will cause other problems.

**Comment by lukescott** [comment]
@zloirock That fixed it, thanks! I'm not sure what the side-effects are, but after doing some extensive testing it seems to be more correct than it was, and it works in my app without any problems.
