### ISSUE TITLE
IE8: errors when seeing a promise

### ISSUE THREAD

**Issue by binarykitchen** [zloirock/core-js#294]
<img width="598" alt="screen shot 2017-04-06 at 11 42 28" src="https://cloud.githubusercontent.com/assets/177641/24731673/a5fc23fe-1abf-11e7-91f2-eb1d2430577c.png">

it is this line `promise.catch(noop);`

I am requiring core-js like that at top of my angularjs app
`require('core-js/shim')`

Any clues?

**Comment by zloirock** [comment]
You can't use `catch` method name without quotes in IE8. You can use it as `promise['catch'](noop);` or use it with [`transform-es3-member-expression-literals` `babel` transform](http://babeljs.io/docs/plugins/transform-es3-member-expression-literals/).
