### ISSUE TITLE
Empty files

### ISSUE THREAD

**Issue by rdfriedl** [zloirock/core-js#295]
Ill start off by saying i have no idea how the build process works, or what files to what.
so i guess this issue it half a question and half a bug report.

so lately iv been using `babel-plugin-transform-runtime` in my projects, which as you know uses `core-js` to polyfill es6 and es7 features.

though when i use `rollup` to build my files, it complains that `/library/modules/es6.object.to-string.js` dose not export anything.

turns out, the file is empty ([link](https://github.com/zloirock/core-js/blob/6fb463d918a0094fc81a677979ca324e58ff149f/library/modules/es6.object.to-string.js))

So my question is, why is this file empty when other files depend on it.
And if its not meant to be empty, would this be an easy fix?

*Edit*
i found more files that are empty
 - `modules/library/es6.function.name.js` [link](https://github.com/zloirock/core-js/blob/6fb463d918a0094fc81a677979ca324e58ff149f/modules/library/es6.function.name.js)
 - `modules/library/es6.number.constructor.js` [link](https://github.com/zloirock/core-js/blob/6fb463d918a0094fc81a677979ca324e58ff149f/modules/library/es6.number.constructor.js)
 - `modules/library/es6.object.to-string.js` [link](https://github.com/zloirock/core-js/blob/6fb463d918a0094fc81a677979ca324e58ff149f/modules/library/es6.object.to-string.js)

**Comment by loganfsmyth** [comment]
My understanding is that they are there is symmetry between the `modules/` and `modules/library` folder, as https://github.com/zloirock/core-js/blob/master/modules/es6.function.name.js has that file, but it is not empty.

**Comment by zloirock** [comment]
@loganfsmyth's answer is correct. `core-js` have 2 main versions - with global polyfills and without global pollution. Not all features from the first version can be implemented in the second, but they have a lot of common code. For this reason, added caps like those files.
