### ISSUE TITLE
Array.prototype.includes

### ISSUE THREAD

**Issue by jeantimex** [zloirock/core-js#299]
Can we support Array.prototype.includes?

**Comment by nebulousdog** [comment]
looks like it is included in the es7 module? https://github.com/zloirock/core-js/blob/master/es7/array.js#L1

**Comment by jeantimex** [comment]
Ah thanks @nebulousdog!

**Comment by nebulousdog** [comment]
also, if you're using babel, see this issue: https://github.com/babel/babel-loader/issues/92
