### ISSUE TITLE
_has module throws error when document.domain set in IE8

### ISSUE THREAD

**Issue by eu81273** [zloirock/core-js#303]
If the document.domain property is set in the page, `_has` module throws error "Access is denied" when try to check window's property for example 'hasOwnProperty'.

So I think it is better to change `_has` module like below.

```javascript
var hasOwnProperty = {}.hasOwnProperty;
module.exports = function(it, key){
  try {
    return hasOwnProperty.call(it, key);
  } catch(e){
    return false;
  }
};
```

**Comment by zloirock** [comment]
`try / catch` is very slow for this case. Also, it will not correctly work with proxies. Could you show me any code where it causes problems?

**Comment by eu81273** [comment]
This may be IE8 issue.

```javascript
import 'core-js/es5';

document.domain = document.domain;
console.log(Object.getOwnPropertyNames(window));
```

**Comment by eu81273** [comment]
Another example. If the document.domain property is set in the page, _has module throws error. 

```html
<script src="https://raw.githubusercontent.com/zloirock/core-js/master/client/core.js"></script>
    <script>
        document.domain = document.domain;
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/rxjs/4.1.0/rx.all.js"></script>
```

**Comment by HalZhan** [comment]
+1.
And I met another similar problem when I try to use core-js/es5 in IE8 when the document.domain property is set before(If the document.domain property is not set, no errors occur.), and "core-js/modules/_object-create.js" throws an error with message "no access".

The origin code is:
```js
// ...
iframe.src = 'javascript:'; // eslint-disable-line no-script-url
// ...
```

I modified it to:
```js
if(document.domain) {
  iframe.src = 'javascript:void(function(){document.open();document.domain=\'' + document.domain + '\';document.write(\'\');document.close();}())';
}
else {
  iframe.src = 'javascript:'; // eslint-disable-line no-script-url
}
```

After the modification, core-js/es5 works fine in IE8. There is maybe some restriction of iframe.contentWindow.document in IE8-.

**Comment by zloirock** [comment]
Since I wanna drop pre-ES5 engines (IE8-) support in `core-js@4`, closed as `wontfix`.
