### ISSUE TITLE
Lighthouse complains use passive listeners 

### ISSUE THREAD

**Issue by awebdeveloper** [zloirock/core-js#305]
Hi,

I am using ionic which internal is using core-js. I ran lighthouse and it asked me to use passive listeners.
https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#feature-detection

I am using their polyfill.ng.js which according to this link (https://github.com/driftyco/ionic/blob/d2975c0ab0a4f35db08e237ebc41c55a2c1ebe68/scripts/gulp/util.ts#L301) uses two files of yours. So the issues is in one of the two files.
```
 'node_modules/core-js/es7/reflect.js',
 'node_modules/zone.js/dist/zone.js',
```

**Comment by aciccarello** [comment]
I looked quickly and didn't see any of the event listeners that [trigger that audit](https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners#how). It is probably an angular issue. See angular/angular#8866

**Comment by zloirock** [comment]
Apparently, @aciccarello is right.
