### ISSUE TITLE
Octal and binary numerics

### ISSUE THREAD

**Issue by RReverser** [zloirock/core-js#31]
Consider overriding `Number` constructor to test for cases like `0o7351...` and `0b010101...` so that those are getting converted with corresponding radix.

Possible implementation:
```javascript
var oldNumber = Number;
Number = function(obj) {
  if (typeof obj === 'string') {
    var res;
    if (res = obj.match(/^0o([0-7]+)$/i)) {
      obj = parseInt(res[1], 8);
    } else if (res = obj.match(/^0b([0-1]+)$/i)) {
      obj = parseInt(res[1], 2);
    }
  }
  return oldNumber.apply(this, arguments);
};
```

I've tried to inject it on my own and send PR, but core-js internals are somewhat complicated so I didn't find a way to override obvious way to override global `Number` with own implementation.

**Comment by zloirock** [comment]
It's already added as experimental [`es6.number.constructor`](https://github.com/zloirock/core-js/blob/master/src/es6.number.constructor.js) module and will be added in default builds after native support in stable v8 (Chromium ~41) and FF (~36) to prevent slowdown.

**Comment by RReverser** [comment]
Yeah, it should not cause any slowdown for non-string values as those will go through optimized flow and direct old `Number` will be inlined, and only for strings there will be subtle yet reasonable difference as it provides more features than original constructor.

**Comment by zloirock** [comment]
The main problem in slow `toPrimitive` conversion.

**Comment by RReverser** [comment]
You can't avoid `toPrimitive` conversion when someone decides to use `Number` directly as it's usually the exact purpose, so I don't see any problem here :)

**Comment by zloirock** [comment]
The problem is that in the fast case remain only numbers, bolleans, `null` and `undefined`. This is a popular and fast function / constructor, any slowdown here - slowdown for most applications. Though looking at the tests, it's not so bad.

**Comment by RReverser** [comment]
If that will become a real problem, you can extract manual number reading from Acorn :) But so far I also don't see any significant slowdowns with it.

**Comment by zloirock** [comment]
> you can extract manual number reading from Acorn

Looked it up, interesting, but I don't think it could be faster in this case.

**Comment by RReverser** [comment]
It could be - instead of looping through string twice (with regex for test, and then with too generic `parseInt` for parsing) it can loop just once and return `NaN` as soon as something unexpected is found. However, perf doesn't seem to be too bad even now.

**Comment by zloirock** [comment]
> instead of looping through string twice

[Once :)](http://jsperf.com/es6-number-constructor/2). But check without regexp [really quickly](http://jsperf.com/es6-number-constructor/3). Fully parsing in 1 loop is slower.

`parseInt` uses only for binary and octal literals, it's not regression for ES5.

I think, this implementation can be added.

**Comment by zloirock** [comment]
Added in 0.5.3.
