### ISSUE TITLE
Uncaught TypeError: Array is not a function

### ISSUE THREAD

**Issue by wood1986** [zloirock/core-js#310]
After the webpack bundling, it gives me some code like `Array(34)`. And this code is supposed to be es5 compatible. As the original source is coded in es6 syntax and with es6 methods, I did include `core-js/es6` in `webpack.config.js`

if I remove the `core-js/es6` and open my app in Chrome, no errors. Oppositely, if I include `core-js/es6`, it shows an error. Array is overridden by `core-js`

`function Array() { [ native code ] }` get overridden by `core-js`

What do I miss?

**Comment by jaydenseric** [comment]
Are you using Webpack v3?

Take a look at https://github.com/webpack/webpack/issues/5135.

**Comment by wood1986** [comment]
Webpack 2 has the same issue

**Comment by zloirock** [comment]
`core-js` should not replace `Array` constructor. Seems it's not a `core-js` bug. Could you add a reproducible example?

**Comment by zloirock** [comment]
Seems a problem of bundler, closed as `can't reproduce`.
