### ISSUE TITLE
EDGE: Unhandled Promise Rejection

### ISSUE THREAD

**Issue by stilefano** [zloirock/core-js#313]
Sorry if it's a duplicated question, but I do not find any similar issue.
I am testing my web app on Microsoft Edge and I am having this issue 

`Unhandled promise rejection TypeError: Invalid calling object`

Can you please help me?

Thank you.

**Comment by loganfsmyth** [comment]
That means somewhere in your code, something is throwing that error. I don't know Edge well enough to tell you how to debug. In Chrome there is a nice little arrow next to most messages like that that will give you a stack trace.

**Comment by zloirock** [comment]
Seems @loganfsmyth is right and the problem on your side.

**Comment by phun-ky** [comment]
I'm getting the same error, only in Edge, not in IE11 or other modern browsers

**Comment by nontachaiwebdev** [comment]
I'm getting the same error, but not every browser. My bundle work with new modern browser but not with mini safari that not support promise. I'm not sure that is reason of this.

If this happen because my code. Why my bundle work with some browser but not with some browser that not support promise.
