### ISSUE TITLE
Permission Issue with your package that breaks the machine and NPM

### ISSUE THREAD

**Issue by jeremykenedy** [zloirock/core-js#314]
After attempting to install your package I can not remove the folder `node_modules\.staging\core-js-5f573941\library\modules`.

The folder has unknown permissions from an unknown user that the Windows Administrator cannot even change. 

This package is causing me a big headache and now I cannot even remove it.

**Comment by loganfsmyth** [comment]
If there is a permission issue, it is likely an `npm` issue, since `core-js` has no control over how it is installed. Beyond googling for Windows permissions issues, I don't think there's a ton we can offer in the way of help.

**Comment by jeremykenedy** [comment]
I have never pulled a package that placed a folder with permissions that are not accessible. It created the directory with an unknown admin user. 

Not via Powershell, Gitbash, and the GUI I cannot remove the file. Even with the -R and -f flags on rm.

I also cannot take ownership nor change permissions of the folder.

This is the only package this has ever happened on so I find it hard to believe that it is a npm error or Windows file perms error.

**Comment by loganfsmyth** [comment]
This repo's scripts, https://github.com/zloirock/core-js/blob/master/package.json#L35, do not include anything that runs at installation time. Literally nothing in this module runs unless a user explicitly loads and runs to the polyfill in Node.

**Comment by jeremykenedy** [comment]
Hmmm, restarting the server seemed to fix the issue. Stupid windows file system lost the user logged in. Thank you for the fast reply :)

**Comment by loganfsmyth** [comment]
No problem, glad you got it fixed.
