### ISSUE TITLE
Map.set does not return instance in IE11 

### ISSUE THREAD

**Issue by jordrake** [zloirock/core-js#315]
Thanks for the great library and hopefully you can help with this issue.

There is known issue with Map.set not returning the Map instance in IE11 (see Compatibility notes of https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/set).

When I import the polyfill version (`core-js/fn/map`) on v2.4.1 it seems to detect that the native implementation of Map in IE11 is suitable and thus doesn't override or fix the `.set` issue. For the time being we are forcing it with:

```js
import Map from 'core-js/library/fn/map';

global.Map = Map;
```

Apologies in advance if this is just a fault of how we are consuming it.

**Comment by zloirock** [comment]
`Map#set` chaining covered by tests and it's tested in IE11. Could you add little more info about your case or add a full reproducible example?

**Comment by jordrake** [comment]
Ah OK, I'll take a further look. Apparently the fix I posted doesn't work either so it sounds like something endemic in our codebase, thanks for the insight however.
