### ISSUE TITLE
Shim element.closest()

### ISSUE THREAD

**Issue by binarykitchen** [zloirock/core-js#317]
Looks like it's not supported on core-js yet? No hits. This one:
http://caniuse.com/#feat=element-closest

That package could be helpful
https://github.com/jonathantneal/closest

**Comment by zloirock** [comment]
Thanks for the proposal, but at this moment DOM polyfills are not in the `core-js` scope.

**Comment by binarykitchen** [comment]
why not?

**Comment by AlexWayfer** [comment]
["Iterable DOM collections" are in the `core-js` scrope](https://github.com/zloirock/core-js#iterable-dom-collections), but "DOM elements" are not :expressionless:

**Comment by zloirock** [comment]
@AlexWayfer iterable DOM collections related ECMAScript iterable protocol and required for correct work of many `core-js` and `babel` features like `for-of` loops, spread, collection constructors, etc.

**Comment by zloirock** [comment]
Theoretically, DOM polyfills could be added to `core-js` in the future, but definitely not soon. I haven't enough time even for that and have much more priority tasks.

**Comment by AlexWayfer** [comment]
They can be added to a separate namespace, doesn't required by general namespace requiring. But it's your choise, just an idea.
