### ISSUE TITLE
unhandledrejectionhandler called multiple times for same error

### ISSUE THREAD

**Issue by cdietze** [zloirock/core-js#318]
When chaining promises using `then` the behavior between Chrome's native `onunhandledrejectionhandler` and core-js' implementation differ.

`Promise.reject(43).then(x => x);` will invoke the handler twice in core-js and once in Chrome.
I suppose Chrome's behavior is correct.

[demo](http://es6.zloirock.ru/#window.onunhandledrejection%20%3D%20e%20%3D%3E%20log('unhandled'%2C%20e.reason%2C%20e.promise)%3B%0A%0APromise.reject(42)%3B%0A%0APromise.reject(43).then(x%20%3D%3E%20x)%3B)

**Comment by zloirock** [comment]
In this example, we have 2 promises, so 2 errors. Need to check HTML spec for confirming which behaviour is correct.

**Comment by benjamingr** [comment]
@zloirock the ES spec is ambiguous about this

**Comment by zloirock** [comment]
Fixed in `core-js@2.5.3`.
