### ISSUE TITLE
"Object expected" in IE 8

### ISSUE THREAD

**Issue by athaeryn** [zloirock/core-js#32]
I'm using [6to5's polyfill](https://github.com/6to5/6to5/blob/master/lib/6to5/polyfill.js)—which includes `"core-js/shim"`—and in IE 8 I'm getting the error "Object expected" referencing [this line of code](https://github.com/zloirock/core-js/blob/master/shim.js#L576):

```js
...
  if(!isNative(Symbol)){
    Symbol = function(description){
      assert(!(this instanceof Symbol), SYMBOL + ' is not a ' + CONSTRUCTOR);
      var tag = uid(description)
        , sym = set(create(Symbol[PROTOTYPE]), TAG, tag);
//      ^----- error here
      AllSymbols[tag] = sym;
      DESC && setter && defineProperty(ObjectProto, tag, {
...
```

I'm packaging things with browserify, and even if the bundle only contains `require("6to5/polyfill")`, I get this error.

**Comment by zloirock** [comment]
`core-js/shim` not support IE8-. Use `core-js/client/shim`.

**Comment by athaeryn** [comment]
Thanks for the quick reply!
