### ISSUE TITLE
How can I tell whether I need this?

### ISSUE THREAD

**Issue by Karolusrex** [zloirock/core-js#320]
I'm having a project with Chrome 55 (Cordova crosswalk chromium webview).

Do I need this library. How can I efficiently determine the delta for what's potentially not covered, other than checking manually through each function? Browser compatibility tables is a lot of manual work.

Maybe someone has a smarter idea.

Thanks,

Karl

**Comment by hzoo** [comment]
https://github.com/babel/babel-preset-env#usebuiltins

uses the compat-table to remove polyfills you don't need

**Comment by zloirock** [comment]
As @hzoo wrote, for determination required modules in your environment, you can use [`babel-preset-env`](https://github.com/babel/babel-preset-env#usebuiltins). But at this moment it will work only with stable ES. Chrome 55 supports almost all stable ES, so you need `core-js` mainly for ES proposals. You can check which features you need in [`compat-table`](http://kangax.github.io/compat-table/esnext/) manually.
