### ISSUE TITLE
''.startsWith('') should return true

### ISSUE THREAD

**Issue by sledorze** [zloirock/core-js#321]
''.startsWith('') returns false (core-js 2.4.1) whereas on chrome it returns true.

Based on this documentation:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith

```
if (!String.prototype.startsWith) {
    String.prototype.startsWith = function(searchString, position){
      return this.substr(position || 0, searchString.length) === searchString;
  };
}
```

it should returns true

**Comment by zloirock** [comment]
I checked it, it returns `true`. Could you add a reproducible example and more info about the environment?

**Comment by zloirock** [comment]
Closed as `can't reproduce`.
