### ISSUE TITLE
Bundled es6.js for client

### ISSUE THREAD

**Issue by abhijeetkpawar** [zloirock/core-js#322]
It will be good to have bundled `es6.js` and probably `es7.js`, so as to include only that part for client usage

**Comment by zloirock** [comment]
Here 2 problems:
- It's additional size in the package. Someone still uses `npm@2`, `core-js` is a too frequent dependency and sometimes we have dozens of `core-js` copies in `node_modules`. I have too many issues about `core-js` package size. It could be solved by creating separate packages with bundles, but...
- the second problem is `core-js` architecture. It's many small separate packages, they use shared helpers and stores. Usage both - `es6` and `es7` - separate bundles can cause problems with interaction those modules and will add additional size.

Most likely, in [`core-js@3`](https://github.com/zloirock/core-js/pull/325) we will have only 1 default bundle - with a global shim. If you wanna something specific - you can bundle it yourself.
