### ISSUE TITLE
Erroneous naming of release? 2016 instead of 2017?

### ISSUE THREAD

**Issue by gruppjo** [zloirock/core-js#324]
Hi :)

Is the recent release from yesterday (August 5th) not named properly maybe? Shouldn't it be 2017.08.05? Or has JavaScript finally gotten timetravel capabilities? :)

![image](https://user-images.githubusercontent.com/1370779/29019810-200799de-7b60-11e7-8105-5128a71a4841.png)

**Comment by zloirock** [comment]
Oops, thanks -)
