### ISSUE TITLE
toISOString is not a function in  $JSON.stringify.apply

### ISSUE THREAD

**Issue by phoet** [zloirock/core-js#326]
hi,

i'm seeing `toISOString is not a function` errors in track.js for a browser with the user agent:

```
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
```

track.js classifies this as Chrome 60.0.3112, Windows 7

the error is raised when serializing a nested state structure `JSON.parse(JSON.stringify(state));`

and track.js points the source to

```
return $JSON.stringify.apply($JSON, arguments);
// ./node_modules/core-js/library/fn/json/stringify.js
```

as far as i understand, there are a couple of polyfills that should take care of proper serialization of JSON. i'm just trying to grab a log for how exactly the structure is when this error happens.

any ideas what could have happened here?

**Comment by zloirock** [comment]
Could you add a reproducible example and / or provide data, passes to `JSON.stringify`? Looks like you pass a date object without `.toISOString` to `JSON.stringify`...

**Comment by phoet** [comment]
i released a new version that adds some logging around this error, so that i can provide a bit more details on the actual data-structure. the thing is that this does not happen with all browsers, so i assume that there must be some special condition that i will most likely not find out with just a dump of the data-structure.

what could be the reason there is no `.toISOString` on a date object? shouldn't the polyfill for date handle this?

**Comment by zloirock** [comment]
I have no ideas. In all modern browsers, it should be available by default and it's polyfilled.

**Comment by phoet** [comment]
this error happens when the app tries to stringify a deep object structure that holds accidentally holds dom-event objects. i assume there is some circular structure (seen logs from safari indicating this) which is not handled well.
