### ISSUE TITLE
feature detect by default? 

### ISSUE THREAD

**Issue by jeremychone** [zloirock/core-js#327]
Sorry for the silly question if it is, but I have been doing quite a bit of searching but I cannot determine if core-js does feature detect (at runtime) by default, or with shim-only, or at all. 

I wanted to do some manual test, but I found something about core-js toString return [native], so, it might be a little bit more involve of what I thought.

**Comment by zloirock** [comment]
Sure, `core-js` uses feature detect at runtime and add only missed / incorrect features.

**Comment by jeremychone** [comment]
@zloirock Perfect, thanks for the quick answer.
