### ISSUE TITLE
Implement `NodeList.prototype.forEach()`

### ISSUE THREAD

**Issue by yuheiy** [zloirock/core-js#329]
should you implement this?

https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach

**Comment by christiansany** [comment]
I'd volunteer for the implementation of this polyfill :)

**Comment by Jarlotee** [comment]
@christiansany DO IT!

**Comment by zloirock** [comment]
Added to [v3](https://github.com/zloirock/core-js/pull/325) branch.

**Comment by AlexWayfer** [comment]
> Hey whats the current status of this? 

It's checked in v3 PR.

https://github.com/zloirock/core-js/pull/325/commits/c908a467672fea885e2528d7c30ced64da5d928e

**Comment by firestar300** [comment]
It doesn't work.

I use Webpack.

```javascript
  entry: {
    app: ['@babel/polyfill', './src/css/style.scss', './src/js/app.js'],
  },
```

input :
```javascript
document.querySelectorAll('.test').forEach(el => {
  console.log(el)
})
```

output :
```javascript
document.querySelectorAll('.test').forEach(function (el) {
  console.log(el);
});
```

So I have this expected error on IE11 : `Object doesn't support property or method 'forEach'`

**Comment by AlexWayfer** [comment]
> Did I miss something ?

[`@babel/polyfill` locked at `core-js 2`](https://github.com/babel/babel/blob/adca165/packages/babel-polyfill/package.json#L11), and [there is no `core-js 3` stable release](https://github.com/zloirock/core-js/releases).

So…

@zloirock, what about v3 release? PR was merged, three betas were released, and no new beta since early June.

**Comment by firestar300** [comment]
> @babel/polyfill locked at core-js 2, and there is no core-js 3 stable release.

Oh yes.. I didn't notice that. Thanks for the answer.

**Comment by SebiTimeWaster** [comment]
no new releases since june?

**Comment by theianjohnson** [comment]
Running into this same issue and would love to see a forEach polyfill get merged in 👍
