### ISSUE TITLE
Reflect.construct doesn't handle constructor objects (ES5)

### ISSUE THREAD

**Issue by rweichler** [zloirock/core-js#330]
Browser: Safari 9.1.2

For example, when I call `Reflect.construct(WebSocket, 'ws://some/websocket')` it says `TypeError: [object WebSocketConstructor] is not a function!`.

**Comment by zloirock** [comment]
In Safari 9:
```js
typeof WebSocket // => 'object'
Object.prototype.toString.call(WebSocket) // => '[object Object]'
```
so `WebSocket` can't be classified as a function without handling it as a special case. It's a very rare example for handle it as a special case. Also, in your example, the second argument should be an array.
