### ISSUE TITLE
"module" field in package.json

### ISSUE THREAD

**Issue by p2227** [zloirock/core-js#331]
I propose that adding a field "module" to support webpack2/3 Tree Shaking
here is the discuss in moment https://github.com/moment/moment/pull/3904

![core-js-module](https://user-images.githubusercontent.com/4214942/29507365-51f31f26-8615-11e7-80d6-b3cf3d4e4074.png)

**Comment by zloirock** [comment]
I think that tree shaking makes no sense with `core-js` architecture.
