### ISSUE TITLE
missing reference to Array.from

### ISSUE THREAD

**Issue by infn8** [zloirock/core-js#334]
I _think_...
i have the following loaded:
```
'core-js/fn/array/some',
'core-js/fn/array/for-each',
'core-js/fn/array/find',
'core-js/fn/array/find-index',
'core-js/fn/object/keys',
'core-js/fn/array/every',
```
and IE11 is giving an error on:
```object doesn't support property or method 'from'```
on a call of Array.from 
I'm not sure which module is missing that polyfill (or if I'm missing something else).

I am using webpack and babel maybe it's an error there.

my code makes no mention of `.from` anywhere.  is one of the modules above accidentally relying on something not polyfilled?

**Comment by zloirock** [comment]
Seems it's used by Babel, see [caveats](http://babeljs.io/docs/usage/caveats/), or your dependencies. You could add `core-js/fn/array/from`.
