### ISSUE TITLE
Magento 1.9 conflict with prototype

### ISSUE THREAD

**Issue by KarolMilewski** [zloirock/core-js#337]
Conflict with magento1.9 prototype when I import promise in my script.js.
Cant match size/color product.

Magento 1.9 have prototype.js, jquery.js and they use noConflict.js with var $j = jQuery.noConflict();

`import 'core-js/fn/promise';`

Chrome DevTools prompt:
> Uncaught TypeError: Cannot read property 'apply' of undefined
    at prototype.js:936
    at prototype.js:865
    at prototype.js:825
    at Array.forEach (<anonymous>)
    at Array.each (prototype.js:824)
    at Array.collect (prototype.js:864)
    at Array.invoke (prototype.js:935)
    at klass.<anonymous> (swatches-product.js:675)
    at prototype.js:391
    at prototype.js:825

EDIT:
We can close this topic. Upgrade core-js resolved this problem.

**Comment by zloirock** [comment]
Could you add a simple reproducible example?
