### ISSUE TITLE
edge cannot find core-js/library/modules/es6.object.to-string.js?

### ISSUE THREAD

**Issue by hei-yu-fa** [zloirock/core-js#342]
I have met this problem and I don't konw why ...

**Comment by loganfsmyth** [comment]
Cannot find it how? Can other browsers? There isn't nearly enough information in this to address the issue.

**Comment by loganfsmyth** [comment]
How are you loading the files? Are you using Webpack, or the pre-bundled files? Can you post a screenshot of exactly what you are seeing?

**Comment by hei-yu-fa** [comment]
(![image](https://user-images.githubusercontent.com/14875519/31324901-f98e101e-ac7c-11e7-827b-22c1ce8c9191.png))
![image](https://user-images.githubusercontent.com/14875519/31324923-3ba94202-ac7d-11e7-861d-a346476b37fb.png)
![image](https://user-images.githubusercontent.com/14875519/31324927-4411b154-ac7d-11e7-8083-29ed08025c91.png)
just these ...

**Comment by loganfsmyth** [comment]
Is `dts.e3webrtc.com` your own website? I'm not sure there's any way to help. That file certainly exists on https://github.com/zloirock/core-js/blob/master/library/modules/es6.object.to-string.js, so it'd be up to you do debug why your server is 404ing in this case.

**Comment by hei-yu-fa** [comment]
Thank you anyway,what makes me confuse is that other browers except edge can get the .js file

**Comment by zloirock** [comment]
It's a cap for the `library` version, so it's just an empty file. As you can see, it exists. I don't know how you loading it, so I can't help.

**Comment by skeggse** [comment]
Just for reference, this is a problem for some bundlers, [such as rollup](https://github.com/rollup/rollup-plugin-commonjs/issues/194).

Certainly bundlers should be able to handle empty files; I don't suppose there's a way to avoid empty files in core-js?
