### ISSUE TITLE
How to rewrite core-js/library/modules to core-js/modules ?

### ISSUE THREAD

**Issue by Airkro** [zloirock/core-js#344]
I find the following modules in my bundle, too many duplicate files

```
core-js/library/modules/*.*          // from babel-polyfill
core-js/modules/*.*                     // from third party modules
```

webpack resolve.alias seems not working.

Thanks.

**Comment by loganfsmyth** [comment]
Those files do two different things, so aliasing one to be the other would almost certainly break stuff.

**Comment by realityking** [comment]
@zloirock Could you reopen this issue?

I just hit the same issue. I'm using `babel-plugin-transform-runtime` to load the babel helpers. 

The transform creates references deep into core-js, e.g. `require("core-js/library/fn/object/create")`.

The application also selectively includes some polyfills like this:
```
require('core-js/fn/object/assign');
require('core-js/fn/array/find');
require('core-js/es6/promise');
require('core-js/es6/map');
require('core-js/es6/set');
```

The end result is that a lot of code is loaded twice, once from `core-js/library/modules` and once from `core-js/modules`.

A quick check using `diff -srq library/modules/ modules/ | grep differ | wc -l` and `diff -srq library/modules/ modules/ | grep identical | wc -l` shows that there are 318 identical files into these folders while only 22 differ.

The following files differ:
```
Files library/modules/_add-to-unscopables.js and modules/_add-to-unscopables.js differ
Files library/modules/_collection.js and modules/_collection.js differ
Files library/modules/_export.js and modules/_export.js differ
Files library/modules/_library.js and modules/_library.js differ
Files library/modules/_path.js and modules/_path.js differ
Files library/modules/_redefine-all.js and modules/_redefine-all.js differ
Files library/modules/_redefine.js and modules/_redefine.js differ
Files library/modules/_set-species.js and modules/_set-species.js differ
Files library/modules/es6.date.to-json.js and modules/es6.date.to-json.js differ
Files library/modules/es6.date.to-primitive.js and modules/es6.date.to-primitive.js differ
Files library/modules/es6.date.to-string.js and modules/es6.date.to-string.js differ
Files library/modules/es6.function.name.js and modules/es6.function.name.js differ
Files library/modules/es6.number.constructor.js and modules/es6.number.constructor.js differ
Files library/modules/es6.object.to-string.js and modules/es6.object.to-string.js differ
Files library/modules/es6.regexp.constructor.js and modules/es6.regexp.constructor.js differ
Files library/modules/es6.regexp.flags.js and modules/es6.regexp.flags.js differ
Files library/modules/es6.regexp.match.js and modules/es6.regexp.match.js differ
Files library/modules/es6.regexp.replace.js and modules/es6.regexp.replace.js differ
Files library/modules/es6.regexp.search.js and modules/es6.regexp.search.js differ
Files library/modules/es6.regexp.split.js and modules/es6.regexp.split.js differ
Files library/modules/es6.regexp.to-string.js and modules/es6.regexp.to-string.js differ
Files library/modules/web.dom.iterable.js and modules/web.dom.iterable.js differ
```

Which appears to be exactly the set of files that are in `modules/library`.

Now at this point I'm lost as I don't understand the specific of which directory of files is responsible for what. It'd would be huge boon for my app (and I suspect many others using `babel-runtime`) if those 318 identical files would disappear and there was a common set of files used for both use cases.

I'd be happy to invest some time into making that happen but I'm not sure where to start.

**Comment by zloirock** [comment]
@realityking the problem here - almost all of those files should have the different internal state. Sure, we can wrap it to top-level functions, but it will seriously increase the size each version of `core-js`.

As a solution, you can add a webpack alias `core-js/library` -> `core-js` and all of the included polyfills will be global.

You can try to resolve this problem and if it will be resolved by a small price, I'll accept a PR. I would recommend using for that [`v3` branch](https://github.com/zloirock/core-js/tree/v3), see [`CONTRIBUTING.md`](https://github.com/zloirock/core-js/blob/v3/CONTRIBUTING.md).
