### ISSUE TITLE
Symbol JSON.stringify returns immediately without calling replacer fn when target is undefined

### ISSUE THREAD

**Issue by christophercr** [zloirock/core-js#345]
Hi, first of all thanks for this nice library, it is really handy for those struggling with cross-browser compatible apps or better said IE-proof apps :p

 I recently stumbled upon an issue though. It took me a bit of time to troubleshoot but here it is:

I have an app in angularjs and it uses the latest `angular-ui-router`. Then, in this router library there is [this line of code](https://github.com/ui-router/core/blob/c5859b8327496d49c3b42bec75a2ee3e4b6823fa/src/common/strings.ts#L110) that tries to get an stringified object passing a replacer function to ultimately log something to the console.

The problem pops up in IE11, when the [core-js Symbol polyfill](https://github.com/zloirock/core-js#ecmascript-6-symbol) is used; which means that also the `JSON.stringify()` method is wrapped to work correctly with Symbols.

At some point, the routing library will call the JSON.stringify method passing `undefined` and a replacer function, and then, [the wrapped JSON.stringify() function simply returns](https://github.com/zloirock/core-js/blob/e44fc0575d566508488d3900baee86aac941e4fd/modules/es6.symbol.js#L211) without doing anything nor even calling the replacer function.

This behaviour seems totally different in the native implementation of compliant browsers like Chrome and Firefox where the replacer function is called even if the target is undefined.

Do you think this could be refactored so that the replacer function is called?

**Comment by christophercr** [comment]
Hi @zloirock, do you think you can have a look on this issue? Is there any reason why the Symbol polyfill was implemented in that way so that the replacer function is not called?

**Comment by zloirock** [comment]
Thanks for the report, sorry for the delay.

**Comment by zloirock** [comment]
Fixed in `core-js@2.5.2`.

**Comment by zloirock** [comment]
@romeovs could you provide your input data? Something like that is possible with incorrect `replacer` argument.

**Comment by romgar** [comment]
@zloirock Thanks for your responsiveness!
I definitely had a weird input for the replacer (`JSON.stringify(data, 2, 2)`), caught in some legacy code.
Do you have any idea why did it previously work? Giving a proper value for the replacer fixed the issue.

**Comment by zloirock** [comment]
@romgar fixed in `core-js@2.5.3`.

**Comment by romgar** [comment]
I confirm that it fixed it!
Thanks for the release and your work @zloirock !
