### ISSUE TITLE
Patch Object.assign for IE11 to work with assigning properties to functions

### ISSUE THREAD

**Issue by benstevens48** [zloirock/core-js#346]
Apologies if this is incorrect, but I think in IE11 if you try and do
```js
function myFunction(){
console.log('hello');
}
Object.assign(myFunction, {test:'hi'});
```
you get an error saying assign is not supported or something. It would be good if including core-js automatically fixed this.

**Comment by zloirock** [comment]
It should work. Are you sure that `core-js` is loaded?

**Comment by benstevens48** [comment]
Sorry, yes it does work, the code was in a Web Worker and I forgot I would need to import the polyfill in the Worker. Sorry about that.
