### ISSUE TITLE
scan for required modules

### ISSUE THREAD

**Issue by roeycohen** [zloirock/core-js#348]
is there a tool of some kind to let me know which modules are needed?

for example, let's say that i'm using Array.find but not Array.findIndex - the tool will let me know the i'm using Array.find that might be missing in IE9 and therefore i should includes it's module.

10x!

**Comment by zloirock** [comment]
You can try `@babel/preset-env` with [`useBuiltIns`](https://github.com/babel/babel/tree/master/experimental/babel-preset-env#usebuiltins) option.
