### ISSUE TITLE
Does core-js have an ECCN?

### ISSUE THREAD

**Issue by otramony** [zloirock/core-js#349]
Hello. Our team would like to use/include your library in our product, and since we export outside of the U.S., we're required to provide ECCN (Export Control Classification Number) information for all 3rd-party libraries that may use/include encryption. Thanks.

**Comment by ljharb** [comment]
This is a JS library that runs in the browser; what encryption do you think it even *might* use?

**Comment by otramony** [comment]
Thank you for your response. I'm sure the person reviewing the code saw "SHA1" and figured I should ask. I know it's being used for hashing, but I still needed to ask for compliance reasons. Thanks again.

**Comment by ljharb** [comment]
Not sure where they'd have seen that: https://github.com/zloirock/core-js/search?utf8=✓&q=sha-1&type=

**Comment by otramony** [comment]
Starting in line 5247 in https://github.com/zloirock/core-js/blob/master/tests/promises-aplus/bundle.js. However, don't worry about it. Test code should not have been part of the review. Sorry.
