### ISSUE TITLE
React with Core-js on IE8

### ISSUE THREAD

**Issue by torarnek** [zloirock/core-js#35]
Can anyone please confirm that they have React working with Core-js (e.g. core-js/client/shim) on IE8?

In our case it fails with "undefined is null or not an object" on the first if-statement in:

```
function createChainableTypeChecker(validate) {
  function checkType(isRequired, props, propName, componentName, location) {
    componentName = componentName || ANONYMOUS;
    if (props[propName] == null) {
      var locationName = ReactPropTypeLocationNames[location];
      if (isRequired) {
        return new Error(
          ("Required " + locationName + " `" + propName + "` was not specified in ")+
          ("`" + componentName + "`.")
        );
      }
    } else {
      return validate(props, propName, componentName, location);
    }
  }
```

**Comment by zloirock** [comment]
[Should work](http://facebook.github.io/react/docs/working-with-the-browser.html#browser-support-and-polyfills). If someone will help detect the problem - I will be happy.

**Comment by zloirock** [comment]
Looks like the problem in [broken IE8 `Object.defineProperty`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#Internet_Explorer_8_specific_notes), core-js replaces it to simple set property. I will try to fix it later.

**Comment by zloirock** [comment]
Should be fixed in 0.6.1.

**Comment by zloirock** [comment]
Possible the same problem with `Object.getOwnPropertyDesciptor`, fixed it w/o release, avaliable in `client` path on github.

**Comment by torarnek** [comment]
I can confirm that this release fixed our issues with react on IE8.  I have also tested and found it working on IE9. Thank you!
