### ISSUE TITLE
promise.finally type definitions

### ISSUE THREAD

**Issue by jgerstle** [zloirock/core-js#355]
I am trying to use promise.finally in typescript this doesn't really seem possible with core-js. I imported the polyfill, but it doesn't fix the compile issues that I have. Can core-js's promise finally functionality be used with typescript. I also tried adding the type definitions for core-js, but that didn't work either. 

I'm not really sure if this should be posted here or in the type definitions repo.

**Comment by zloirock** [comment]
This repo does not contain type definitions, you could add a PR to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/core-js) repo.

**Comment by jgerstle** [comment]
OK thanks I posted there: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/21398
