### ISSUE TITLE
Array.prototype === core.Array.prototype /* => return false */ ?

### ISSUE THREAD

**Issue by npelletm** [zloirock/core-js#358]
global scope Array prototype does not equals to core.Array.prototype.
Other collections such as Map, Set, typed arrays does not have this behavior.

I used a core-js custom build 2.5.1 without Promise and core.delay function with global namespace pollution

Reproduced on IE11 and Chrome 62  Windows 7.

**Comment by npelletm** [comment]
Sorry but my test is not relevant. I must investigate to determine the js lib that change the Array prototype...

**Comment by npelletm** [comment]
With additional "unit test" with only requirejs + core-js custom build i reproduce the issue

`Array.prototype === core.Array.prototype /* => return false */ `

**Comment by nertzy** [comment]
That’s how polyfills work. They are only copied into place if the browser doesn’t already have an implementation. The browser you’re using has an Array.prototype already, and it doesn’t make sense to remove the optimized native implementations of various functions (such as forEach) just to make the prototype equal to this library’s prototype.

In other words, core-js doesn’t blow away the existing Array.prototype. It merely extends it with anything that is missing. Thus they aren’t the same objects.

**Comment by npelletm** [comment]
Yes but other native types such as Map, Set, typed arrays prototypes have not this behavior. Actually only Array prototype differs between native and core js.

**Comment by zloirock** [comment]
It's expected behaviour. `core.Array` is not a constructor, moreover, it could cause a global pollution for the `library` version.

**Comment by npelletm** [comment]
Ok thanks for the explanation.
