### ISSUE TITLE
Githack links in README and Github seem to be serving different files

### ISSUE THREAD

**Issue by scottwey** [zloirock/core-js#359]
The README links to https://raw.githack.com/zloirock/core-js/v2.5.1/client/core.min.js in Usage/Basic. The file that loads from this URL varies in size and is up to 10kb larger than https://raw.github.com/zloirock/core-js/v2.5.1/client/core.min.js. The content also appears to be different. Just thought I'd bring this to your attention. Thanks!

**Comment by zloirock** [comment]
They contain the same script.
![image](https://user-images.githubusercontent.com/2213682/33338983-555cb4cc-d4aa-11e7-9dd5-5669940c7a00.png)
Seems, the difference in size (I see ~2kb difference) mainly is the difference in headers.

Anyway, I removed all bundled files from the repo, they available in the package, so githack link will not be available in the next major release.
