### ISSUE TITLE
How to bundle npm module

### ISSUE THREAD

**Issue by lifeiscontent** [zloirock/core-js#360]
Hi, I'm writing a package in ES6 using Babel, what would be the best way to package up a module that will be used in a browser that requires dom iterables as functionality in the browser?

**Comment by zloirock** [comment]
If you write a library, it should not pollute the global namespace, so `library` version is the best option. The best way to do it automatically - use `babel-runtime` which automatically injects required part of `core-js` without global namespace pollution.
