### ISSUE TITLE
Conflict - Library is rewriting 'core' variable in window

### ISSUE THREAD

**Issue by JulienBonnin-ABTasty** [zloirock/core-js#362]
Hello,

I have a javascript tag placed on many of my customers website. I was using a single polyfill from your library: core-js/fn/math/trunc.

By doing so, my webpack bundle output had this line : global.core = core;

I had to remove the library and use Math.round instead of Math.trunc so my code continue to work on IE.

The problem is my customers sometimes have their own 'window.core' variable, and core-js is overwriting it for some reasons, breaking the customer's website entirely.

(I was using ^2.5.1)

Bug congrats on the lib anyway and good luck with it. 👍

**Comment by nertzy** [comment]
What happens if you load the poly fill before loading your customer’s code?

Also, have you tried adding `delete window.core;`in a script tag in between?

Just some ideas for a workaround.

**Comment by zloirock** [comment]
As @nertzy wrote, you should load global polyfills before any other code, so you can delete or override `window.core` without any problems. Most likely, I'll remove `window.core` for global polyfills in the next major release.
