### ISSUE TITLE
$replacer.call is not a function

### ISSUE THREAD

**Issue by jschuler** [zloirock/core-js#366]
Just started seeing this issue appear in our builds:

Running "jscs:gui" (jscs) task
Warning: $replacer.call is not a function Use --force to continue.

Maybe related to this PR? https://github.com/zloirock/core-js/commit/cd78e42ca5a39711c35919065c6be19a5037f2a8

Thanks!

**Comment by zloirock** [comment]
It should be fixed after mentioned PR in `core-js@2.5.3`.
