### ISSUE TITLE
Promise.prototype.finally having issues in ios 10.3 and firefox 57

### ISSUE THREAD

**Issue by ekeric13** [zloirock/core-js#369]
Importing Promise.prototype.finally via babel-polyfill (which imports promise.finally via core-js).

```
"babel-core": "^6.4.0",
"babel-polyfill": "^6.26.0",
"babel-preset-env": "^1.6.1",
"babel-preset-stage-0": "^6.16.0",
```

.babelrc:
```
    "dev": {
      "presets": [
        ["env", {
          "targets": {
            "browsers": [
              "ios >= 10",
              "safari >= 10",
              "chrome >= 60",
              "edge >= 15",
              "firefox >= 55"
            ],
            "uglify": true
          },
          "modules": false,
          "useBuiltIns": true
        }],
        "react",
        "stage-0"
      ],
      "plugins": [
        "transform-decorators-legacy"
      ]
    },
```

At the beginning of my app bundle I just do:
`import babel-polyfill`
But to my understanding this should import only the polyfills I need to support my browser targets since I have "useBuiltIns": true

Specific code that is failing
```
    return axios
      .post(url)
      .then(res => {
        //stuff
      })
	.catch((err)=>{
       // stuff
     })
      .finally(() => {
        //stuff
      });
```

error: `TypeError: undefined is not a function (near '...].done())})).finally(Object(o["action"])...')`

**Comment by zloirock** [comment]
Sorry, but I'm not sure that it's a `core-js` issue. `core-js/modules/es7.promise.finally` exports `Promise#finally` as it's required. Please, check the list of imported `core-js` modules.
