### ISSUE TITLE
Promise#finally polyfill doesn't add finally method to fetch() results

### ISSUE THREAD

**Issue by wa-Nadoo** [zloirock/core-js#371]
Affected browsers: at least FF 57 and Edge 16
Affected versions: core-js@^2.5.0

Reproducible example:
```js
import 'core-js/fn/promise/finally'
typeof fetch('https://gooogle.com').finally
> "undefined"
```

If include polyfill partially then following code works as expected:
```js
import 'modules/es7.promise.finally'
typeof fetch('https://gooogle.com').finally
> "function"
```

[Online demo](http://es6.zloirock.ru/#Promise.resolve(42).finally(()%20%3D%3E%20log('You%20will%20see%20it%20anyway'))%3B%0A%0APromise.reject(42).finally(()%20%3D%3E%20log('You%20will%20see%20it%20anyway'))%3B%0A%0Afetch('https%3A%2F%2Fgooogle.com').finally(()%20%3D%3E%20log('You%20will%20see%20it%20anyway'))%3B)

**Comment by zloirock** [comment]
It's a duplicate of issues like #332 or #178.

**Comment by wa-Nadoo** [comment]
Ok. I will close it.

**Comment by wa-Nadoo** [comment]
Ok. I will close it.
