### ISSUE TITLE
Do library/ polyfills check for native implementations first?

### ISSUE THREAD

**Issue by ZeeCoder** [zloirock/core-js#373]
Title says it all, but basically I'm interested if this:
```js
import Promise from 'core-js/library/fn/promise';
```

Would give me a native Promise implementation first, if available, and only then fall back to the polyfill or not?

**More Context**
As a lib author I'm planning on automating building a "no-polyfill" version of my lib with babel-plugin-transform-runtime, which internally uses core-js to auto-polyfill things for me, by replacing this:
```js
const p = new Promise();
```

with this:
```js
import _Promise from "babel-runtime/core-js/promise";
var p = new _Promise();
```

I could not for the life of me figure out whether that may or may not give me the native implementation, however. 😅

**Comment by zloirock** [comment]
> Would give me a native Promise implementation first, if available, and only then fall back to the polyfill or not?

Sure.

> `import _Promise from "babel-runtime/core-js/promise";`

But not completely for the version without global namespace pollution. In some cases, like collections, `core-js` use native implementation internally, but wrap it for preventing pollution global constructors or prototypes.

**Comment by ZeeCoder** [comment]
Awesome, thanks @zloirock 👏
