### ISSUE TITLE
Is v3 usable/installable?

### ISSUE THREAD

**Issue by JohnnyCrazy** [zloirock/core-js#376]
Hi :wave: 

We currently need the polyfill for `NodeList.forEach` which is already in the v3 branch, but tt seems like your v3 branch creates some kind of new structure with the packages being in a subdirectory `packages`. This way, it can't be installed via `yarn add <git repo>`. 

Should the v3 branch be used at all? If so, do you plan on publishing it to NPM under an alpha version?

Thanks!

**Comment by JohnnyCrazy** [comment]
I just saw #325 (Sorry, sadly didn't search PRs the first time) which shows quite a progress, so I guess my question is narrowed down to `is v3 currently somehow installable`?

**Comment by zloirock** [comment]
Hi. It's unstable and often has breaking changes. I hope to publish the first alpha version within a week or two.

**Comment by zloirock** [comment]
`core-js@3.0.0-alpha.1` is available for testing.
