### ISSUE TITLE
`Symbol.toStringTag` is failing in certain edge cases

### ISSUE THREAD

**Issue by MylesBorins** [zloirock/core-js#378]
I'm still digging into exactly what is going on here... but the following code works in es6 environments

```js
const TypedArrayPrototype = Object.getPrototypeOf(Uint8Array.prototype);
Object.getOwnPropertyDescriptor(TypedArrayPrototype, Symbol.toStringTag).get;
```

The same code fails when you attempt

```js
delete global.Symbol;
require( "core-js" );
const TypedArrayPrototype = Object.getPrototypeOf(Uint8Array.prototype);
Object.getOwnPropertyDescriptor(TypedArrayPrototype, Symbol.toStringTag).get;
```

This was discovered when smoke testing Node v6.13.0. Please let me know if any other information is helpful

**Comment by zloirock** [comment]
The problem not in `Symbol.toStringTag`. The most part of typed arrays polyfills polyfilled without support `%TypedArrayPrototype%`, it's not always possible. Anyway, at this moment I'm reworking typed arrays polyfills, so I'll try to fix this issue.

**Comment by zloirock** [comment]
Fixed in `v3` branch.
