### ISSUE TITLE
Breaks Number matching in Meteor

### ISSUE THREAD

**Issue by settinghead** [zloirock/core-js#38]
See discussions here: https://github.com/grigio/meteor-babel/issues/5

**Comment by zloirock** [comment]
Looks like `match` required before `core-js` and compare pattern with original `Number` constructor. I can't fix it.

Possiblle ways to fix:

1. Require `core-js` before `match`.
2. Use in `match` compare pattern with actual `global.Number`.
3. [Build](https://github.com/zloirock/core-js#custom-build) `core-js` without `es6.number.constructor`. TODO for me: add blacklist option for simplify.

**Comment by settinghead** [comment]
@zloirock thanks. I'll look into custom-building core-js.
