### ISSUE TITLE
Object.assign not working in IE11 when using es6.symbol

### ISSUE THREAD

**Issue by Satans-Kruemelmonster** [zloirock/core-js#383]
When I use the Symbol polyfill, Object.assign does not work any more.

My test setup:

webpack.config.js:

    path = require('path');
    
    module.exports = {
        entry: {
            app: 'core-js/es6/symbol.js'
        },
        output: {
            filename: '[name].js',
            path: path.resolve(__dirname, 'public/')
        },
        resolve: {
            modules: [
                path.resolve('./'),
                path.resolve('./node_modules')
            ]
        }
    };

public/index.html

    <!doctype html>
    <html>
    <head>
        <title>ES6-Symbol polyfill</title>
        <meta charset="UTF-8" />
        <script type="text/javascript" src="app.js"></script>
        <script>
            console.log(Object.assign({}, {}));
        </script>
    </head>
    <body></body>
    </html>

So I just include the symbol polyfill via my bundled app.js file and then try to do an `Object.assign`. The code should just log `{}` to the console, which it does in Firefox and Chrome, but in IE11 I get an error:

    SCRIPT438: Object doesn't support property or method "assign"

Since IE11 is a supported browser, I was wondering if there is something I can do to get Object.assign working again.

**Comment by zloirock** [comment]
Maybe because IE11 haven't native `Object.assign` and you don't load `Object.assign` polyfill (for example, `core-js/fn/object/assign`)? -)

**Comment by Satans-Kruemelmonster** [comment]
Yes. That was the problem. Thank you!
