### ISSUE TITLE
Intersection Observer Support? (Enhancement)

### ISSUE THREAD

**Issue by Giovanni-Mattucci** [zloirock/core-js#386]
Core-js has support for Observer, what about [Intersection Observer](https://github.com/w3c/IntersectionObserver/blob/master/explainer.md)?

W3C [provides a polyfill here](https://github.com/w3c/IntersectionObserver/tree/master/polyfill).

Info on [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API).

**Comment by zloirock** [comment]
`core-js` has support for `Observable` and it's ECMAScript proposal. `IntersectionObserver` is browser-only feature. At this moment, only ECMAScript and closely related ECMAScript features in the scope of `core-js`. In the future, this position can be changed, but not soon.
