### ISSUE TITLE
Object.assign strange behavior under jvm nashorn engine

### ISSUE THREAD

**Issue by denghongcai** [zloirock/core-js#389]
reproduce step:
0. install jdk8
1. run `jjs` command, enter interactive shell
2. run `load('./core.js')`, browser version core-js bundle
3. run `JSON.stringify(Object.assign({}, {1:2}, {x:1}))`

output: {"x":1}

![image](https://user-images.githubusercontent.com/1433247/38225813-4613339c-3729-11e8-800e-fe37fe99cd10.png)

and if integer key is long enough, it works

![image](https://user-images.githubusercontent.com/1433247/38225833-591fcac2-3729-11e8-8041-2387ccae1058.png)

**Comment by zloirock** [comment]
Seems the answer here:
![image](https://user-images.githubusercontent.com/2213682/38282026-f7ff7788-37d7-11e8-8445-787dfd786ac7.png)

**Comment by zloirock** [comment]
Fixed in [`v3` branch](https://github.com/zloirock/core-js/pull/325), thanks for the interesting issue -)
