### ISSUE TITLE
Bind issue in IE8

### ISSUE THREAD

**Issue by scttnlsn** [zloirock/core-js#39]
Described here: https://github.com/facebook/react/pull/3273

**Comment by scttnlsn** [comment]
Is it possible to just use `es5-shim` with `core-js`?  What's different about the ES5 module in `core-js`?

**Comment by zloirock** [comment]
It's possible, but possible some problems. Hmm... You are using the latest version from `client` path? I can't find problem, `RegExp.prototype.test.bind(/a/)('a') // => true`.

**Comment by scttnlsn** [comment]
Yeah, I'm using `core-js/client/shim` from 0.6.1 and `RegExp.prototype.test.bind(/a/)('a')` is throwing the error in IE8.  `es5-shim` seems to handle it fine.

**Comment by zloirock** [comment]
@scttnlsn [I can't detect problem.](http://habrastorage.org/files/d2c/36d/33b/d2c36d33b1b240e9934bfb28d32f4a15.png) Show me a reproducible broken case.

**Comment by zloirock** [comment]
@scttnlsn ?

**Comment by scttnlsn** [comment]
Hmmm, I can't reproduce this in the core-js test suite.  I'll re-open if I figure out where the issue is.

**Comment by scttnlsn** [comment]
Okay, here's a screenshot of the issue: http://cl.ly/image/401z333r322j
This is in IE 11 running with IE 8 compatibility mode.

**Comment by scttnlsn** [comment]
When testing this directly in IE 8 (via browserstack.com) it seems to work fine.

**Comment by zloirock** [comment]
IE quirks mode bug. I will fix it in next version. You can manually add condition `if(fn[PROTOTYPE])bound[PROTOTYPE] = fn[PROTOTYPE];`

**Comment by scttnlsn** [comment]
Fantastic.  Thanks!
