### ISSUE TITLE
Map & Set Error in 2.5.4

### ISSUE THREAD

**Issue by HaykPolymorphic** [zloirock/core-js#390]
hi
Seems my issue is fixed in this ticket  https://github.com/zloirock/core-js/issues/368
but I am using 2.5.4 version in my react-native project. And I am facing this error for android.
![screenshot_20180329-180410](https://user-images.githubusercontent.com/33617909/38233157-9e18a580-372a-11e8-9132-533ba5c9439d.png)

Can you please advise?

**Comment by zloirock** [comment]
Closed as `can't reproduce`.

**Comment by kalyanijamunkar10** [comment]
![screenshot_2018-08-20-12-34-40-292_com contentstream](https://user-images.githubusercontent.com/27677593/44383302-f3fb9100-a535-11e8-8d56-a01725b60ffa.png)

I am facing same issue tried using 2.5.4, 2.4.0, @3 but still not working..
