### ISSUE TITLE
Array.from polyfill not working as expected in ie11

### ISSUE THREAD

**Issue by npup** [zloirock/core-js#395]
Specifically, what i encountered was that Array.from operation on a set is not what is generally returned.

Set is available natively in i11 (but with some flaws, https://kangax.github.io/compat-table/es6/#ie11):
```
require("core-js/fn/array/from");

const s = new Set;
s.add(1);
s.add(2);
s.add(3); // { 1, 2, 3 }

const a = Array.from(s);
console.log("a:", a); // [ 1, 2, 3 ]
```
For the above code, ie11 prints an empty array.

Is the Set polyfill needed to be forcefully in effect for the Array.from polyfill to work in this instance?

**Comment by zloirock** [comment]
In IE11, `Set` is available without iterators, so you should also polyfill `Set`.
