### ISSUE TITLE
Promise.allSettled polyfill?

### ISSUE THREAD

**Issue by xtuc** [zloirock/core-js#399]
The proposal is here: https://github.com/jasonwilliams/proposal-promise-allSettled (Stage 0)

And the polyfill can be found in the example: https://github.com/jasonwilliams/proposal-promise-allSettled#example

cc @jasonwilliams

**Comment by jasonwilliams** [comment]
ahh thank you @xtuc !

**Comment by zloirock** [comment]
Looks interesting, but I don't see any related info [here](https://github.com/tc39/proposals) and don't remember something related from TC39 meetings. Who is the champion? Is this an official proposal?

**Comment by jasonwilliams** [comment]
@zloirock currently seeking a champion, although a few delegates have said they would support this i don't have any name yet. Maybe we can hold this here until i have more news

**Comment by zloirock** [comment]
Ok, when you will find the champion, I'll add this polyfill.

**Comment by jasonwilliams** [comment]
hi @zloirock just to let you know, i have a champion now
https://github.com/jasonwilliams/proposal-promise-allSettled its not on the proposals page yet, but i'm dealing with that

**Comment by zloirock** [comment]
Added to [`v3` branch](https://github.com/zloirock/core-js/pull/325).
