### ISSUE TITLE
Error Access is denied when executing the code _meta.js in IE11

### ISSUE THREAD

**Issue by ykornilov** [zloirock/core-js#403]
Hello!
Can you help me, please?
var setMeta = function (it) {
  setDesc(it, META, { value: {
    i: 'O' + ++id, // object ID
    w: {}          // weak collections IDs
  } });
};
When this section of code in the file _meta.js is executed by the browser IE11, an error occurs Access denied.
Maybe there are suggestions why this can happen?

**Comment by zloirock** [comment]
Could you add a simple reproducible example?

**Comment by zloirock** [comment]
Most likely, you have this error when you try to add to (weak)?(map|set) or freeze a very specific object like a global object from another realm. It's a very specific case and we can't do anything here.
