### ISSUE TITLE
The detect method of iterator causes the problem of cross domain calls in safari 10.1.2

### ISSUE THREAD

**Issue by appleskiller** [zloirock/core-js#404]
https://github.com/zloirock/core-js/blob/492679b53e441862c6b4aa8ed0a1ee05ec3baacb/modules/_iter-detect.js#L6

This problem can occur in Iframe, when embeds other domain codes.
'Blocked a frame with origin "<domain-A>" from accessing a frame with origin "<domain-B>" Protocols, domains, and ports must match'

safari v10.1.2(12603.3.8)

oh, help me~

**Comment by zloirock** [comment]
Interesting. Could you add a reproducible example? I have no idea how this code could cause cross-domain issues.
