### ISSUE TITLE
Rename .flatten to .flat as per May TC39 meeting

### ISSUE THREAD

**Issue by Jamesernator** [zloirock/core-js#405]
In the May TC39 meeting the name of `.flatten` was changed for web compatibility to be `flat` (https://tc39.github.io/proposal-flatMap/). So this is just asking for `core-js` to rename the method (or make `.flatten` an alias for `.flat`).

**Comment by zloirock** [comment]
Sure, it will be renamed in the next `core-js@3` beta.

**Comment by zloirock** [comment]
Updated in [`core-js@3.0.0-beta.2`](https://github.com/zloirock/core-js/releases/tag/v3.0.0-beta.2).
