### ISSUE TITLE
How to require core.js and inject to phantom?

### ISSUE THREAD

**Issue by Gunner17** [zloirock/core-js#415]
I want to inject core.js to phantom, as mentioned in an online example. But it is nowhere mentioned how to require core.js to my Node module so that it can be injected like below :

```
if(page.injectJs('dore.js')){
	return page;
} else {
	console.log("Polyfill Failed");
}
```
Here 'page' is my phantom page. (https://www.npmjs.com/package/phantom).
Can anyone please help me with the require?

**Comment by zloirock** [comment]
I'm not familiar with this API for Phantom and it does not looks like an issue with `core-js`. Try to get the answer [here](https://github.com/amir20/phantomjs-node/issues/749).
