### ISSUE TITLE
IE 11 issue - "Access Denied" in getOwnPropertyNames in modules/_object-gopn-ext.js

### ISSUE THREAD

**Issue by doctorssm** [zloirock/core-js#417]
In IE11, getOwnPropetyNames throws an "Access Denied" error in modules/_object-gopn-ext.js

![2018-08-03_1636](https://user-images.githubusercontent.com/10260908/43645733-759e138a-973b-11e8-8d2a-adf5aa7319a7.png)

**Comment by djskinner** [comment]
I am also seeing this in IE 11. Will report back if I can glean any further info.

**Comment by zloirock** [comment]
Please, add a reproducible example. As you can see, this line in a `try` block for preventing this error.

**Comment by zloirock** [comment]
Closed as `can't reproduce`.

**Comment by djskinner** [comment]
FWIW for me this was related to the use of iframes on IE11. Specifically I had to get rid of any references to iframe windows before they were unloaded from the page.
