### ISSUE TITLE
Question: polyfills for babel for..of loop

### ISSUE THREAD

**Issue by senner007** [zloirock/core-js#419]
Hello.

Recently I became aware of the need to add polyfills because babel doesn't support ie 11, as the for..of loop transpiles to symbol and iterator code. I don't want to overcompensate by adding the entire library which adds 85 kb minified.

My question is:
What are the exact imports needed for this code?

**Comment by zloirock** [comment]
For `core-js@3`, you need, at least:
> `core-js/features/symbol/iterator` or `core-js/features/symbol` for `Symbol.iterator`
> `core-js/features/array/iterator` for iteration over arrays
> `core-js/features/string/iterator` for iteration over strings
> `core-js/features/dom-collections/iterator` for iteration over DOM collections
