### ISSUE TITLE
core-js/es6/promise from 2.5.7 causes a slowdown on some array operations.

### ISSUE THREAD

**Issue by vlajos** [zloirock/core-js#420]
The same thing happens as described here: https://github.com/zloirock/core-js/issues/377
when I used the promise module like this:
```
import 'core-js/es6/promise';
```
I used this timer script to "detect" the issue:
```
var arr = [];
for (var i=0; i<3200000; i++) {
    arr.push(Math.random())
}
var startTime = performance.now();

x = new Float32Array(arr);

document.write('Time spent: ' + (performance.now() - startTime) + ' ms');
```
The time needed to run the loop is around 100x bigger when the promise is imported.

(If you think it helps I am happy to create similar more detailed test scripts like in the other issue.)

**Comment by zloirock** [comment]
What about `core-js@3`? I have no ideas how it can touch typed arrays. I'll test it later.

**Comment by vlajos** [comment]
@zloirock With `3.0.0-beta.3` our app seems to be quick.

**Comment by zloirock** [comment]
I don't wanna rewrite all possible problem cases in legacy `core-js@2` branch if it works in `core-js@3`. Feel free to add a PR to `v2` branch if performance of `core-js@2` is something critical for you.
