### ISSUE TITLE
ES6 Array modules don't include 'keys/values/entries'?

### ISSUE THREAD

**Issue by dwb1994** [zloirock/core-js#421]
[https://github.com/zloirock/core-js/tree/v2#ecmascript-6-array](https://github.com/zloirock/core-js/tree/v2#ecmascript-6-array)

version: v2

expect:
I'd like to use 'core-js-builder' building a polyfill.js file. Options.modules['es6.array.values'] is expected.

``` javascript
const build = require('core-js-builder');
const fs = require('fs');

build({
  modules: [
    'es6.array.values'
  ], 
  library: true,
  umd: true
}).then((code) => {
  fs.writeFileSync('./polyfill.js', code, { encoding: 'utf8' })
}).catch((err) => {
  console.log(err);
});
```

**Comment by zloirock** [comment]
They available in module `es6.array.iterator`.
