### ISSUE TITLE
[Firefox 1.0.7] Number.prototype.valueOf called on incompatible Object

### ISSUE THREAD

**Issue by latentstops** [zloirock/core-js#425]
try to use core-js for old browser ( Firefox 1.0.7 )
could anyone help me

```
    /* 20 */
    /***/ (function(module, exports) {

        var toString = {}.toString;

        module.exports = function (it) {
            return toString.call(it).slice(8, -1); // <- error here
        };


        /***/ }),
```

**Comment by zloirock** [comment]
Just interesting, where you found FF 1.0.7? -) `core-js` tested in FF4+ in saucelabs, old versions in FF3+. Feel free to add a PR which will fix this issue.

**Comment by zloirock** [comment]
Since I wanna drop pre-ES5 engines support in `core-js@4`, closed as `wontfix`.
