### ISSUE TITLE
changing the name of the global created variable name

### ISSUE THREAD

**Issue by ommehaz** [zloirock/core-js#436]
Babel uses core-js which creates a global variable called core , is it possible to change the name of the global variable???

**Comment by zloirock** [comment]
Nope. It `core-js@3` it's just removed for global polyfill.

**Comment by ommehaz** [comment]
What do you mean?

**Comment by loganfsmyth** [comment]
@ommehaz Maybe you can load `core-js` and then delete the global to allow your other library to load?

What he's saying is that version 3.x of `core-js` does have toe global anymore, so you can also explore that as an option, but at the moment Babel still uses `core-js@2` if you opt for polyfill-related features.
