### ISSUE TITLE
Clash with other polyfills / infinite recursion

### ISSUE THREAD

**Issue by fmardini** [zloirock/core-js#437]
Hello,
I need to polyfill some string functions to work around platform specific bugs. My polyfill seems to be interacting adversely with core-js. The following code causes an infinite loop

```
console.log(d.charCodeAt(1));
const charCodeAt = String.prototype.charCodeAt;
String.prototype.charCodeAt = function (i) {
  console.log("patched");
  return charCodeAt.call(this, i);
}
require("core-js/fn/string");
```

Not sure I understand what is going on.
Thanks!

**Comment by webschik** [comment]
Hi, @fmardini !

It's not a problem of the `core-js` module.
Try to debug this example in Node.js env.:

```
const charCodeAt = String.prototype.charCodeAt;

String.prototype.charCodeAt = function (i) {
    console.log("patched", this);
    return charCodeAt.call(this, i);
}

's'.charCodeAt(0);
```

The debug output will look like (I've used VSCode):

```shell
patched String {[[PrimitiveValue]]: "s"}
patched String {[[PrimitiveValue]]: "patched"}
patched String {[[PrimitiveValue]]: "patched"}
...
```

That's because the internal implementation of `console.log` is using `.charCodeAt` and that's why you get an infinitive loop.

**Comment by fmardini** [comment]
Hi @webschik,
Thanks for taking a look.
You're right, the above code has an infinite loop.
Interestingly, this works fine.

```
require("core-js/es/string");
const d = "foo";
console.log(d.charCodeAt(1));

const charCodeAt = String.prototype.charCodeAt;
String.prototype.charCodeAt = function (i) {
  console.log("patched");
  return charCodeAt.call(this, i);
}

console.log(d.charCodeAt(1));
```
