### ISSUE TITLE
Tree-root is not working in IE

### ISSUE THREAD

**Issue by pranavtechnossus** [zloirock/core-js#438]
I am working in angular using Tree-node for side navigation it's working fine in google-chrome, Edge, and also in Mozilla, but when I try to use in IE it doesn't work, Issue is I am able to expand the node but not able to select the node-children, as my side-nav have a functionality that after expanding  I can select the children node but its not working in IE, tried almost solution provided in internet, but nothing helped, if anyone can help me I will appreciate a lot

![screenshot_5](https://user-images.githubusercontent.com/39586967/46803204-275fdc80-cd7d-11e8-944b-c05cdba32e6d.png)
In the screenshot, you can see all nodes I am not able to click on that, and actual functionality is after clicking on any node its getting selected and selected node is highlighted with colour

**Comment by zloirock** [comment]
I don't think that this issue related `core-js`. `core-js` provides only polyfills for ECMAScript and closely related features.
