### ISSUE TITLE
Upgrading to core-js 3*

### ISSUE THREAD

**Issue by CodySchaaf** [zloirock/core-js#439]
In my current app I'm using 

```
import "core-js/es6";
import "core-js/es7/array";
```

As per the Angular standard setup. If I want to upgrade to core-js@3 what is the most foolproof way to emulate that? I'm not 100% sure which aspects of es6/es7.array I'm using in my application. Should I just import `core-js/es` or is it better to look at exactly what the es6 file was importing in version 2 and import those as specific line items through `core-js/features/*`? 

Thanks, and sorry if I missed an upgrade guide somewhere.

**Comment by zloirock** [comment]
The upgrade guide is not finished.

In `core-js@3` we have one namespace for stable ECMAScript features - you can import it as
```js
import 'core-js/es';
```

If required for you `Array` feature is not stable, you can also add
```js
import 'core-js/features/array';
```
for adding all `Array` features with proposals. If you need any concret proposal, you can add
```js
import 'core-js/proposals/array-flat-and-flat-map';
import 'core-js/proposals/array-last';
```
