### ISSUE TITLE
What will happen when Object/String/Array ware frozen by context?

### ISSUE THREAD

**Issue by zswxp32** [zloirock/core-js#444]
Hello:

I had issue with this file.
 
-- _core-js@2.5.7@core-js/modules/_fails-is-regexp.js

![image](https://user-images.githubusercontent.com/16289166/47286793-bfce4a80-d622-11e8-8237-fbda16e954f6.png)

Unfortunately, these objects in my context is frozen...

I can't run where I marked with a red line.

Is there another plan for this，thank you~

**Comment by JakeChampion** [comment]
Hi @zswxp32, could you list down the steps to reproduce this error? Is it in a particular browser version or node version?

**Comment by zswxp32** [comment]
> Hi @zswxp32, could you list down the steps to reproduce this error? Is it in a particular browser version or node version?

Hi @JakeChampion 

It‘s working well in browsers, but not on my [weex](https://github.com/apache/incubator-weex/) application.

In weex application context, the prototype of javascript build-in objects were frozen with code below
`/**
 * Freeze the prototype of javascript build-in objects.
 */
/* istanbul ignore next */
function freezePrototype$1 () {
  Object.freeze(Object);
  Object.freeze(Array);

  // Object.freeze(Object.prototype)
  freezeObjectProto();
  Object.freeze(Array.prototype);
  Object.freeze(String.prototype);
  Object.freeze(Number.prototype);
  Object.freeze(Boolean.prototype);

  // Object.freeze(Error.prototype)
  freezeErrorProto();
  Object.freeze(Date.prototype);
  Object.freeze(RegExp.prototype);
}

function freezeObjectProto () {
  var proto = Object.prototype;
  var protoName = 'Object.prototype';
  freezeProtoProperty(proto, '__defineGetter__', protoName);
  freezeProtoProperty(proto, '__defineSetter__', protoName);
  freezeProtoProperty(proto, '__lookupGetter__', protoName);
  freezeProtoProperty(proto, '__lookupSetter__', protoName);
  freezeProtoProperty(proto, 'constructor', protoName);
  freezeProtoProperty(proto, 'hasOwnProperty', protoName);
  freezeProtoProperty(proto, 'isPrototypeOf', protoName);
  freezeProtoProperty(proto, 'propertyIsEnumerable', protoName);
  freezeProtoProperty(proto, 'toLocaleString', protoName);
  freezeProtoProperty(proto, 'toString', protoName);
  freezeProtoProperty(proto, 'valueOf', protoName);
  Object.seal(proto);
}

function freezeErrorProto () {
  var proto = Error.prototype;
  var protoName = 'Error.prototype';
  freezeProtoProperty(proto, 'name', protoName);
  freezeProtoProperty(proto, 'message', protoName);
  freezeProtoProperty(proto, 'toString', protoName);
  freezeProtoProperty(proto, 'constructor', protoName);
  Object.seal(proto);
}

function freezeProtoProperty (proto, propertyName, protoName) {
  if (!proto.hasOwnProperty(propertyName)) {
    return
  }

  var origin = proto[propertyName];
  Object.defineProperty(proto, propertyName, {
    get: function () {
      return origin
    },
    set: function (value) {
      if (this === proto) {
        throw Error(("Cannot assign to read only property " + propertyName + " of " + protoName))
      }

      Object.defineProperty(this, propertyName, {
        value: value,
        writable: true
      });

      return value
    }
  });
}`

> this is my babel.config.js
`module.exports = () => {
  const babelConfig = {
    presets: [
      [require.resolve('@babel/preset-env'), {
        modules: false,
        useBuiltIns: 'usage',
      }],
      [require.resolve('@babel/preset-react'), {
        pragma: 'createElement',
      }],
    ],
    plugins: [
      require.resolve('@babel/plugin-transform-runtime'),
      require.resolve('@babel/plugin-transform-modules-commonjs'),
      require.resolve('babel-plugin-add-module-exports'),
      require.resolve('@babel/plugin-transform-object-assign'),
      [require.resolve('@babel/plugin-proposal-class-properties'), { loose: true }],
      require.resolve('@babel/plugin-proposal-object-rest-spread'),
      require.resolve('@babel/plugin-proposal-export-namespace-from'),
      [require.resolve('@babel/plugin-proposal-decorators'), { legacy: true }]
    ],
    ignore: [/@core-js/, /@babel\/runtime/],
    babelrc: false,
  };
  return babelConfig;
};
`
So, Core-js modifing or redefining prototypes of built-in objects will not work.

![image](https://user-images.githubusercontent.com/16289166/47342214-c1a51600-d6d5-11e8-9dbb-d345af567713.png)

In browsers, the code above works well，
In weex, can't set false to re[MATCH].

**Comment by zswxp32** [comment]
Call for help~~~

**Comment by zloirock** [comment]
It's strange to wait that polyfills will work after freezing built-in's. If you freeze a prototype, you can't set a property to an instance if it's existent in a prototype, it's expected behavior. See [this presentation](https://docs.google.com/presentation/d/17dji3YM5_LeMvdAD3Y3PQoXU1Mgm5e2yN_BraBSTkjo/edit#slide=id.p) from the previous TC39 meeting. So breaking built-ins definitely not a good idea.
