### ISSUE TITLE
Polyfill support for AbortController and AbortSignal

### ISSUE THREAD

**Issue by HeberLZ** [zloirock/core-js#445]
I searched on the issue tracker and repo but didn't find anything about it, are there any plans to add a polyfill for AbortController and AbortSignal? It's primary purpose is to be able to cancel fetch requests, but can also be used manually as a standard mechanism for cancelling promises or any kind of async behavior.

The final version of [AbortController](https://dom.spec.whatwg.org/#aborting-ongoing-activities) has been added to the DOM specification
The [corresponding PR](https://github.com/whatwg/fetch/pull/523) for the fetch specification is now merged.
Browser bugs tracking the implementation of AbortController is available here: Firefox: [#1378342](https://bugzilla.mozilla.org/show_bug.cgi?id=1378342), Chromium: [#750599](https://bugs.chromium.org/p/chromium/issues/detail?id=750599), WebKit: [#174980](https://bugs.webkit.org/show_bug.cgi?id=174980), Edge: [#13009916](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/13009916/).

Current browser support: https://www.caniuse.com/#feat=abortcontroller

**Comment by zloirock** [comment]
That does not look like something in the scope of `core-js`. Like `fetch`, see #25. `core-js` about ECMAScript spec and cross-platform related features. For canceling promises, I'm waiting for https://github.com/tc39/proposal-cancellation

**Comment by petamoriken** [comment]
Since they have become a de facto standard, I suggest to support them in core-js as well.

FYI: The DOM Standard specification has just been updated (https://github.com/whatwg/dom/pull/1027). It has not yet been implemented on any platform.

**Comment by zloirock** [comment]
I wanted to reopen this discussion a little later.

**Comment by petamoriken** [comment]
It may be helpful to refer to WinterCG's [Minimum Common Web Platform API](https://common-min-api.proposal.wintercg.org/).

**Comment by aleen42** [comment]
It is the scope of `core-web`: https://github.com/aleen42/core-web/commit/651d3ba271402d862e70a385df239ebfeea9895d

**Comment by zloirock** [comment]
@aleen42 thanks, maybe it will be possible to reuse something from that.

**Comment by CaptainPants** [comment]
I hacked together a basic polyfill for AbortController/AbortSignal at https://github.com/CaptainPants/zerodeps-multipart-parser/blob/main/src/polyfills/abort.ts. I haven't spent a lot of time on spec compliance, but it might be worth something to the project.

**Comment by petamoriken** [comment]
`AbortSignal.any` is probably difficult to implement because it requires iterable weak sets (`WeakSet` + `WeakRef`) in spec

https://github.com/whatwg/dom/pull/1152

**Comment by zloirock** [comment]
@petamoriken I have not delved into the features and the specification of this API, but at first glance, it looks like a simple combinator like `Promise.any`, so I don't see why it's required. Could you explain?

**Comment by zloirock** [comment]
Ok, I looked at the PR that you mentioned and see what you mean. It's bad, but I don't think that it's a critical problem if in the case of the existence of `WeakRef` we will have proper garbage collecting here and in the case of old engines - leaks.

**Comment by TimoStolz** [comment]
> `AbortSignal.any` is probably difficult to implement because it requires iterable weak sets (`WeakSet` + `WeakRef`) in spec
> 
> [whatwg/dom#1152](https://github.com/whatwg/dom/pull/1152)

Would [this implementation](https://github.com/mo/abortcontroller-polyfill/blob/master/src/abortsignal-ponyfill.js#L58) be prone to memory leaks?
