### ISSUE TITLE
Polyfil for Promise is used in Firefox despite having native support

### ISSUE THREAD

**Issue by kkapsner** [zloirock/core-js#446]
Firefox supports native Promise but core-js uses the polyfil instead.

The problem is that here: https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/es.promise.js#L53
Firefox neither isNode nor does it support PromiseRejectionEvent.

Real live problem with that: https://github.com/violentmonkey/violentmonkey/issues/466

**Comment by zloirock** [comment]
It's expected behavior. FF hasn't full support of promises - at least, unhandled rejection tracking. Polyfills should be loaded before any other code for preventing problems like this.

**Comment by loganfsmyth** [comment]
@kkapsner What about WebExtensions does not work? What is swapping out the implementation breaking? It seems like that would be the real issue to report, rather than the fact that `core-js` changes the implementation.

**Comment by kkapsner** [comment]
It's https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage
It does not send the response asynchronously when a core-js Promise is returned.
