### ISSUE TITLE
Custom build with browserslist

### ISSUE THREAD

**Issue by fenderil** [zloirock/core-js#449]
Hi there.

How about modify [core-js-builder](https://github.com/zloirock/core-js/tree/master/packages/core-js-builder) with browserslist and caniuse-db (or some other feature db)? It's would be useful to exclude some imports, that don't need to be polyfiiled.

**Comment by fenderil** [comment]
- Fine. On the other hand I had an idea about json generation, that includes only required and unsupported features.
- Yeah, caniuse-db is not so good.
- I had seen this. It's looks like what I need, but not. :) I need to generate features pack for single injection on document start, for reuses between modules and pages with window.history and different bundles. But why compat-table is not a good data source? Just interesting.
- I think there could be detached package, that definitely know all relations between features and engines, and this package generate json meta with usage of browserslist and unused_feature_list.

I can pick it for implementation.

**Comment by zloirock** [comment]
@fenderil sorry, I missed your answer.

#466 fixes this issue. Also, in this PR you can find argumentation.

**Comment by fenderil** [comment]
That is what i expected.
