### ISSUE TITLE
Object.assign does not copy symbol-typed properties

### ISSUE THREAD

**Issue by samwgoldman** [zloirock/core-js#45]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Example:_Symbol_properties

**Comment by stefanpenner** [comment]
this is surprising as they are marked as nonEnumerable...

**Comment by samwgoldman** [comment]
I agree, but ¯\\_(ツ)_/¯

**Comment by stefanpenner** [comment]
> I agree, but ¯\(ツ)/¯

ya, just surprising. We should confirm that those docs are correct.

**Comment by zloirock** [comment]
Yes, I know about this problem, but I can't simply fix it. All shimmed symbols are not enumerable, `Object.assign` should copy only enumerable symbols. I'll try to fix it when I'll rewrite `Symbol` implementation (not sure of success - a lot of problems), but not in near days - hasn't time.

**Comment by sebmck** [comment]
I don't see how those docs can be correct. The spec explicitly says that only `[[Enumerable]] is true` is set on the property descriptors:

http://people.mozilla.org/~jorendorff/es6-draft.html#sec-object.assign

> if _desc_ is not **undefined** and _desc_.[[Enumerable]] is **true**, then

Leaning more towards those docs being incredibly wrong.

**Comment by zloirock** [comment]
@sebmck docs are correct, but strange behavior. Symbols are `enumerable` by default. Most features, like `for-in` or `Object.keys` ignores all symbols, but, IIRC, there are 2 exceptions: `Object.assign` and `Object.defineProperties`. For emulate correct behavior need to wrap most `Object` methods in pre-ES6 environment =\

**Comment by zloirock** [comment]
Will be fixed in next release.
