### ISSUE TITLE
library/modules/_descriptors.js is throwing an error "a is not defined"

### ISSUE THREAD

**Issue by JessicaSachs** [zloirock/core-js#450]
Hey,

I'm getting a stack trace in production, mostly in Chrome 49, where `a is not defined`. It points me to this line. I can't reproduce it locally, but it's clearly happening in the wild.

I don't know where to start with debugging this. Thoughts?

```
...
(function (require, module, exports) {
/*** [13] /myproject/core-js/library/modules/_descriptors.js ***/

// Thank's IE8 for his funny defineProperty
module.exports = !require('./_fails')(function () {
  return Object.defineProperty({}, 'a', { get: function () { return 7; } }).a != 7;
});
...
```

**Comment by zloirock** [comment]
`_fails` is just `try/catch`, it's descriptors feature detection logic, you can try anywhere. Most likely you have a broken environment, I have no ideas how to help you.

**Comment by JessicaSachs** [comment]
I don't think it's a broken environment because this exact code is deployed in production and works fine for a few million users :-)

What else could I log out in the stack trace that would be useful? The state of Object.prototype? Like why would `a` ever be undefined? Did another script on the page modify `Object` and remove `a`? Given that I don't support IE8, is there a way for me to exclude plugin?

**Comment by zloirock** [comment]
One more time: it's a simple feature detection. It's equal of
```js
try {
  module.exports = Object.defineProperty({}, 'a', { get: function () { return 7; } }).a == 7;
} catch (e) {
  module.exports = false;
};
```
Because it's `try/catch`, I have no ideas how even breaking of `Object.prototype` can break it. I don't see even a variable `a` which can be `undefined`. Maybe you have a problem with your build process - but you say that it works for a few million users. Maybe the problem in another place. So, please, add a reproducible example or, at least, a stack trace.

**Comment by JessicaSachs** [comment]
I understand what you mean.

Actually, I think it might actually be this line, where it calls defineProperty on `dom-create`... and yes, you're right my environment isn't in a good state at this point. The area the failure is happening in might not have a document (we're not on an html page at this point.. I think we're inside of a pdf?)...

So while you're really defensive in `dom-create.js` already, perhaps `createElement` fails or something, and we get `undefined` back.

I think I'm going to try and exclude using core-js for that part of the code base and see if that fixes it.


```
module.exports = !require('./_descriptors') && !require('./_fails')(function () {
  return Object.defineProperty(require('./_dom-create')('div'), 'a', { get: function () { return 7; } }).a != 7;
});
```

Anyway. Thank you for the help and reassuring me that there was nothing wrong with the library on its own. 💯
