### ISSUE TITLE
WeakFactory (weak references) 

### ISSUE THREAD

**Issue by Jamesernator** [zloirock/core-js#451]
There's currently some [spec text](https://github.com/tc39/proposal-weakrefs/blob/master/specs/spec.md) for the feature now and it's behind the flag `--harmony-weak-refs` in Chrome Canary.

While it's technically not possible to fully implement WeakRefs (like Proxy) it is possible to implement the API surface (unlike Proxy) by simply storing strong references which isn't technically disobeying the spec as garbage collection is not required by the spec.

Very minimal polyfill (doesn't bother implementing `WeakFactoryCleanupIterator` as it won't be observable):

```js
class WeakCell {
  constructor(value, holdings) {
    if (typeof value !== 'object' && typeof value !== 'function') {
      throw new TypeError(`Can't create ${ new.target.name } of ${ String(value) }`);
    }
    this._value = value;
    this._holdings = holdings;
  }

  get holdings() {
    return this._holdings;
  }

  clear() {
    this._value = undefined;
    this._holdings = undefined;
  }
}

class WeakRef extends WeakCell {
  deref() {
    return this._value;
  }
}

export default class WeakFactory {
  makeCell(value, holdings) {
    return new WeakCell(value, holdings);
  }

  makeRef(value, holdings) {
    return new WeakRef(value, holdings);
  }

  shutdown() {
    /* Can't actually do anything in a polyfill */
  }
}
```

**Comment by zloirock** [comment]
Thanks to this proposal. I was thinking about it, but I don't think that only API implementations without real weak references make sense.
