### ISSUE TITLE
Uint8Array.fill() error in IE11 

### ISSUE THREAD

**Issue by Alex-Sokolov** [zloirock/core-js#452]
Hi! Seems missing `fill` method for Uint8Array. In IE11 this code will throw an error:
```js
import 'core-js'

const BASE_MAP = new Uint8Array(256)
BASE_MAP.fill(255)
```
Used core-js 2.5.7

**Comment by zloirock** [comment]
Sorry, I can't reproduce it:
![image](https://user-images.githubusercontent.com/2213682/48213572-b843cb00-e3b0-11e8-8f3d-707cdc3eb254.png)

**Comment by Alex-Sokolov** [comment]
@zloirock can you say in which core-js module this polyfilled?

**Comment by zloirock** [comment]
For `core-js@2`, it's [here](https://github.com/zloirock/core-js/blob/v2/modules/_typed-array.js#L168-L169).

**Comment by zloirock** [comment]
Closed as `can't reproduce`.
