### ISSUE TITLE
`Array.prototype.flatten` was renamed to `Array.prototype.flat`

### ISSUE THREAD

**Issue by caiotoon** [zloirock/core-js#457]
As per TC39 proposal (https://github.com/tc39/proposal-flatMap), `Array.prototype.flatten` was renamed to `Array.prototype.flat`.

`flat` is not yet present in v2.

**Comment by zloirock** [comment]
It's renamed in `core-js@3`. Because this proposal also had some minor internal changes, it will not be updated in `core-js@2`.
