### ISSUE TITLE
Object#__proto__ / Object.setPrototypeOf sham?

### ISSUE THREAD

**Issue by zloirock** [zloirock/core-js#459]
We can't add a real polyfill for a setting prototype of an existent object. But we can add a copy-based cap for most common cases which used for inheritance, for example, in Babel. Many cases like this
```js
function A() {};
function B() {};

A.__proto__ = B;

B.fn = () => console.log('fn');

A.fn();
```

will not work.

I'm not a fan of this approach. Makes it sense or not?

**Comment by webcarrot** [comment]
:+1: 
1. I think `__proto__` and `setPrototypeOf` are not used directly by most programmers. Even:
```js
class X {}
class Z extends X {}
X.foo = "bar";
```
probably will be written like this:
```js
class X {
  static foo = "bar";
}
class Z extends X {}
```
2. Applying new static properties to already used/extended classes looks like an anti-pattern for me.
3. Shim will handle 99% real use cases (my shim ignore pseudo Symbols :disappointed: ).

:-1: 
1. Still shim
2. Reliance on inherited static class properties is not common practice (?)
3. IE < 10 will die soon anyway

PS. Sorry for my English.

**Comment by zloirock** [comment]
I'm closing it since seems it already makes no sense.
