### ISSUE TITLE
Code too slow because of "mutating the [[Prototype]] of an object [..]" error 

### ISSUE THREAD

**Issue by pindamonhangaba** [zloirock/core-js#46]
Using babel/browser-polyfill.js my app gets so slow it momentarily makes firefox not respond, with the warning:
     
    mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

From https://github.com/babel/babel/issues/1099

**Comment by zloirock** [comment]
If you have concrete `core-js` performance issue - specify it.

It's only warning in FF that app uses `__proto__` or `Object.setPrototypeOf`. IIRC, at this moment, `core-js` uses `__proto__` only for polyfilling `Object.setPrototypeOf`, where it is not supported - you will not have this message if you don't uses it. `babel` uses `__proto__` for inheriting class static propertiies, `regenerator` uses `__proto__` for emulation `%GeneratorPrototype%`.

**Comment by Kagami** [comment]
I get the same warning when I enable "babel/polyfil" and I traced it down in Firefox Nightly 42 (which has `Object.setPrototypeOf`) to [this line](https://github.com/zloirock/core-js/blob/v1.0.0/modules/es6.promise.js#L41).

It seems to be Firefox doesn't like usage of `setPrototypeOf` as well. For example this code gives the warning too:

```js
var o1 = {};
var proto = {};
Object.setPrototypeOf(o1, proto);
console.log(o1);
```

The conrete usage in core-js (promise feature detection) shouldn't cause any performance issues though as far as I can understand.

**Comment by stefanpenner** [comment]
sounds like an overzealous Firefox warning...

**Comment by zloirock** [comment]
@Kagami this test was added after creation current issue. It's only notification about usage `setPrototypeOf` and does not creates any performance problems.
