### ISSUE TITLE
regexpExec: require is not defined 2.6.0

### ISSUE THREAD

**Issue by vvpvvp** [zloirock/core-js#460]
Problem:
Use webpack build our codes, it's all occur errors.
We found it's because of core-js new version 2.6.0.
And we used dependence babel-polyfill.

![_72ec3a50-a04e-4d2a-80b5-dc11de6c3275](https://user-images.githubusercontent.com/7303371/49575298-4fcf1600-f97d-11e8-9b95-7ab57572109d.png)
![_be3d5c10-3c44-4ec3-8a99-e0f760511d7a](https://user-images.githubusercontent.com/7303371/49575304-52ca0680-f97d-11e8-8ae7-a6703ed90eab.png)
![_a98f2c6f-e99e-4647-8acb-e93a850e7a14](https://user-images.githubusercontent.com/7303371/49575306-552c6080-f97d-11e8-9c1f-77e844c0da6c.png)

**Comment by nicolo-ribaudo** [comment]
What is the webpack output for that code when you disable eval-source-map?

**Comment by vvpvvp** [comment]
I have config devtool to false, and there is no error output when build.

**Comment by nicolo-ribaudo** [comment]
@vvpvvp Could you share a small repo which reproduces the issue?

**Comment by zloirock** [comment]
Closed as `can't reproduce`.

**Comment by vvpvvp** [comment]
This is the online website，it's always this error , and I can't fix it now :
https://www.heyui.top/
and the webpack tool is complicated, I will do my best to reproduce it.

**Comment by vvpvvp** [comment]
Some webpack config use script-loader for the legacy code. (*.exec.js)，that would be a problem at 2.6.0
