### ISSUE TITLE
Out of stack space error in IE 11 when loading shim.min.js from core-js 2.6.0

### ISSUE THREAD

**Issue by theodorejb** [zloirock/core-js#463]
I have an Angular app, and it works fine in all browsers when loading shim.min.js from core-js v2.5.7. However, after updating to core-js v2.6.0, I get an "Out of stack space" error in shim.min.js in IE 11.

I tried switching to the non-minified file and got the same error, on the following line:
https://github.com/zloirock/core-js/blob/f980318866f5cfb2933493c81ba89e1baf0f33c2/client/shim.js#L6312

**Comment by nicolo-ribaudo** [comment]
How are you calling String#split()?

**Comment by nicolo-ribaudo** [comment]
I'll check it tomorrow

**Comment by zloirock** [comment]
@theodorejb could you add a reproducible example?

**Comment by nicolo-ribaudo** [comment]
The problem is that `$split` refers to the function which calls it, I stead of the original `$split`

**Comment by georgechr** [comment]
+1
Having the same problem.

Looking at the original uncompiled file https://github.com/zloirock/core-js/blob/v2.5.7/modules/es6.regexp.split.js which doesn't have the issue makes me suspect that when it's built the assignment to $split gets optimized out and thus we get this issue

**Comment by nicolo-ribaudo** [comment]
You are right

**Comment by lenny1806** [comment]
We are getting the same issue, downgrading to 2.5.7 fixed it for now.

**Comment by vytautas-pranskunas-** [comment]
Same issue here

**Comment by nicolo-ribaudo** [comment]
The fix has been merged and it will be released in 2.6.1.
