### ISSUE TITLE
setImediate callback not called

### ISSUE THREAD

**Issue by pepone** [zloirock/core-js#464]
we are using the core-js setImediate included by babel-polyfill we are observing that with safari some times but not always the callback pass to setImediate is not dispatched

We are observing this in a large application and have non been able to track it down to a more simple test case, we added a workaround to use setTiemout with safari workers, and it solves our issue, but will be nice to track this down.

https://github.com/zeroc-ice/ice/blob/f44f04e79537e45ba28f61317d7233ee19f05313/js/src/Ice/browser/TimerUtil.js#L64-L71

**Comment by JakeChampion** [comment]
Have you tried replicating the issue by having a worker which only contains core-js and setImmediate?

**Comment by zloirock** [comment]
What's the version of Safari?

**Comment by zloirock** [comment]
I remember [the same problem for microtasks in Safari](https://github.com/zloirock/core-js/issues/339), but not for tasks.

**Comment by pepone** [comment]
So far I have been testing an alternate implementation based on MessageChannel and works fine with the same Safari version

https://github.com/zeroc-ice/ice/blob/145d53a7cdb489a95178d7e6be95d98f16596e75/js/src/Ice/browser/TimerUtil.js#L89

**Comment by zloirock** [comment]
@pepone `core-js` [should use the same](https://github.com/zloirock/core-js/blob/master/packages/core-js/internals/task.js#L57-L61) in Safari.

**Comment by zloirock** [comment]
Maybe you also implicitly use another `setImmediate` polyfill which overrides `core-js` implementation?

**Comment by pepone** [comment]
>core-js should use the same in Safari.
Yes I know, I looked at the implementation before and didn't see anything wrong there, we are observing the callback is not called with Safari but not always

>Maybe you also implicitly use another setImmediate polyfill which overrides core-js implementation?
I don't think so, I will try to create a test with only the core-js implementation, we are getting this from babel polyfill that as far as I know uses core-js

**Comment by zloirock** [comment]
Closed as `can't reproduce`.
