### ISSUE TITLE
Older Android: error on es6.object.statics-accept-primitives

### ISSUE THREAD

**Issue by eknkc** [zloirock/core-js#47]
Hi,

I have got some reports regarding to older Android devices throwing on this particular line (807):

`TypeError: Result of expression 'fn' [undefined] is not a function`

![](http://d.ekin.io/1ciCr+)

This is the bundled core-js version in latest babel (ref: babel/babel#1109). I'm not sure if this has been fixed in later releases of core-js, I can't reproduce it myself but we received several complaints from Android users since we switched to babel and core-js for polyfills.

Any ideas?

**Comment by zloirock** [comment]
Hi. Tests been passed on actual Android. At the moment, I do not have at hand the necessary test environment, I investigate it later. In version `0.7.x`, this module has been significantly changed, try the latest version. Problems are possible on older Android w/o fully ES5 support.

**Comment by zloirock** [comment]
Looks like it's error on `Object.freeze` call. `babel` uses it for template strings. This method was added in v8 ~ Chromium 6 and missing on older Android. As I wrote above, try version from `client` path with es5 polyfill.
