### ISSUE TITLE
URL object constructor broken in IE11 (some versions

### ISSUE THREAD

**Issue by gekkedev** [zloirock/core-js#477]
I've encountered "Object doesn't support this action" errors in IE11.0.96 when constructing the URL object. The OS used is Win7. Example: `new URL(location.href)` works fine in other browsers but throws an error in IE.
As far as I can tell from the polyfill code, the constructor [should be working](https://github.com/zloirock/core-js/blob/e33ab6455ff6ef7728be25405b83e448a5376c84/packages/core-js/modules/web.url.js#L1002) although the constructor appears to be empty:
![image](https://user-images.githubusercontent.com/17025257/51481141-7ca38500-1d93-11e9-8897-adabf2b093cb.png)
The usage context is an AngularJS 6 project where I imported the whole corejs stack. Wish I was able to tell what causes this behavior but I don't have a deep understanding of this library yet.

**Comment by zloirock** [comment]
In what `core-js` version?

**Comment by gekkedev** [comment]
After trying out some more importing, it appeared I had been using the wrong import script. The `index.js` in the root path was barely documented but looked like it imports the shim and all the other scripts from the subfolders. Not checking each and every import was my mistake, sorry.
My issue was resolved after importing `core-js/client/shim`.

**Comment by zloirock** [comment]
@gekkedev `URL` polyfill was added in `core-js@3` and `core-js@3` does not contain `core-js/client/shim` entry.

**Comment by gekkedev** [comment]
You're right... I've checked it again and the line causing my application to break was `new URL(location.href).searchParams.get('language')` from where i assumed the `URL` object is to blame. The `URL` constructor does not work/exist in IE console anyway, but I'm getting no more errors about this after the polyfill import path change.

**Comment by gekkedev** [comment]
I couldn't afford updating the library to an experimental version, so I wrote my own workaround (which isn't perfect though):
```
try {
        var myParam = new URL(location.href).searchParams.get('myParam');
      } catch { //fallback for IE and others due to missing URL() support
        try { //inspired by https://css-tricks.com/snippets/javascript/get-url-variables/
          var query = window.location.search.substring(1);
          var vars = query.split("&");
          for (var i = 0; i < vars.length; i++) {
            var pair = vars[i].split("=");
            if (pair[0] == "myParam") {
              var myParam = pair[1];
            }
          }
          if (myParam == undefined) throw false;
        } catch { //if nothing works...
          var myParam = "default_value";
        }
      }
```
Leaving this here in case anyone encounters the same issue.

**Comment by Delagen** [comment]
@zloirock Seems it doesn't work in current version

**Comment by zloirock** [comment]
@Delagen it should work in the current version.

**Comment by Delagen** [comment]
@zloirock Very strange. I try to investigate...
