### ISSUE TITLE
Module not found: Error: Can't resolve './es6.array.iterator' after updating to Babel v7

### ISSUE THREAD

**Issue by dep** [zloirock/core-js#478]
I've recently updated to Babel v7 and afterwards my build is failing with the following error:

```
Module not found: Error: Can't resolve './es6.array.iterator' in '/root/project/packages/ui-library'
```

I've tried a `npm install core-js --save-dev` in that package, but it continues to fail. I haven't found many if any related articles online sadly.

I've also tried removing my local node_module directories and re-running `yarn install && yarn build` to no avail.  Bit of a hail mary posting here, but thought someone might see this and have an idea.

**Comment by zloirock** [comment]
I don't think that it's a `core-js` issue. All `core-js@2` versions contain [`core-js/modules/es6.array.iterator` file](https://github.com/zloirock/core-js/blob/v2/modules/es6.array.iterator.js). Seems the problem in your configs of `babel` or something else.

**Comment by dep** [comment]
Looks like the issue was using `require('@babel/polyfill')` instead of `require('babel-polyfill')` in my config. Switched to the later and everything is fine.
