### ISSUE TITLE
Issue with babeljs on node 0.10.x

### ISSUE THREAD

**Issue by Globegitter** [zloirock/core-js#48]
I am having an issue with babeljs, see my gist https://gist.github.com/Globegitter/ee46154b9a1b7506af19 as well as explaining comment: https://github.com/babel/babel/issues/1134#issuecomment-89229700

And according to https://github.com/babel/babel/issues/1134#issuecomment-89262465 this seems to be an issue with core-js itself.

To summarise the issue:
I am using babeljs to transpile my tests but not in the actual app-code itself. The app-code in question uses promises without a library, so should only work in node 0.12.x  as well as io.js 1.x. But for some reason the tests are still passing on node 0.10.x.

And it seems the issue lies in core-js and the globals it pollutes. Anyway, let me know if you need any more clarification about the test-example.

**Comment by zloirock** [comment]
I do not understand the question. `babel-register` includes global polyfill. W/o global pollution works `runtime` transformer / `core-js/library` version.

**Comment by sebmck** [comment]
@Globegitter 

> And according to babel/babel#1134 (comment) this seems to be an issue with core-js itself.

I never said it was an actual issue.

> I am using babeljs to transpile my tests but not in the actual app-code itself. The app-code in question uses promises without a library, so should only work in node 0.12.x as well as io.js 1.x. But for some reason the tests are still passing on node 0.10.x.

Yes, this is how the polyfill works. It polyfills in missing features, why shouldn't `Promise` work?

**Comment by Globegitter** [comment]
@sebmck @zloirock the problem I am running into is that I want to limit babel/the polyfill it provides to files only within my `tests` folder. Otherwise the tests are not truthful across all platforms.

I also provided 2 repos demonstrating that effect. One simple one: https://github.com/Globegitter/babel-promise

And one where the problem actually occurred with a more detailed readme: https://github.com/Globegitter/enpeem-promise-test

Let me know if this needs any further clarification. I guess the question from my side: Is there currently a way to limit babel, including it's polyfills to specific folders/files?

**Comment by sebmck** [comment]
@Globegitter 

> Is there currently a way to limit babel, including it's polyfills to specific folders/files?

No that is not possible because there is only one global namespace in JavaScript and it's impossible for core-js to know what file is calling it and even if it did it would have to reroute it to the original and it would be extremely crude and complicated.

**Comment by Globegitter** [comment]
@sebmck Hmm yeah that makes sense. So is there any other workaround you can imagine to fix this particular issue?

On thing that I could imagine is to be able to not use certain polyfills. The tests here would fail if I could simply turn off the `Promise` polyfills which I do not need anyway. So is that possible?

**Comment by sebmck** [comment]
@Globegitter Not without a custom build of core-js. If you want fine grained control over your environment you should not be using `babel/register` in the first place.
