### ISSUE TITLE
Code Issues

### ISSUE THREAD

**Issue by fastmarketo** [zloirock/core-js#481]
`function USScroll(options) {
        var defaults = {
            attachOnInit: '.menu-item a[href*="#"], .menu-item[href*="#"], a.w-btn[href*="#"], .w-iconbox a[href*="#"], .w-image a[href*="#"], .w-img a[href*="#"], .w-text a[href*="#"], ' + '.vc_icon_element a[href*="#"], .vc_custom_heading a[href*="#"], a.w-grid-item-anchor[href*="#"], .w-toplink, ' + '.w-blogpost-meta-comments a[href*="#"], .w-comments-title a[href*="#"], .w-comments-item-date, a.smooth-scroll[href*="#"]',
            buttonActiveClass: 'active',
            menuItemActiveClass: 'current-menu-item',
            menuItemAncestorActiveClass: 'current-menu-ancestor',
            animationDuration: $us.canvasOptions.scrollDuration,
            animationEasing: 'easeInOutExpo'
        };`

This is the code in th core.js |  The above code is creating issue I have a modal box that should be clicked on clicking an anchor tag, but instead of rendering the click behavior and opening the modal box it scrolls to the destination of #anchors and that is taking away the target. How should I fix this?

**Comment by zloirock** [comment]
It does not look like a code from `core-js`.
