### ISSUE TITLE
ios8.3: symbol of window key where  error occurred

### ISSUE THREAD

**Issue by Dailoge** [zloirock/core-js#487]
var a = Symbol('fff')
console.log(winow[a])   //undefined
window[a] = 'a'   //TypeError: undefined is not an object (evaluating 'hasOwnProperty.call(it, key)')

var b = {}
b[a] = 'a' // true, most surprised

**Comment by zloirock** [comment]
Interesting. Seems ios8.3 incorrectly pass `this` context to global object setters.

Could you replace [this code](https://github.com/zloirock/core-js/blob/aaa32e611e9d853889b1118989dae478dcf4470a/packages/core-js/modules/es.symbol.js#L160-L162) (or similar code in `core-js/modules/es6.symbol`, if you use `core-js@2`) to
```js
      var that = this === undefined ? global : this;
      if (that === ObjectPrototype) setter.call(ObjectPrototypeSymbols, value);
      if (has(that, HIDDEN) && has(that[HIDDEN], tag)) that[HIDDEN][tag] = false;
      setSymbolDescriptor(that, tag, createPropertyDescriptor(1, value));
```
and test it again?

**Comment by Dailoge** [comment]
Are very pleased to receive your reply !
i test, ios11.4 is right, but ios8.3 still happen error；
i test 
`    var that = this === undefined ? global : this;
      if (that === ObjectProto) setter.call(ObjectPrototypeSymbols, value);
      if (has(that, HIDDEN) && has(that[HIDDEN], tag)) that[HIDDEN][tag] = false;
      setSymbolDesc(that, tag, createDesc(1, value));
`
it's right, very nice

**Comment by zloirock** [comment]
I'm not sure that I understood your comment. So, with this code, you still have an error in iOS 8.3?
