### ISSUE TITLE
IE11: _for-of.js causes IE11 to throw Error

### ISSUE THREAD

**Issue by fsubal** [zloirock/core-js#489]
Using `core-js@2.6.5`.

### What happened

I added some polyfills to my project like...

```ts
import 'core-js/modules/es6.string.starts-with'
import 'core-js/modules/es7.object.entries'
import 'core-js/modules/es7.object.values'
import 'core-js/modules/es6.set'
```

And then IE11 came to say something like this.

```
catch ステートメントでは適用されますが、throw ステートメントでは適用されません。
```

This error means `It is applied in catch statement, but not in throw statement.` in Japanese ( Sorry but I could not find how this message is stated in English browser ).

I found this error occurred at this line of `_for-of.js`. This was actually caused by the `TypeError` thrown here ( It seems that the error above implies the `TypeError` was not thrown correctly, and IE says "Failed to throw error" with that strange error message ).

https://github.com/zloirock/core-js/blob/e778e8026aed8a58f93f1ee4e3192cd1a7d7bdf5/modules/_for-of.js#L14

So, there are two problems here.

- IE cannot go on to load `_for-of.js` with TypeError.
- Looks IE does not throw the TypeError correctly ( with that strange error message ).

Actually I have not detected which of the four polyfills caused this ( seems `es6.set`, though ).

### Expected Behaviour

IE loads these polyfills correctly, without throwing. ( If not, declare that `for-of` or `Set` cannot be pollyfilled for IE ? )

**Comment by zloirock** [comment]
> I added some polyfills to my project like...

Please, don't add polyfills from `core-js/modules` path directly if you don't completely understand what are you doing! This path doesn't include dependencies of those polyfills. In this case - iterators for `Set`. Use something like
```js
import 'core-js/fn/string/starts-with'
import 'core-js/fn/object/entries'
import 'core-js/fn/object/values'
import 'core-js/fn/set'
```
