### ISSUE TITLE
Call stack exceeded when setting symbol property on blob/file on IE11

### ISSUE THREAD

**Issue by hcomnetworkers** [zloirock/core-js#490]
Checked in `core-js@2.6.5`  `core-js@3.0.0-beta.9`, issue present in both versions.

### Description

When setting a property, which uses a symbol as key, on a File or Blob instance, a call stack exceeded error is triggered in Internet Explorer 11. On a normal object everything works as expected.

### Example Code

test.js
```
import 'core-js';

var hash = Symbol();
var b = new Blob(["randomblob"], { type: "text/plain" });
b[hash] = 'Failing here';
```

package.json
```
{
  "name": "core-js-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {},
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "webpack": "^4.29.5",
    "webpack-cli": "^3.2.3"
  },
  "dependencies": {
    "core-js": "^2.6.5"
  }
}
```

webpack.config.js

```
const path = require('path');

module.exports = {
  entry: './src/index.js',
  mode: 'development',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist')
  }
};
```

**Comment by zloirock** [comment]
Seems it's an equal of #163. Some exotic objects have specific/non-standard behavior on `get` or `set` and `Symbol` polyfill can't work with them. I don't think that attempting to adding workarounds for cases like this makes sense.

**Comment by zloirock** [comment]
However, if you think that it can be simply fixed - feel free to propose a solution.
