### ISSUE TITLE
Support for Intl.PluralRules

### ISSUE THREAD

**Issue by adipascu** [zloirock/core-js#491]
This is much smaller than the full Intl, [eemeli/intl-pluralrules](https://github.com/eemeli/intl-pluralrules) could be used.

If not, I suggest adding this into the project [README](https://github.com/zloirock/core-js/blob/4d3549dc0490e2d581006de87350006852754d10/README.md#missing-polyfills) file.

**Comment by zloirock** [comment]
Thanks for the proposal. [`README` already contains a note about `Intl` at all](https://github.com/zloirock/core-js#missing-polyfills), I don't think that add a polyfill only for `Intl.PluralRules` makes sense.

**Comment by adipascu** [comment]
@zloirock The polyfill specified in the readme does not contain plural rules.
