### ISSUE TITLE
Typo in AgregateError?

### ISSUE THREAD

**Issue by jdreesen** [zloirock/core-js#493]
I just read the announcement for `v3.0.0-beta.17` and I'm afraid there's a typo here: 
`- Added AgregateError for Promise.any rejections.`

Shouldn't it be `AggregateError` (note the two `g`) instead?

This does seem to not only affect the release notes but the implementation, too.

(Note that I'm not a native english speaker, though)

**Comment by zloirock** [comment]
Oops... Thanks -)

**Comment by zloirock** [comment]
I wrote it on the plane and did not check the spec -)
