### ISSUE TITLE
rollup treeshaking breaks es.string.split.js

### ISSUE THREAD

**Issue by AndrewLeedham** [zloirock/core-js#494]
## Issue
When using rollup with babel to inject core-js polyfills, the [SUPPORTS_Y check](https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/es.string.split.js#L17) gets truncated from 

```javascript
var SUPPORTS_Y = !fails(function () { RegExp(MAX_UINT32, 'y'); });
```

to

``` javascript
var SUPPORTS_Y = !fails(function () {  });
```

rollup seems to see this as having no side-effects and tree-shakes it. Whereas in reality the side-effect is an error being thrown.

## Repro
I created a minimal repro to showcase that toggling treeshaking through rollup is causing the issue: https://codesandbox.io/s/r0vj2k7znn. See line 22 on the `dest/output-*.js` files.

## Possible Solution
Perhaps this is an issue for rollup. But a quick fix would be to just return the RegExp call:

```javascript
var SUPPORTS_Y = !fails(function () { return RegExp(MAX_UINT32, 'y'); });
// or
var SUPPORTS_Y = !fails(function () { return new RegExp(MAX_UINT32, 'y'); });
```

**Comment by zloirock** [comment]
Seems it an issue for `rollup`. However, I can add a fallback on `core-js` side.

**Comment by AndrewLeedham** [comment]
Thanks for adding the workaround @zloirock. Much appreciated. Is there any plan to release a beta version with this in?
