### ISSUE TITLE
AppleWebKit/533.1: Object.getOwnPropertyDescriptor() doesn't report number-coerceable properties

### ISSUE THREAD

**Issue by bard** [zloirock/core-js#495]
This is a bug in a JavaScript engine, not in core-js. It can be worked around in a polyfill. To the best of my knowledge, no polyfill library currently does.

```js
import 'core-js/features/object/get-own-property-descriptor'

const obj = {
  '_123': 'bar',
  '123': 'foo',
}
console.error(Object.getOwnPropertyDescriptor(obj, '_123'))
// => {"value":"bar","writable":true,"enumerable":true,"configurable":true} 

console.log(Object.getOwnPropertyDescriptor(obj, '123'))
// => undefined
```
User agent: `AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1`

Core-js version tested: 3.0.0-beta.19

Repro: https://github.com/bard/repro-immer-numeric-properties-pre-es5/blob/master/minimal.js

Workaround: https://github.com/mweststrate/immer/issues/336#issuecomment-473884546

**Comment by zloirock** [comment]
Since I wanna drop ES3 support in `core-js@4` and it's Safari 4 issue, closed as `wontfix`.
