### ISSUE TITLE
Map/Set.prototype.toJSON

### ISSUE THREAD

**Issue by thomasfoster96** [zloirock/core-js#50]
As per the proposal at https://github.com/DavidBruant/Map-Set.prototype.toJSON, the toJSON method for Map/Set objects would be a useful addition to core-js.

**Comment by zloirock** [comment]
I've long wanna add them, but [do not consider the current behavior of `Map#toJSON`](https://github.com/DavidBruant/Map-Set.prototype.toJSON/issues/1) logical. About `Set#toJSON` - I think, I will add it in the next release.
