### ISSUE TITLE
Module not found: Error: Can't resolve 'core-js/modules/web.dom.iterable' 

### ISSUE THREAD

**Issue by janryWang** [zloirock/core-js#500]
when i build my source code by webpack, it will throw Module not found: Error: Can't resolve 'core-js/modules/web.dom.iterable'

**Comment by lengziyu** [comment]
me too.
```
These dependencies were not found:
[0]
[0] * core-js/modules/es6.array.iterator in ./src/entry-client.js
[0] * core-js/modules/es6.object.assign in ./src/entry-client.js
[0] * core-js/modules/es6.promise in ./src/entry-client.js
[0] * core-js/modules/es6.regexp.constructor in ./src/utils/util.js
[0] * core-js/modules/es6.regexp.match in ./src/utils/util.js
* core-js/modules/es6.regexp.search in ./src/utils/util.js
[0] * core-js/modules/es7.promise.finally in ./src/entry-client.js
[0]
[0] To install them, you can run: npm install --save core-js/modules/es6.array.iterator core-js/modules/es6.object.assign core-js/modules/es6.promise core-js/modules/es6.regexp.constructor core-js/modules/es6.regexp.match core-js/modules/es6.regexp.search core-js/modules/es7.promise.finally

```
if i run ` npm install --save core-js/modules/es6.array.iterator...`,this will report wrong.

```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "core-js\modules\es6.array.iterator" as it does not contain a package.json file.
```
core-js v3.0.0
node v10.x

**Comment by janryWang** [comment]
I have found a solution

```
module.exports = {
  babelrc:false,
  plugins: [
    // https://github.com/babel/babel/issues/8562
    [require.resolve('@babel/plugin-proposal-decorators'), { legacy: true }],
    require.resolve('@babel/plugin-transform-runtime'),
    require.resolve('babel-plugin-add-module-exports'),
    require.resolve('@babel/plugin-proposal-class-properties'),
    require.resolve('@babel/plugin-syntax-dynamic-import'),
    require.resolve('babel-plugin-react-docgen')
  ],
  presets: [
    [
      require.resolve('@babel/preset-env'),
      {
        targets: {
          chrome: '65'
        },
        modules: false,
        loose: true,
        useBuiltIns: 'usage' //Remove this line of code to solve the problem 
      }
    ].filter(Boolean),
    require.resolve('@babel/preset-react')
  ]
}

```

**Comment by lengziyu** [comment]
I returned core-js to the @2.6.5 version without misreporting.

**Comment by zloirock** [comment]
A big part of the modules renamed in `core-js@3`. You should update your `core-js` / `babel` settings. You could find more info [here](https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md).

**Comment by zkmark** [comment]
Install babel on package.json or https://stackoverflow.com/questions/55308769/module-not-found-error-cant-resolve-core-js-es6

```
"dependencies": {
    "@babel/core": "^7.4.5",
    "core-js": "^2.6.5",
  },
```

**Comment by nhooyr** [comment]
Was getting this with all the correct settings. Just had to `yarn add core-js`

**Comment by jndxzqc** [comment]
core-js@3.x has problems,return to core-js@2.x

**Comment by smallTiger001** [comment]
> me too.
> 
> ```
> These dependencies were not found:
> [0]
> [0] * core-js/modules/es6.array.iterator in ./src/entry-client.js
> [0] * core-js/modules/es6.object.assign in ./src/entry-client.js
> [0] * core-js/modules/es6.promise in ./src/entry-client.js
> [0] * core-js/modules/es6.regexp.constructor in ./src/utils/util.js
> [0] * core-js/modules/es6.regexp.match in ./src/utils/util.js
> * core-js/modules/es6.regexp.search in ./src/utils/util.js
> [0] * core-js/modules/es7.promise.finally in ./src/entry-client.js
> [0]
> [0] To install them, you can run: npm install --save core-js/modules/es6.array.iterator core-js/modules/es6.object.assign core-js/modules/es6.promise core-js/modules/es6.regexp.constructor core-js/modules/es6.regexp.match core-js/modules/es6.regexp.search core-js/modules/es7.promise.finally
> ```
> 
> if i run ` npm install --save core-js/modules/es6.array.iterator...`,this will report wrong.
> 
> ```
> npm ERR! code ENOLOCAL
> npm ERR! Could not install from "core-js\modules\es6.array.iterator" as it does not contain a package.json file.
> ```
> 
> core-js v3.0.0
> node v10.x

I also encounter this problem. How do you solve it?

**Comment by zqw** [comment]
thanks

**Comment by shaibam** [comment]
> Was getting this with all the correct settings. Just had to `yarn add core-js`

Yap... that fixed it.

**Comment by ohadbitt** [comment]
i installed core-js again (npm install core-js) and it solved it

**Comment by Ekkstein** [comment]
adding to ohadbitt:
maybe if it doesn't help to `npm install core-js` you can first do stuff like: `npm uninstall core-js`, delete your node_modules. Then run `npm install` and `npm install core-js`.

**Comment by RiZKiT** [comment]
How about adding `"corejs": 3` to the`@babel/preset-env` options? That should fix the issue, too.

**Comment by bastianhilton** [comment]
so i'm having issues with this on Nuxt and the solution i found was roll core-js back to 2.6.5 like someone said above. Once you change the version number to 2.6.5 in package.json then you just need to npm install and then run your program again and the error goes away.

**Comment by toddheslin** [comment]
I had the same issue as @bastianhilton with `nuxt-composition-api` failing.

Fixed with `npm i -D core-js@2.6.5`

**Comment by testacode** [comment]
I'm having this issue when using `useBuiltIns: 'usage'` I think it has something to do with webpack and babel transpilation. I have installed `core-js@3` and `regenerator-runtime` but this keeps breaking.

my config:
`
const baseConfig = {
  context: SRC_PATH,
  entry: INDEX_JS_PATH,
  resolve: {
    extensions: ['.js'],
    // Avoid duplicates (each module imports only once from app/node_modules)
    modules: [NODE_MODULES_PATH]
  },
  externals,
  output: {
    path: DIST_PATH,
    filename: path.join(parentPath, packageId, 'index.js'),
    chunkFilename: path.join(packageId, 'static', '[name].[chunkhash].js'),
    publicPath: '/',
    library: packageName || packageId,
    libraryTarget: 'umd'
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        include: [SRC_PATH],
        use: [
          {
            loader: require.resolve('babel-loader'),
            options: {
              presets: [
                [
                  require.resolve('@babel/preset-env'),
                  {
                    // https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md
                    useBuiltIns: 'usage',
                    corejs: {
                      version: '3.6',
                      proposals: true
                    },
                    targets: 'defaults',
                    debug: true
                  }
                ],
                [
                  require.resolve('@babel/preset-react'),
                  {
                    development: process.env.BABEL_ENV === 'development'
                  }
                ]
              ],
              plugins: [
                require.resolve('babel-plugin-styled-components'),
                require.resolve('@babel/plugin-proposal-class-properties')
              ]
            }
          }
        ]
      },
      {
        test: /\.css$/,
        use: [
          MiniCssExtractPlugin.loader,
          'css-loader'
        ]
      },
      {
        test: /\.(png|jpe?g|gif|woff|woff2|eot|ttf)$/,
        loader: 'url-loader'
      },
      {
        test: /\.svg$/,
        use: [
          require.resolve('@svgr/webpack'),
          {
            loader: require.resolve('url-loader'),
            options: {
              esModule: false
            }
          }
        ]
      }
    ]
  },
  plugins: [
    new MiniCssExtractPlugin({
      filename: 'index.css'
    }),
    new CleanWebpackPlugin()
  ]
};
`

**Comment by FA-toanlc** [comment]
Edit `babel.config.js` file:

```
module.exports = {
	presets: [
		['@vue/app', { useBuiltIns: "entry" }]
	],
	"env": {
		"development": {
			presets: [
				['@vue/app', { useBuiltIns: "entry", jsx: { injectH: false } }]
			]
		},
		"production": {
			presets: [
				['@vue/app', { useBuiltIns: "entry", jsx: { injectH: false } }]
			],
		  "plugins": ["transform-remove-console"]
		}
	}
}

```

**Comment by Domiii** [comment]
For me, it was some dependency bringing a deprecated version. You generally want to add `core-js@3` as an explicit dependency.

First step if you encounter this error: open `node_modules/core-js/package.json` and check you got the right version.

PS: I use VSCode. I usually do `code node_modules/core-js/package.json` to check package versions.

**Comment by ktrzos** [comment]
I'm still having this issue:

> Module not found: Error: Can't resolve 'core-js/modules/web.dom.iterable'

The interesting part is, that it occurs while having this in `.babelrc`:

```
["@babel/plugin-proposal-class-properties", { "loose": true }],
["@babel/plugin-proposal-private-methods", { "loose": true }]
```

When I'm removing `{ "loose": true }` from the 2nd one,

```
["@babel/plugin-proposal-class-properties", { "loose": true }],
["@babel/plugin-proposal-private-methods"]
```


I got only a warning

> Module build failed [...] 'loose' mode configuration must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled).

Using Storybook 6.1.0-beta.3.

**Comment by zloirock** [comment]
One more time: if you have this issue - you have an incorrect version of `core-js` in your `node_modules` or set an incorrect version of `core-js` in `@babel/preset-env` settings.
