### ISSUE TITLE
core-js-compat npm install fails

### ISSUE THREAD

**Issue by chandrutvl** [zloirock/core-js#504]
No matching version found for core-js@3.0.0

npm install core-js-compat

npm ERR! code ETARGET
npm ERR! notarget No matching version found for core-js@3.0.0

**Comment by nicolo-ribaudo** [comment]
Are you using an npm proxy?

**Comment by mlhkr** [comment]
Don't know if its related but couple of hours ago we start to get:
Cannot find "/client/shim.min.js" in core-js@3.0.0
https://unpkg.com/core-js@3.0.0/client/shim.min.js getting 404 here.

**Comment by zloirock** [comment]
@mlhkr it was removed from `core-js@3`. Instead of, use `core-js-bundle` package, https://unpkg.com/core-js-bundle@3.0.0/minified.js.
