### ISSUE TITLE
core-js@3.0.0/modules/es6.array.copy-within not found

### ISSUE THREAD

**Issue by luvluvxiu** [zloirock/core-js#506]
new core-js@3.0.0 in vue-cli3.0 version  incompatible. Just downgrade the version to 2.6.5. Version 3.0 prompts no ES6 or ES7 module.

**Comment by zloirock** [comment]
[It's renamed in `core-js@3`.](https://github.com/zloirock/core-js/blob/v3.0.0/packages/core-js/modules/es.array.copy-within.js) It's a major release and this implies breaking changes. If `vue-cli@3.0` incompatible with `core-js@3`, it should be fixed on `vue-cli` side.

**Comment by zloirock** [comment]
See [this explanation](https://github.com/parcel-bundler/parcel/issues/2819#issuecomment-475008861).

**Comment by dxc-jbeck** [comment]
This problem may also appear if using babel and explicitly adding core-js.  
Babel will already bring the node package in for core-js
We don't need core-js in our package.json

**Comment by zloirock** [comment]
@dxc-jbeck implicit dependencies sooner or later will cause problems, so it would be better to add the required core-js version to your package.json.
