### ISSUE TITLE
corejs was upgraded to 3.0.0，ES6 Modules are not supported

### ISSUE THREAD

**Issue by chenmychou** [zloirock/core-js#508]
My project worked well before.But today, when I reinstalled node_modules（with cnpm）, something went wrong. Preliminary checks were made because corejs was upgraded to 3.0.0 and vue-cli3 was upgraded with dependency packages.
![image](https://user-images.githubusercontent.com/15727736/54744479-12c42200-4c02-11e9-9a65-7175da0d4597.png)

**Comment by nicolo-ribaudo** [comment]
`./src/components/bubble/bubble.vue` imports `core-js@2`: you were probably lucky and it already was in your `node_modules` because some of your dependencies depended on it, but you should have explicitly listed it in your `package.json`.
