### ISSUE TITLE
Assignment instead of conditional expression

### ISSUE THREAD

**Issue by niftylettuce** [zloirock/core-js#509]
I noticed that in conditionals there are assignments and not expressions:

```sh
rg "then = isThenable" node_modules

node_modules/core-js/client/core.js
6685:          } else if (then = isThenable(result)) {
6752:    if (then = isThenable(value)) {

node_modules/core-js/client/library.js
5846:          } else if (then = isThenable(result)) {
5913:    if (then = isThenable(value)) {

node_modules/core-js/client/shim.js
6583:          } else if (then = isThenable(result)) {
6650:    if (then = isThenable(value)) {

node_modules/core-js/modules/es6.promise.js
83:          } else if (then = isThenable(result)) {
150:    if (then = isThenable(value)) {

node_modules/core-js-pure/modules/es.promise.js
105:          } else if (then = isThenable(result)) {
185:    var then = isThenable(value);

node_modules/core-js/library/modules/es6.promise.js
83:          } else if (then = isThenable(result)) {
```

**Comment by zloirock** [comment]
Thanks for the worry! However, in this line, It's expected. Since it's it `else if` condition, splitting it to some lines would complicate the code.

**Comment by niftylettuce** [comment]
This throws ESLint error for everyone with `eslint:recommended` standard defaults.  The entire JS community using ESLint that would lint anything compiled with `core-js` would get this error thrown:

```sh
  3575:22  error  Expected a conditional expression and instead saw an assignment  no-cond-assign
  3599:20  error  Expected a conditional expression and instead saw an assignment  no-cond-assign
  3619:16  error  Expected a conditional expression and instead saw an assignment  no-cond-assign
  3642:9   error  Expected a conditional expression and instead saw an assignment  no-cond-assign
  3846:14  error  Expected a conditional expression and instead saw an assignment  no-cond-assign
```

And then have to manually set `"no-cond-assign: "off"` in their config rules override.  I think complicating the code vs. making the entire community using ESLint to lint their builds (e.g. with [eslint-plugin-compat][]) would be the lesser of two evils.

[eslint-plugin-compat]: https://github.com/amilajack/eslint-plugin-compat

**Comment by niftylettuce** [comment]
See this comment here <https://github.com/airbnb/javascript/issues/1439#issuecomment-306378691> for why this is such bad practice.

**Comment by niftylettuce** [comment]
I've submitted a PR just now which fixes this issue, while only adding two lines of code.  The code is much easier to understand now as well through this and the community won't have to worry about this ESLint rule specific to this project's build.

https://github.com/zloirock/core-js/pull/510

**Comment by zloirock** [comment]
I'm not a fan of styles and the best part practices from `eslint:recommended` and `airbnb`. However, yes, this rule makes sense because at the past time `core-js` has been reworked for better readability.

**Comment by nicolo-ribaudo** [comment]
You shouldn't lint your dependencies, only your own code.
