### ISSUE TITLE
How do I use this in the browser?

### ISSUE THREAD

**Issue by DM2489** [zloirock/core-js#512]
I need to be able to use all `core-js` pollyfills in the browser, it seems that `@babel\polyfill` is deprecated in favour of `core-js/stable` and `regenerator-runtime/runtime`.

In `@babel\polyfill`, there was a `dist` with the compiled code, which I could take and bundle up with other packages. How can I do this now that there are no `dist` folders in these packages?

This was explicitly stated at https://babeljs.io/docs/en/next/babel-polyfill:

![image](https://user-images.githubusercontent.com/40390596/54825346-3a1ffb00-4ca5-11e9-9c1e-ca6efbeddd51.png)

Despite the article at https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md being very lengthy, I can't see a section or note on how we are supposed to run this in the browser anymore.

How are we supposed to do this now?

**Comment by nicolo-ribaudo** [comment]
You can use `core-js-bundle`: https://unpkg.com/core-js-bundle@3.0.0/

**Comment by nicolo-ribaudo** [comment]
You can use `core-js-bundle`: https://unpkg.com/core-js-bundle@3.0.0/

**Comment by DM2489** [comment]
@nicolo-ribaudo Excellent - thank you so much!
