### ISSUE TITLE
error in IE11 with "internals/well-known-symbol.js"

### ISSUE THREAD

**Issue by scrollbar-ww** [zloirock/core-js#513]
version: core-js@3.0.0

"internals/fix-regexp-well-known-symbol-logic.js":
line: 8
`var SPECIES = wellKnownSymbol('species')`
this "wellKnownSymbol" method got wrong.

"internals/well-known-symbol.js":
```
module.exports = function (name) {
  return store[name] || (store[name] = NATIVE_SYMBOL && Symbol[name]
    || (NATIVE_SYMBOL ? Symbol : uid)('Symbol.' + name));
};
```
there's no global Symbol, and "NATIVE_SYMBOL" is "true"

**Comment by scrollbar-ww** [comment]
upgrade to core-js@3.0.0， in my bundled js file，there're these "Symbol" stuff，but not exist @v2.6.5

more configuration files:
"babel.config.js":
```
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        modules: false,
        useBuiltIns: 'usage',
        corejs: 3
      }
    ]
  ]
}
```
".browserslistrc"
```
chrome >= 50
firefox >= 50
ie >= 10
```

**Comment by zloirock** [comment]
> there's no global Symbol, and "NATIVE_SYMBOL" is "true"

I have no ideas in which case it's possible - without global `Symbol`, `NATIVE_SYMBOL` can't be `true`. Could you add a simple reproducible example?

**Comment by somebody32** [comment]
Not sure if better is to open a new issue or piggyback on that one but I too have issues in IE11 trying to upgrade to core-js 3.

The error is `Exception thrown and not caught`, is caused by `internals/internal-state.js` line 26 because `!isObject(it)` returns true.

I've started with just plain `import "core-js/stable"` but managed to pin it down to `import "core-js/es/symbol"`.

Where should I look to provide more data about the issue? Thanks in advance!

**Comment by zloirock** [comment]
@somebody32 seems it's another issue. Could you open it and provide more data / a reproducible example?

**Comment by somebody32** [comment]
@zloirock thanks, done https://github.com/zloirock/core-js/issues/514

**Comment by zloirock** [comment]
BTW are you sure that `core-js` is not transpiled by `babel`? It could be one of the reasons for this issue.

**Comment by scrollbar-ww** [comment]
i am using rollup & rollp-plugin-babel plugin for bundling my project，here's the plugin args:

**Comment by alippai** [comment]
Rollup treeshakes the following:
```
// Chrome 38 Symbol has incorrect toString conversion
module.exports = !require('../internals/fails')(function () {
  // eslint-disable-next-line no-undef
  String(Symbol());
});
```
into:
```
// Chrome 38 Symbol has incorrect toString conversion
module.exports = !require('../internals/fails')(function () {
});
```
Which evaluates to `true`

**Comment by zloirock** [comment]
Interesting. Seems it's a `rollup` issue, could you create it in their repo? I can add a workaround to `core-js`.
