### ISSUE TITLE
[core-js-compat] Edge implementation of Number.toFixed()

### ISSUE THREAD

**Issue by frlinw** [zloirock/core-js#526]
Is there a major issue in edge implementation of Number.toFixed() ? I don't understand why it is polyfilled
https://github.com/zloirock/core-js/blob/19907822d054bc2b57d70cc5e6d510cac2fcdac5/packages/core-js-compat/src/data.js#L510-L514

**Comment by nicolo-ribaudo** [comment]
You can find the test used to determine those versions at https://github.com/zloirock/core-js/blob/master/tests/compat/tests.js
I don't have Edge, but you can check yourself if the conditions for `es.number.to-fixed` work there.

**Comment by frlinw** [comment]
Thank you !
