### ISSUE TITLE
[Question] client/core.js vs client/library.js vs client/shim.js

### ISSUE THREAD

**Issue by dwiyatci** [zloirock/core-js#528]
Hi! :)

In the built package, how are the three different? :thinking:

**Comment by zloirock** [comment]
It's related to `core-js@2`. `client/core.js` is a bundle of the full global version, with some non-standard features. `client/shim.js` is a bundle of the global version only with polyfills. `client/library.js` is a bundle of the version without global namespace pollution.

In `core-js@3` they were removed from the main package. The `core-js-bundle` package is an equal of `client/shim.js` from `core-js@2`.

**Comment by dwiyatci** [comment]
Ok, thank you. I just need a little more clarification on this:

> `client/shim.js` is a bundle of the global version only with polyfills.

Does this mean `client/shim.js` (`v2`) = `core-js/stable` (`v3`) + polyfills = `core-js-bundle` (`v3`)?

**Comment by zloirock** [comment]
Not exactly.

`client/shim.js` (`v2`) = `core-js` (`v3`) = `core-js-bundle` (`v3`)?

**Comment by dwiyatci** [comment]
Thank you, it's pretty much clear now. 👍
