### ISSUE TITLE
WeakSet es6 test failed: WeakSet.prototype isn't an instance

### ISSUE THREAD

**Issue by rzymek01** [zloirock/core-js#529]
Hello!
I'm interested whether someone else run into this problem as well.
In core-js@2.6.5 the following test is failing
http://kangax.github.io/compat-table/es6/#test-WeakSet_WeakSet.prototype_isn't_an_instance

According to the matrix it should work with babel-7 and core-js 2 and 3.

The test code:

```
new WeakSet();
var obj = {};
try {
  WeakSet.prototype.has(obj);
}
catch(e) {
  return true;
}
```

It should throw an error (sth like `TypeError: Method WeakSet.prototype.has called on incompatible receiver #<WeakSet>` and the same as `Set` is throwing).

I don’t know what’s the rationale behind this check and how relevant it is.

However, on IE11 with core-js loaded `Set` is throwing the exception while `WeakSet` is not. It returns `false` (I mean `WeakSet.prototype.has(obj) === false`).

To me it looks like a bug in core-js WeakSet polyfill.

Cheers!

**Comment by zloirock** [comment]
It was fixed in `core-js@3`, adding this fix `core-js@2` not planed since it's a serious change of the architecture. Feel free to add a PR to `compat-table` and mark this test as not passed for `core-js@2`.

**Comment by zloirock** [comment]
`core-js@3`:

![image](https://user-images.githubusercontent.com/2213682/55904708-b8afee80-5bfa-11e9-90a5-b640fb31a86a.png)

**Comment by rzymek01** [comment]
Thank you @zloirock for the quick response!

Cheers!
