### ISSUE TITLE
no files in core-js@3.0.1

### ISSUE THREAD

**Issue by miaulightouch** [zloirock/core-js#531]
I can't find any files in **node_modules/core-js/** folder when I update to 3.0.1, do I have to update my babel config or do something to fix it?

**Comment by nicolo-ribaudo** [comment]
Try deleting `node_modules` and rerunning `npm install`.

**Comment by miaulightouch** [comment]
hmmm, seems yarn got some problem with core-js@3, `npm install` works, thanks!
