### ISSUE TITLE
[Unhandled promise rejection: SyntaxError: JSON Parse error: Unexpected identifier "Phaza"]

### ISSUE THREAD

**Issue by olee2002** [zloirock/core-js#532]
[Unhandled promise rejection: SyntaxError: JSON Parse error: Unexpected identifier "Phaza"]
- node_modules/promise/setimmediate/core.js:37:14 in tryCallOne
- node_modules/promise/setimmediate/core.js:123:25 in <unknown>
- ... 8 more stack frames from framework internals

**Comment by zloirock** [comment]
Why do you think that it's a `core-js` issue?
