### ISSUE TITLE
Error :- when install the latest version@3.0.1 of core-js in angular 7

### ISSUE THREAD

**Issue by NikitaPooja** [zloirock/core-js#533]
When update the core-js latest version I got the following error in polyfills.ts file

ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/client/shim' in '/home/iron/Documents/latest gene update/gene/gene/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/array' in '/home/iron/Documents/latest gene update/gene/gene/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/date' in '/home/iron/Documents/latest gene update/gene/gene/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/function' in '/home/iron/Documents/latest gene update/gene/gene/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/map' in '/home/iron/Documents/latest gene update/gene/gene/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/math' in '/home/iron/Documents/latest gene update/gene/gene/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/number' in '/home/iron/Documents/latest gene update/gene/gene/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/object' in '/home/iron/Documents/latest gene update/gene/gene/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/parse-float' in '/home/iron/Documents/latest gene update/gene/gene/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/parse-int' in '/home/iron/Documents/latest gene update/gene/gene/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/reflect' in '/home/iron/Documents/latest gene update/gene/gene/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/regexp' in '/home/iron/Documents/latest gene update/gene/gene/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/set' in '/home/iron/Documents/latest gene update/gene/gene/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/string' in '/home/iron/Documents/latest gene update/gene/gene/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/symbol' in '/home/iron/Documents/latest gene update/gene/gene/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/weak-map' in '/home/iron/Documents/latest gene update/gene/gene/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es7/array' in '/home/iron/Documents/latest gene update/gene/gene/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es7/object' in '/home/iron/Documents/latest gene update/gene/gene/src'
ERROR in ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/jit-polyfills.js
Module not found: Error: Can't resolve 'core-js/es7/reflect' in '/home/iron/Documents/latest gene update/gene/gene/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es7/reflect' in '/home/iron/Documents/latest gene update/gene/gene/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/shim' in '/home/iron/Documents/latest gene update/gene/gene/src'

**Comment by zloirock** [comment]
CommonJS API was updated in `core-js@3`, so it's expected that old entry points do not work. See [this article](https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md).
