### ISSUE TITLE
Suggest adding non-enumerable properties support when implementing Object.assign under IE8

### ISSUE THREAD

**Issue by aleen42** [zloirock/core-js#541]
Under IE8, there are some non-enumerable properties like `toString`, which is actually not standard. However, the shim for `Object.assign` has not solved the problem for us, like what described [here](https://github.com/aleen42/PersonalWiki/issues/32#issuecomment-486556378), and I hope the source shim can do this for us.

**Comment by aleen42** [comment]
The solved code snippet is shown as followed:

```js
let fn = Object.assign;
Object.assign = function () {
    const [target, ...sources] = [].slice.call(arguments, 0);
    const result = fn.apply(this, [target, ...sources]);

    [
        'valueOf',
        'isPrototypeOf',
        'toString',
        'hasOwnProperty',
        'toLocaleString',
        'propertyIsEnumerable',
    ].forEach(property => {
        if (property === 'propertyIsEnumerable'
            || !({[property] : null}).propertyIsEnumerable(property)) {
            /** non-enumerable properties */
            sources.forEach(source => source
                                      && source.hasOwnProperty(property)
                                      && (result[property] = source[property]));
        }
    });

    return result;
};
```

**Comment by zloirock** [comment]
A workaround like this should be already used in enumerable keys related `core-js` features.

**Comment by aleen42** [comment]
Has that feature been already released?

**Comment by zloirock** [comment]
Yes. I'll test it a little later.

**Comment by aleen42** [comment]
Thanks for your responses.

**Comment by zloirock** [comment]
Looks like a bug. `Object.keys` works with those keys fine, but `Object.assign` not. But they should use the same way of getting enumerable keys internally.

**Comment by zloirock** [comment]
Seems the problem in one `propertyIsEnumerable` extra check.

**Comment by aleen42** [comment]
Check it and wait for upgrading.

**Comment by aleen42** [comment]
The problem is still existed with using @3.1.2

**Comment by zloirock** [comment]
@aleen42 your test case passed in 3.1.2, but I can confirm that 2.6.8 still has this problem.

**Comment by zloirock** [comment]
Nope, 2.6.8 also works fine, some problems with the cache in the testing platform.

**Comment by aleen42** [comment]
With using 2.6.8:

![image](https://user-images.githubusercontent.com/9573300/58446642-07c2cc00-8134-11e9-840c-d2778ce0c2bc.png)

**Comment by aleen42** [comment]
Are you sure you have run your test under IE8?

**Comment by zloirock** [comment]
@aleen42 
![image](https://user-images.githubusercontent.com/2213682/58448759-004ef300-8133-11e9-9558-d018ef90c24a.png)

**Comment by aleen42** [comment]
wired
