### ISSUE TITLE
is it possible to generate the polyfills for multiple bundles in one file?

### ISSUE THREAD

**Issue by enmanuelduran** [zloirock/core-js#547]
We are using core-js 3 to polyfill our bundles in a multi-page application but it is adding 400k+ extra to our final js folder. We were thinking if maybe there is a way to add all the polyfills required in a single file so the same polyfills are not repeated in our individual bundles. 

we are using these options:

```javascript
{
    useBuiltIns: 'usage',
    corejs: 3,
    targets: {
        ie: '11',
    },
}
```

and we pass our entries like objects:

```javascript
{
    chunkName: path,
    chunkName2: path2,
    ...
}
```

It is polyfilling all the bundles correctly but repeating the polyfills individually per bundle which is expected, we were wondering if there is maybe a way to move all polyfills to a single file (polyfills.js) to avoid repetitions?

**Comment by zloirock** [comment]
In your case could be better to use `useBuiltIns: 'entry'` and load required parts of `core-js` to a separate bundle.

**Comment by enmanuelduran** [comment]
This would have to be a manual process right? I mean I would have to manually add the polyfills into a polyfills file?

**Comment by zloirock** [comment]
It's manual adding of `core-js` entries. Even if you add just `core-js/stable` and apply `useBuiltIns: 'entry'` for optimization for the target engines it will be much better than current 400k+. You can optimize it if you know which features can be used in your project and instead of `core-js/stable` to use more granular entry points.

**Comment by zloirock** [comment]
Your initial question about a kind of the second point from [this](https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#better-optimization-of-polyfill-loading), but at this moment we have no tool for it.
