### ISSUE TITLE
Symbol exception in IE11 again @ 3.1.0

### ISSUE THREAD

**Issue by scrollbar-ww** [zloirock/core-js#550]
i use rollup + babel@7 + core-js for bundling my web app,
after update core-js from 3.0.1 to 3.1.0, i got a new symbol exception .

@ core-js/packages/core-js/modules/es.symbol.js :
```
$export({ target: 'Object', stat: true, forced: fails(function () { getOwnPropertySymbolsModule.f(1); }) }, {
  getOwnPropertySymbols: function getOwnPropertySymbols(it) {
    return getOwnPropertySymbolsModule.f(toObject(it));
  }
});
```
"getOwnPropertySymbolsModule" equals undefined, which import from:
`var getOwnPropertySymbolsModule = require('../internals/object-get-own-property-symbols');`

there was a similar exception with 3.0.0, but fixed in 3.0.1.
[https://github.com/zloirock/core-js/issues/513](url)

**Comment by zloirock** [comment]
How it could be equals `undefined`? `object-get-own-property-symbols` exports an object.

Please, provide more info or a reproducible example.

**Comment by scrollbar-ww** [comment]
sorry, it's "getOwnPropertySymbolsModule.f" equals undefined, in IE 11

**Comment by zloirock** [comment]
I have no ideas in which case it's possible. Seems a new kind of strange `rollup` optimizations. In which engine you have this problem? Maybe you could create a reproducible example?

**Comment by scrollbar-ww** [comment]
sorry again, it caused by another package, that try to implement window.Symbol, but not completely.
it makes "NATIVE_SYMBOL" equals true, without "getOwnPropertySymbols" method.
but the strange thing is, it's ok with core-js 3.0.1

**Comment by zloirock** [comment]
I'll add an additional check for `NATIVE_SYMBOL`, thanks.

**Comment by zloirock** [comment]
Added.

**Comment by PikachuEXE** [comment]
In case people don't know
The fix is committed in https://github.com/zloirock/core-js/commit/08d2f566558f7fdc30f4fed0cc39abb19bbb8e9a
