### ISSUE TITLE
Suggestion: Add a short description to the top of the README.

### ISSUE THREAD

**Issue by sbrl** [zloirock/core-js#552]
Many people like myself will visit this repository out of curiosity after an `npm install`, where you don't actually directly install it, but it's required as dependency of another package you've installed.

I propose that a short description of what this package is and what it does (say, no more than ~4-5 sentences) is added to the top of the README, because as of now I'm rather confused (and the repo description of "standard library" is _singularly unhelpful_ - sorry!)/

**Comment by zloirock** [comment]
It's under `raising funds` section. Maybe makes sense to move it a little higher. Feel free to propose a PR.
