### ISSUE TITLE
postinstall not found issue during npm install

### ISSUE THREAD

**Issue by scalebig** [zloirock/core-js#557]
![image](https://user-images.githubusercontent.com/6069355/58124165-2c1e2600-7bd3-11e9-864e-b742ecb9ca7d.png)

dependency of `sequelize-cli` version: 4.0.0
node version: 10.15.3
npm version: 6.4.1

this happens while sequelize-cli is npm installing in our alpine container build via Google Container Builder. This build has worked repeated until today :(

**Comment by zloirock** [comment]
Seems a duplicate of #551

**Comment by scalebig** [comment]
Sorry about that!
