### ISSUE TITLE
Broken OpenCollective links in README

### ISSUE THREAD

**Issue by c0bra** [zloirock/core-js#560]
Not an issue but wanted the author to be aware. These links result in a Heroku error page right now:

![image](https://user-images.githubusercontent.com/105007/58257694-fb570180-7d36-11e9-8dda-2f927aeaad23.png)

**Comment by zloirock** [comment]
Thanks. The problem only with the cap / the second link which should redirect to Open Collective page. Seems it's an Open Collective issue since they [propose](https://github.com/zloirock/core-js/pull/520/files) the same structure sponsors section with the same links.

**Comment by zloirock** [comment]
Now it works, but pictures do not load periodically. Seems a problem with Open Collective servers.
