### ISSUE TITLE
 Cannot read property 'android' of undefined

### ISSUE THREAD

**Issue by yusidi** [zloirock/core-js#561]
config:
![image](https://user-images.githubusercontent.com/21719674/58317035-90e1b680-7e47-11e9-8cfc-c6fb31008c0e.png)

throw error:
 Cannot read property 'android' of undefined

**Comment by nicolo-ribaudo** [comment]
What is the full stack trace? It doesn't seem caused by core-js. It's probably a bug in Babel, browserlist or in the Vue preset.

**Comment by yusidi** [comment]
thank you

**Comment by Evertt** [comment]
@yusidi what was it? I need this right now
