### ISSUE TITLE
Blob is not working in IE11. Getting array.prototpe.tostring() this is null or undefined in PDFMAKE

### ISSUE THREAD

**Issue by sureshrathod1531** [zloirock/core-js#563]
Blob is not working in IE11. Getting array.prototpe.tostring() this is null or undefined
IE version : IE 11
Pdfmake version : 0.1.36
Mathod where getting error : pdfmake.createpdf(this.docDefination).getblob(blob =>{
})

**Comment by zloirock** [comment]
`Blob` is out of scope `core-js`. `core-js` provide only polyfills for ECMAScript features and closely related cross-platform features from web standards.  However, [in the future, this position can be changed](https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#extended-web-standards-support).
