### ISSUE TITLE
Cannot convert object to primitive value with core-js 3.1.3 + webpack

### ISSUE THREAD

**Issue by PikachuEXE** [zloirock/core-js#566]
### Env
- webpack `4.32.2`
- babel-loader `8.0.6`
- core-js `3.1.3`

Not sure what else should be added
Will update this list if more entries are needed

### Description
I already applied patch from https://github.com/rails/webpacker/pull/2031 to fix #514
But now I got this error
Below are screenshots to the backtrace

![1](https://user-images.githubusercontent.com/1018543/58447357-af40fe00-8136-11e9-8a9f-ae52e51467e2.png)
![2](https://user-images.githubusercontent.com/1018543/58447358-af40fe00-8136-11e9-9598-effa07085da1.png)
![3](https://user-images.githubusercontent.com/1018543/58447359-afd99480-8136-11e9-84b6-9e638e088cb7.png)
![4](https://user-images.githubusercontent.com/1018543/58447360-afd99480-8136-11e9-8c6a-220f29728ec1.png)

**Comment by jacobp100** [comment]
I've narrowed it down to this statement being broken,

```js
$defineProperty({}, Symbol.toStringTag, { value: 'test' })
```

As you can see in the above code, webpack seems to add this to every harmony module

**Comment by zloirock** [comment]
In which engine? Could you add a reproducible example?

**Comment by jacobp100** [comment]
IE11. If you run my exact example in IE11, it throws an exception

**Comment by zloirock** [comment]
@jacobp100 you really think that this example is not tested and still no one run `webpack` + `babel-loader` + `core-js@3` where it will be added in modules by default? Seems the problem **how** it's used - configs, possible conflicts with other polyfills, etc.

**Comment by PikachuEXE** [comment]
I can see the backtrace as:
#### 1. Webpack require => Define property with `defineProperty` on `Symbol.toStringTag`
```js
// define __esModule on exports
__webpack_require__.r = function(exports) {
	if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
		Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
	}
	Object.defineProperty(exports, '__esModule', { value: true });
};
````

#### 2. Calling core-js symbol polyfill of `defineProperty` in `core-js/modules/es.symbol.js`
Key statement is `key = toPrimitive(key, true)`
```js
var $defineProperty = function defineProperty(it, key, D) {
  if (it === ObjectPrototype) $defineProperty(ObjectPrototypeSymbols, key, D);
  anObject(it);
  key = toPrimitive(key, true);
  anObject(D);
  if (has(AllSymbols, key)) {
    if (!D.enumerable) {
      if (!has(it, HIDDEN)) nativeDefineProperty(it, HIDDEN, createPropertyDescriptor(1, {}));
      it[HIDDEN][key] = true;
    } else {
      if (has(it, HIDDEN) && it[HIDDEN][key]) it[HIDDEN][key] = false;
      D = nativeObjectCreate(D, { enumerable: createPropertyDescriptor(0, false) });
    } return setSymbolDescriptor(it, key, D);
  } return nativeDefineProperty(it, key, D);
};
```

#### 3. Calling `toPrimitive` in `core-js/internals/to-primitive.js`
```js
var isObject = require('../internals/is-object');

// 7.1.1 ToPrimitive(input [, PreferredType])
// instead of the ES6 spec version, we didn't implement @@toPrimitive case
// and the second argument - flag - preferred type is a string
module.exports = function (it, S) {
  if (!isObject(it)) return it;
  var fn, val;
  if (S && typeof (fn = it.toString) == 'function' && !isObject(val = fn.call(it))) return val;
  if (typeof (fn = it.valueOf) == 'function' && !isObject(val = fn.call(it))) return val;
  if (!S && typeof (fn = it.toString) == 'function' && !isObject(val = fn.call(it))) return val;
  throw TypeError("Can't convert object to primitive value");
};
```

That means value referenced by `Symbol.toStringTag` is incompatible with `ToPrimitive`


Here is a bit of console debugging in IE 11:
![1](https://user-images.githubusercontent.com/1018543/58526112-8ab15880-8200-11e9-994c-5330c88f1a27.png)
![2](https://user-images.githubusercontent.com/1018543/58526113-8ab15880-8200-11e9-89ee-e4dd9db63a09.png)
![3](https://user-images.githubusercontent.com/1018543/58526114-8ab15880-8200-11e9-8963-7958c2d70f2e.png)
![4](https://user-images.githubusercontent.com/1018543/58526115-8b49ef00-8200-11e9-9b85-e1881df117f2.png)



If I remove `import "core-js/modules/es.symbol"` the error is gone
But I have no idea what else will be broken

**Comment by PikachuEXE** [comment]
It seems that `jscomp_symbol_xxxx` (the polyfill) is from Google Maps JS file
https://maps.googleapis.com/maps/api/js?v=3&libraries=places

Loading it after the file containing `core-js` symbol polyfill would solve this issue

**Comment by jacobp100** [comment]
Thanks @PikachuEXE - we had exactly the same issue with Google Maps, and managed to fix it with your solution 😀

**Comment by Cobertos** [comment]
This also seems to be an issue with Google's Recaptcha API. Removing it from the project or making it load after your packed bundle fixes IE11. The file in question that I had to move was `//www.google.com/recaptcha/api.js?h1=en&amp;render=explicit`.

The specific IE11 error I was getting was:

`SCRIPT5005: String expected` in the [`regenerator-runtime`](https://github.com/facebook/regenerator/blob/master/packages/regenerator-runtime/README.md) library that seems to extend from this Symbol polyfill conflict.

![image](https://user-images.githubusercontent.com/6759176/61804184-7a34ed00-ae01-11e9-9934-2776f5adfda0.png)

Kind of annoying...

**Comment by firestar300** [comment]
@Cobertos Did you find a fix ?

**Comment by Cobertos** [comment]
@firestar300 Yeah, you have to make sure recaptcha loads after any other script that messes with `Symbol`, including polyfills or webpacked bundles. Moving it to just before the end of the `<body>` tag fixed it for our apps.

**Comment by firestar300** [comment]
Thanks :)

**Comment by greatwitenorth** [comment]
I'm having the exact same issue as @PikachuEXE. Same stack trace and everything, but I'm not using Google maps or recaptcha on my page. Any other ideas as to why this error might be happening in ie11?

**Comment by erictonussi** [comment]
I reverted to core-js 2.5.7 and all the module.export errors stopped displaying.

**Comment by judygab** [comment]
> It seems that `jscomp_symbol_xxxx` (the polyfill) is from Google Maps JS file
> https://maps.googleapis.com/maps/api/js?v=3&libraries=places
> 
> Loading it after the file containing `core-js` symbol polyfill would solve this issue

@PikachuEXE what do you mean by file containing core-js symbol polyfil?

**Comment by PikachuEXE** [comment]
Any file that import `core-js/features/symbol` or other polyfill requiring that module
@judygab
