### ISSUE TITLE
Unicode property escapes support

### ISSUE THREAD

**Issue by flcl42** [zloirock/core-js#569]
Do you have some plans to support 
https://github.com/tc39/proposal-regexp-unicode-property-escapes either accept contributions?

Firefox and Edge fail to handle such things like: 

`/\p{Alphabetic}/u.test('Ж')`

**Comment by nicolo-ribaudo** [comment]
core-js can't handle new syntax (e.g. new regular expression escapes), you'll need Babel for that.

**Comment by zloirock** [comment]
`core-js` can handle this syntax in `RegExp` constructor like `RegExp('\p{Alphabetic}', 'u').test('Ж')`, but if I understood the situation correctly, it's too costly - it requires adding to the library big part information from Unicode standard - dozens of kilobytes, so I'm not sure that it's worth it.

**Comment by flcl42** [comment]
May it be made like some optional package that need expicit mention to be included and loaded? I can help with importing it from existing babel polyfills.

**Comment by zloirock** [comment]
Yes, we could make it as an optional module. Feel free to add a PR.
