### ISSUE TITLE
Understanding the ES6 Promise polyfill

### ISSUE THREAD

**Issue by l-easwar-akiyama** [zloirock/core-js#570]
I wanted to know more about the factors that `core-js-compat` takes into account before deciding to add a polyfill for a browser. I had gone through similar issues such as #480 but couldn't find a clear answer.

For example according to MDN and caniuse, `ES6 Promise` support had arrived for most browsers since couple of years. But even for the latest Firefox (67), `es6.promise` is shown as required by `core-js-compat`.

Could you please explain if this is due to incorrect vendor implementation or is some major Promise API not working  as expected.

**Comment by zloirock** [comment]
The source code of the feature detection [contains enough comments](https://github.com/zloirock/core-js/blob/6e3106817aa46919273b80d6f961e75a65967d22/packages/core-js/modules/es.promise.js#L52-L68).

Modern FF does not support [unhandled rejection tracking](https://developer.mozilla.org/en-US/docs/Web/API/PromiseRejectionEvent).
