### ISSUE TITLE
Replace advertising in npm postinstall message with real advertisement

### ISSUE THREAD

**Issue by rontap** [zloirock/core-js#571]
This package is quite popular, and if you are so desperate to get money _and_ keep the package free _and_ bother literally thousands with 15 lines of messages, then why not go all the way and introduce actual advertisements, i am sure there exists a package for that, that could pull google adverts directly to the command line. Untapped market i say.

**Comment by zloirock** [comment]
Perfect idea. But we can go further - advertising in the browser console, loading google adverts to sites which use `core-js` and cryptominer in the code of the library 💯

**Comment by Arcanemagus** [comment]
As tongue-in-cheek as the original post is here, can you imagine if _every_ package started spamming users with messages like this? Just on the installation that I first saw this on that would amount to over 1 MiB of text plastered on the screen begging for donations... a situation hardly anyone would consider acceptable.

I'd imagine that's exactly why NPM put this in their [Acceptable Use](https://www.npmjs.com/policies/open-source-terms#acceptable-use) policy:
> 8. You will not send advertisements, chain letters, or other solicitations via npm Services.

**Comment by zloirock** [comment]
@Arcanemagus sorry, your message is offtopic, you could write it in #548. It's the thread about replacing the `postinstall` message with a real advertisement.

**Comment by revelt** [comment]
But guys, this package is not a spacial snowflake, there are many open source packages and if everybody starts to put advertisements it will be impossible to work.

@zloirock I think you should remove the terminal advertisement messages because it makes you look desperate. Readme already contains enough info for supporters.

Mind you, at any time any open source package can be forked and ads can be removed this way. I'm not threatening, just saying.

**Comment by tristanleboss** [comment]
@revelt Forking is one thing, maintaining is another ;)

**Comment by zloirock** [comment]
@revelt please, don't say me what I should do -) Feel free to fork and maintain it - I will only be glad that `core-js` maintenance now it's not my problem. Also, one more time, it's not a correct place for comments like this, if you wanna write it - please, write it in #548.

**Comment by zloirock** [comment]
Closed for preventing spam.
