### ISSUE TITLE
SVGElement.contains support for IE9+

### ISSUE THREAD

**Issue by Catchwa** [zloirock/core-js#572]
IE9+ supports Node.contains, but not for SVGElement nodes, per https://developer.mozilla.org/en-US/docs/Web/API/Node

See issues from other projects:
https://github.com/FezVrasta/popper.js/issues/515
https://github.com/react-bootstrap/dom-helpers/issues/11

Would you be open to a PR for this? I'm asking first because I can't see any other SVG-related polyfills (although maybe I was looking in the wrong place).

Thanks.

**Comment by zloirock** [comment]
`SVGElement.contains` is out of scope `core-js`. `core-js` provide only polyfills for ECMAScript features and closely related cross-platform features from web standards.  However, [in the future, this position can be changed](https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#extended-web-standards-support).
