### ISSUE TITLE
Supporting core-js spam

### ISSUE THREAD

**Issue by liudas-stonys** [zloirock/core-js#574]
Can you stop, please?
![support the spammers](https://user-images.githubusercontent.com/38351121/59388697-200e2a00-8d75-11e9-81d2-786beabd146d.png)

**Comment by liudas-stonys** [comment]
It's just the first page...

**Comment by zloirock** [comment]
No.

**Comment by jdegger** [comment]
Completely agree this is spam and should not be in the package
