### ISSUE TITLE
TypeError: Invalid calling object in es.promise in IE 11

### ISSUE THREAD

**Issue by Splurov** [zloirock/core-js#578]
After updating from babel-polyfill 6.26 to core-js 3.1.3 I'm getting exceptions like this in Sentry (js error tracking system) in IE 11 on Windows and Windows Mobile:

```
TypeError: Invalid calling object
  at result(./node_modules/core-js/modules/es.promise.js:103:0)
  at run(./node_modules/core-js/modules/es.promise.js:120:0)
  at fn(./node_modules/core-js/internals/microtask.js:26:0)
```
https://github.com/zloirock/core-js/blob/v3.1.3/packages/core-js/modules/es.promise.js#L103
https://github.com/zloirock/core-js/blob/v3.1.3/packages/core-js/modules/es.promise.js#L120
https://github.com/zloirock/core-js/blob/v3.1.3/packages/core-js/internals/microtask.js#L26

Any idea what cause it?

Unfortunately I can not reproduce it by myself or write reproducible example so I can only guess for reason behind this error.

**Comment by zloirock** [comment]
As you can see, it's it `try / catch` block, so I have no ideas about how it can come to Sentry.

**Comment by Splurov** [comment]
Ok, thank you for paying attention. Since there are no ideas I close the issue.

**Comment by edwh** [comment]
I've also seen this reported in Sentry.  I can't repro it myself either, but it's happened for 88 of my site's users so far.  Sometimes it's IE11, often Windows 7, but mobile Safari 9 sees it too.

It's weird, isn't it?  The code is clearly inside a try...catch and so the error should be caught.  

But it does clearly happen.  Would it be possible to put an if test in that achieves the same effect as the catch?  I know that shouldn't be necessary, but we are in the business of supporting weird browsers, after all...
