### ISSUE TITLE
Test error after upgrading to corejs 3

### ISSUE THREAD

**Issue by mohsinulhaq** [zloirock/core-js#583]
After using `{corejs: 3}` option for both `@babel/preset-env` and `@babel/plugin-transform-runtime`, and using `@babel/runtime-corejs3`, my tests are failing with the following error:
```
/node_modules/core-js-pure/internals/well-known-symbol.js:10
  return store[name] || (store[name] = NATIVE_SYMBOL && Symbol[name]
                                                              ^
TypeError: Cannot read property 'iterator' of undefined
```

**Comment by zloirock** [comment]
> After using `{corejs: 3}` option for both `@babel/preset-env` and `@babel/plugin-transform-runtime`...

You should you `corejs: 3` in `@babel/preset-env` **OR** in `@babel/plugin-transform-runtime`, but not together.

**Comment by mohsinulhaq** [comment]
I am using the `useBuiltins: 'usage'` option for `@babel/preset-env`, so I get this warning if I remove `corejs: 3` from options:
```

**Comment by zloirock** [comment]
Ok, let say in other words: you should use `useBuiltIns` option of `preset-env` **OR** `corejs` option of `runtime`, but not together.

**Comment by mohsinulhaq** [comment]
https://github.com/babel/babel/issues/10121#issuecomment-505002153
yeah I just found that out :)

But even after this, I get the exact same error.

**Comment by zloirock** [comment]
I hope that you don't transform `core-js` in your `node_modules`?

**Comment by mohsinulhaq** [comment]
No, I don't think so.

**Comment by mohsinulhaq** [comment]
Scrolling down, I see another error:
```
/node_modules/@babel/core/lib/config/files/configuration.js:206
    throw err;
    ^

TypeError: /.babelrc.js: Error while loading config - Cannot read property 'species' of undefined
    at module.exports (/node_modules/core-js-pure/internals/well-known-symbol.js:10:63)
```

**Comment by zloirock** [comment]
Seems it's a similar error.

Take a look at [`well-known-symbol.js`](https://github.com/zloirock/core-js/blob/v3.1.4/packages/core-js/internals/well-known-symbol.js) code. `NATIVE_SYMBOL && Symbol[name]` will be executed only when `NATIVE_SYMBOL` is `true`. [`NATIVE_SYMBOL` will be `true` only when `Symbol` is a `function`](https://github.com/zloirock/core-js/blob/63b0b4468aab272e2cca8ceee23a5d3d81943e9d/packages/core-js/internals/native-symbol.js). So this error is possible only if this code is changed (most likely by transpiler) or someone directly removed global `Symbol` before some parts of `core-js` will be executed.

**Comment by mohsinulhaq** [comment]
I will check what is causing this, but I have a question. The environment where these tests are being run is Node 10.14.1, where Symbol is natively supported. Why is Symbol not available here? Why am I encountering the polyfill of Symbol?

**Comment by zloirock** [comment]
It should not be polyfilled, just wrapped in you uses a version without global pollution.

**Comment by mohsinulhaq** [comment]
Yeah, so when it calls `Symbol[name]`, the `Symbol` should be the one in the node environment, right? In which case can this turn up `undefined`?

**Comment by zloirock** [comment]
See [this comment](https://github.com/zloirock/core-js/issues/583#issuecomment-505362577), this is exactly the answer to your question.

**Comment by mohsinulhaq** [comment]
Hi, just putting it there if it helps:
![image](https://user-images.githubusercontent.com/7688231/60154503-208ed200-9805-11e9-814e-61e93dce1585.png)
While debugging, I found that `Symbol` from closure is `undefined` at this time, but `global.Symbol` is not. Does that tell you anything?

**Comment by mohsinulhaq** [comment]
When I replace `Symbol` with `global.Symbol`, and then apply breakpoint, I find that `global.Symbol` is undefined, while `Symbol` from closure is not. 🤷‍♂

**Comment by mohsinulhaq** [comment]
![image](https://user-images.githubusercontent.com/7688231/60154909-6ac48300-9806-11e9-8070-e5c07db641c2.png)
In another case where I try to use `Symbol || global.Symbol`, both are `undefined`

**Comment by mohsinulhaq** [comment]
Could you please tell me how to debug this issue. I mean where do I start looking? I am stuck 😢

**Comment by zloirock** [comment]
Looks like `core-js` code is transpiled. Could you check it in your configs, in the bundle?

**Comment by mohsinulhaq** [comment]
That's the thing, my build is working fine.
But when I run mocha test, which I do by loading @babel/register before running tests, I get this error. As such I don't have any bundle to check.

**Comment by mohsinulhaq** [comment]
It seems that the error was due to me doing `window.Math = Math` in the mocha entry file to work around this issue in jsdom with RxJS:

https://github.com/ReactiveX/rxjs/issues/2651#issuecomment-338648013

Removing this line fixed the issue, however I wonder how could it wipe out global Symbol? 🤔

**Comment by zloirock** [comment]
Interesting. So, seems you use mocked `window` and, because of `window.Math === Math`, it passes current [global object detection](https://github.com/zloirock/core-js/blob/v3.1.4/packages/core-js/internals/global.js). But it's not a real global object, so you try to use `core-js` in a broken environment. You should use `core-js` before that. Seems the issue resolved.

**Comment by mohsinulhaq** [comment]
Yes it is, thanks!

**Comment by mohsinulhaq** [comment]
https://github.com/babel/babel/issues/10133
I have a query regarding corejs and babel. Could you please help me there as well.
Thanks! 😄

**Comment by zloirock** [comment]
@nicolo-ribaudo already answered to this question.
