### ISSUE TITLE
IE11 Vue build

### ISSUE THREAD

**Issue by cliffordh** [zloirock/core-js#586]
Thankfully found core-js. The Vue docs and other websites still mention @babel/polyfill as the recommended solution for polyfills. I created a project with Vue CLI 3 and have made the following changes:

NPM
`npm install --save core-js@3.0.1
`

```
//babel.config.js
module.exports = {
plugins: ['@babel/plugin-syntax-dynamic-import'],
presets: [
            ['@babel/preset-env', {
                targets: {
                    ie: '11',
                    browsers: 'last 2 versions',
                },
                useBuiltIns: 'usage',
                corejs: { version: 3, proposals: true },
            }],
        ]
}
```
Also my main.js (entry) has the following imports:
```
import "core-js/fn/array/entries";
import "core-js/fn/array/includes";
import "core-js/fn/array/find";
import "core-js/fn/array/from";
import "core-js/es6/promise";
import "core-js/fn/object/assign";
import "core-js/es6/symbol";
import "whatwg-fetch";
```
Is there a better way of specifying the missing polyfills? Also, is there a way that the polyfills are only  included in my Vue build for the legacy browsers? I am building my Vue project with the following:

`vue-cli-service build --modern`

But it results in practically the same size bundle for legacy and modern.

Any help would be appreciated.

**Comment by ustun** [comment]
I'm not sure what best practice is, but you can get polyfill data via something like 

`const allPolyfills = Object.keys(
  require('@babel/preset-env/data/built-ins.json')
)
` and then iterate over those to filter required polyfills.

**Comment by zloirock** [comment]
@ustun I definitely don't recommend to do something like that. `@babel/preset-env/data/built-ins.json` is not a public API. It contains data for obsolete `core-js@2` and data about the support of features generated from `compat-table`. `core-js-compat` contains correct data for `core-js@3` if it's required for any case. However, iteration on polyfills list is not required in almost all cases.

**Comment by zloirock** [comment]
@cliffordh

> `core-js@3.0.1`
> `corejs: { version: 3, proposals: true }`
> ...
> `import "core-js/fn/array/entries";`
> `import "core-js/fn/array/includes";`
> `import "core-js/fn/array/find";`
> `import "core-js/fn/array/from";`
> `import "core-js/es6/promise";`
> `import "core-js/fn/object/assign";`
> `import "core-js/es6/symbol";`

`/fn/` and `/es6/` entry points will not work in `core-js@3`, they are replaced to `/features/` and `/es/` respectively.

If you use `useBuiltIns: 'usage'` and does not transpile, the definition of polyfills which can be used in your dependencies in the correct strategy of polyfilling. However, for big projects I recommend to use `useBuiltIns: 'entry'`.

> `vue-cli-service build --modern`

I don't know what is it and how it works.

**Comment by ustun** [comment]
Thank you for the info @zloirock 

We are currently on v2 as that is what nuxt recommends for the time being for some reason, but I'll that in mind when we upgrade to v3.

Thank you for your efforts.
