### ISSUE TITLE
core-js causing infinite loop (probably PEBKAC?)

### ISSUE THREAD

**Issue by jschill** [zloirock/core-js#587]
I have a problem in my code causing an infinite refresh loop.

`var location = global_1.location;`

This line is from: https://github.com/zloirock/core-js/blob/6e3106817aa46919273b80d6f961e75a65967d22/packages/core-js/internals/task.js#L8

I'm bundling with rollup (and rollup-plugin-babel).

My file being bundled is empty except for the core-js import and a console.log:

```
import 'core-js/stable';
console.log('hello');
```

Anyone who knows what I'm missing here?

**Comment by zloirock** [comment]
Could you show your config?

**Comment by jschill** [comment]
@zloirock Sure.

```
var config = {
  input: 'static/static/js/app.js',
  output: {
    file: 'dist/static/js/app-bundle.js',
    format: 'cjs'
  },
  plugins: [
    commonjs({
      include: /(node_modules)/
    }),
    nodeResolve({
      mainFields: ['jsnext', 'module', 'main']
    }),
    inject({
      $: 'jquery',
      jQuery: 'jquery'
    }),
    babel({
      exclude: 'node_modules/**',
      sourceMap: true,
      presets: [
        ["@babel/preset-env", {
          targets: {
            chrome: 59,
            edge: 13,
            firefox: 50,
            ie: 11,
          },
          forceAllTransforms: true,
          useBuiltIns: 'entry',
          corejs: 3
        }],
      ],
      plugins: ["transform-es2015-for-of"],
      compact: false,
    })
  ]
};
```

**Comment by jschill** [comment]
Changing `useBuiltIns` to `usage` and removing the core-js import kind of fixed the problem, but I don't understand why it's not possible to use the `import 'core-js/stable';`

**Comment by nicolo-ribaudo** [comment]
This can be easily reproduced: if you write `var location = "foo";` in the console, it will redirect to `/foo`. Renaming that variable would be a sufficient fix.

The real problem is that core-js files are CommonJS modules: Rollup shouldn't run them in the global scope; or at least it should rename any variable conflicting with global builtins.

**Comment by zloirock** [comment]
Seems it's an issue of `rollup`, not `core-js`.

**Comment by lukastaegert** [comment]
You should not use `cjs` as output format if you intend to run your bundle directly in the browser. The `iife` and `umd` formats were designed for that and will also prevent this issue from happening as they put your code into a function scope. Alternatively, using `es` and putting it into a script tag with `type: "module"` will also work and prevent this issue as `var` does not declare global variables in ES modules.
