### ISSUE TITLE
es.string.includes in IE is forced

### ISSUE THREAD

**Issue by truebden** [zloirock/core-js#588]
I have a webpage, which already contains a polyfill for String.includes. This polyfill is defined with Object.defineProperty with the flags for configurable and writeable to false (default is false).

```javascript
if (!String.prototype.includes) {
    Object.defineProperty(String.prototype, 'includes', {
        value: function (search, start) {
            if (typeof start !== 'number') {
                start = 0
            }

            if (start + search.length > this.length) {
                return false
            } else {
                return this.indexOf(search, start) !== -1
            }
        }
    })
}
```

Additional I included my own library which uses core-js (through babel) and therefor tries to apply the polyfill again. This does not work as the property can not be redefined.
Should the polyfill from core-js not also check if the function already exists like the example above?
Currently there is only some check with `correctIsRegExpLogic` which I do not really understand.

The polyfill on mdn checks also if it is already present: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes#Polyfill

Thanks for your help!

**Comment by zloirock** [comment]
`core-js` works here as expected. In `core-js`, `es.string.includes` contains detection of correct internal `IsRegExp` logic which fails in this "polyfill", so `core-js` should redefine this method. But this method in this "polyfill" is incorrectly defined as non-writable and non-configurable, so `core-js` can't redefine it.

`core-js` can't work in broken environments. So it's an issue for this "polyfill" (however, I can't call it a real polyfill since it's too incorrect), but not for `core-js`.

**Comment by truebden** [comment]
@zloirock can you explain me whath the isReqExp logic does?

For me the environment is not "broken" (depends a little on the explanation you can give me for the above) as it defines the includes method.
If this method is already defined and works as it should, I would not see, why core-js should try to redefine it as all?

**Comment by zloirock** [comment]
The environment is broken since this method does not work as should by the spec. `IsRegExp` for this method means that it should not allow regex (or something regex-like) as the first argument of this method. And, sure, this method should have a correct descriptor.

**Comment by truebden** [comment]
But the implementation of this polyfill is the one from MDN except that it is defined with defineProperty.
So every page which would use the polyfill from MDN with defineProperty would be a broken environment...

I see your point about the specification, but I am not so sure, if this is a good approach.
The main problem I see is, if you are a thirdparty library provider (like it is the case for me) and the lib will be integrated into a webpage. If this page has the polyfill as above, it will simply not work. Very often it is then not possibe to change the webpage.
Probably there could be some mode where you can say, that if a function already exists, but it does not match the specification, you can still use it. So no override would happen. In this case, there would be a big warning, that you do this on your own risk.
Maybe you have better approach?

**Comment by nicolo-ribaudo** [comment]
If you are a third-party library, you shouldn't define global polyfills in the first place. Even if it is a "good" polyfill, your library used doesn't expect it.
I suggest two options:
1. Do not add any polyfill, and specify that your library needs feature X, Y and Z to work. If someone wants to use your library in an older environment, they should load the polyfills theirselves.
2. Use a "shim": a polyfill which doesn't attach itself to the global environment. You can check `@babel/plugin-transform-runtime` (_instead of_ `useBuiltIns`) or `core-js-pure`.

**Comment by zloirock** [comment]
@truebden 
> But the implementation of this polyfill is the one from MDN except that it is defined with defineProperty.
So every page which would use the polyfill from MDN with defineProperty would be a broken environment...

MDN polyfill does not use `Object.defineProperty`, however, it should, but, unlike your version, with `writable: true, configurable: true` attributes.

>  I am not so sure, if this is a good approach

You could use [`core-js/configurator`](https://github.com/zloirock/core-js#configurable-level-of-aggressiveness).

**Comment by truebden** [comment]
@nicolo-ribaudo  @zloirock thanks for the good explanations!
