### ISSUE TITLE
Question: How to transform output of presets?

### ISSUE THREAD

**Issue by mohsinulhaq** [zloirock/core-js#589]
I want to transform the core-js imports added by @babel/preset-env, but plugins always run before presets, as such I don't have access to those imports. Is there any other way to achieve this?

**Comment by nicolo-ribaudo** [comment]
Please don't post the same issue in multiple places (https://github.com/babel/babel/issues/10142). This question is only related to how Babel plugins work, not to how core-js works.

**Comment by mohsinulhaq** [comment]
sorry for that, closing!
