### ISSUE TITLE
Postinstall fails on Elastic Beanstalk

### ISSUE THREAD

**Issue by gkfolsendho** [zloirock/core-js#591]
On AWS Elastic Beanstalk, my installation fails with the following entries in the npm log file: 
```
28815 verbose stack Error: core-js-pure@3.1.4 postinstall: `node scripts/postinstall || echo "ignore"`
28815 verbose stack spawn sh ENOENT
28815 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
28815 verbose stack     at onErrorNT (internal/child_process.js:415:16)
28815 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
28816 verbose pkgid core-js-pure@3.1.4
28817 verbose cwd /var/app/ondeck
28818 verbose Linux 4.14.123-86.109.amzn1.x86_64
28819 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
28820 verbose node v10.16.0
28821 verbose npm  v6.9.0
28822 error file sh
28823 error path sh
28824 error code ELIFECYCLE
28825 error errno ENOENT
28826 error syscall spawn sh
28827 error core-js-pure@3.1.4 postinstall: `node scripts/postinstall || echo "ignore"`
28827 error spawn sh ENOENT
28828 error Failed at the core-js-pure@3.1.4 postinstall script.
28828 error This is probably not a problem with npm. There is likely additional logging output above.
28829 verbose exit [ 1, true ]
```
My .ebextensions container_command:
```
  03_run_npm:
    cwd: "/var/app/ondeck"
    command: 'npm install'
```
I have tried using `--silent` and `--quiet` on the `npm install`  command, but always with the same result. I have also set the environment paramenter `CI=true` and `ADBLOCK=true`, still same result.
When running `npm install´ from the command line on the same instance it works. 

Any ideas how to solve this?

**Comment by leny** [comment]
Same issue here, no idea on how to get rid of it.

For a package so used, it's a very big problem to have that kind of issues.

How can we help you solve this?

**Comment by leny** [comment]
> **NOTE:** I've solved the issue on my side by adding `DISABLE_OPENCOLLECTIVE` var to `true` in the **Environment properties** in **Configuration** panel of Elastic Beanstalk.

**Comment by zloirock** [comment]
Could you check it with the current version?

**Comment by zloirock** [comment]
Closed due to lack of response. Most likely, the current approach should not cause this issue.
