### ISSUE TITLE
Please stop with the spam.

### ISSUE THREAD

**Issue by Qix-** [zloirock/core-js#592]
I know you're going to lock this. I know you're going to respond negatively.

Just voicing my opposition for `npm install`-based advertisements. I wish npm would take a firm stance against this (cc @seldo - cmon, guys).

![image](https://user-images.githubusercontent.com/885648/60958192-3a9cda00-a306-11e9-92fe-f7d19a17a43b.png)

I know the job market is hard, but don't annoy the absolute shit out of other developers when we're trying to do ours, please.

**Comment by Qix-** [comment]
Actually - again, cc @seldo - this is in **direct violation** of section 8 of the [AUP of npm](https://www.npmjs.com/policies/open-source-terms#acceptable-use):

> 8. You will not send advertisements, chain letters, or other solicitations via npm Services.

**Comment by zloirock** [comment]
Please, use search, #548.
