### ISSUE TITLE
Opera Presto: Uint8ClampedArray.prototype.__proto__ 

### ISSUE THREAD

**Issue by EyeAndTea** [zloirock/core-js#595]
Any attempts to write to "Uint8ClampedArray.prototype.__ proto __" on opera presto, which includes versions 12.x of the browser, causes an immediate crash. The problem happens in the file 

./packages/core-js/internals/array-buffer-view-core.js

on the lines,

```javascript
if (global[NAME]) setPrototypeOf(global[NAME].prototype, TypedArrayPrototype);
```

and

```javascript
setPrototypeOf(Uint8ClampedArrayPrototype, TypedArrayPrototype);
```

Due to my lack of familiarity with your code, its philosophy and architecture, I refrain from offering my own fix. An educated guess tells me that this will likely require an explicit detection of presto due to the nature of the bug, which is what I have done for my own copy of the library.

**Comment by zloirock** [comment]
I'll try to reproduce when I'll have time and access to opera presto.

**Comment by EyeAndTea** [comment]
Thank you. 

A simple, 

```javascript
Uint8ClampedArray.prototype.__ proto __ = {};
```

should be sufficient to cause a crash. A copy of opera presto 12.18 **32bit** can be found at 

[https://www.techspot.com/downloads/40-opera-for-windows.html](https://www.techspot.com/downloads/40-opera-for-windows.html)

MD5: "329287dd3d69adbf93e66daa29e79e9e"


Whatever effort you put in this is appreciated.

**Comment by zloirock** [comment]
Thanks for the issue -)

**Comment by EyeAndTea** [comment]
Tested with v3.2.0, and things do appear stable on Opera Presto now.

Thank you. Much appreciated.
