### ISSUE TITLE
Cannot read property 'for' of undefined

### ISSUE THREAD

**Issue by crock** [zloirock/core-js#599]
**Cannot read property 'for' of undefined**

```
(While processing: "/node_modules/next/babel.js") at Object.<anonymous> 
(/node_modules/core-js/library/fn/symbol/for.js:2:55)
```

Happened after I updated my Node modules.

**Comment by zloirock** [comment]
Any ideas about how to reproduce it? I have no ideas in which case it's possible.

**Comment by crock** [comment]
Closing this. I noticed next.js was a version behind, so I updated it.
