### ISSUE TITLE
Promise.finally - not polyfilling globally

### ISSUE THREAD

**Issue by melloc01** [zloirock/core-js#602]
Hi there, I am using Firefox 60.0.1 and while the `finally` method seems to work fine within the bundle, I can't get it to work in the global namespace.

My goal is to provide the `finally` and other polyfills to the *runtime* not only to the bundle runtime, what am I missing? 

*babelrc*:

```
module.exports = {
    presets: [
        [
            '@babel/env',
            {
                useBuiltIns: false,
                targets: {
                    browsers: ['ie >= 11']
                }
            }
        ],
        '@babel/react',
        '@babel/flow'
    ],
    plugins: [
        require('@babel/plugin-transform-flow-strip-types'),
        require('@babel/plugin-proposal-class-properties'),
        require('@babel/plugin-proposal-object-rest-spread'),
        require('@babel/plugin-transform-async-to-generator'),
        require('@babel/plugin-syntax-dynamic-import'),
        require('@babel/plugin-transform-modules-commonjs'),
        require('babel-plugin-styled-components')
    ]
}
```

**Comment by zloirock** [comment]
With `useBuiltIns: false` polyfills are not applied.  Use `useBuiltIns: 'usage' (or 'entry'), corejs: '3.1'`.

**Comment by melloc01** [comment]
hey @zloirock, I didn't put my whole babel config here for brevity and turned out it was a babel plugin that was causing the namespace out of the module runtime to remain untouched.

`@babel/plugin-transform-modules-commonjs` was guilty - I really need this plugin since it's a large codebase and other external bundles depends on some "runtime require"  behavior, maybe I should open an issue on their repo

**Comment by melloc01** [comment]
Turns out it was a Handsontable issue... :disappointed: 
https://github.com/handsontable/handsontable/issues/5398#issuecomment-446581084

I'll just update it, thanks @zloirock
