### ISSUE TITLE
TypeError from redefine.js on IE11, Mobile Safari 9

### ISSUE THREAD

**Issue by arggh** [zloirock/core-js#614]
A simple Hello World app, made with Svelte, bundled with Rollup, breaks when transpiled/polyfilled with Babel+core-js, but only on older browsers. So far known affected include IE 11 and Mobile Safari 9.

I'm not sure what specifically in the app upsets core-js/Babel, but at least I can reliably reproduce the bug with Svelte.

<details>
  <summary>Stack trace</summary>

  ```
[Error] TypeError: Type error
	toString (bundle.js:312:95)
	toString (bundle.js:312:95)
	_isNativeFunction (bundle.js:11152)
	_wrapNativeSuper (bundle.js:11290)
	_wrapNativeSuper (bundle.js:11317)
	(anonymous function) (bundle.js:12708)
	Global Code (bundle.js:12814)
```

</details>

A reproduction with instructions is here: https://github.com/arggh/core-js-svelte-issue

The error seems to be coming from core-js, redefine.js:

```js
...
// add fake Function#toString for correct work wrapped methods / constructors with methods like LoDash isNative
})(Function.prototype, 'toString', function toString() {
  return typeof this == 'function' && getInternalState(this).source || nativeFunctionToString.call(this); // <---- this line
});
```

I'm still wrapping my head around all the moving parts, but it seems to have something to do with Svelte extending `HTMLElement`, as that's what `this` seems to be when the `TypeError` is thrown.

**Comment by arggh** [comment]
This seems to have been solved, in our case, with the help from these friendly people in [this Babel issue](https://github.com/babel/babel/issues/8915).

Not sure if this _polyfill problem should be considered further in the polyfill library used by Babel, or not, since I'm not that familiar with the overlapping responsibilities of these tools.

Feel free to close if this requires no further actions regards to `core-js`

**Comment by zloirock** [comment]
It's just a wrapper for native `Function#toString`, with the native method you will have the same problem. The issue in calling `Function#toString` on exotic built-ins which are not a part of ES, so I don't think that it's a `core-js` issue.
