### ISSUE TITLE
Since 3.2.0: Promise.then stopped working on old devices

### ISSUE THREAD

**Issue by fdc-viktor-luft** [zloirock/core-js#615]
I want to report a **bug** which is related to the release of version **3.2.0**.

It works on 3.1.4 perfectly and I found the piece of code that breaks the application which has to run on Andoird 2.x devices.

## What happened:
`Promise.then` stopped working. The provided callbacks do not execute at all.

## How I fixed it:
In the file [es.promise.js](https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/es.promise.js) I commented out lines 278 - 286, which is currently:
```js
nativeThen = NativePromise.prototype.then;

// wrap native Promise#then for native async functions
redefine(NativePromise.prototype, 'then', function then(onFulfilled, onRejected) {
  var that = this;
  return new PromiseConstructor(function (resolve, reject) {
    nativeThen.call(that, resolve, reject);
  }).then(onFulfilled, onRejected);
});
```

Then everything worked again on Adnoird 2.x. Since I don't know what this peace of code was intended to achieve, I didn't upload a pull request myself.

Please find some expert to fix that issue. I would be glad to help by testing whatever changes on the Andoird 2.x devices.

**Comment by zloirock** [comment]
It's a patch for a native `Promise` when it's available but incorrect, however, used by some APIs like async functions, see #579. Android 2.x haven't native promises, so it can be a conflict with another polyfill. Could you add a reproducible example?

**Comment by fdc-viktor-luft** [comment]
I'm polyfilling only via `core-js`.

Since it highly depends on the used browser, I don't know how to build something to reproduce it. Maybe you have access to some EInk-Reader based on old Android version (like the Tolino Shine 1 - sold in Germany).

What I've tested then was:

```js
import 'core-js/es';

new Promise(resolve => {
    // promise resolves in 2 seconds
    setTimeout(resolve, 2000);
}).then(() => {
    // this function get's never executed
    window.alert('foo');
});
```

**Comment by zloirock** [comment]
Without another global `Promise`, this issue is impossible. At least, please, add a stack trace.

**Comment by zloirock** [comment]
Theoretically, it can be caused by recursion in promise, used in the microtask implementation, but the reason could be only in the conflict with another polyfill. I'll add a workaround, could you test it?

**Comment by fdc-viktor-luft** [comment]
Of course I would test it :+1:

**Comment by fdc-viktor-luft** [comment]
Ok. I don't know why exactly, but that fixed it :grin: Thanks for your fast fix. When can I expect to download the next version with that fix?

**Comment by zloirock** [comment]
Done.
