### ISSUE TITLE
How to check if core-js is already applied?

### ISSUE THREAD

**Issue by ajkl2533** [zloirock/core-js#616]
Hello there,
is there any way how to find out if `core-js` is already applied on the page? I want to import it only if I have to. We were using `_babelPolyfill` property on `window/global` before, but after upgrading to `babel@7` this is not the case anymore.

**Comment by zloirock** [comment]
From `core-js@2.6`, in `(window|global)['__core-js-shared__'].versions` see versions in the `global` mode:
![Снимок экрана 2019-08-13 в 16 35 02](https://user-images.githubusercontent.com/2213682/62931497-aa602200-bde8-11e9-88ea-74cda1c79c55.png)

**Comment by ehmPlankje** [comment]
> From `core-js@2.6`, in `(window|global)['__core-js-shared__'].versions` see versions in the `global` mode:
> ![Снимок экрана 2019-08-13 в 16 35 02](https://user-images.githubusercontent.com/2213682/62931497-aa602200-bde8-11e9-88ea-74cda1c79c55.png)

I would like to highlight that you made a typo in your comment. The correct syntax is `(window||global)['__core-js_shared__']?.versions`.

**Comment by zloirock** [comment]
@ehmPlankje `?.` was not available in 2019. However yes, it's safer. The most proper way at this moment is [here](https://github.com/zloirock/core-js/blob/bc3ba44b7a3d9031e2df4a8494b492003d8e32d3/scripts/usage.mjs#L33-L38).

**Comment by ehmPlankje** [comment]
@zloirock I was also referring to that you wrote `'__core-js-shared__'` instead of `'__core-js_shared__'`, and that you wrote `(window|global)` instead of `(window||global)`.

**Comment by zloirock** [comment]
@ehmPlankje ah, yes, thanks, `__core-js-shared__` was a mistake. `window|global` was an example, since `window||global` can't be used since if `window` is missed, it will be an uncaught `ReferenceError`.
