### ISSUE TITLE
Conflict of `web.url-search-params` and Google Maps JavaScript SDK

### ISSUE THREAD

**Issue by AlexWayfer** [zloirock/core-js#619]
The code:

```js
import 'core-js/modules/web.url-search-params';
```

The address:

```
our.host/namespace/current_page?entity%5Bfield%5D=%D0%9B%D0%B8%D0%BF%D0%B5%D1%86%D0%BA%2C+%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D1%8F&entity%5Banother_field%5D=%2852.6121996%2C+39.598122500000045%29
```

Without there are requests to:

```
https://maps.googleapis.com/maps/vt?pb=!1m5!1m4!1i6!2i37!3i19!4i256!2m3!1e0!2sm!3i479188624!3m9!2sru!3sUS!5e18!12m1!1e68!12m3!1e37!2m1!1ssmartmaps!4e0&key=%API_KEY%&token=129221
```

![image](https://user-images.githubusercontent.com/6510020/63194028-9e3dc400-c077-11e9-9cd5-c22944aab0cb.png)

With there are requests to:

```
our.host/namespace/undefinedpb=!1m5!1m4!1i6!2i37!3i19!4i256!2m3!1e0!2sm!3i479188624!3m9!2sru!3sUS!5e18!12m1!1e68!12m3!1e37!2m1!1ssmartmaps!4e0&key=%API_KEY%&token=129221
```

(and 404, obviously)

![image](https://user-images.githubusercontent.com/6510020/63194119-d34a1680-c077-11e9-8f57-d6ac7f542ae9.png)

**Comment by zloirock** [comment]
I have no ideas about what happens in your case. I supposed that the problem in the parsing of one of those urls and checked - but it works fine in the polyfill. It can be one more conflict with another polyfill. Without a reproducible exmple, I can't say anything.

**Comment by AlexWayfer** [comment]
I hope it's enough: https://gist.github.com/AlexWayfer/5cb15784af3761aa75ce71736a08f9ec

With commented `import` it works. With uncommented — errors.

**Comment by zloirock** [comment]
I still can't reproduce it. Without `core-js`, `URLSearchParams` constructor is not available, with `core-js` it works as expected.

**Comment by AlexWayfer** [comment]
> with core-js it works as expected.

And map works?

My case:

![image](https://user-images.githubusercontent.com/6510020/63276107-69b24e00-c2ab-11e9-9750-11b92726f38e.png)

So, `URLSearchParams` works (`null` in console), but map (images) doesn't.

**Comment by AlexWayfer** [comment]
It fixes also by adding `import 'core-js/modules/es.symbol.iterator'`, unbelievably.

**Comment by AlexWayfer** [comment]
Maybe this module (`es.symbol.iterator`) should be required (auto-imported) by `es.array.from` and `web.url-search-params`, no?

**Comment by zloirock** [comment]
You should not use `/modules/` path directly. It's only for internal usage, transpilers and users who completely understand how it works. I tried in your examples `core-js/stable/url-search-params` and  it works fine. This entry point includes all required dependencies.

**Comment by zloirock** [comment]
The same for `Array.from` - `core-js/stable/array/from`.

However, yes, I saw just console output and if Google Maps internally uses own iterables, `Symbol` polyfill also should be added - `core-js/stable/symbol` or `core-js/stable/symbol/iterator`.

**Comment by AlexWayfer** [comment]
OK, thank you. But I see some `import "core-js/modules/` in README. Also I see `stable/`, `features/`, `proposals/`, `stage/`, `es/` — and I don't understand the difference.

**Comment by AlexWayfer** [comment]
> I tried in your examples core-js/stable/url-search-params and it works fine.
>
> The same for Array.from - core-js/stable/array/from.

Doesn't work for me. :disappointed_relieved:

**Comment by zloirock** [comment]
> Doesn't work for me. (without `core-js/stable/symbol/iterator`)

As I wrote - if Google Maps API internally uses custom iterables, you should add it, otherwise, they use own `Symbol.iterator` polyfill which breaks `core-js`.

> But I see some import `core-js/modules/` in README.

Only in transpilers output and in the links where you could see polyfills code.

> Also I see `stable/`, `features/`, `proposals/`, `stage/`, `es/` — and I don't understand the difference.

- `es` includes only stable ES features
- `stable` also includes polyfills for web standards
- `features` also includes proposals
- `stage` allows include proposals polyfills by the stage number
- `proposals` allows include all polyfills from required proposal

**Comment by AlexWayfer** [comment]
> As I wrote - if Google Maps API internally uses custom iterables, you should add it, otherwise, they use own Symbol.iterator polyfill which breaks core-js.

If some polyfill, used by `core-js` modules, can be required — maybe these modules should require it?

I still mean:

> Maybe this module (es.symbol.iterator) should be required (auto-imported) by es.array.from and web.url-search-params, no?

You replied:

> This entry point includes all required dependencies.

But it seems that `es.symbol.iterator` required by modules, mentioned above.

---

> Only in transpilers output and in the links where you could see polyfills code.

OK. But you can pay attention to [`@babel/preset-env` documentation](https://babeljs.io/docs/en/next/babel-preset-env.html):

> Since @babel/polyfill was deprecated in 7.4.0, we recommend directly adding core-js and setting the version via the corejs option.

**Comment by zloirock** [comment]
One more time: it's not required for correct work of this polyfill - it can work with all standard iterables. If someone wanna create custom iterables - he will use `Symbol.iterator` and for that should include `Symbol.iterator` polyfill. However,`core-js` can't interact with iterables based on third-party `Symbol` polyfill if it's included after `core-js` since `Symbol.iterator` used as the base of iterators protocol.

**Comment by zloirock** [comment]
It's like asking why `Array.from` does not work with `Set` instances in IE11 after import only `Array.from` polyfill module - for correct work in this case also required `Set` polyfill module. Import of all features somehow related `Array.from` -> iterators will take 100Kb+.

**Comment by zloirock** [comment]
> OK. But you can pay attention to `@babel/preset-env` documentation

Here it's also just in the transpilers output.

**Comment by zloirock** [comment]
> It can looks good in README.

You could find it, for example, [here](https://github.com/zloirock/core-js#commonjs-api). Feel free to add a PR for improving it.
