### ISSUE TITLE
Support for AMD Modules

### ISSUE THREAD

**Issue by roti** [zloirock/core-js#620]
`core-js` does not support AMD modules and it would be nice if it would.

When using `core-js` in an AMD environment with [requirejs](https://requirejs.org/) I get the error [Module name ... has not been loaded yet for context: ...](https://requirejs.org/docs/errors.html#notloaded), which occurs when the modules are loaded in CommonJS style.

Some more information here: https://github.com/requirejs/requirejs/wiki/Differences-between-the-simplified-CommonJS-wrapper-and-standard-AMD-define

The solution would be for `core-js` releases to include both CommonJS and AMD modules. CommonJS modules can be transformed to AMD either through `requirejs`s [conversion tool](https://requirejs.org/docs/commonjs.html#autoconversion), or though babel with [@babel/plugin-transform-modules-amd](https://babeljs.io/docs/en/babel-plugin-transform-modules-amd).

**Comment by zloirock** [comment]
By my vision, AMD modules are something obsolete. Soon, I'm planning to add a core-js version with ES modules support, #385, but I don't want to spend time to the creation and the maintenance of AMD version and increase the size of packages by AMD version.

**Comment by roti** [comment]
Then I guess it needs to be removed from `babel-preset-env` as well. Currently `babel-preset-env` supports AMD modules, but without support from `core-js` it's pretty much useless. (I opened a ticket there as well, on a related issue: https://github.com/babel/babel/issues/10333 )
It is actually a quite common practice in the npm world for releases to include commonjs, AMD and UMD, at least that's my impression. I don't know much about ES modules though.
If you are willing to accept a pull request on this matter, I could look into how it can be done.

**Comment by zloirock** [comment]
It's the first issue about AMD support for 5 years of `core-js`. I don't see any serious AMD modules support in popular packages.

You can use `babel-preset-env` without `useBuiltIns` option and create a `core-js` bundle generated by [`core-js-builder`](https://github.com/zloirock/core-js/tree/master/packages/core-js-builder) with your browserslist targets or the full `core-js` version.

UMD wrappers for ~500 internal `core-js` modules? It's too heavy.
AMD version in the package? It's +600KB to the package size which will be useless for almost all of users and will cause additional issues about the package size.
AMD version as a separate package? It's additional maintenance problems.
Or what do you propose?

If I'll see a serious interest around this issue, I could change this position.

**Comment by roti** [comment]
Indeed, core-js is not small, and adding AMD or UMD to it will increase it's size. Production builds shouldn't be affected though, there's almost always a minifier involved which eliminates dead code to some degree. 
Well, my wish would be to have AMD included in the core-js distribution. :)
The other option is to convert it via requirejs's [conversion tool](https://requirejs.org/docs/commonjs.html#autoconversion).
Unfortunately it doesn't work completely. Conversion fails for `es6.regexp.to-string.js`. I don't know why yet, I'm looking into it. It's probably linked to this conditional:
```
if (require('./_fails')(function () { return $toString.call({ source: 'a', flags: 'b' }) != '/a/b'; })) {
```
(I'm using for `core-js` 2).

**Comment by zloirock** [comment]
@roti in `core-js@3`, for simplifying adding ES modules version in the future, all modules moved to the head of files, so it should not be a problem. Feel free to add a PR if you wanna fix it in `core-js@2`.

**Comment by roti** [comment]
In the end I decided to switch to webpack, so from my point of view the issue can be closed.

**Comment by broonage** [comment]
Hi folks, I'm working on a legacy AMD project that uses babel for transpiling to modern JS and need to get full ES6+ support by pollyfilling. Going round in circles, and it seems that if your project is AMD you can't polyfill with core-js? I get the same error above.

**Comment by rhpijnacker** [comment]
Any news on this?
I would also like to use newer ES features (async/await) in a legacy AMD project.

**Comment by prma85** [comment]
> I would also like to use newer ES features (async/await) in a legacy AMD project.

Same here :(

**Comment by broonage** [comment]
> > I would also like to use newer ES features (async/await) in a legacy AMD project.
> 
> Same here :(

❤️

**Comment by rhpijnacker** [comment]
Actually, if you use Babel for transpiling your code, you only need [regenerator-runtime](https://www.npmjs.com/package/regenerator-runtime) to be able to use async/await.
You might need a Promise polyfill, though.
We are using the Dojo AMD loader succesfully with async/await and a Promise polyfill implemented using Dojo's Deferred/Promise API.

**Comment by mm-sam** [comment]
add plugin [transform-amd-to-commonjs](https://github.com/msrose/babel-plugin-transform-amd-to-commonjs)

```
plugins: [
    "@babel/plugin-transform-runtime",
    "@babel/plugin-syntax-dynamic-import",
    "transform-amd-to-commonjs"
],
```
