### ISSUE TITLE
Consider using Mathias Bynens `globalThis` polyfill

### ISSUE THREAD

**Issue by alfaproject** [zloirock/core-js#622]
Because it works everywhere and it doesn't use unsafe code: https://mathiasbynens.be/notes/globalthis

**Comment by zloirock** [comment]
Thanks for the proposal.

- This polyfill does not work in ES3 environment.
- This polyfill (temporarily) mutates `Object.prototype` and it could deoptimize some engines.
- The current implementation also works everywhere and uses `Function` constructor only if it can't be found by standards way.

This article is a good educational resource, but I don't think that it should be used in real polyfills.

**Comment by brad4d** [comment]
closure-compiler team member here with some more info

@shicks, @vxlydia, and I considered and rejected using https://mathiasbynens.be/notes/globalthis in closure-compiler. It's probably worth recording some of our reasoning here.

1. With a small modification it can work fine in an ES3 environment (wrap in an IIFE and use `this` if it's an object, so no need to call `__defineGetter__`).
2. However, we were concerned that changing the shape of `Object.prototype` could potentially cause a large performance regression by forcing the JS VM to recalculate the shape of all objects.
3. Also, we couldn't come up with any environments we really cared about that would need the "perfect" way. Certainly none for which we maintain tests.

variable  | environment
------------ | ------------------------------
`window` | windows and iframes in all browsers, whether module or script
`self`       | `WebWorkers`
`global`   | NodeJS
`this`       | Rhino, including Apps Script
