### ISSUE TITLE
Loading only required features when using Nashorn

### ISSUE THREAD

**Issue by RobGries** [zloirock/core-js#623]
Hello, I have a project that uses the OpenJDK8 Nashorn JS runtime that I'd like to extend with the modules inside of core-js. Currently I am using the Map functionality gained when importing the entirety of the core-js browser bundle package. 

While this works fantastically, the loading of the entire bundle takes about 20 seconds to load. Looking at the example code in the readme of this project it should be possible to import only what I need from core-js, presumably to speed up the loading of the JS engine. Now Nashorn works a little bit differently than vanilla V8 or other JS runtime environments when loading JS objects and syntax like `import Map from '/pipe/core-js/features/map';` is not recognized by Nashorn, but the entire bundle can be loaded using the Nashorn syntax using the `load('./path/to/file.js');`function. I've tried loading map using the Nashorn syntax like this for example `load ('/core-js/features/map/index.js')`, but this fails with `core-js/features/map/index.js:1 ReferenceError: "module" is not defined`. 

I looked into this further and it appears that the browser bundle package that I am using currently using actually defines the `require` and `module` methods that are required for loading the entirety of the core-js functionality. 

My question is how do I load all of the dependencies for the functionality that I need from core-js in Nashorn? I think that I need to first load the dependencies that are required to load it, but I am unsure where these are in the project.

**Comment by zloirock** [comment]
Since now `core-js` uses commonjs, in environments which does not support commonjs, you should bundle `core-js` before usage. You could use already bundled `core-js` version - `core-js-bundle` package. In the future, will be added `core-js` version which supports ES modules.
