### ISSUE TITLE
Broken `es.promise` with `inlineRequires` on `react-native`

### ISSUE THREAD

**Issue by vinceplusplus** [zloirock/core-js#625]
In a newly created `react-native` (`0.60.5`) project. If we turn on the inline require feature (`inlineRequires: true` in `metro.config.js`), the `then` callbacks will not be called. For instance, if we have the following code, `then` will not be printed
```
import 'core-js';
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

new Promise(resolve => resolve('then')).then(result => console.log(result));
AppRegistry.registerComponent(appName, () => App);
```
However, if we turn off the inline require feature (`inlineRequires: false`), `then` will be printed

Also, if i comment the following line in `core-js/es/index.js`
```
require('../modules/es.promise');
```
`then` callbacks will work again

Version `3.2.1`

**Comment by zloirock** [comment]
`core-js` is a polyfill and should be loaded before any other code. If you change the order of loading by `inlineRequires`, and if it works without it, it's not a `core-js` issue.

**Comment by vinceplusplus** [comment]
@zloirock as can be seen from the snippet above (`index.js`), `core-js` is imported in the first line. The code works fine with `inlineRequires` off but not with `inlineRequires` on. The code above doesn't utilize inline require (e.g. `require('abc').default`)

**Comment by vinceplusplus** [comment]
the line
```
new Promise(resolve => resolve('then')).then(result => console.log(result));
```
simply verifies if `Promise.prototype.then()` works or not by printing some value

**Comment by zloirock** [comment]
How could I know is this file your entry point or not? -) I'm not an expert in React Native, I don't know how `inlineRequires` works and I don't know what's imported before `core-js` in this case. It looks like a conflict with another `Promise` polyfill.

**Comment by vinceplusplus** [comment]
@zloirock just had some debugging, the issue is with the `inlineRequires` itself. with `inlineRequires` on, every module will only get loaded when it's first referenced. so, for instance, imagine the following code:
```
// a.js
global.a = 'a';

module.exports = function () {};

// b.js
module.exports = function () {
  console.log(global.a);
};

// index.js
import a from './a';
import b from './b';

b();
a();
b();
```
normally, the first `b()` will log `a` but with `inlineRequires` on, it would log `undefined`. since `./a.js` isn't referenced anywhere before the first `b()`, `./a.js` source hasn't been loaded yet thus the initializers in the code has not yet been executed. the second `b()` will log `a` correctly because `a()` will load the module and execute all initializers before really executing the function

this will be catastrophic for any module that loading the module itself will have some side effect another module requires and this could be common in projects with considerable sizes and `core-js` as well

in our case, the actual exception caused by maximum call stack size exceeded but it doesn't matter since the configuration is already messed

wrapping all initializers in a file in an explicit initializer function and have it called after `require` might work but that would be quite some work and introduce too much noise

another way is to add all module paths into the blacklist for the `inlineRequires` feature. or just wait for the async `import()` support coming to `react-native` to explicitly specify which modules we want to load lazily

**Comment by zloirock** [comment]
Thanks, interesting. Maybe makes sense to open this issue on `react-native` side? Seems it could be better if they somehow could detect modules with side effects.
