### ISSUE TITLE
core-js/modules misses modules emitted by core-js-compat

### ISSUE THREAD

**Issue by andrew--r** [zloirock/core-js#628]
I’m using `core-js-compat` to determine a list of required `core-js` modules by `browserslist` query. I have installed `core-js@3.2.1` and `core-js-compat@3.2.1`. Logic is simple:

```js
const {list} = coreJsCompat({
  targets: pkg.browserslist,
});

const scriptSource = list
  .map((moduleName) => `core-js/modules/${moduleName}`)
  .map((modulePath) => `import '${modulePath}';`)
  .join('\n');

fs.writeFileSync('polyfills.js', scriptSource);
```

I discovered that at least four modules that are emitted by `core-js-compat` are actually missing in `core-js`, if I require them using `import 'core-js/modules/${moduleName}';`:

1. `es.promise.all-settled`
2. `esnext.array.is-template-object`
3. `esnext.map.update-or-insert`
4. `esnext.symbol.async-dispose`

As I understand, module names from `core-js-compat` should match module files from `core-js/modules`. Am I right? If not, how such situations should be handled?

**Comment by zloirock** [comment]
Seems you have installed `core-js@3.1`. Those modules were added in `core-js@3.2`, [see the current `/modules/` path](https://github.com/zloirock/core-js/tree/master/packages/core-js/modules). The data about it available in [`core-js-compat/modules-by-versions`](https://github.com/zloirock/core-js/blob/master/packages/core-js-compat/src/modules-by-versions.js) and used by tools like `preset-env` only if you directly set used `core-js` minor version.
