### ISSUE TITLE
Array.from not working with Set

### ISSUE THREAD

**Issue by xkizer** [zloirock/core-js#630]
The implementation of Array.from behaves incorrectly with `Set`s. Example:

```js
Array.from(new Set([1, 2, 3]));
```

Expected result:
> [1, 2, 3]

Actual result:
> [] (empty array)

This differs from the native implementation.

**Comment by xkizer** [comment]
Closed as this issue seems to be from an older version

**Comment by dp21g** [comment]
@xkizer what version did this issue get fixed in, do you know?
