### ISSUE TITLE
Add Ethereum name or address to FUNDING.yml

### ISSUE THREAD

**Issue by lastmjs** [zloirock/core-js#632]
I would like to see an Ethereum name or address added to the custom field of the FUNDING.yml file. This will allow consumers of the project to know a canonical address to send funds to.

Having an Ethereum address would allow various cryptocurrencies to be donated, including stablecoins pegged to USD, like USDC or DAI. Essentially it is another payment network like PayPal, but open and decentralized like the internet. Getting an address is relatively straightforward through something like MetaMask or Coinbase. You could also generate one on your own.

**Comment by zloirock** [comment]
Sorry, I wanted to add it, but 2 years have gone and cryptocurrencies support is still not added to GitHub `FUNDING.yml`. I added a Bitcoin address to all the rest funding docs / messages, but I think that Ethereum could be superfluous. If you or someone else want to support `core-js` with Ethereum, the address is **0x42BC87b8A44D8ed7f8b0C728B7BF94Ab73fd2B75**
