### ISSUE TITLE
Why are the `url` features also included in `proposals/`?

### ISSUE THREAD

**Issue by liuyunzhuge** [zloirock/core-js#636]
Version: core-js@3.

Source code of "core-js/stable":
```js
require('../es');
require('../web');

module.exports = require('../internals/path');
```
That means all features in "core-js/web" are stable.  For example, the `url` feature of file `core-js/web/url.js`:
```js
require('../modules/web.url');
require('../modules/web.url.to-json');
require('../modules/web.url-search-params');
var path = require('../internals/path');

module.exports = path.URL;
```

But I see another file of `url` feature in `proposals` directory: `proposals/url.js`. Code is: 
```js
require('../modules/web.url');
require('../modules/web.url.to-json');
require('../modules/web.url-search-params');
```
`web/url.js` and `proposals/url.js` are almost the same, why are the `url` also included in `proposals/`?

**Comment by zloirock** [comment]
Because it's also [a stage 0 proposal](https://github.com/jasnell/proposal-url).
