### ISSUE TITLE
Whether whitelist is available？

### ISSUE THREAD

**Issue by crixusshen** [zloirock/core-js#637]
My current container environment is not a browser, but a self-created JsCore environment.In this environment, I myself implemented setTimeout, setInterval and clearTimer through C++. But the setTimeout API is converted by jscore3. Is there any way to get my specified API to not convert？thanks!

**Comment by zloirock** [comment]
I'm not completely sure that I understood the problem. It's converted by `babel` (`runtime` or `preset-env`?) or it's replaced by `core-js` (it should be replaced only in IE9-)?

**Comment by crixusshen** [comment]
Thank you, your understanding is correct, I just confused. I should go to the runtime code repository to check out issue
