### ISSUE TITLE
Array.prototype.slice (IE8) throws when used on nodeList

### ISSUE THREAD

**Issue by AutoSponge** [zloirock/core-js#64]
```js
Array.prototype.slice.call(document.body.childNodes) //=> JSObject Expected
```

This code: https://github.com/zloirock/core-js/blob/275afdd031a511450501bc7cfa2cd0dd316275ea/client/shim.js#L275 should be able to handle array-like objects.

**Comment by zloirock** [comment]
[Need fix it](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice#Streamlining_cross-browser_behavior).
