### ISSUE TITLE
Android 4.4.4: Uncaught TypeError: Cannot redefine property: then

### ISSUE THREAD

**Issue by conechan** [zloirock/core-js#640]
As title, this error throwed in some old Android devices (such as 4.4.4 KTU84P), due to core-js try to redefine the native promise.

```js
    // wrap native Promise#then for native async functions
    redefine(NativePromise.prototype, 'then', function then(onFulfilled, onRejected) {
      var that = this;
      return new PromiseConstructor(function (resolve, reject) {
        nativeThen.call(that, resolve, reject);
      }).then(onFulfilled, onRejected);
    });
```

I've looked at https://github.com/zloirock/core-js/issues/615, but seems not the same issue.

**Comment by conechan** [comment]
I run `Object.getOwnPropertyDescriptor(Promise.prototype, 'then')` on the device, it show the descriptor as below.

```js
{
  configurable: false,
  enumerable: true,
  value: function()
  writable: true
}
```

It seems this error caused by the `configurable: false`.

**Comment by zloirock** [comment]
Are you sure that it's a *native* `Promise`? IIRC it was tested in Android 4.4. It looks like a non-correct polyfill, however, I'm not 100% sure.

**Comment by conechan** [comment]
Yes, it's a native `Promise`. And the browser env is a webview in our app, I am not sure whether it's a regular Android 4.4.4 webview.

I know it's an incorrect behavior :(

Are there any work around to solve this issue? If no, I have to downgrade and lock the core-js version to 3.1.4.

**Comment by zloirock** [comment]
I'll add a workaround.

**Comment by bdwain** [comment]
thanks for fixing this so quickly @zloirock. Are you planning on releasing the fix anytime soon? I see there's a few unreleased fixes out

**Comment by zloirock** [comment]
Now I haven't enough time for that. Little later.

**Comment by caycek** [comment]
Definitely don't want to rush you because I'm sure you're busy, but wanted to just state that this fix would be super helpful in a few spaces I'm in! :) Hope you can release soon.
