### ISSUE TITLE
Testing core-js@3 loaded in window

### ISSUE THREAD

**Issue by DyBrenn** [zloirock/core-js#646]
Hello,

With @babel/polyfill being depricated, I am migrating to core-js@3. I have run into the problem of testing that core-js has been loaded in the window. In core-js@2.6.9 && @babel/polyfill I was able to check this with window.core.version but have seen that has now been removed. How would I do this in core-js@3?

Thanks.

**Comment by zloirock** [comment]
See [this answer](https://github.com/zloirock/core-js/issues/616#issuecomment-520765743).
