### ISSUE TITLE
Function Bind Syntax-friendly library API

### ISSUE THREAD

**Issue by UltCombo** [zloirock/core-js#65]
Would it be possible to expose a library API that works with the [Function Bind Syntax](https://github.com/zenparsing/es-function-bind)?

I mean, an API similar to the current library API, but which uses the `this` binding instead of the first argument for instance methods. For instance, instead of:

```js
var core = require('core-js/library');
core.String.repeat('*', 10);
```

Do something like:

```js
var core = require('core-js/library');

'*'::core.String.prototype.repeat(10);
// transpiles to:
core.String.prototype.repeat.call('*', 10);
```

Needless to say, this would be an excellent way to avoid polluting the built-in prototypes while maintaining composability.

**Comment by zloirock** [comment]
Now it's missing. Before, I wanted to add it for abstract references proposal and added it for `Dict ` module, [see example from this comment](https://github.com/zenparsing/es-abstract-refs/issues/12#issuecomment-76418860), but with current proposal it's impossible. I'll try add something like this when will be available this syntax in compilers, but it will not be so convenient as with abstract refs.

**Comment by UltCombo** [comment]
ES7 function bind has been implemented in Babel -- https://github.com/babel/babel/pull/1518 and https://github.com/babel/babel/commit/724bf52929d0e83e86ce1cf3b2966a7e5a6b7fb5

Any chance to have bind-operator-friendly methods soon? I'll be giving a talk to ~300 people this Saturday and it would be nice to demonstrate core-js + bind operator. :smiley:

If you give me the directions on how this should be approached, I can help implementing it too.

**Comment by zloirock** [comment]
@UltCombo I can add it as you proposed - `'*'::core.String.prototype.repeat(10)`, but not sure it's a convenient API. Maybe as temporary solution.

**Comment by UltCombo** [comment]
Yes, I believe it can be improved, but I can't think of a better solution at the moment.
Using Babel, the syntax is not too ugly though:

```js
import { String_ } from 'core-js';
const { repeat, startsWith /*...*/ } = String_.propotype;

'*'::repeat(10);
```

**Comment by zloirock** [comment]
Should be available in 0.9.9.

Problem with single entry points for methods - currently only for static versions. I'll think about it later.

If someone have better ideas about this API - awaiting proposals.

**Comment by UltCombo** [comment]
Awesome, thanks!

**Comment by zloirock** [comment]
In [2.0](https://github.com/zloirock/core-js/releases/tag/v2.0.0) in `library` version it's changed to `core.%CONSTRUCTOR%.virtual.%METHOD%` and [available special entry points](https://github.com/zloirock/core-js#commonjs-and-prototype-methods-without-global-namespace-pollution).

**Comment by UltCombo** [comment]
Nice. :+1:
