### ISSUE TITLE
IE11SCRIPT5017: Syntax error in regular expression 

### ISSUE THREAD

**Issue by CubaJas** [zloirock/core-js#650]
After windows update KB4516046 there is an error in IE11 in es6.regexp.constructor.js (37, 3)
IE11SCRIPT5017: Syntax error in regular expression 

` for (var keys = gOPN(Base), i = 0; keys.length > i;) proxy(keys[i++]);`

**Comment by zloirock** [comment]
It's just a wrapper that doesn't change the pattern, because of this you see this line in the stack trace, so most likely you will have this error even without `core-js`. If you don't think so, please, add a reproducible example or more information.

**Comment by zloirock** [comment]
Closed as `can't reproduce`.
