### ISSUE TITLE
Add `new URL(someUrl, undefined)` feature testing for URL polyfill

### ISSUE THREAD

**Issue by trotyl** [zloirock/core-js#656]
From [URL specification](https://url.spec.whatwg.org/#url-class), the URL constructor has an optional `base` parameter:

```typescript
interface URL {
  constructor(USVString url, optional USVString base);
};
```

From [Web IDL spec](https://heycam.github.io/webidl/#dfn-present), explicit passed `undefined` is treated as missing value:

> In the ECMAScript binding, a value of `undefined` is treated as _not present_, or will trigger the _default value_ where applicable.

So that `new URL(text, undefined)` should be equivalent to `new URL(text)`, but which failed in Safari (tested in 13.0.1) by throwing a `TypeError`:

![image](https://user-images.githubusercontent.com/6059170/66052991-1b5bc480-e564-11e9-877f-2b5462b1cc93.png)

This should be a BUG in JavaScriptCore implementation, where in Chrome and Firefox it works properly:

![image](https://user-images.githubusercontent.com/6059170/66053115-4fcf8080-e564-11e9-99b2-5a750fb2e94f.png)
![image](https://user-images.githubusercontent.com/6059170/66053124-53630780-e564-11e9-92ea-b25dce8bd41d.png)

Currently the [`native-url` testing](https://github.com/zloirock/core-js/blob/ba63aec37db946081b40148521bdf27188c3f258/packages/core-js/internals/native-url.js#L7-L24) cannot detect this failure and may resulting a malfunctioning Safari native `URL` being used even when this polyfill loaded.

**Comment by zloirock** [comment]
`native-url` test relaxed because at the moment of writing `core-js` `URL` polyfill no one from browsers implementations were enough correct by the spec at least in some aspects. However, I think makes sense to make it a little more strict at least at this moment.

**Comment by dilyanpalauzov** [comment]
Filed https://bugs.webkit.org/show_bug.cgi?id=216841 for 'new URL('https://x', undefined) throwing an error in WebKit.

**Comment by dilyanpalauzov** [comment]
Which test fails on Safari for URLSearchParams, so that https://github.com/zloirock/core-js/commit/8699b9a3024c1703d7b158ad3236288b38633af6#diff-6016a0a7725ceb1f68ed6ea1c7b96491 requires polyfill only for it?
