### ISSUE TITLE
Issue on Edge Mobile

### ISSUE THREAD

**Issue by cnourai** [zloirock/core-js#657]
We are currently running into an issue on edge mobile devices. No matter where you go in the site, it fails to display.

Babel Core-js : 6.26.3
Babel Polyfill : 6.23.0

And we get this error:
![PolyfillEdited](https://user-images.githubusercontent.com/56128210/66145035-f43eda80-e5d7-11e9-9770-e028fd89f0b3.jpg)

Is edge mobile not supported ? Do we need to update to Babel 7?

**Comment by zloirock** [comment]
Sorry, I can't understand your issue. You listing haven't any mention of `core-js`. "Babel Core-js : 6.26.3"? It's a nonexistent package. Latest `core-js` version is 3.2.1. Edge mobile should be supported. `babel-polyfill` uses obsolete `core-js@2`.

**Comment by zloirock** [comment]
Closed as `can't reproduce`.
