### ISSUE TITLE
CRLF line endings

### ISSUE THREAD

**Issue by amasad** [zloirock/core-js#67]
I hope it's not too much trouble to ask to use unix line endings? At Facebook, we are checking in core-js via babeljs and this is causing trouble with our source control system.

**Comment by zloirock** [comment]
I do not bother about it. Don't think it's a problem. I'll add `eol=crlf` to `.gitattributes`, it will not help available PR.

**Comment by Naddiseo** [comment]
@zloirock unix line endings are `lf` not `crlf`

**Comment by sebmck** [comment]
@Naddiseo He said that he wasn't interested in changing them to Unix line endings.

**Comment by Naddiseo** [comment]
@sebmck, amasad asks if core-js can use unix line endings: "I hope it's (not too much trouble) (to ask (to use unix line endings))"

**Comment by sebmck** [comment]
@Naddiseo Yes and @zloirock said no.

**Comment by Naddiseo** [comment]
Okay, I misunderstood what @zloirock wrote. Please ignore me.

**Comment by amasad** [comment]
Thanks @zloirock I'll see if your .gitattribute change helps next time I update the library.

**Comment by zloirock** [comment]
Oops, it looks like I understood the issue wrongly looked only at the title :D If you need `lf` - I will change it.

**Comment by amasad** [comment]
@zloirock haha, yes, I think what I wrote is confusing. I meant that `crlf` was causing problems and `lf` would be ideal (if it's not too much trouble).
