### ISSUE TITLE
Breakup array iterator files

### ISSUE THREAD

**Issue by ehmicky** [zloirock/core-js#670]
The following file:

```js
[...array]
```

With the following `.babelrc.js`:

```js
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      { targets: { node: '9.11.2' }, useBuiltIns: 'usage', corejs: '3' },
    ],
  ],
}
```

Results in:

```js
"use strict";

require("core-js/modules/es.array.iterator");

[...array];
```

`core-js` is included here but it is not necessary since the array spread operator is supported by Node `9.11.2`. Note that this line is not added when targeting Node `10.0.0`.

It seems to me the reason this file is included is because `Array.values()` was added by Node `10.0.0`. However I am not using it in this case.

Using `core-js@3.3.2`, `@babel/preset-env@7.6.3`, Ubuntu `19.10`.

**Comment by zloirock** [comment]
It's how it works - we have compat data for `es.array.iterator`, but not for `Array.prototype[@@iterator]` (btw, here also some other issues). Most likely, it `core-js@4` or after that, I'll split `Array.prototype.{ @@iterator, keys, values, entries }` to different modules and it will be solved.

**Comment by ehmicky** [comment]
Hi @zloirock, thanks for your quick answer.
