### ISSUE TITLE
is it a bug about version

### ISSUE THREAD

**Issue by fox19920726** [zloirock/core-js#671]
i have specified the version：
![image](https://user-images.githubusercontent.com/7921911/66884704-9b723780-f004-11e9-96ff-90c0a55f45e4.png)

but why ?
![image](https://user-images.githubusercontent.com/7921911/66884850-0a4f9080-f005-11e9-95c9-b84dd6eab67b.png)

**Comment by nicolo-ribaudo** [comment]
Try running `npm install` again

**Comment by fox19920726** [comment]
> Try running `npm install` again

not work，sad。。。。。。

**Comment by nicolo-ribaudo** [comment]
Try running `npx nls why core-js`, it will tell you why it installed core-js 2.

**Comment by fox19920726** [comment]
> Try running `npx nls why core-js`, it will tell you why it installed core-js 2.

awesome ！！！！！！3Q
