### ISSUE TITLE
Internet Explorer 11 throws an error because of es.symbol.js

### ISSUE THREAD

**Issue by yevhey** [zloirock/core-js#672]
There is an attempt to set again `length` property, which is not configurable, in `$defineProperty` method inside `es.symbol.js` file. Here are screenshots with errors from IE itself:

![Screen Shot 2019-10-17 at 12 09 39](https://user-images.githubusercontent.com/13643681/66996083-bada9480-f0d8-11e9-887e-d41985ec791e.png)

![Screen Shot 2019-10-17 at 12 10 01](https://user-images.githubusercontent.com/13643681/66996109-cb8b0a80-f0d8-11e9-8c53-a179b767f3a7.png)

Version of `core-js`: `3.3.2`

**Comment by nicolo-ribaudo** [comment]
What is the full stack trace?
That code delegates to the native define property when you are setting a normal property (effectively ignoring the polyfill), so the problem is somewhere else.

**Comment by yevhey** [comment]
Call stack:
![Screen Shot 2019-10-17 at 14 08 15](https://user-images.githubusercontent.com/13643681/67003862-a5b93200-f0e7-11e9-8de7-1c867bdf42dc.png)

**Comment by yevhey** [comment]
Maybe it is here?

![Screen Shot 2019-10-17 at 14 17 53](https://user-images.githubusercontent.com/13643681/67004457-085efd80-f0e9-11e9-94d7-f4c03b45c085.png)

**Comment by zloirock** [comment]
Nope. One more time - it's just a wrapper on native `Object.defineProperty` call which does not change the functionality with usual keys like `'length'`. It seems the problem in your code.

**Comment by yevhey** [comment]
Это sad :(

**Comment by sergeyshmakov** [comment]
Hello guys! I have the same error on Chrome 35.

*es.symbol.js*
```js
redefine(ObjectPrototype, 'propertyIsEnumerable', $propertyIsEnumerable, { unsafe: true });
```

After that its going to *create-non-enumerable-property.js* and after that falling on 
*es.symbol.js*
```js 
nativeDefineProperty(O, key, Attributes)
```

Im not doing anything unusial in my code, this is happen just after importing `core-js/stable`.
```js
import "core-js/stable";
```

Here is my browserlist: `> .5%, last 4 versions, Firefox ESR, Chrome > 34, IE > 10`

**Comment by sergeyshmakov** [comment]
And in my case all is ok in IE 11...

![image](https://user-images.githubusercontent.com/7429684/116236426-7d989d80-a778-11eb-8176-f0a97be940ac.png)

**Comment by zloirock** [comment]
@sergeyshmakov please, next time open a new issue. It works fine in Chrome 35.
![image](https://user-images.githubusercontent.com/2213682/116236831-b8ef9800-a789-11eb-9d06-e334b3d3e6b8.png)
It looks like a broken environment (for example, frozen `Object.prototype`) case.
