### ISSUE TITLE
ERRO

### ISSUE THREAD

**Issue by bnhampossa** [zloirock/core-js#678]
ENOENT: no such directory

**Comment by zloirock** [comment]
Please, add more info -)

**Comment by bnhampossa** [comment]
ENOENT: no surch file or directory, open 'C:\Users\Aussaci\Documents\workspace\ionic\package.json'

**Comment by zloirock** [comment]
How it's related to `core-js`? -)

**Comment by bnhampossa** [comment]
Na verda sou novato para esse framework, segui todas as instruções de instalação, para rodar o programa na minha pasta deu erro e tentei importar 'core-js' tambem dá mesmo erro

**Comment by zloirock** [comment]
Could you show me, how did you try to use it?

**Comment by bnhampossa** [comment]
Está bem, posso demorar porque ainda estou comprimindo o pacote em rar

**Comment by bnhampossa** [comment]
![ionic](https://user-images.githubusercontent.com/45749425/67604950-3e515100-f77d-11e9-9247-efd9b30282f4.PNG)

**Comment by bnhampossa** [comment]
Ai está o erro que recebo

**Comment by zloirock** [comment]
It's definitely not related `core-js`. Seems you forgot to install `@ionic/react` to your project...
