### ISSUE TITLE
Remaining V8 deoptimizations on features detection

### ISSUE THREAD

**Issue by zloirock** [zloirock/core-js#679]
In addition to:
- #306 - deoptimization of `RegExp` methods on `@@species` support detection or on any changes of `RegExp.prototype`
- #677 - deoptimization of `Array#{ splice, filter, map }` methods on `@@species` support detection

I see other cases:
- deoptimization of `Array#concat` on [`@@isConcatSpreadable` support detection](https://github.com/zloirock/core-js/blob/v3.3.4/packages/core-js/modules/es.array.concat.js#L17-L21) (performance degradation ~4x in my tests) ([added a workaround](https://github.com/zloirock/core-js/commit/f0ea725b40ac29a3a9ee2a050617b631a62d757e))
- deoptimization of `Promise` on [`@@species` support detection](https://github.com/zloirock/core-js/blob/v3.3.4/packages/core-js/modules/es.promise.js#L52-L67) (some percents of performance degradation in my tests) ([added a workaround](https://github.com/zloirock/core-js/commit/22626ed453bd7c408863c7d949b969270915397c))

Maybe I missed something? Maybe something not on features detection?

cc @schuay @mathiasbynens @littledan

**Comment by schuay** [comment]
The full list of V8 global fast/slow-path states (so-called protectors): https://cs.chromium.org/chromium/src/v8/src/execution/protectors.h?l=19&rcl=be638514c9876e80c222068059b205d64091c78d. They affect at least Array, RegExp, Promise, Map, Set, String, TypedArray builtins.

**Comment by zloirock** [comment]
@schuay seems to need to write a modern version of [this post](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers).

**Comment by zloirock** [comment]
I checked all the rest feature detections and I don't see any possible problems.

In runtime code, deoptimizations are possible, so, please, report about then in separate issues.

**Comment by zloirock** [comment]
`ArrayBufferDetaching` protector cell invalidation on `ArrayBuffer` trensfer detection
```js
const a = new ArrayBuffer(8);
structuredClone(a, { transfer: [a] });
```
(will be added a workaround in `core-js@3.23`)
