### ISSUE TITLE
polyfill iterators on HTMLCollection

### ISSUE THREAD

**Issue by AprilArcus** [zloirock/core-js#68]
Hi! In re: [this discussion](https://github.com/babel/babel/issues/545) and [commit](https://github.com/zloirock/core-js/commit/88c68e05efce4f9f0243e8c1f404ba731dd1302a), it would be helpful to polyfill `Symbol.iterator` onto HTMLCollection as well as NodeList.

**Comment by zloirock** [comment]
See https://github.com/zloirock/core-js/issues/37 . Currently this bug is fixed, but still actual old buggy Chromium. I will add it in the future.
