### ISSUE TITLE
uint8-array shim breaks native Uint8Array inheritance on Safari

### ISSUE THREAD

**Issue by ashi009** [zloirock/core-js#683]
I created the following snippet to demonstrate the issue. The code then being down leveled with babel (present-env targeting browsers >1%) and bundled with rollup.

Please find the source at https://github.com/ashi009/corejs-typedarray-bug-on-safari.

```js
class A extends Uint8Array {}
class B extends Uint8Array {}
const a = new A(1);
console.log(a instanceof A, a instanceof B, a instanceof Uint8Array);
// should log true, false, true
// Safari logs false, false, tru
```

The final bundle looks as follow:

```js
var bundle = (function () {
	'use strict';
	
	// omitted core-js modules
    // omitted babel helpers

	var A =
	/*#__PURE__*/
	function (_Uint8Array) {
	  _inherits(A, _Uint8Array);

	  function A() {
	    _classCallCheck(this, A);

	    return _possibleConstructorReturn(this, _getPrototypeOf(A).apply(this, arguments));
	  }

	  return A;
	}(_wrapNativeSuper(Uint8Array));

	var B =
	/*#__PURE__*/
	function (_Uint8Array2) {
	  _inherits(B, _Uint8Array2);

	  function B() {
	    _classCallCheck(this, B);

	    return _possibleConstructorReturn(this, _getPrototypeOf(B).apply(this, arguments));
	  }

	  return B;
	}(_wrapNativeSuper(Uint8Array));

	var a = new A(1);
	console.log(a instanceof A, a instanceof B, a instanceof Uint8Array); // should log true, false, true
	// Safari logs false, false, true

	var babel_out = {

	};

	return babel_out;

}());
```

This final bundle works fine on Chrome and Firefox. But not Safari. As Safari is ES6 compatible, so I removed all the core-js modules in babel output and bundled it again, as a result, Safari also prints the right output.

Then I put core-js modules back in one by one and found the culprit is `core-js/modules/es.typed-array.uint8-array`.

To be clear, this is tested with core-js 3.3.5. Please see the package.json and yarn.lock in the linked repo for the complete dependency.

**Comment by majksner** [comment]
I'm still experiencing this issue in Safari with the latest version of core-js.

Removing code below fixes the issue.

```
import 'core-js'
import 'regenerator-runtime/runtime'
```

![Screen Shot 2019-12-02 at 15 08 00](https://user-images.githubusercontent.com/512355/69965914-949c7700-1515-11ea-8841-62a0a7213946.png)
