### ISSUE TITLE
Add polyfill for Object.constructor.prototype.name

### ISSUE THREAD

**Issue by binarykitchen** [zloirock/core-js#685]
Any code which has Object.constructor.prototype.name is breaking on IE11 which hasn't reachend EOL yet.

Turns out core-js isn't polyfilling or transpiling it into IE11 compatible ES5 code. Would be good to add yeah?

**Comment by zloirock** [comment]
What do you mean? [It's available and works fine.](https://github.com/zloirock/core-js/blob/v3.3.6/packages/core-js/modules/es.function.name.js)

**Comment by binarykitchen** [comment]
Ah, my bad. Thanks for pointing to this!

Wondering how I can include only this es.function.name.js only without anything else?

**Comment by zloirock** [comment]
`core-js/es/function/name`?
