### ISSUE TITLE
Can I disable redefine.js when I cannot redefine the Function.prototype?

### ISSUE THREAD

**Issue by wss534857356** [zloirock/core-js#688]
Some runtime environments disable redefinition based on security considerations.

In addition, redefining the toString method does not seem to have a real impact, and no function will depend on the return value of this method.

```js
...
// add fake Function#toString for correct work wrapped methods / constructors with methods like LoDash isNative
})(Function.prototype, 'toString', function toString() {
  return typeof this == 'function' && getInternalState(this).source || nativeFunctionToString.call(this); // <---- this line
});
```

**Comment by zloirock** [comment]
`core-js` is a polyfill, it should patch built-ins. `core-js` architecture does not allow disabling replacing of `Function#toString`. Maybe in the future.

You can use the version without global namespace pollution, `core-js-pure`.

**Comment by wss534857356** [comment]
Thanks!
