### ISSUE TITLE
isInteger is returning isFinite

### ISSUE THREAD

**Issue by bathos** [zloirock/core-js#69]
Native:

    > Number.isInteger(3.14)
      false

Core JS (via Babel runtime):

    > _Number$isInteger(3.14)
      true
    > _Number$isInteger
      [Function: isFinite]

The relevant code seems to be here, where isFinite is the export value: https://github.com/zloirock/core-js/blob/05fdc711efa07aaa412a18189903f37a1458cadc/fn/number/is-integer.js

**Comment by zloirock** [comment]
Thanks! Will be fixed in next release.
