### ISSUE TITLE
/node_modules/core-js/postinstall works only with unsafe-perm=true

### ISSUE THREAD

**Issue by belqit** [zloirock/core-js#698]
![image](https://user-images.githubusercontent.com/44238749/68862105-c5427b00-06e4-11ea-9099-c2a7034b1956.png)
how can I solve this?

**Comment by zloirock** [comment]
Could you check it with the current version?

**Comment by zloirock** [comment]
Closed due to lack of response. Most likely, the current approach should not cause this issue.

**Comment by belqit** [comment]
Hi, sorry but it still happens on current version

![image](https://user-images.githubusercontent.com/44238749/69625390-6105ac80-103e-11ea-8b55-6cdd6a01939c.png)

**Comment by zloirock** [comment]
2.6.10 is not the current version - it's obsolete and unmaintained.

**Comment by belqit** [comment]
you're right package.json was updated but package-lock.json still point to 2.6.4

I deleted package-lock.json and it works, thanks

**Comment by zloirock** [comment]
Maybe later I'll release `2.6.11`. Your screenshot shows that it works fine with `3.4.2`.
