### ISSUE TITLE
Proposal: tag creation optimization

### ISSUE THREAD

**Issue by tailot** [zloirock/core-js#699]
Creating the html code is probably inefficient with string concatenation in https://github.com/zloirock/core-js/blob/master/packages/core-js/internals/create-html.js 
It might be a good idea to use the "literals templates" available in es2015 ?

Examples:
```
  var p1 = `<${ tag }`;
  if (attribute !== '') p1 += ` ${ attribute }="${ String(value).replace(quot, '&quot;') }"`;
  return `${ p1 }>${ S }</${ tag }>`;
```

Vincenzo

**Comment by nicolo-ribaudo** [comment]
I don't see why string concatenation should be inefficient: afaik they are one of the most optimized parts in engines.

**Comment by tailot** [comment]
@nicolo-ribaudo Ha ok, Thank you for the valuable information!  It’s probably just more elegant.

**Comment by zloirock** [comment]
Thanks for the proposal, but `core-js` is written in ES3 for better optimization, so it's inapplicable. Maybe in the future, the source version of `core-js` will be rewritten to the modern syntax, but not soon.
