### ISSUE TITLE
Promises `finally` method

### ISSUE THREAD

**Issue by fdubost** [zloirock/core-js#70]
I have noticed that the `finally` method for Promises isn't implemented. Is there any reason?

**Comment by zloirock** [comment]
Currently, `core-js` `Promise` implementation - only [ES6 `Promise`](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-promise-constructor) + [unhandled rejection tracking](https://gist.github.com/benjamingr/0237932cee84712951a2) (but it's not polyfilled for native `Promise`). `.finally` / `.done` methods missing in the spec, see discussions https://github.com/domenic/promises-unwrapping/issues/18, https://github.com/domenic/promises-unwrapping/issues/19. I thought about adding these as non-standard method, but I do not think it's needed.

**Comment by fdubost** [comment]
Thank you :smiley:
