### ISSUE TITLE
ERROR in ./node_modules/core-js/modules/es.regexp.exec.js 1:2 Module parse failed: Unexpected character '�' (1:2)

### ISSUE THREAD

**Issue by Alecgodwin** [zloirock/core-js#700]
after installing core-js@3 it works well at first then immediately after turning off the network and running npm run start. it throws the following error: 
```
ERROR in ./node_modules/core-js/modules/es.regexp.exec.js  1:2
Module parse failed: Unexpected character '�' (1:2)
```
when i proceed to check the file it just displays a series of unknown characters.

**Comment by zloirock** [comment]
I don't see anything related https://github.com/zloirock/core-js/blob/v3.4.1/packages/core-js/modules/es.regexp.exec.js - try to clean `node_modules` and reinstall dependencies.

**Comment by Alecgodwin** [comment]
Thanks. I have done that a couple of times but i keep getting the same error. its always the same file that throws the error

**Comment by Alecgodwin** [comment]
Thanks I copied the file from  github and replaced the corrupted file.. Do you have any idea what might have been corrupting the file. I use vs code thanks

**Comment by zloirock** [comment]
Seems it's the problem with your cache / proxy.

**Comment by PelumiWeb** [comment]
> Thanks I copied the file from github and replaced the corrupted file.. Do you have any idea what might have been corrupting the file. I use vs code thanks

Hello, please how do you know the corrupted file, because, I can't find it here.
