### ISSUE TITLE
Module not found: Can't resolve 'core-js/modules/es7.string.pad-end' in '/node_modules/fetch-mock/es5'

### ISSUE THREAD

**Issue by kopax** [zloirock/core-js#706]
I am having this error, when trying to run the react-admin 3.0.1 demo.

I have tested with `core-js` 3.4.3 and 3.4.4, both does not have this file.

When was it removed? I am using react-admin 3.0.1.

**Comment by zloirock** [comment]
`core-js/modules/es7.string.pad-end` comes from `core-js@2-`. It was renamed in `core-js@3.0` to `core-js/modules/es.string.pad-end`. It's a major release with breaking changes -)
