### ISSUE TITLE
Consider wider CI recognition

### ISSUE THREAD

**Issue by yomed** [zloirock/core-js#707]
Hi, I noticed that the postinstall script attempts to recognize CI before showing the banner. It would be great if this supported a wider range of CI services, since not all of them use the `CI` environment variable.
https://github.com/zloirock/core-js/blob/5a66505301b64d13f7bcf96b1e9ab55e4ff35fe6/packages/core-js/postinstall.js#L8

There are packages that help support more CI services:
https://github.com/watson/ci-info#api

I can submit a PR if we are ok making this change. Thanks!

**Comment by zloirock** [comment]
The problem that `core-js` should be zero dependencies. However, I'll take a look at [this](https://github.com/watson/ci-info/blob/master/index.js#L52-L59), thanks.

**Comment by zloirock** [comment]
Feel free to improve it.

**Comment by yomed** [comment]
Thank you!
