### ISSUE TITLE
$.g is undefined

### ISSUE THREAD

**Issue by askaza** [zloirock/core-js#71]
Hi!
I have issue in FF and Chrome (both last versions):

'TypeError: $.g is undefined store = $.g[SHARED] || $.hide($.g, SHARED, {})[SHARED];

As I understood it's a part of core-js modules.
I'm using:
Windows 7
node: '0.12.0',
babel-runtime 5.4.7
babelify 6.0.2
react 0.13.3

Sorry, can't show you working example. How this issue could be fixed?

**Comment by zloirock** [comment]
In my tests all works correct with `webpack` / `browserify`. `$.g` should be global object. I can not understand the problem without reproducible example.

**Comment by askaza** [comment]
Ok, will try to create exampe, thank you!
In Crome I see this error:
'Uncaught TypeError: Cannot read property '__core-js_shared__' of undefined'

**Comment by zloirock** [comment]
The most likely problem with your build system - [`require`](https://github.com/zloirock/core-js/blob/v0.9.13/modules/%24.shared.js#L1) or [detection `global`](https://github.com/zloirock/core-js/blob/v0.9.13/modules/%24.js#L2).

**Comment by askaza** [comment]
thank you and sorry for disturbing
seems it was babel-runtime bug, removed it
