### ISSUE TITLE
MODULE_NOT_FOUND in @babel/cli/bin/babel.js => node_modules/core-js-compat/helpers.js:3:14)

### ISSUE THREAD

**Issue by kopax** [zloirock/core-js#711]
## Bug Report

We are experience errors on all our projects since a few minutes, we are still investigating

**Current Behavior**

`core-js` or `babel` is having issue to run babel build, this happen on all our projects that use babel and we are still investigating

**Input Code**
- REPL or Repo link if applicable: https://github.com/bootstrap-styled/provider

```js
> BABEL_ENV=production babel --out-dir lib src --copy-files

Error: Cannot find module './src/data'
Require stack:
- /home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/core-js-compat/helpers.js
- /home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/core-js-compat/get-modules-list-for-target-version.js
- /home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/preset-env/lib/index.js
- /home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/core/lib/config/files/plugins.js
- /home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/core/lib/config/files/index.js
- /home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/core/lib/index.js
- /home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/cli/lib/babel/options.js
- /home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/cli/lib/babel/index.js
- /home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/cli/bin/babel.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:800:15)
    at Function.Module._load (internal/modules/cjs/loader.js:693:27)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/core-js-compat/helpers.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32)
    at Function.Module._load (internal/modules/cjs/loader.js:730:14)
    at Module.require (internal/modules/cjs/loader.js:864:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/core-js-compat/helpers.js',
    '/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/core-js-compat/get-modules-list-for-target-version.js',
    '/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js',
    '/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/preset-env/lib/index.js',
    '/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/core/lib/config/files/plugins.js',
    '/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/core/lib/config/files/index.js',
    '/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/core/lib/index.js',
    '/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/cli/lib/babel/options.js',
    '/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/cli/lib/babel/index.js',
    '/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/cli/bin/babel.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @bootstrap-styled/provider@1.5.2 build:lib: `BABEL_ENV=production babel --out-dir lib src --copy-files`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @bootstrap-styled/provider@1.5.2 build:lib script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dka/.npm/_logs/2019-12-02T18_02_24_436Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @bootstrap-styled/provider@1.5.2 build: `npm run build:lib && npm run build:dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @bootstrap-styled/provider@1.5.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dka/.npm/_logs/2019-12-02T18_02_24_446Z-debug.log

```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
module.exports = {
  only: [
    'src',
    'styleguide',
  ],
  presets: [
    [
      '@babel/preset-env',
      {
        modules: false,
      },
    ],
    '@babel/preset-react',
  ],
  plugins: [
    'styled-components',
    '@babel/plugin-syntax-dynamic-import',
    '@babel/plugin-syntax-import-meta',
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-proposal-json-strings',
    [
      '@babel/plugin-proposal-decorators',
      {
        legacy: true
      }
    ],
  ],
  env: {
    production: {
      plugins: [
        'add-module-exports',
        '@babel/plugin-transform-modules-commonjs',
      ],
    },
    test: {
      plugins: [
        '@babel/plugin-transform-modules-commonjs',
        'dynamic-import-node',
      ],
    },
  },
};

```

**Environment**

```

```
- Babel version(s): 7.7.4
- Node/npm version: v13.0.1
- OS: Debian buster
- Monorepo: no
- How you are using Babel: cli

**Possible Solution**

Not yet

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nicolo-ribaudo** [comment]
This bug was introduced a few hours ago in v3.4.6, but has already been fixed in v3.4.7.

**Comment by kopax** [comment]
There is still `const data = require('./src/data');` that does issue here `/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/core-js-compat/helpers.js` 

`src` is not published

**Comment by nicolo-ribaudo** [comment]
That was in 3.4.6.

3.4.7 looks like this: https://unpkg.com/browse/core-js-compat@3.4.7/helpers.js

**Comment by kopax** [comment]
How should I update my project? I am not using those dependency in my `package.json`, they are subdeps.

**Comment by nicolo-ribaudo** [comment]
Yarn or npm?

**Comment by nicolo-ribaudo** [comment]
Try `npm --depth 999 update core-js`

**Comment by genestd** [comment]
> That was in 3.4.6.
> 
> 3.4.7 looks like this: https://unpkg.com/browse/core-js-compat@3.4.7/helpers.js
> 
> Could you check `/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/core-js-compat/package.json`?

But `./data` does not exist in the file structure

**Comment by nicolo-ribaudo** [comment]
It does. https://unpkg.com/browse/core-js-compat@3.4.7/data.json

**Comment by kopax** [comment]
> > That was in 3.4.6.
> > 3.4.7 looks like this: https://unpkg.com/browse/core-js-compat@3.4.7/helpers.js
> > Could you check `/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/core-js-compat/package.json`?
> 
> But `./data` does not exist in the file structure

This is true: https://github.com/zloirock/core-js/tree/v3.4.7/packages/core-js-compat

Maybe it's a wise idea to add some sort of testing and code building when adding such change

**Comment by kevinmarrec** [comment]
**3.4.7** has failed to build, I think it's why we're not be able to download it ? (I'm using `yarn` and it keeps installing **3.4.6**.

**Comment by kevinmarrec** [comment]
![image](https://user-images.githubusercontent.com/25272043/69984025-5d8b8d00-1538-11ea-9348-d58976aaf26e.png)

**Comment by nicolo-ribaudo** [comment]
It's on the registry (https://www.npmjs.com/package/core-js-compat)
If it isn't working it's probably because of a proxy/cache between you and the npm registry which isn't updated yet.

**Comment by kopax** [comment]
it is fixed for me

**Comment by alexandrebodin** [comment]
Yep probably need some time to propagate this version. Still getting 3.4.6 for now

**Comment by nicolo-ribaudo** [comment]
As a workaround, you could add `"core-js-compat": "3.4.5"` to your dependencies.

**Comment by barraponto** [comment]
I thought `npm cache clean --force` would have `npm install` notice the newer version but it didn't work. What worked was explicitly installing 3.4.7 `npm install core-js-compat@3.4.7`, then removing the entry from package.json, removing package-json.lock and running `npm install` to regenerate the  lock file.

**Comment by kevinmarrec** [comment]
`3.4.7` is now correctly installed with `yarn`.
