### ISSUE TITLE
Cannot find module ./src/data

### ISSUE THREAD

**Issue by mikemak-es** [zloirock/core-js#712]
Hello, 

my rollup builds have suddenly started failing...

i get the attached screenshot, and when i look in the related node_modules folder i can see `core-js-compat/helpers.js` is trying to require a file/folder that does not exist. Can anyone help out?

I know there's a lot of info you may require... please let me know what you need - but i hope it's just a case of not requiring a file that doesn't exist.

![image](https://user-images.githubusercontent.com/1919297/69985834-ef44cb80-1533-11ea-845c-9fcf1278edef.png)

**Comment by zloirock** [comment]
It's fixed in `3.4.7`.

**Comment by wilforlan** [comment]
Installing this module says
```
➜  loadbalancer-ff git:(master) ✗ npm i core-js@3.4.7
npm ERR! code ETARGET
npm ERR! notarget No matching version found for core-js@3.4.7
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
```

@mikemak-es @zloirock has this been pushed?

**Comment by nicolo-ribaudo** [comment]
Yes, it's on npm: https://www.npmjs.com/package/core-js-compat/v/3.4.7

Likely it's a proxy/cache between you and the registry which hasn't been updated yet.

**Comment by Ju66ernaut** [comment]
Is there a way to force update the package to 3.4.7? I get the same error @wilforlan got

**Comment by BlueSeph28** [comment]
I can confirm this. I can't install version 3.4.7
>No matching version found for core-js-compat@3.4.7

I used 
>npm cache clean --force
And still the same. A workaround could be only wait?

**Comment by nicolo-ribaudo** [comment]
Ref - https://github.com/npm/cli/issues/545
Please :+1: that issue.

**Comment by JoshuaCollis** [comment]
running nom show core-js tells me I am running version 3.4.7.  However, I still get the following error when building
```Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
[BABEL] /Users/joshua/Documents/Projects/---/---/src/main.js: Cannot find module './src/data' (While processing: "/Users/joshua/Documents/Projects/---/---/node_modules/@vue/cli-plugin-babel/
preset.js")
    at PoolWorker.fromErrorObj (/Users/joshua/Documents/Projects/---/---/node_modules/thread-loader/dist/WorkerPool.js:262:12)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/joshua/Documents/Projects/---/---/node_modules/core-js-compat/helpers.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

 @ multi ./src/main.js

**Comment by roadstar93** [comment]
I used npm i core-js-compat@3.4.7 --save  to force update it

**Comment by JoshuaCollis** [comment]
> I used npm i core-js-compat@3.4.7 --save to force update it

This fixed it for me, thank you!
