### ISSUE TITLE
core-js-compat@3.4.6 (latest version) is broken

### ISSUE THREAD

**Issue by simllll** [zloirock/core-js#713]
I guess "data" is missing? probably because src is not exported (haven't checked though). I've seen you just made some commits regarding this... just wanted to let you know that the current release has this issue.

```
Cannot find module './src/data'
Require stack:
- /buddy/hokify-pwa/node_modules/core-js-compat/helpers.js
- /buddy/hokify-pwa/node_modules/core-js-compat/get-modules-list-for-target-version.js
- /buddy/hokify-pwa/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
```

Thanks a lot,

Best Regards

**Comment by zloirock** [comment]
It was fixed in `3.4.7`.

**Comment by simllll** [comment]
Ah it seems this is fixed in 3.4.7
see  #710

but can't find this version on npm yet

**Comment by contra** [comment]
@simllll NPM cache is taking an excruciatingly long time to update.

**Comment by nicolo-ribaudo** [comment]
Ref - https://github.com/npm/cli/issues/545

**Comment by esetnik** [comment]
Something must be wrong with npm. Their status page is all green but the package has been live for over 1 hour. Strangely enough `npm view` returns the correct version.

```
❯ npm view core-js

core-js@3.4.7 | MIT | deps: none | versions: 167
Standard library
https://github.com/zloirock/core-js#readme

keywords: ES3, ES5, ES6, ES7, ES2015, ES2016, ES2017, ES2018, ES2019, ES2020, ECMAScript 3, ECMAScript 5, ECMAScript 6, ECMAScript 7, ECMAScript 2015, ECMAScript 2016, ECMAScript 2017, ECMAScript 2018, ECMAScript 2019, ECMAScript 2020, Harmony, Strawman, Map, Set, WeakMap, WeakSet, Promise, Observable, Symbol, TypedArray, URL, URLSearchParams, queueMicrotask, setImmediate, polyfill, ponyfill, shim

dist
.tarball: https://registry.npmjs.org/core-js/-/core-js-3.4.7.tgz
.shasum: 57c35937da80fe494fbc3adcf9cf3dc00eb86b34
.integrity: sha512-qaPVGw30J1wQ0GR3GvoPqlGf9GZfKKF4kFC7kiHlcsPTqH3txrs9crCp3ZiMAXuSenhz89Jnl4GZs/67S5VOSg==
.unpackedSize: 648.9 kB

maintainers:
- zloirock <zloirock@zloirock.ru>

dist-tags:
alpha: 3.0.0-alpha.4  beta: 3.0.0-beta.20   latest: 3.4.7

published an hour ago by zloirock <zloirock@zloirock.ru>

``

**Comment by simllll** [comment]
I manually edited my package and pacakge-lock files, specifying the exact version seems to fix this for now

**Comment by olegstepura** [comment]
@esetnik same here. `3.4.7` is not pulled as newer semver release for indirect dependencies:
```bash
$ rm package-lock.json; npm install; npm ls core-js-compat
...
@mypackage@1.0.0
└─┬ ember-auto-import@1.5.3
  └─┬ @babel/preset-env@7.7.4
    └── core-js-compat@3.4.6 
```

**Comment by al-the-x** [comment]
Caching? We had to dump `node_modules/.cache` in all environments to resolve, otherwise `npm` used the cached version of the package: 3.4.6

@zloirock when I last checked, 3.4.6 has not been deprecated. That could help.

**Comment by al-the-x** [comment]
And thanks so much for responding to this issue so quickly, @zloirock. We're still shaking out the caches here, but the re-release was super-fast. Nice work.

**Comment by elylucas** [comment]
Not sure if it was coincidence or a combination of me running npm cache clean --force / npm cache verify, but i finally got 3.4.7 to come down.

**Comment by zloirock** [comment]
@al-the-x deprecation can't help here. This version was unpublished but it seems it did not help for some users.

**Comment by nsberndt** [comment]
Just chiming in to say @3.4.7 is finally working now for me as well.

**Comment by olegstepura** [comment]
@elylucas `npm cache clear --force` did not help here...
But editing `package-lock.json` manually worked:
```json
    "core-js-compat": {
      "version": "3.4.7",
      "resolved": "https://registry.npmjs.org/core-js-compat/-/core-js-compat-3.4.7.tgz",
      "integrity": "sha512-57+mgz/P/xsGdjwQYkwtBZR3LuISaxD1dEwVDtbk8xJMqAmwqaxLOvnNT7kdJ7jYE/NjNptyzXi+IQFMi/2fCw==",
      "requires": {
        "browserslist": "^4.8.0",
        "semver": "^6.3.0"
      },
      "dependencies": {
        "semver": {
          "version": "6.3.0",
          "resolved": "https://registry.npmjs.org/semver/-/semver-6.3.0.tgz",
          "integrity": "sha512-b39TBaTSfV6yBrapU89p5fKekE2m/NwnDocOVruQFS1/veMgdzuPcnOM34M6CwxW8jH/lxEa5rBoDeUwu5HHTw=="
        }
      }
    },
```

**Comment by patlamontagne** [comment]
I went with olegstepura's solution and it worked.
