### ISSUE TITLE
core-js-compat missing files in distribution package

### ISSUE THREAD

**Issue by janstuemmel** [zloirock/core-js#714]
my parcel-bundler requires this version of `core-js-compat` in `package-lock.json`:

```json
"core-js-compat": {
  "version": "3.4.6",
  "resolved": "https://registry.npmjs.org/core-js-compat/-/core-js-compat-3.4.6.tgz",
  "integrity": "sha512-pSAGNy9InkZOld1sKtQnh+rB0lR2FIKYACoscaHvxRmLGV6YJ+1FtjQQwm92CFp8X3IJFWqDA4BtOE/8xu6QiQ==",
  "dev": true,
  "requires": {
    "browserslist": "^4.8.0",
    "semver": "^6.3.0"
  },
```

when i run parcel-bundler inside my lerna repository i get following error:

```
Error: Cannot find module './src/data'
Require stack:
- /home/user/code/repo/packages/client/node_modules/core-js-compat/helpers.js
...
```
if you download `https://registry.npmjs.org/core-js-compat/-/core-js-compat-3.4.6.tgz` and unzip this archiv, you will see that there's no `src/data.js` file, but `helpers.js` requires it.

**Comment by zloirock** [comment]
It was fixed in `3.4.7`.
