### ISSUE TITLE
ChildNode.remove() missing?

### ISSUE THREAD

**Issue by saschagehlich** [zloirock/core-js#718]
According to https://developer.mozilla.org/de/docs/Web/API/ChildNode/remove this is Living Standard, but not supported in IE. Would a polyfill in core.js make sense then?

**Comment by nicolo-ribaudo** [comment]
`core-js` only supports standard ECMAScript features (things that you can find, for example, in a browser, in nodejs and in an IoT device).

I suggest looking for a DOM polyfill for that function!
