### ISSUE TITLE
Uncaught TypeError: inspectSource is not a function

### ISSUE THREAD

**Issue by LukaszSawicki** [zloirock/core-js#719]
Hi,
after update core-js to version 3.4.5 I've got an error when using Promise.all() function.

`
Uncaught TypeError: inspectSource is not a function
    at Object../node_modules/core-js/internals/native-weak-map.js
    at __webpack_require__
    at Object../node_modules/core-js/internals/internal-state.js
    at __webpack_require__
    at Object../node_modules/core-js/internals/redefine.js
    at __webpack_require__
    at Object../node_modules/core-js/internals/export.js
    at __webpack_require__
    at Object../node_modules/core-js/modules/es.promise.js
    at __webpack_require__
`

I can see that there was an 'fix' for inspectSource in 3.4.5
`
Fixed inspectSource helper with multiple core-js copies and some related features like some edge cases of Promise feature detection
`

Before this update everything worked fine.

**Comment by zloirock** [comment]
It was fixed in `3.4.7`.

**Comment by zloirock** [comment]
Or not? Could you check it?

**Comment by zloirock** [comment]
Ok, I see one possible case - you use some copies of `core-js`, one of them - the previous version with broken `inspectSource` helper and your actual version inherit this helper.

**Comment by LukaszSawicki** [comment]
Okay, I found where the problem was: @babel/runtime-corejs3 was using an old copy of core-js-pure. Thanks for your answer.

**Comment by kamilic** [comment]
@zloirock This workaround works for me, what time you will publish this unreleased version?

**Comment by zloirock** [comment]
Soon.
