### ISSUE TITLE
Maybe it is not a proper way to create object with `null` prototype with using Iframe

### ISSUE THREAD

**Issue by aleen42** [zloirock/core-js#727]
Recently, I have found that when I used IE11 to simulate IE8, and required `core-js/stable` in an iframe, it throwed an error specifiying that `iframe.contentWindow` was not asscessible when the script was run in an iframe, where scripts were not allowed to execute.

I set the iframe with `sandbox="allow-scripts"`, but it seemed that IE 11 did not acted like what I expected. In true IE8, `sandbox` is not worked, and there is no problem when accessing `iframe.contentWindow`. Therefore, is there any alternative to create `Object` with `null` prototype without using iframe?

**Comment by zloirock** [comment]
Could you propose a better alternative? I don't see anything.

**Comment by zloirock** [comment]
We could try to add a `ActiveXObject`-based workaround.

**Comment by zloirock** [comment]
You could play with [it](https://github.com/es-shims/es5-shim/blob/ef78f316fee3eebc51a78f86f008bdac5b9790cf/es5-sham.js#L207-L242) and add a PR.

**Comment by aleen42** [comment]
OK, I'll try it next weekday
