### ISSUE TITLE
Error:  node -e "try{require('./postinstall')}catch(e){}"

### ISSUE THREAD

**Issue by dantn93** [zloirock/core-js#729]
Please fix this error. Three days ago, my project does not have any error. But now, it has some bug, the Popover in react-boostrap does not show where I want.
When I install packages, the terminal show:

![Screen Shot 2019-12-16 at 16 56 53](https://user-images.githubusercontent.com/20403819/70898004-5e3b1d80-2026-11ea-99b8-962a64f9412f.png)

**Comment by zloirock** [comment]
I don't see any errors. What do you mean?

**Comment by dantn93** [comment]
I don't know why it is. But I thinks it makes my source code be incorrect. If this is not the reason, I will close this issue. Thanks for your support.

**Comment by zloirock** [comment]
Seems it's not the reason.

**Comment by thisiskylierose** [comment]
I have the same issue on Windows 7. The issue seems to be with core-js postinstall script. 

At the moment, it is not possible to install react-scripts package. Or any package that relies on core-js postinstall script.

**Comment by jerome-fl** [comment]
If it can be of any help, after a few hours of research, I solved this error by just cancelling Node debugger which I activated in `NODE_OPTIONS` env var, set with `--inspect`.
After an `export NODE_OPTIONS=""`, I didn't have this issue anymore.

**Comment by gauthamshettykaup** [comment]
**Even I getting above message/warning:**

> core-js@2.6.11 postinstall E:\Hitachi_Vantara\Code\Front_End\Eris\node_modules\babel-runtime\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@3.6.5 postinstall E:\Hitachi_Vantara\Code\Front_End\Eris\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js-pure@3.6.5 postinstall E:\Hitachi_Vantara\Code\Front_End\Eris\node_modules\core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

**Comment by kanchanpriya17** [comment]
same error with my code i don't understand how to resolve this create-react-app doen't work because of this

![image](https://user-images.githubusercontent.com/66526883/92014785-6b8f6800-ed6d-11ea-95b4-d0f5fb74e42e.png)

**Comment by JOEMICS03** [comment]
> same error with my code i don't understand how to resolve this create-react-app doen't work because of this
> 
> ![image](https://user-images.githubusercontent.com/66526883/92014785-6b8f6800-ed6d-11ea-95b4-d0f5fb74e42e.png)

same error found any fix!!!

**Comment by janmauler** [comment]
> Seems it's not the reason.

It most certainly is the reason. What's the solution? Updating `core-js` won't help. There's always a postinstall script error breaking any project that uses webpack/babel.

**Comment by reifnotreef** [comment]
Just ran in to this error today when trying to `npm i -g expo-cli`  

![image](https://user-images.githubusercontent.com/4626724/108737878-a55d5200-74f8-11eb-87f9-3e18558ec5fd.png)  
Not sure why I would be seeing a "Permission denied" as I'm logged in as root.  
I am using VS Code and ssh'd in to a DigitalOcean droplet running Ubuntu.
