### ISSUE TITLE
Maps not getting loaded in Internet Explorer 11

### ISSUE THREAD

**Issue by trmalhotra16** [zloirock/core-js#731]
Google maps API is not showing maps and throwing error in console of Internet Explorer 11, while it is working perfectly fine in other browsers. 

**SCRIPT5005: String expected 
js(50,286)**

I am using maps API version 3.14 & 3.36, but both are giving same error. Is there any known bug which is causing this issue?

**Comment by zloirock** [comment]
Seems it's a bug of Google Maps, see #618, #619, #566, #567. You should load `core-js` before Google Maps.
