### ISSUE TITLE
Please stop with the spam.

### ISSUE THREAD

**Issue by karolsw3** [zloirock/core-js#734]
**Is this a joke?**

<img width="908" alt="Screenshot 2019-12-18 at 21 47 24" src="https://user-images.githubusercontent.com/1695865/71122058-047e5300-21e0-11ea-909e-8706ff47a394.png">
You're completely ruining thousands of console logs with these messages. This spam is just inappropriate. Please stop doing it. This dependence is a pile of complete rubbish with these messages.

_(Yup, you can add that "spam" label and continue being selfish, or just finally resolve this issue. Your choice.)_

**Comment by zloirock** [comment]
Please stop writing bullshit, use search, update your version to the actual a don't spam in this repo.
