### ISSUE TITLE
TypeError: getBuiltIn(...) is not a constructor

### ISSUE THREAD

**Issue by piranna** [zloirock/core-js#737]
https://github.com/zloirock/core-js/blob/f10bf27fa665cde29e549262da977946557c84b4/packages/core-js/modules/esnext.promise.any.js#L38

I'm using `Promise.any()`, and when passing my project tests with `babel-jest` I get the `TypeError: getBuiltIn(...) is not a constructor` error. Seems like it interpret `getBuiltIn` function as the constructor, instead of respect the parenthesis and use as constructor the result of the call to `getBuiltIn('AggregateError')`.

# .babelrc
```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "corejs": {
          "proposals": true,
          "version": 3
        },
        "useBuiltIns": "usage"
      }
    ]
  ]
}
```

# .browserslist
```txt
defaults
maintained node versions
```

# package.json
```json
{
  "devDependencies": {
    "@babel/cli": "^7.7.7",
    "@babel/preset-env": "^7.7.7",
    "babel-eslint": "^10.0.3",
    "babel-jest": "^24.9.0",
    "eslint": "^6.8.0",
    "jest-cli": "^24.9.0",
    "prettier": "^1.19.1"
  },
  "dependencies": {
    "core-js": "^3.6.0"
  }
}
```

**Comment by zloirock** [comment]
The problem in built-ins definitions on the Babel side - on `Promise.any` should be injected also `esnext.agregate-error` module. So, please, open this issue in the Babel repo.

**Comment by piranna** [comment]
> The problem in built-ins definitions on the Babel side - on `Promise.any` should be injected also `esnext.agregate-error` module.

You are right, by changing `useBuiltIns` to `entry` and adding

```js
require("core-js/modules/esnext.aggregate-error");
require("core-js/modules/esnext.promise.any");
```

at the top of the file (I know should not use `modules` directly, it was just a check) it works. Seems like `getBuiltIn('AggregateError')` is returning `undefined`, not sure if it should throw an exception with a clear message, or do a check before using the returned value...

> So, please, open this issue in the Babel repo.

Done at https://github.com/babel/babel/issues/10910

**Comment by piranna** [comment]
This got fixed in https://github.com/babel/babel/pull/10930, thanks for the suggestion of writting them :-)
