### ISSUE TITLE
IE8 and FF3.6.28 parse error for core-js/es5

### ISSUE THREAD

**Issue by seeden** [zloirock/core-js#74]
when I use core-js/es5 I can see error in the console (IE8, ff 3.6.28): Accessors not supported.

The problem is with this line:
if('get' in Attributes || 'set' in Attributes)throw TypeError('Accessors not supported!');

Do you have any advice how to avoid it?
Thanks a lot

**Comment by zloirock** [comment]
Looks like you uses `Object.defineProperty` / `Object.defineProperties` / `Object.create` with getters / setters. In ES3 is no way to add assessors, so we generate this error.
