### ISSUE TITLE
2.6.11 broke babel on Node v4

### ISSUE THREAD

**Issue by simov** [zloirock/core-js#740]
Just FYI things like:

```json
"babel-cli": "^6.26.0",
"babel-polyfill": "^6.26.0",
"babel-preset-env": "^1.7.0",
```

with

```json
{
  "presets": [
    ["env", {
      "targets": {
        "node": "4.0.0"
      }
    }]
  ]
}
```

no longer work.

It throws on missing `Array.prototype.includes` introduced in Node v6. I fixed that but then even more things broke ..

Anyway, I'll be deprecating Node v4 in my module, but I wanted to be when I'm ready with my major, so for the time being I just patched my build script with this:

```bash
# fix for Node v4
rm -rf node_modules/core-js
npm i core-js@2.6.10 --no-save
```

**Comment by zloirock** [comment]
Maybe because you haven't `useBuiltIns` option in your Babel config or direct `core-js` / `babel-polyfill` import?
