### ISSUE TITLE
No matching version found for browserslist@^4.8.3.

### ISSUE THREAD

**Issue by BulldogCTISolutions** [zloirock/core-js#742]
According to npmjs  core-js-compat was updated yesterday

When I execute npm install on my project I get this error:

npm ERR! code ETARGET
npm ERR! notarget No matching version found for browserslist@^4.8.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'core-js-compat'
npm ERR! notarget

Worked fine yesterday morning, not today.  I attached my npm dependency stack and install log and package.json.

Looking for which versions of which dependency to downgrade.

Thanks,
--jay

[npm_dependency_stack.txt](https://github.com/zloirock/core-js/files/4033011/npm_dependency_stack.txt)
[npm_install.log](https://github.com/zloirock/core-js/files/4033012/npm_install.log)

[package.json.txt](https://github.com/zloirock/core-js/files/4033014/package.json.txt)

**Comment by zloirock** [comment]
It's available on NPM:
![image](https://user-images.githubusercontent.com/2213682/71956777-9a752e80-321e-11ea-85bd-315043d0b6cf.png)
So the problem on your side. You try cleaning the NPM cache.

**Comment by BulldogCTISolutions** [comment]
Unfortunately, I had already tried to install browserslist and I still get the same error.  I had also deleted the node_modules directory beforehand too.

Installing browserslist with the command above, installs version 4.8.2.  However, core-js-compat is specifically requiring 4.8.3 - as noted in the dependency stack.

I manually adjusted my package.json to 4.8.3 and I still have the same problem.

Was there a specific reason for core-js-compat to upgrade browserslist?

Thanks
--jay

**Comment by zloirock** [comment]
> Was there a specific reason for `core-js-compat` to upgrade `browserslist`?

Because it's the actual version on this package.

**Comment by BulldogCTISolutions** [comment]
Thanks, it seems that clearing npm cache and pointing to the npmjs.org registry fixed the issue.
