### ISSUE TITLE
version 3.6.2 causes the following error in IE11 

### ISSUE THREAD

**Issue by alanbentley** [zloirock/core-js#746]
cannot redefine non-configurable property 'find'

**Comment by zloirock** [comment]
If in IE11 `.find` is non-configurable that means that in addition to `core-js` used another polyfill, incorrect, which defines non-configurable `.find` method.

**Comment by zloirock** [comment]
Maybe related to #702 - MDN loves to propose buggy polyfills which should not be used in real life.

**Comment by alanbentley** [comment]
Thanks for the explanation, looks like I'm going to have a fun time identifying the culprit :)

**Comment by zloirock** [comment]
Since it seems as not a `core-js` bug, closed.
