### ISSUE TITLE
3.6.3: setGlobal is not a function

### ISSUE THREAD

**Issue by phaistonian** [zloirock/core-js#748]
Hello.

As of 3.6.3, when building using webpack (production) I get a `setGlobal is not a function` error.

Not sure what this is about, but falling back to 3.6.2 does the trick.

**Comment by zloirock** [comment]
`core-js` should not be transpiled, but it seems you do it. [`setGlobal` definitely a function.](https://github.com/zloirock/core-js/blob/acc2d72c64eb7c026bcb8a3653438a3702c4585a/packages/core-js/internals/set-global.js#L4-L10)

**Comment by phaistonian** [comment]
@zloirock Transpiling core-js triggered this issue, indeed.

Thank you.
