### ISSUE TITLE
Importing core-js/modules/es.promise causes Promise.finally to be undefined

### ISSUE THREAD

**Issue by plaa** [zloirock/core-js#749]
I am using [Storybook](https://storybook.js.org/) with React Native. I discovered that after Storybook was imported `Promise.prototype.finally` became undefined.  I hunted the problem down to Storybook performing:

    import 'core-js/modules/es.promise';

Before the import `Promise.prototype.finally` is a function, after the import it is undefined (but other promise functions work as expected).  [Example repo](https://github.com/plaa/CoreJsPromiseBug).

I tried also `import 'core-js/features/promise'` - this changes `Promise.prototype.finally` from a JS function to native code function and seems to work.

I am unsure whether this is a bug in core-js or in the way Storybook is using core-js.

**Comment by zloirock** [comment]
Yes, with the current logic also should be imported `core-js/modules/es.promise.finally`. `/modules/` path not for direct usage - it should be used by entry points like `core-js/es/promise` or tools like `@babel/preset-env` and it should inject required modules.

**Comment by plaa** [comment]
In case someone else hits this, I eventually found [Storybook #8371](https://github.com/storybookjs/storybook/issues/8371). If I understand it correctly, Storybook includes incorrect polyfills in the RN code due to build issues.

Thanks.
