### ISSUE TITLE
Track updated spec for Promise.resolve()

### ISSUE THREAD

**Issue by cscott** [zloirock/core-js#75]
TC39 agreed to get rid of the hidden [[PromiseConstructor]] property from the spec and simplify `Promise.resolve`.  The adopted proposal also makes `Promise.resolve` ignore "species":

https://esdiscuss.org/topic/fixing-promise-resolve

Opening an issue to track core-js adopting the new semantics.

**Comment by cscott** [comment]
Whoa, you read my mind: https://github.com/zloirock/core-js/commit/af723a1bd7212183d7d7b1030ef77caeedf035ee

**Comment by zloirock** [comment]
In this commit I didn't remove `@@species` logic from `Promise.resolve` - it creates some compatibility problems with other methods, I wanted to wait meeting notes, but ok - I'll change this logic too.
