### ISSUE TITLE
Core-js chrome 41 - .trim() undefined

### ISSUE THREAD

**Issue by jcdsr** [zloirock/core-js#750]
I have an issue with core-js we use angular universal v8 as SSR 

We have an issue with google search console, seems search-console uses chrome v41 when testing the url and rendering, and when we load our site the javascript info on the page shows an error with  .trim() undefined.

If we have an error on the google search console the page won't be indexed. So this error is critical

We also remove all the .trim() on our project and the error still showing up. So we are struggling to find the solution. Any ideas what the cause? or what do I need to include?
 
**package.json**
"core-js": "~3.6.3",

**polyfills.ts - we load this**
import "core-js/stable";
import 'core-js/es/reflect';
import 'event-source-polyfill/src/eventsource.min.js'
import 'js-polyfills/polyfill.min.js'
import 'web-animations-js'; 
(window as any).__Zone_disable_requestAnimationFrame = true; // disable patch requestAnimationFrame
(window as any).__zone_symbol__UNPATCHED_EVENTS = ['resize'];
import 'zone.js';

**ERROR**
![image](https://user-images.githubusercontent.com/4386097/72268102-1ef9ef80-3619-11ea-8b17-2cb9ecd428c6.png)

**Comment by zloirock** [comment]
Are you sure that it's a `core-js` issue, before `core-js` it existed and immediately after `core-js` import it's `undefined`?

**Comment by zloirock** [comment]
Looking to your stack trace, you try to access `.trim` of `undefined`, not a string, so it's not a `core-js` issue.
