### ISSUE TITLE
Please remove the post install script

### ISSUE THREAD

**Issue by pronebird** [zloirock/core-js#757]
Hi,

It's absolutely terrific that you're looking for a job, but please do not do this via `postinstall` script. There are job boards, meetups where you can connect with others, LinkedIn, and so forth. 

```
>> node -e "try{require('./postinstall')}catch(e){}"
```

Cheers,
Andrej

**Comment by veeral-patel** [comment]
@pronebird Hey! Looking at other issues in the repository, the maintainer has said that he won't remove the postinstall message, to spite people who want to remove it and maybe for financial reasons as well -- he's mentioned he'll be going to prison in a couple days.

Correct me if I'm wrong @zloirock

**Comment by ljmerza** [comment]
where did you see this? If that's true I hope someone forks this projects and takes it from him

**Comment by veeral-patel** [comment]
https://github.com/zloirock/core-js/issues/747#issuecomment-573318269

https://github.com/zloirock/core-js/issues/548#issuecomment-494112872

@ljmerza

**Comment by veeral-patel** [comment]
@pronebird agree with your original comment. I don't mind the postinstall message, considering all the work he's put into this library for free, but I worry that continuously saying he wants a good job undermines him. I'd expect he be in high demand considering he's authoring a standard library for Javascript, no small undertaking, and I hope this doesn't hurt him.

**Comment by ljmerza** [comment]
well considering he was committing on a almost daily basis then went silent 12 days ago i would imagine this project just died. here's to hoping babel or someone else takes this over. he sounded like a real winner

**Comment by Kein** [comment]
> [#747 (comment)](https://github.com/zloirock/core-js/issues/747#issuecomment-573318269)
> [#548 (comment)](https://github.com/zloirock/core-js/issues/548#issuecomment-494112872)
> @ljmerza

Since he is from Russia - I dont think he was joking at all.

**Comment by slowcheetah** [comment]
@Kein this is not a joke.
@zloirock will be unavailable for some time. 
[Here](https://github.com/zloirock/core-js/issues/548#issuecomment-494112872) he clearly expressed his opinion on this issue.
Closed.

**Comment by Daniel15** [comment]
> well considering he was committing on a almost daily basis then went silent 12 days ago i would imagine this project just died. here's to hoping babel or someone else takes this over. he sounded like a real winner

@ljmerza just because a project hasn't received commits in two weeks doesn't mean it's dead. People have commitments other than open source work that doesn't make them any money. Also, there is such a thing as a project being 'complete'. Some projects go years between major updates, and that's fine. In fact, often I much prefer libraries that are stable and move slowly.

**Comment by ljmerza** [comment]
Yes, prison commitments apparently.
