### ISSUE TITLE
Issue with IE/Edge compatibility in 3.4.5

### ISSUE THREAD

**Issue by simon-jouet** [zloirock/core-js#759]
Hi,

After spending quite some time debugging an issue in an angular app I've pinpointed it to a detection issue in 3.4.5 https://github.com/zloirock/core-js/commit/66f13854cf552bdcf01e16daaa033eb2ecc7e234#diff-1db6478fc99b66a5dcda3ce77d9a794fR40

Okay, so the issue was that angular was crashing when calling `getHtmlTagDefinition('a')`, looking at the code it was returning `1` which clearly wasn't expected. That's because `a` is defined on the prototype of Object.

For the time being I reverted back to 3.4.4 and it's working fine.

This might be related to #720 ?

**Comment by j-verse** [comment]
Same issue here in IE11, my production code gives an error that I traced back to upgrading core-js from 3.4.4 to 3.4.5. In my (minified) React library is giving an error because of this define of 'a' on the prototype of object in IE11.

**Comment by zloirock** [comment]
See https://github.com/zloirock/core-js/issues/847#issuecomment-717259614
