### ISSUE TITLE
Force override Array.prototype.reduce in Chrome 80

### ISSUE THREAD

**Issue by buu700** [zloirock/core-js#766]
[Apparently `reduce` is broken in Chrome 80.](https://www.reddit.com/r/angular/comments/f1ucoj/chrome_80_introduces_angular_breaking_bug)

Given that users may stay on old browser versions for unknown amounts of time, even after this is fixed ideally every website would continue including a workaround for the problem, so core-js seems like a natural place to handle it.

**Comment by BojanKogoj** [comment]
They have stopped Chrome 80 rollout, and will be releasing a fix soon. I don't think it's worth adding this hack.

**Comment by buu700** [comment]
Ah, perfect, that's good to know.
