### ISSUE TITLE
ES6 Promise in Internet Explorer 9

### ISSUE THREAD

**Issue by jessedijkstra** [zloirock/core-js#77]
I've tried to use the ES6 Promise through BabelJS with Webpack in Internet Explorer 9, but the moment I include a Promise IE9 errors.

It gives me the following error: 'SCRIPTXXX: Invalid calling object'.

Debugging the error points to the following line in the code:
```js
  // Modern browsers, skip implementation for WebWorkers
  // IE8 has postMessage, but it's sync & typeof its postMessage is object
  } else if(addEventListener && isFunction(postMessage) && !global.importScripts){
    defer = function(id){
      postMessage(id, '*');
    };
    addEventListener('message', listner, false);
  // WebWorkers
```

It gives me the error at the ```addEventListener('message', listner, false);``` statement.

I hope I have time to debug the error further the coming weekend, but for now I'm using the [es6-promise polyfill](https://github.com/jakearchibald/es6-promise) which works fine.

**Comment by zloirock** [comment]
Looks like https://github.com/zloirock/core-js/issues/62 - `webpack` problem, but I'll try fix at `core-js` side when I'll have time.

**Comment by jessedijkstra** [comment]
Awesome, thanks.

**Comment by danielhusar** [comment]
Un sorry I googled a lot and that thread didn't came up!

So the solution is to not process it with babel ?
I have 
```
{
        test: /\.js*$/,
        exclude: 'node_modules',
        loader: 'babel'
},
```

in my webpack so all node modules should be already ignored by babel.

**Comment by danielhusar** [comment]
actually never-mind, my exclude patter is wrong
