### ISSUE TITLE
`setImmediate` is broken in `file://` protocols in iOS.

### ISSUE THREAD

**Issue by dtinth** [zloirock/core-js#770]
## Background

We at @taskworld noticed that when our application is running inside Cordova, some Promise would never resolve. Instead, we’d get a weird error message on the console: “_Unable to post message to file://. Recipient has origin null._”

Upon further investigation, we found that some of our 3rd-party libraries are using an outdated Promise implementation which depends on `setImmediate`. `setImmediate` is broken in Cordova, so I decided to file an issue here in `core-js`.

## Investigation

This situation happens in Cordova apps,

- Web application is run on `file://` protocol using Safari’s engine.

- The `defer` selection logic selects `postMessage` to be used (`MessageChannel` is not used due to `IS_IOS` clause):

  https://github.com/zloirock/core-js/blob/4546ffeca298cbccf0843e31e8af6403693ab8ae/packages/core-js/internals/task.js#L61-L81

- The `postMessage` implementation of defer doesn’t work with `file:` protocol, it errors out with this:

  ```
  Unable to post message to file://. Recipient has origin null.
  ```

## Suggested fix

If `location.protocol === 'file:'`, fallback to alternative methods. I made a PR #771 that implements the suggested fix.

## Current workaround

```js
require('core-js/stable')

// `setImmediate` is currently broken on Cordova.
// Falling back to `setTimeout` implementation.
//
// See: https://github.com/zloirock/core-js/issues/770
// See also: https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate#Notes
//
window.setImmediate = f => {
  setTimeout(f, 0)
}
```

---

I investigated this issue while working on [Taskworld](https://taskworld.com/), so gotta plug that in. 😄

**Comment by diegodalbosco** [comment]
Same problem here. After updating to latest core-js version we cannot deploy our web app to ios (inside a WKWebView that points to local files).

**Comment by slowcheetah** [comment]
@diegodalbosco try that patch #771 
@dtinth thx for solution

**Comment by diegodalbosco** [comment]
@slowcheetah We tried the patch and for our use case is working 🎉  Thanks @dtinth!
