### ISSUE TITLE
[IE11][Since 3.6.2] "Calling delete on 'find' is not allowed in strict mode"

### ISSUE THREAD

**Issue by corinnaerin** [zloirock/core-js#773]
**Browser**: IE11
**Compatibility Mode**: Disabled
**Platform**: Windows 7
**Version**: v3.6.2 - v3.6.4
**Babel**: v6.26.3 (with `useBuiltins` = `false`). 
**Expected behavior**: `core-js` package loads without throwing any errors in IE11
**Actual behavior**: `core-js` package throws an uncaught exception: `Calling delete on 'find' is not allowed in strict mode`. 

We are loading core-js by prepending `core-js-bundle/minified` to our bundle as is. 

![image](https://user-images.githubusercontent.com/2001071/74862117-66eaf100-5300-11ea-9383-82dde595cc51.png)

I've traced the error to this line: https://github.com/zloirock/core-js/blob/4546ffeca298cbccf0843e31e8af6403693ab8ae/packages/core-js/internals/redefine.js#L25

According to the debugger, it looks like the error is thrown when it's trying to redefine the `find` method on `Array`:

![image](https://user-images.githubusercontent.com/2001071/74863151-41f77d80-5302-11ea-9654-8f7e4daab7e5.png)

**Comment by JakeChampion** [comment]
I don't think core-js is meant to be loaded in strict mode, which is why you are seeing this error

**Comment by corinnaerin** [comment]
Yeah that was my first thought as well, but Iooking at the built code, each individual module has a function-level `use-strict`.

**Comment by kucherov-mail** [comment]
I have the same error but witch includes, @corinnaerin do you have any progress on this?

**Comment by zloirock** [comment]
Seems it's an issue with an alternative incorrect 3rd party `Array#find` polyfill which defined as non-configurable and which does not pass `core-js` feature detection. `core-js` tries to fix it, but can't delete the previous implementation. It's a bug in this 3rd party polyfill, it's not a `core-js` issue.

**Comment by suguanYang** [comment]
> Seems it's an issue with an alternative incorrect 3rd party `Array#find` polyfill which defined as non-configurable and which does not pass `core-js` feature detection. `core-js` tries to fix it, but can't delete the previous implementation. It's a bug in this 3rd party polyfill, it's not a `core-js` issue.

I just wonder why corejs would redefine a finction that already exists?

**Comment by zloirock** [comment]
@suguanYang because polyfills should fix not proper functionality? -)

**Comment by suguanYang** [comment]
@zloirock thanks for your reply, thats a good opinion.
 I was thinking plolyfill should just define things that not exists in the env, maybe it's the duty for the caller?
