### ISSUE TITLE
Object doesn't support property or method 'matches'

### ISSUE THREAD

**Issue by MichelBast** [zloirock/core-js#780]
Hello, 

I'm trying to figure out why I have this error in IE11..
I setup core-js on the simplest project as possible. It seems to work fully as I am also using `WeakSet([])` and don't have any errors in IE. 
However when it comes to `matches ` I have the following error : 
![image](https://user-images.githubusercontent.com/61871892/76080930-4da49e80-5fa8-11ea-8748-0cef07ee432e.png)

Code : 
```
  handleChange(event) {
    const { value } = event.target;
    const div = document.getElementsByTagName('div');
    var to = new WeakSet([]);
    for (var i =0; i < div.length; i++ ) {
        const toto = div[i].matches('div')
    }
  }
```
One solution I found is to manually add the polyfill from [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/matches) but I though core-js would do it automatically.. 
So my code would become: 
```
  handleChange(event) {
    const { value } = event.target;
    const div = document.getElementsByTagName('div');
    var to = new WeakSet([]);
    for (var i =0; i < div.length; i++ ) {
        const matches = div[i].matches ? 'matches': 'msMatchesSelector';
        const toto = div[i][matches]('div')
    }
}
```

Configuration : 
React with Webpack and Babel. 
```
//.babelrc
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "useBuiltIns": "entry",
                "corejs": 3
            }
        ],
        "@babel/preset-react"
    ]
}
```

```
//webpack.config.js

const path = require('path');
const HtmlWebPackPlugin = require("html-webpack-plugin");

module.exports = {
    entry: './src/index.js',
	mode: 'development',
	output: {
		filename: 'main.js',
		path: path.resolve(__dirname, 'dist')
	},
    module: {
      rules: [
        {
          test: /\.(js|jsx)$/,
          exclude: /node_modules/,
          use: {
            loader: "babel-loader"
          }
        },
        {
            test: /\.html$/,
            use: [
              {
                loader: "html-loader"
              }
            ]
        }
      ]
    },
    plugins: [
      new HtmlWebPackPlugin({
        template: "./src/index.html",
        filename: "./index.html"
      })
    ]
  };
```

```
//index.js
import "core-js/stable";
import "regenerator-runtime/runtime";
import Form from "./js/components/Form";
```

**Comment by pmrotule** [comment]
I'm having the same error thrown on IE11 using `"core-js": "3.6.4"`. As @MichelBast already mentioned, I could add a polyfill but I think `core-js` should handle it.

**Comment by slowcheetah** [comment]
Core js implements features around ES.

**Comment by MichelBast** [comment]
@slowcheetah OK thank you for this answer.
@pmrotule I guess he have our answer.. They are not handling it!

**Comment by JakeChampion** [comment]
DOM polyfills can be handled via [`polyfill-library`](url) or [https://polyfill.io](https://polyfill.io) or [`dom4`](https://github.com/WebReflection/dom4)
