### ISSUE TITLE
NPM install returning 1 after core-js Post-install in a Docker Environment  

### ISSUE THREAD

**Issue by dev-whiteflag** [zloirock/core-js#781]
Heyo,

I'm using Drone CI on a AWS Ubuntu to build a Angular project that depends on core-js; but don't know why core-js postinstall keeps stopping my building process, event with ``npm config set unsafe-perm true``.

Verbose isn't returning anything strange and my Docker image is node's latest, core-js's version is 3.6.4.

```
npm info lifecycle cookie-signature@1.0.6~postinstall: cookie-signature@1.0.6
npm info lifecycle copy-descriptor@0.1.1~postinstall: copy-descriptor@0.1.1
npm info lifecycle core-js@3.6.4~postinstall: core-js@3.6.4

> core-js@3.6.4 postinstall /drone/src/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"
```
Environment Variable CI is currently TRUE as well, there's anything more I've need to do?

**Comment by dev-whiteflag** [comment]
Okay, I've tried running with `--silent` and it worked. Maybe is related to that CI var in the postinstall script. Don't know if Drone's env variables are in this filter.
https://github.com/zloirock/core-js/blob/4546ffeca298cbccf0843e31e8af6403693ab8ae/packages/core-js/postinstall.js#L13

**Comment by ties-s** [comment]
I’m also having this issue. `--silent` doesn’t work for me.

**Comment by slowcheetah** [comment]
Try this path #794

**Comment by ties-s** [comment]
I’ve already tried with using the `CI` env var
