### ISSUE TITLE
Remove ads or support OPEN_SOURCE_CONTRIBUTOR=true

### ISSUE THREAD

**Issue by mikemaccana** [zloirock/core-js#783]
```
Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
```

[Ads are banned per npm policy](https://www.infoq.com/news/2019/08/npm-bans-package-ads/) so these shouldn't appear, but even if they do, the package should support `OPEN_SOURCE_CONTRIBUTOR` (which I am) to suppress this output.

About to file a bug on two other projects with ads in console output.

**Comment by neutraali** [comment]
Yeah, AD-spam will only lead to a carbon-copy fork minus the ads.

**Comment by MaximZemskov** [comment]
See https://github.com/zloirock/core-js/issues/767
