### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by mryellow** [zloirock/core-js#784]
It's okay to spam my console. So it's okay if I take your attention with a spam issue right?

**Comment by Jim-Fan** [comment]
I appreciate zloirock's effort but that's probably not the good way to advertise if any person is looking for a job. What should happen if every developer is doing that...

**Comment by MattiaPette** [comment]
If you don't like how this project is maintained or the way the core dev thinks, just don't use it, if you can, or can't you?

**Comment by Jim-Fan** [comment]
Your suggestion appears to be a counter-productive one, by driving people away from the repo. The comment made (the one I made at least) is trying to ask for improvement. And the fact is, I am not free to opt out because the project I was building belongs to, my employer.

**Comment by slowcheetah** [comment]
[#548](https://github.com/zloirock/core-js/issues/548#issuecomment-494112872)

**Comment by mryellow** [comment]
> Almost 5 years almost every day I spend some hour for maintenance core-js. 

Irrelevant.

**Comment by mryellow** [comment]
@slowcheetah   Now that he's not getting out of jail anytime soon do you think it might be a good idea to remove the job advert?

**Comment by mryellow** [comment]
@mattlubner 

> put that energy into a more productive form of dissent (such as championing a solution).

The solution is easy. Remove the spam and get back to not having every topic descend into calls to remove the spam.

> No one is actually helped by the collective complaining that's happening throughout the GitHub issues for this repo.

Remove the spam. Problem goes away. The spam is the problem.
