### ISSUE TITLE
TypeError: $.setDesc(...) is not extensible when using core-js in Firefox add-on

### ISSUE THREAD

**Issue by vasyas** [zloirock/core-js#79]
(Almost) Full stack:

TypeError: $.setDesc(...) is not extensible
Stack trace:
require<["/home/vasyas/workspace/browserplugin/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/$.js"]</createDefiner/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://87677a2c52b84ad3a151a4a72f5bd3c4-at-jetpack/f/data/src/js/_vendor.js:766:12

That's becase core-js uses self as global object and later tries to add property to it. But in Firefox add-on self object is sealed so you can't add properties to it.

**Comment by zloirock** [comment]
If `self` is sealed, I can't do anything in standard version `core-js`, it should add global properties. I can replace `$.setDesc` / `defineProperty` to simple property set, but it will not help if `self` is really sealed. Can you suggest solution?

**Comment by zloirock** [comment]
I removed calling `Object.defineProperty` / `$.setDesc` on global object. If it will not help - I have no ideas. If you have - you can propose here or add PR.

**Comment by zloirock** [comment]
Should be fixed in 1.0, #91.
