### ISSUE TITLE
[RegExp] `dotAll` flag

### ISSUE THREAD

**Issue by brettz9** [zloirock/core-js#792]
As it does not seem that core-js polyfills the RegExp constructor to handle the `s` flag, I'm wondering whether you might be willing to depend on https://github.com/mathiasbynens/regexpu-core (using its `dotAllFlag: true`), rewriting the pattern to work compatibly?

Might help with #521 also (the `namedGroup: true` option).

**Comment by zloirock** [comment]
I'll think about it. It could be simple enough.
