### ISSUE TITLE
Does core-js/stable include Promise.allSettled?

### ISSUE THREAD

**Issue by Mrman** [zloirock/core-js#793]
Hi there, trying to understand a little more of core-js. I need to polyfill to Promise.allSettled for Edge. 

I see allSettled was recognized as stable in v3.2.0 of core-js (Release notes: "Promise.allSettled moved to stable ES, per July TC39 meeting"). Am I interpreting that correctly to mean it should be there when I ```import "core-js/stable"```?

I've tested with a new brand new app using create-react-app and see Promise.allSettled as ```undefined``` in Microsoft Edge 44.18362.449.0.

Browserlist from package.json is:
```
"development": [
            ">0.2%",
            "not dead",
            "not ie <= 11",
            "not op_mini all",
            "edge > 1"
    ]
```

I see it does get polyfilled correctly if I just ```import "core-js"```

What am I overlooking? 

Thanks :)

**Comment by erikt9** [comment]
I had this problem too.  What you need to do is in your `@babel/env` configuration you need to specify corejs of `3.2` or higher (the examples and docs all just show using `3` 😝 so it's difficult to know this).  https://babeljs.io/docs/en/babel-preset-env

**Comment by Mrman** [comment]
Thanks @erikt9. That appears to be the issue, CRA uses just major version 3 in the configuration and it isn't possible to change without ejecting. I created an issue there: https://github.com/facebook/create-react-app/issues/8779
