### ISSUE TITLE
use babel-runtime and corejs3 The compiled code is much large

### ISSUE THREAD

**Issue by huzedong2015** [zloirock/core-js#798]
**Source**
`const arr = [1, 2, 3, 4];
const findIndex = arr.findIndex((value) => value === 2);`

**Build Size**
1KB

**Use corejs3 build size**
9KB

[demo](https://github.com/huzedong2015/test)

**Comment by slowcheetah** [comment]
What's wrong? `exports `+ all dependencies & `findIndex` polyfill with dependencies.

**Comment by huzedong2015** [comment]
> 怎么了？`exports `+所有依赖项＆`findIndex`用依赖项填充。

Array findIndex why has 9KB？Can we optimize the space

**Minimum repurchase**
[https://github.com/huzedong2015/test](https://github.com/huzedong2015/test)

**Comment by huzedong2015** [comment]
@slowcheetah 
Array findIndex why has 9KB？Can we optimize the space

Minimum repurchase
[https://github.com/huzedong2015/test](https://github.com/huzedong2015/test)

**Comment by slowcheetah** [comment]
@huzedong2015 there is nothing to optimize. Only required polyfills are included

**Comment by huzedong2015** [comment]
> @huzedong2015 there is nothing to optimize. Only required polyfills are included

OK Tks👍
