### ISSUE TITLE
Replaces native WeakMap implementation

### ISSUE THREAD

**Issue by vdemedes** [zloirock/core-js#8]
Core.js replaces native WeakMap implementation. Tested in Node.js v0.11.14 with latest 6to5, which includes core.js as a polyfill for ES6 features.

**Comment by zloirock** [comment]
Core.js uses native `WeakMap`, if it exists, just fixes constructor for init from iterable and `.set` for chaining.

```javascript
var a = {}, b = {};

new WeakMap([[a, 1], [b, 2]]).has(a);     // => false
new WeakMap().set(a, 1).set(b, 2).has(a); // TypeError: Cannot call method 'set' of undefined

require('core-js'); // WeakMap still returns native weakmap

new WeakMap([[a, 1], [b, 2]]).has(a);     // => true
new WeakMap().set(a, 1).set(b, 2).has(a); // => true
```

**Comment by trusktr** [comment]
Should we be adding features, or stick to spec?

**Comment by loganfsmyth** [comment]
I'm not sure what you're asking. Could you elaborate?

**Comment by trusktr** [comment]
I'm just saying that core-js provides polyfills, but maybe it should not add extra features (like making `.set()` chainable), and it should only do it's job of providing polyfills?

**Comment by loganfsmyth** [comment]
But making `.set` chainable _is_ the specced behavior. `core-js` adds it when the version implemented natively does not implement the spec properly.

**Comment by trusktr** [comment]
Ah, oops. I had incorrectly assumed that native implementations were following such a simple spec. Why would they not return `this` if something so simple is spec'd? Do vendors not like that idea?

**Comment by loganfsmyth** [comment]
As a polyfill, it is `core-js`'s job to homogenize implementations. In this case, as the original issue says, the issue is with Node 11.14, which didn't yet implement the `this` return behavior. Given the timeline, it may be that there was an earlier version of the spec for them that didn't include that.
