### ISSUE TITLE
RegExp escape

### ISSUE THREAD

**Issue by benjamingr** [zloirock/core-js#80]
It would be nice if you could align https://gist.github.com/kangax/9698100's old proposal (currently implemented) with this new proposal https://github.com/benjamingr/RexExp.escape (which I'm championing). 

They're similar with minor changes to the outside - you can find a polyfill in the spec page.

**Comment by zloirock** [comment]
Done, will be available in next release.

**Comment by zloirock** [comment]
Available in `0.9.17`.

**Comment by benjamingr** [comment]
Awesome, thanks!
