### ISSUE TITLE
[Question] Upgrading from core-js@2 to core-js@3 and using via CDN

### ISSUE THREAD

**Issue by hardikmodha** [zloirock/core-js#800]
Hi, I'm trying to upgrade from `v2.4.0` to `v3.6.4`. Due to some limitations and backward compatibility issues, I'm using core-js-bundle externally via CDN (https://unpkg.com/core-js-bundle@3.6.4/minified.js). This gets bundles and included in `index.html` via `<script>` at the very top of all scripts.  

I verified the updated version via `window['__core-js_shared__'].versions` and found that another version (v2.6.11) is also there which is coming from one of the dependencies. 

```json
"[
  {
    "version": "3.6.4", // Version which I've included
    "mode": "global",
    "copyright": "© 2020 Denis Pushkarev (zloirock.ru)"
  },
  {
    "version": "2.6.11", // Version coming from the dependency
    "mode": "pure",
    "copyright": "© 2019 Denis Pushkarev (zloirock.ru)"
  }
]"
```

The version coming from the dependency is the `pure` one so I understand that it shouldn't affect anything globally. The one which I've included is the `global` one so it will apply polyfills at the global level. 

My questions are, 
- Will it result in a clash between versions and any undefined behavior? If so, How do I make sure that only the latest version is used? 
- Is there anything else that I need to take care of to make sure that I don't run into issues? 

**PS**: Here is the script loading structure of `index.html`

```html
<script src="static/js/core-js-bundle-3.6.4.min.js"></script> <!-- Loaded at first. It's core-js-global -->
<script src="dist/js/bundle_1.js"></script> <!-- Version 2.6.11 is coming from this bundle. It's core-js-pure.  -->
```

**PPS**: I'm using babel@7.x to transpile the source files and generate `bundle_1.js`. I'm not using the `useBuiltIns` options for babel config. 

Here is the relevant part from `package.json`

```
"@babel/core": "7.8.4",
"@babel/plugin-proposal-class-properties": "7.8.3",
"@babel/plugin-transform-runtime": "^7.8.3",
"@babel/preset-env": "7.8.4",
"@babel/preset-react": "7.8.3",
```

and `babel.config.js`

```
module.exports = {
    presets: ["@babel/env", "@babel/react"],
    plugins: [
        "@babel/plugin-proposal-class-properties",
        "@babel/plugin-transform-runtime",
        ["@babel/plugin-transform-modules-commonjs", { strictMode: false }],
    ],
};
```

**Comment by slowcheetah** [comment]
@hardikmodha can you give a reproducible example?

**Comment by zloirock** [comment]
> - Will it result in a clash between versions and any undefined behavior? If so, How do I make sure that only the latest version is used?
> - Is there anything else that I need to take care of to make sure that I don't run into issues?

Since only one version is global, it should work fine.
