### ISSUE TITLE
Webpack minified output contains "copyright:"© 2020 Denis Pushkarev (zloirock.ru)"

### ISSUE THREAD

**Issue by josephfischer** [zloirock/core-js#807]
Can we remove "copyright:"© 2020 Denis Pushkarev (zloirock.ru)" from the minified output.  Great job on the library and all, but why do we need this in the minification?   Is there a way to remove this?

**Comment by JakeChampion** [comment]
Because they retain copyright, much like you have to retain license headers in minified code.
