### ISSUE TITLE
Resurfacing this

### ISSUE THREAD

**Issue by sgammon** [zloirock/core-js#808]
```
Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
```

Can we cut this out? Please?

**Comment by JakeChampion** [comment]
No, they are asking for help funding this project. 

If you want to silence the output then you can set any one of these environment variables before running npm install:

    ADBLOCK
    CI
    DISABLE_OPENCOLLECTIVE
    SILENT
    OPEN_SOURCE_CONTRIBUTOR

**Comment by sgammon** [comment]
@JakeChampion I thought they had found funding, including $5,000 for this library and its creator, who is now in prison? Why does this project still need funding

**Comment by sgammon** [comment]
also for anyone else encountering this issue

`echo "ADBLOCK=1" >> ~/.profile`

Suppress these forever and once these fundraising methods don't work, maybe they will find another way that doesn't pollute _thousands of terminals downstream_.

**Comment by slowcheetah** [comment]
I will send the information to @zloirock. But I have nothing to say now. If @zloirock decides to remove the ads, then I will do it.

**Comment by JakeChampion** [comment]
> @JakeChampion I thought you had found funding, including $5,000 for this library and its creator, who is now in prison? Why does this project still need funding
> 
> (edited to _you_ from _they_ because apparently you are a contributor even though you phrased that like this isn't your fault)

Ha, I fixed a bug in this project a few times, yes, because I value open source. I am involved in the project in the fact I fix code/bugs in the projects that I use for free such as this.

**Comment by sgammon** [comment]
@JakeChampion great can you ask your fellow contributors then?
