### ISSUE TITLE
Object expected error thrown in angular 9 application - In IE11

### ISSUE THREAD

**Issue by Vikki123** [zloirock/core-js#812]
i all. I  am developing an angular application which is running on version 9.0.x. The application runs as an ifame of the parent application. There is a signalR connection to the backend and we try to close the connection when the frame is unloading using @microsoft/signalr HubConnection.stop() method.

**What is the problem:**
When the application runs on IE 11, when the above is called , it works fine in the normal scenario. But when called on window unload as follows

```
import { Component, OnDestroy, OnInit } from '@angular/core';
import { HubConnection, HubConnectionBuilder } from '@microsoft/signalr';
import { Subject } from 'rxjs';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  title = 'lkasjsd';

  hubConnection: HubConnection;
  subject = new Subject();
  subjectObs = this.subject.asObservable();

  ngOnInit() {
    this.hubConnection =
      new HubConnectionBuilder().withUrl('/diagHub?RequestId=ed8a41ef-9c47-4de6-8029-bbe7971041ce&AuthenticationToken=4EVYS-Q39CA&AuthenticationType=1&ToolId=EA0100&WorkStreamId=None').build();
    window.addEventListener('unload', this.handleWindowUnload.bind(this));

    this.hubConnection.start().then(() => {
      console.log('Connnected Success');
    });

    this.subjectObs.subscribe(() => {
      console.log('Stopping');
      this.hubConnection.stop();
    })
  }

  handleWindowUnload() {
      this.subject.next();
  }
}
```

i see the following error in the IE  browser console

![image](https://user-images.githubusercontent.com/8450434/79594938-9b5e0c00-80fb-11ea-9980-7db9fd252160.png)

**What is more weird:**

Just out of curiosity i changed the code in node_modules\core-js\internals\to-integer.js and put a console log

![image](https://user-images.githubusercontent.com/8450434/79595189-04458400-80fc-11ea-9a00-6ebfd3eed89d.png)

This results in the log as follows

![image](https://user-images.githubusercontent.com/8450434/79595303-3820a980-80fc-11ea-924c-1eb0cdb60927.png)

 If you see isNaN was deffined before but gets undefined in the middle of executiion. !!

Also the issue gets resolved if i install core-js@2.5.4 manually and import the following in the polyfills file

```
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
// import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following for the Reflect API. */
import 'core-js/es6/reflect';


/** Evergreen browsers require these. **/
// Used for reflect-metadata in JIT. If you use AOT (and only Angular decorators), you can remove.
import 'core-js/es7/reflect';
```
How is this possible ? What am i missing here ?

My dev box

Angular CLI: 9.0.4
Node: 10.19.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Angular

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.4
@angular-devkit/core         9.0.4
@angular-devkit/schematics   9.0.4
@schematics/angular          9.0.4
@schematics/update           0.900.4
rxjs                         6.5.3

tsconfig
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}
```

**Comment by slowcheetah** [comment]
@Vikki123 can you give reproducible example?

**Comment by Vikki123** [comment]
Sure. Its a bit of set up as it is observed only when you are connected to a signalR websocket  server. You can use this [link](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-3.1&tabs=visual-studio) for creating a websocket end point . After that

1) create a new angular application.
2) Add @microsoft/signalr as dependency
3) Replace the app component with following code. Replace withUrl('/url') with any websocket url created with the above mentioned steps.

```
import { Component, OnDestroy, OnInit } from '@angular/core';
import { HubConnection, HubConnectionBuilder } from '@microsoft/signalr';
import { Subject } from 'rxjs';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  title = 'lkasjsd';

  hubConnection: HubConnection;
  subject = new Subject();
  subjectObs = this.subject.asObservable();

  ngOnInit() {
    this.hubConnection =
      new HubConnectionBuilder().withUrl('/url').build();
    window.addEventListener('unload', this.handleWindowUnload.bind(this));

    this.hubConnection.start().then(() => {
      console.log('Connnected Success');
    });

    this.subjectObs.subscribe(() => {
      console.log('Stopping');
      this.hubConnection.stop();
    })
  }

  handleWindowUnload() {
      this.subject.next();
  }
}
```

4) Create a empty html script to load the angular application as an iframe as follows

```
< !DOCTYPE html>
    <html>

    <body>

        <button id="add" onclick="add()">Add</button>
        <button id="remove" onclick="remove()">Remove</button>
        <div id="iframe">

        </div>

    </body>
    <script>
        function add() {
            var ifrm = document.createElement("iframe");
            ifrm.setAttribute("src", "https://localhost:4200/");
            ifrm.style.width = "640px";
            ifrm.style.height = "480px";
            document.getElementById('iframe').appendChild(ifrm);
        }

        function remove() {
            let element = document.getElementsByTagName('iframe')[0];
            document.getElementById('iframe').removeChild(element);
        }
    </script>

    </html>
```
5) Now add the iframe and remove, you can see the error.

**Comment by Vikki123** [comment]
@slowcheetah Were you able to reproduce the issue ? Any update on this ?

**Comment by slowcheetah** [comment]
@Vikki123 thanks for example steps. Within a couple days I plan to address this issue

**Comment by Vikki123** [comment]
That would be of great help. Thanks 👍

**Comment by slowcheetah** [comment]
@Vikki123 Some library redefines isNaN function. I can’t say exactly what this does.

Since isNaN is overridden, I tried replacing isNaN with val !== val (is NaN check) and i get another second error (Object expected)...
![image](https://user-images.githubusercontent.com/11753373/81510639-89a80700-933d-11ea-9266-15734a2ceeca.png)
![image](https://user-images.githubusercontent.com/11753373/81510650-9fb5c780-933d-11ea-8807-12b62f30659b.png)

Maybe core-js should not use the global isNaN directly (in case of external interference), but this is still not a bug in core-js.

**Comment by djleonskennedy** [comment]
Hello all
I have this error on **prod** build only, cannot reproduce it in **dev** mode

**Comment by Vikki123** [comment]
@slowcheetah I get this error when i am using the @microsoft/signalR library. Issue raised [Here](https://github.com/dotnet/aspnetcore/issues/20959). But according to the issue mentioned over there by the contributors there is a problem with corejs + zonejs. Check []([Here](https://github.com/dotnet/aspnetcore/issues/20959#issuecomment-618061167))

**Comment by nw-rgails** [comment]
Currently getting this with core-js@^3.3.3 and zone.js@~0.10.2 and I'm not using signalR. I'm not getting the issue with prod builds, but am with dev.

**Comment by slowcheetah** [comment]
@Vikki123 @anurse just suggested that it might not work correctly in core-js. Once again, the error described above is due to something overriding the standard function isNull, most likely this is zone.js. 
I don't see core-js problems here.

**Comment by djleonskennedy** [comment]
@slowcheetah I'll create issue in zone js repo, thanks

**Comment by slowcheetah** [comment]
@djleonskennedy Thanks. I will follow the created issue

**Comment by JiaLiPassion** [comment]
@djleonskennedy , @Vikki123 , I would like to check zone.js part, but I have no idea how to create a SignalR server, is that possible I can connect to any test server or I can just get a binary package to start a SignalR server?

**Comment by JiaLiPassion** [comment]
I can reproduce now, and this issue has nothing to do with `zone.js` or `core-js` or `rxjs`, the error happened in `to-integer.js`, and the reason is `isNaN` becomes `undefined`, in fact, not only `isNaN`, all global object inside `iframe window` object becomes `undefined`, I don't know it is the spec of IE or not, it seems , after `iframe window unload`, the window clear itself by setting all it's properties to `undefined`. And since `hubconnection.stop()` is async operations, so it happened after `unload`. 
Also I don't think the comment https://github.com/dotnet/aspnetcore/issues/20959#issuecomment-618061167 is correct, since `Array.prototype.slice()` allow pass no parameters, it will just clone the whole array, and also the error stack trace is not from `zone.js`, it is from `rxjs`, but still I don't think it is any lib's issue, it is just a IE behavior.
![screenshot](https://user-images.githubusercontent.com/1442575/84978930-22b21500-b169-11ea-97ea-88966cb2c12c.PNG)

And I also created a sample application to reproduce it without `zone.js` or `rxjs` or even `angular` and `signalR`.

1. create a html file `test.html`.

```
<html>
  <body>
    <button id="add" onclick="add()">Add</button>
    <button id="remove" onclick="remove()">Remove</button>
    <div id="iframe"></div>
  </body>
  <script>
    function add() {
      var ifrm = document.createElement("iframe");
      ifrm.setAttribute("src", "http://localhost:8080/frame.html");
      ifrm.style.width = "640px";
      ifrm.style.height = "481px";
      document.getElementById("iframe").appendChild(ifrm);
    }

    function remove() {
      let element = document.getElementsByTagName("iframe")[0];
      document.getElementById("iframe").removeChild(element);
    }
  </script>
</html>

```

2. create a `frame.html`.

```
<script src="https://raw.githack.com/zloirock/core-js/v2.6.9/client/core.min.js"></script>
<script>
  window.onload = function () {
    console.log("iframe loaded");
    window.addEventListener("unload", function () {
      console.log("unload");
      Promise.resolve().then(function () {
        var isNumber = isNaN(1);
        console.log("isNumber", isNumber);
      });
    });
  };
</script>
<div>
  iFrame
</div>
```

3. use a http-server to host `frame.html` in 8080
4. open test.html and `add` then `remove` in IE

you can see the `isNaN` becomes `undefined.

**Comment by Vikki123** [comment]
@JiaLiPassion But i see that it works fine when i call hunconnection.stop() outside of angular. So if it was IE default behavior, shouldnt it fail all the time ?

**Comment by JiaLiPassion** [comment]
@Vikki123, what so you mean outside of angular? Could post a reproduce repo?

**Comment by zloirock** [comment]
It's definitely not a `core-js` issue.
