### ISSUE TITLE
Core-JS 3.6.5 results in mini-css-extract-plugin error but 2.6.11 does not

### ISSUE THREAD

**Issue by aysiscore** [zloirock/core-js#819]
I have set up my Webpack 4 config to handle `babel-loader` like this:

```
 {
      module : {
        rules : [{
          test : /\.js$/,
          // Some module should not be transpiled by Babel
          // See https://github.com/zloirock/core-js/issues/743#issuecomment-572074215
          exclude: ['/node_modules/', /\bcore-js\b/, /\bwebpack\/buildin\b/, /@babel\/runtime-corejs3/],
          loader : "babel-loader",
          options : {
            babelrc : false,
            // Fixes "TypeError: __webpack_require__(...) is not a function"
            // https://github.com/webpack/webpack/issues/9379#issuecomment-509628205
            // https://babeljs.io/docs/en/options#sourcetype
            sourceType : "unambiguous",
            presets : [
              ["@babel/preset-env", {
                // Webpack supports ES Modules out of the box and therefore doesn’t require
                // import/export to be transpiled resulting in smaller builds, and better tree
                // shaking. See https://webpack.js.org/guides/tree-shaking/#conclusion
                modules : false,
                // Adds specific imports for polyfills when they are used in each file.
                // Take advantage of the fact that a bundler will load the polyfill only once.
                useBuiltIns : "usage",
                corejs : {
                  version : "3",
                  proposals : true
                }
              }]
            ]
          }
        }
      }
    }
```
I expect my build to build but it does not. I get an error stating:

>     Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
>     TypeError: Cannot convert undefined or null to object
>     at hasOwnProperty (<anonymous>)
>     at module.exports.module.exports (C:\Site\node_modules\css-loader\dist\cjs.js!C:\Site\src\assets\css\site.css:115:25)

There is nothing wrong with the CSS file at all, and nothing at line 115 that is invalid. I know this because the same error occurs with an empty CSS file!

If I run the same build but downgrade to `core-js@2.6.11` in my `package.json` and change `corejs: { version: "3" }` to `corejs: { version: "2" }` then everything compiles fine.

In my `node_modules` and my own code I am unable to find anything that starts with `import 'core-js/es6/'` or `import 'core-js/es7/array'`. 

What is the fix for this?

**Comment by bartfeenstra** [comment]
I've got the exact same issue in two unrelated existing projects when introducing Babel and core-js. My Webpack rules:
```
const rules = [
      {
        test: /\.css$/,
        use: [MiniCssExtractPlugin.loader, 'css-loader'],
      },
      {
        test: /\.m?js$/,
        exclude: /node_modules\/core-js/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: [
              [
                '@babel/preset-env', {
                  debug: config.debug,
                  useBuiltIns: 'usage',
                  corejs: 3,
                },
              ],
            ],
            cacheDirectory: config.cacheDirectory,
          },
        },
      },
    ]
```

**Comment by diachedelic** [comment]
You may be transpiling `css-loader`, see https://stackoverflow.com/questions/58489738/minicssextractplugin-error-on-entry-point-build

**Comment by bartfeenstra** [comment]
I was indeed transpiling `css-loader`. Excluding the entirety of `node_modules` solved our problems. Thank you!
