### ISSUE TITLE
Strict mode errors in file(s) which overwrite constructor

### ISSUE THREAD

**Issue by ckisielius** [zloirock/core-js#820]
There's an issue with a couple of versions of chromium (list below) browser's Map implementation.  I can't reproduce the error on browserstack with an identical useragent, so I don't trust the userAgent in my logs.  But I can tell from splunk logging that it's failing for them at this line: 
https://github.com/zloirock/core-js/blob/09529a13c8d800d3e566a1b06b51fd6a2ab6ba38/packages/core-js/internals/collection.js#L76
With this message: `TypeError: Cannot modify readonly property: constructor.`

My question is, what do you think about removing the "use strict" from any file which overwrites a constructor?  IE11 doesn't care either way, and since [isForced defaults to true](https://github.com/zloirock/core-js/blob/09529a13c8d800d3e566a1b06b51fd6a2ab6ba38/packages/core-js/internals/collection.js#L50) core-js will inevitably see more cases like this one where it tries and fails to overwrite.

Reproduce the error by running this code (taken from the file above) in chrome or most modern browsers:
```
(function() {
'use strict';
 try {
   var NativeConstructor = window['Map'];
   var NativePrototype = NativeConstructor && NativeConstructor.prototype;
   var Constructor = NativeConstructor;
   Constructor.prototype = NativePrototype;
   NativePrototype.constructor = function() { }
 } catch(e) {
   console.log(e);
 }
})();
```

User Agents which log the error (again, I can't reproduce it but in case someone else is seeing the same thing):
```
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
```

Please let me know your thoughts.  Thank you so much for maintaining this repo.  It makes using babel an amazing experience for those of us who still need to support IE11.

**Comment by zloirock** [comment]
Sorry, but I can't reproduce it.

Your example has a mistake:
```diff
+(function() {
+'use strict';
+ try {
+   var NativeConstructor = window['Map'];
+   var NativePrototype = NativeConstructor && NativeConstructor.prototype;
-   var Constructor = NativeConstructor;
-   Constructor.prototype = NativePrototype;
+   NativePrototype.constructor = function() { }
+ } catch(e) {
+   console.log(e);
+ }
+})();
```
In `core-js`, `Constructor` is just a new function and have `{ writable: true }` `prototype` descriptor, but in your code, it's `Map` and descriptor is `{ writable: false }`, so your example should throw an error anyway, but with another error message:
```diff
-TypeError: Cannot modify readonly property: constructor.
+TypeError: Cannot modify readonly property: prototype.
```
I checked this case in mentioned browsers - and they work properly, `Map.prototype.constructor` has `{ configurable: true, writable: true }` descriptor and redefinition of this property can't throw an error.

This issue looks like a conflict with another, incorrect, polyfill, which set `Map.prototype.constructor` as non-writable like #746 or #702.

If you could add a reproducible example - please, add it here.
