### ISSUE TITLE
Core-js breaks create-react-app

### ISSUE THREAD

**Issue by huylequang210** [zloirock/core-js#823]
In my terminal:
`D:\>npx create-react-app myapp                                                                                      
npx: installed 98 in 21.893s                                                                                        

Creating a new React app in D:\myapp.                                                                               

Installing packages. This might take a couple of minutes.                                                           
Installing react, react-dom, and react-scripts with cra-template...                                                 

> core-js@2.6.11 postinstall D:\myapp\node_modules\babel-runtime\node_modules\core-js                               
> node -e "try{require('./postinstall')}catch(e){}"                                                                 

> core-js@3.6.5 postinstall D:\myapp\node_modules\core-js                                                           
> node -e "try{require('./postinstall')}catch(e){}"                                                                 

> core-js-pure@3.6.5 postinstall D:\myapp\node_modules\core-js-pure                                                 
> node -e "try{require('./postinstall')}catch(e){}"                                                                 

+ react-scripts@3.4.1                                                                                               
+ react-dom@16.13.1                                                                                                 
+ cra-template@1.0.3                                                                                                
+ react@16.13.1                                                                                                     
added 1613 packages from 750 contributors and audited 921730 packages in 287.89s                                    

58 packages are looking for funding                                                                                 
  run `npm fund` for details                                                                                        

found 1 low severity vulnerability                                                                                  
  run `npm audit fix` to fix them, or `npm audit` for details      

 CRA installation runs smoothly until core-js and it stuck there. Only package.json, package-lock.json and node_modules folder installed.

**Comment by slowcheetah** [comment]
Can't reproduce. Please show your enviroment

**Comment by huylequang210** [comment]
> Can't reproduce. Please show your enviroment

`Environment Info:                                                                                                
                                                                                                                 
  current version of create-react-app: 3.4.1                                                                     
  running from C:\Users\Administrator.Y8\AppData\Roaming\npm-cache\_npx\4528\node_modules\create-react-app                                                                                                           
                                                                                                                 
  System:                                                                                                        
    OS: Windows 7 6.1.7601                                                                                       
    CPU: (4) ia32 Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz                                                       
  Binaries:                                                                                                      
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE                                                             
    Yarn: Not Found                                                                                              
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD                                                                
  Browsers:                                                                                                      
    Internet Explorer: 8.0.7601.17514                                                                            
  npmPackages:                                                                                                   
    react: Not Found                                                                                             
    react-dom: Not Found                                                                                         
    react-scripts: Not Found                                                                                     
  npmGlobalPackages:                                                                                             
    create-react-app: Not Found`

**Comment by 1gunju12345** [comment]
May be you should check your Resource monitor, if the script running on CMD found suspended, try to resume it.
It worked for me.

**Comment by krishan93985** [comment]
@1gunju12345 Thank you, it worked for me as well, but I wanna know that, will this happen for every next time I try to make a react app!

**Comment by 1gunju12345** [comment]
@krishan93985  No, it will not occur again  but in case if this happen again try to get your windows fully scanned and remove all the malwares that is causing so.

**Comment by RichardFelipe-collab** [comment]
Thank you it worked, here Win10 had an antivirus running in real time, but he did not notify the blocking of the installation of the rest of react's dependencies, (Pelomenos I think it was that) and installed only node-modules, and package.json, I uninstalled the antivirus, (Name: Segurazo), and finally the command create-reac-app worked.

**Comment by soumyabhardwaj** [comment]
wow this worked for me too but still dont know the reason
