### ISSUE TITLE
IE11: Object.getOwnPropertyNames returns caller and arguments in strict mode for function instance

### ISSUE THREAD

**Issue by betalb** [zloirock/core-js#825]
In IE11 Object.getOwnPropertyNames returns `caller` and `arguments` object when called with function as argument.

```
Object.getOwnPropertyNames(function a() {})
```

I was not able to find a place in spec with explanation of how those properties should be defined, but other browsers change their output depending on strict/non-strict mode.

IE11
```
eval("'use strict'; Object.getOwnPropertyNames(function a() {})")
// -> ["prototype", "caller", "arguments", "length"]

eval("Object.getOwnPropertyNames(function a() {})")
// -> ["prototype", "caller", "arguments", "length"]
```

Chrome
```
eval("'use strict'; Object.getOwnPropertyNames(function a() {})")
// -> ["length", "name", "prototype"]

eval("Object.getOwnPropertyNames(function a() {})")
// -> ["length", "name", "arguments", "caller", "prototype"]
```

**Comment by slowcheetah** [comment]
@betalb [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Securing_JavaScript) everything is quite clearly described

**Comment by betalb** [comment]
@slowcheetah yeah, I'm aware how those properties behave at runtime.

But the issue is that Chrome / FF doesn't define `caller` and  `arguments` properties as own in strict mode, and only prototype level implementation is present, which throws exception.

But IE11 defines them as own, even though they also throw exception.

So Runtime behavior is the same, but implementation is different. And this is what was not clear to me from the spec initially.

But looks like in the latest spec it is pretty clear, that there should not be such properties defined as own: http://www.ecma-international.org/ecma-262/7.0/#sec-forbidden-extensions. And only Function prototype will contain accessors that should throw TypeError on access.

**Comment by zloirock** [comment]
It's not related `core-js` `Object.getOwnPropertyNames`, it's related IE strict mode implementation:
```js
eval("'use strict'; (function a() { return [a.hasOwnProperty('caller'), a.hasOwnProperty('arguments')] })()") // => [true, true]
```
We can't do anything here.
