### ISSUE TITLE
What's iframeDocument.write document.F=Object

### ISSUE THREAD

**Issue by garyfoo** [zloirock/core-js#827]
Hello,

I have a couple of security related questions regarding core-js. Hope someone can help!

Just a quick question regarding core-js version 2.6.11 that is being embedded in Angular 7 that we're using.

Our static code scan picked up the .write() method in the following block of code below found in _object-create.js

![image](https://user-images.githubusercontent.com/5109700/82001282-65299300-968d-11ea-8f15-53de8f38fa56.png)

Could you explain what's the purpose of the createDict method and what's "document.F=Object" highlighted in the screenshot?

Thanks!!

**Comment by slowcheetah** [comment]
@garyfoo It is fallback for Object.create(null) in IE8-. IE8 don't allow to create object without prototype.
