### ISSUE TITLE
Split up `web.immediate` and `web.timers` data

### ISSUE THREAD

**Issue by TomerAberbach** [zloirock/core-js#828]
Would you consider splitting up the `web.immediate` data into `web.set-immediate` and `web.clear-immediate`, and the the `web.timers` data into `web.set-interval`, `web.clear-interval`, `web.set-timeout`, and `web.clear-timeout`?

Most of the data keys are named after a single method and I think being consistent would be nice. In addition to adding the new keys I suggested, we could also keep `web.timers` and `web.immediate` until `core-js@4` to avoid a breaking change. I would be happy to make a pull request for this so let me know if you're up for it.

**Comment by slowcheetah** [comment]
@TomerAberbach This is planned in the new version of core-js 4, but in the current version this is not necessary. Thanks for the offer, I’ll take note that you can offer an implementation.
