### ISSUE TITLE
core-js-compat@3.6.5 includes non-required features

### ISSUE THREAD

**Issue by Tauka** [zloirock/core-js#829]
Hello! Thank you for this library!

I use following `browserslist` query:
```
last 2 Chrome versions,
last 2 Firefox versions,
last 2 Edge versions,
last 2 Opera versions,
last 2 iOS version,
last 2 safari version
```

And some of the features `core-js-compat` includes
```
'web.url': { ios: '13.2', safari: '12.1' },
'web.dom-collections.iterator': { ios: '13.2', safari: '12.1' },
'es.string.replace': { firefox: '74', ios: '13.2', safari: '12.1' }
```

But those features are supported way beyond `last 2 versions of IOS and safari` (according to MDN), could you please help me clarify what is going wrong?

**Comment by slowcheetah** [comment]
@Tauka 
`web.url` - safari has no standard implementation
`web.dom-collections.iterator` - safari has standard implementation from v13.1
`es.string.replace` - safari has no standard implementation

About implementation by standards, I described a little [here](https://github.com/zloirock/core-js/issues/817#issuecomment-620458818)

**Comment by Tauka** [comment]
@slowcheetah 
Thanks for the response! I wonder though, if it's possible to specify external `core-js-compat` for the `core-js-builder`, which implements the same interface? This way, we could opt in for custom compat tables

**Comment by wardpeet** [comment]
Thanks for the explanation slowcheetah, I wonder if there is a good way to find out why compat table includes things you don't expect. Git blame isn't super helpful in these cases. I also would like @Tauka's idea, or maybe add a loose option 🤷

**Comment by slowcheetah** [comment]
@wardpeet @Tauka something like you want is realized already. [link](https://github.com/zloirock/core-js#configurable-level-of-aggressiveness)

There are plans for the future to improve this mechanism.

**Comment by Tauka** [comment]
Thank you @slowcheetah, I think we can close it now :)
