### ISSUE TITLE
Symbols aren't cross-realm

### ISSUE THREAD

**Issue by bisubus** [zloirock/core-js#834]
Symbol registry and built-in symbols aren't cross-realm in Symbol polyfill.

Native symbols are cross-realm (a [demo](https://jsfiddle.net/1aqnL054/)), this results in `1 2` console output:
```html
<iframe srcdoc="<script>window.fooSymbol = Symbol.for('foo'); window.aiSymbol = Symbol.asyncIterator;</script>">
  </iframe>
<script>
var iframe = document.querySelector('iframe');
iframe.addEventListener("load", function () {
    var obj = {};
    var fooSymbol = Symbol["for"]('foo');
    var aiSymbol = Symbol.asyncIterator;
    obj[fooSymbol] = 1;
    obj[aiSymbol] = 2;
    var content = iframe.contentWindow;
    console.log(obj[content.fooSymbol], obj[content.aiSymbol]);
});
</script>
```

Polyfilled symbols aren't cross-realm (a [demo](https://jsfiddle.net/vxare3wg/1/)), this results in `undefined undefined` console output:
```html
<script>delete window.Symbol;</script>
<script src="https://unpkg.com/core-js-bundle@3.6.5/minified.js"></script>
<iframe srcdoc="<script>delete window.Symbol;</script><script src='https://unpkg.com/core-js-bundle@3.6.5/minified.js'></script><script>window.fooSymbol = Symbol.for('foo'); window.aiSymbol = Symbol.asyncIterator;</script>">
  </iframe>
<script>
var iframe = document.querySelector('iframe');
iframe.addEventListener("load", function () {
    var obj = {};
    var fooSymbol = Symbol["for"]('foo');
    var aiSymbol = Symbol.asyncIterator;
    obj[fooSymbol] = 1;
    obj[aiSymbol] = 2;
    var content = iframe.contentWindow;
    console.log(obj[content.fooSymbol], obj[content.aiSymbol]);
});
</script>
```

**Comment by JakeChampion** [comment]
`Symbol.for` and `Symbol.keyFor` can't be shimmed/polyfilled cross-realm. Symbol should never be used cross-realm unless natively supported.

**Comment by bisubus** [comment]
It appears that they really shouldn't in a way they are currently implemented, but since this doesn't comply to native behaviour, I hope this can be improved.
I wonder what was the reasoning for using random uids for symbol string representations. The issue could be fixed by using pseudo random uids for symbols from global registry and builtins.

**Comment by JakeChampion** [comment]
It is impossible to write a polyfill for symbols which works cross realm

**Comment by zloirock** [comment]
Symbols can't be properly polyfilled cross-realm. It's possible to make symbols cross-realm for some minor cases, but I don't think that it's worth it.
