### ISSUE TITLE
These dependencies were not found: * core-js/library/fn/object/assign in ./node_modules/babel-runtime/core-js/object/assign.js

### ISSUE THREAD

**Issue by PengQingYao** [zloirock/core-js#837]
I use the command vue serve create project ,

These dependencies were not found:
* core-js/library/fn/object/assign in ./node_modules/babel-runtime/core-js/object/assign.js
* core-js/library/fn/symbol in ./node_modules/babel-runtime/core-js/symbol.js
* core-js/library/fn/symbol/iterator in ./node_modules/babel-runtime/core-js/symbol/iterator.js
Can you help me?

**Comment by zloirock** [comment]
It's not a `core-js` issue since that entry points available in `core-js@2` on which relies this old `babel-runtime`.
