### ISSUE TITLE
Unable to push to heroku. Getting a core-js post install error.

### ISSUE THREAD

**Issue by zendevil** [zloirock/core-js#843]
While pushing on heroku, I'm getting the following error:

```
remote: > core-js-pure@3.6.5 postinstall /root/.nvm/versions/node/v12.18.1/lib/node_modules/karma/node_modules/core-js-pure        
remote: > node -e "try{require('./postinstall')}catch(e){}"        
remote: 
remote: sh: 1: node: Permission denied        
remote: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/karma/node_modules/chokidar/node_modules/fsevents):        
remote: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})        
remote:         
remote: npm ERR! code ELIFECYCLE        
remote: npm ERR! syscall spawn        
remote: npm ERR! file sh        
remote: npm ERR! errno ENOENT        
remote: npm ERR! core-js-pure@3.6.5 postinstall: `node -e "try{require('./postinstall')}catch(e){}"`        
remote: npm ERR! spawn ENOENT        
remote: npm ERR!         
remote: npm ERR! Failed at the core-js-pure@3.6.5 postinstall script.        
remote: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.        
remote:         
remote: npm ERR! A complete log of this run can be found in:        
remote: npm ERR!     /root/.npm/_logs/2020-07-04T09_49_17_733Z-debug.log        

```

How to fix this?

**Comment by mfitton** [comment]
I'm hitting a very similar error

**Comment by mfitton** [comment]
Oops, sorry, it was due to a node update, not core-js.

**Comment by codethief** [comment]
I've been experiencing the same issue. Shouldn't the postinstall script call `nodejs` instead of `node`? See also https://askubuntu.com/questions/404929/node-command-not-found

**Comment by lbeschastny** [comment]
I think it's not a good idea to spawn an executable file from the host system.
Current solution is based on an assumption that there is a `node` executable in `$PATH`, which it's not always so.

I think it would be better to use `child_process.fork` instead, since it doesn't depend on execution environment at all.

**Comment by xlnk** [comment]
> I've been experiencing the same issue. Shouldn't the postinstall script call `nodejs` instead of `node`? 

Official node.js package for ubuntu doesn't have "nodejs" command, only "node" command. The Snap package only has "node" command.

**Comment by liu-minjie** [comment]
node -e "try{require('./postinstall')}catch(e){}"
sh: node: command not found

**Comment by zloirock** [comment]
Closed due to inactivity.
