### ISSUE TITLE
Do we need both of core-js and core-js-pure in the bundle?

### ISSUE THREAD

**Issue by intelcoder** [zloirock/core-js#848]
I am using core-js to support IE11 mainly for promise and generator(Saga)
In my bundle I see core-js and core-js-pure. Do we need both of them?

![Screen Shot 2020-07-23 at 9 24 27 AM](https://user-images.githubusercontent.com/10482739/88407901-cb731600-cda0-11ea-899c-8afa3500eb61.png)

I have some setup on babelrc.

```
["@babel/preset-env", {
      "useBuiltIns": "usage",
      "corejs": 3,
      "targets": {
        "ie": "11"
      }
}]

["@babel/transform-runtime", {
      "corejs": 3
}],
index.js

```

I have this code on my root for clientside
import 'core-js/stable'
import 'regenerator-runtime/runtime'

**Comment by zloirock** [comment]
No. It's **3** different ways of `core-js` usage. You should use only one of them:
- `core-js` direct import
- `core-js` injecting by `usage` plugin from `@babel/preset-env`
- `core-js` injecting without global pollution by `@babel/transform-runtime` plugin

**Comment by perqa** [comment]
What if I include a library which uses `core-js-pure` into my app which only uses `core-js` by direct import? I guess it is inevitable then to get both `core-js-pure` and `core-js` in the bundle?

**Comment by zloirock** [comment]
@perqa yes. Now, since `core-js` and `core-js-pure` have the same commonjs API structure, you can try to configure `webpack` aliases or something similar, but it can be dangerous. However, I'm planning to add a way to avoid this duplication properly. This issue is tracked in https://github.com/zloirock/core-js/issues/833.
