### ISSUE TITLE
@types/core-js for a dynamic import of "core-js/stable" not working

### ISSUE THREAD

**Issue by cbdeveloper** [zloirock/core-js#850]
Hi everyone,

I do a dynamic import for `core-js/stable` features in my `index.ts` file.

```
import(
    /* webpackChunkName: "core-js-stable" */
    /* webpackMode: "lazy" */
    'core-js/stable'
  ).then(renderApp);
```

Even though I've installed `@types/core-js` I get an error/warning for "implicit any" when I'm dynamically importing `core-js/stable`

![image](https://user-images.githubusercontent.com/43407798/89177661-d6d5f680-d583-11ea-91ac-c38ca36bfca4.png)

If I import it directly as a regular top level `import "core-js/stable"` I do not get any errors/warnings.

Also if I dynamic import just the `core-js` without the `/stable` path, I also do not get any errors.

Example: This doesn't trigger any errors/warnings:

```
 import(
    /* webpackChunkName: "core-js-stable" */
    /* webpackMode: "lazy" */
    'core-js'
  ).then(renderApp);
```

Is there a workaround to this? Because I usually work with the `noImplicitAny` flag and my project won't compile like this.

Any help is appreciated.

Thanks

**Comment by zloirock** [comment]
I'm not someone who maintains `@types/core-js`, so it's not a correct repo for this issue - it should be [here](https://github.com/DefinitelyTyped/DefinitelyTyped).

If someone wants to add TypeScript definitions for `core-js` to here - feel free to add a PR.
