### ISSUE TITLE
Why setting prototype to boundFunction in function.bind?

### ISSUE THREAD

**Issue by MarvinXu** [zloirock/core-js#851]
https://github.com/zloirock/core-js/blob/8586728033f27eeba063d1be3204c46d144a2ff2/packages/core-js/internals/function-bind.js#L25

I was learning to recreate `Function.prototype.bind` for study purpose, and I noticed your implementation gave the `boundFuction` a prototype where as the native `bind` doesn't.

Then I checked ECMA-262 specification and I found a NOTE saying this:
https://tc39.es/ecma262/#sec-function.prototype.bind
> NOTE 1
Function objects created using Function.prototype.bind are exotic objects. They also do not have a "prototype" property.

So could you kindly explain to me why you implement like this ?

**Comment by loganfsmyth** [comment]
I _think_ this is because the spec requires that `.bind` work on constructor functions too, e.g.
```
function SomeClass(arg) { this._arg = arg; }
SomeClass.prototype.arg = function() { return this._arg; };

var inst = new (SomeClass.bind(null, 42))();
console.log(inst.value() == 42); // true
```
and the only way for that behavior to work in older environments is for the function to have a `.prototype`.

**Comment by MarvinXu** [comment]
> I _think_ this is because the spec requires that `.bind` work on constructor functions too, e.g.
> 
> ```
> function SomeClass(arg) { this._arg = arg; }
> SomeClass.prototype.arg = function() { return this._arg; };
> 
> var inst = new (SomeClass.bind(null, 42))();
> console.log(inst.value() == 42); // true
> ```
> 
> and the only way for that behavior to work in older environments is for the function to have a `.prototype`.

Thanks for the quick reply! I thought about this senario before, and I had tested it without the above line of code which turned out to work as well.

From where I stand, the "constructor function" senario was implemented in this line of code already
https://github.com/zloirock/core-js/blob/8586728033f27eeba063d1be3204c46d144a2ff2/packages/core-js/internals/function-bind.js#L12

**Comment by zloirock** [comment]
IIRC it was added for correct work of `instanceof` operator:
```js
function f() {}
const g = f.bind(null);
new g instanceof g; // => should be true
new g instanceof f; // => should be true
```
