### ISSUE TITLE
Bundle size for [].includes() is ~9kb

### ISSUE THREAD

**Issue by SanichKotikov** [zloirock/core-js#857]
Hi,

Could anybody explain why I've got ~9kb bundle for just using `[1,2,3].includes(2);`? Isn't it too much for such a simple thing? Or I doing something wrong and there is a better way?

<img width="1439" alt="Screenshot 2020-08-25 at 12 27 52" src="https://user-images.githubusercontent.com/10884736/91127155-d7b7ff00-e6cf-11ea-8513-e0a94e50f416.png">

Webpack loader options:

```js
use: {
	loader: 'babel-loader',
	options: {
		presets: [
			[
				'@babel/preset-env',
				{
					useBuiltIns: 'usage',
					corejs: '3.6',
				},
			],
		]
	}
}
```

Thanks!

**Comment by zloirock** [comment]
You could find the answer [here](https://github.com/zloirock/core-js/issues/388) and [here](https://github.com/babel/babel/pull/7646#discussion_r179474561). The main problem that `core-js` should support ES3 engines like IE8. Most likely I'll drop support of IE8- in `core-js@4` and the bundle size in your example will be decreased several times.
