### ISSUE TITLE
Copyright claim in webpack builds

### ISSUE THREAD

**Issue by kkaminski-github** [zloirock/core-js#861]
Hi!

In this file there is a copyright claim that is further passed to target script when building with webpack.
https://github.com/zloirock/core-js/blob/master/packages/core-js/internals/shared.js

Maybe it could be possible to change this line:
  copyright: '© 2020 Denis Pushkarev (zloirock.ru)'
into:
  author: 'Denis Pushkarev (zloirock.ru)'

Best regards,
Krzysztof

**Comment by JakeChampion** [comment]
The code is copyrighted to Denis --> https://github.com/zloirock/core-js/blob/master/LICENSE#L1

**Comment by zloirock** [comment]
You shouldn't worry. However, I'd prefer to leave it here.
