### ISSUE TITLE
TypeError Cannot convert undefined or null to object     at hasOwnProperty (<anonymous>)

### ISSUE THREAD

**Issue by DamienCompere** [zloirock/core-js#867]
Hello, 
After a yarn upgrdade I have the following error : 
```
has.js:4 Uncaught TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at ./node_modules/core-js/internals/has.js.module.exports
```
I tried to exclude `./node_modules/core-js` from my` '@babel/preset-env'` but still have the error, 
Do you know how to fix it ?

**Comment by zloirock** [comment]
Please, add a reproducible example. Without it, I can't say anything. Most likely, it's not a `core-js` issue.

**Comment by zloirock** [comment]
Closed as `can't reproduce`.

**Comment by tinhnghiadn3** [comment]
> Hello, After a yarn upgrdade I have the following error :
> 
> ```
> has.js:4 Uncaught TypeError: Cannot convert undefined or null to object
>     at hasOwnProperty (<anonymous>)
>     at ./node_modules/core-js/internals/has.js.module.exports
> ```
> 
> I tried to exclude `./node_modules/core-js` from my` '@babel/preset-env'` but still have the error, Do you know how to fix it ?

Have you fixed it? I need your solution, please reply me.
