### ISSUE TITLE
Support for @zloirock

### ISSUE THREAD

**Issue by alex3s** [zloirock/core-js#868]
Denis @zloirock , can we somehow send you crypto currency? Or at least support you directly to your paypal account?
I don't want to register on Patreon and go through the whole process just to be able to send you something. I prefer crypto because Paypal charges me 3% for each transaction, and I think Patreon is not better in this regard.
I understand that you are in a tight financial situation now, and I would like to help. :+1: 
Thanks.
All the best to you.

**Comment by zloirock** [comment]
Sorry for the delayed reply. Initially, I was in prison, after I was not up to it. [I added PayPal and Bitcoin to the funding section](https://github.com/zloirock/core-js#raising-funds).
