### ISSUE TITLE
[Question]Could we import the "pure" implmentation and set it to global for global polyfill?

### ISSUE THREAD

**Issue by NE-SmallTown** [zloirock/core-js#870]
If so, global polyfill like `import 'core-js'` can share modules/libs with pure polyfill like `@babel/transfrom-runtime` or `import 'core-js-pure'`

But now they don't share libs, so if an application use global polyfill and the 3rd party libs use pure polyfill, there will be many core-js libs with same content.

**Comment by NE-SmallTown** [comment]
related to https://github.com/babel/babel/issues/11515#issuecomment-623613118

**Comment by zloirock** [comment]
Seems it's almost a duplicate of [this you issue](https://github.com/zloirock/core-js/issues/833), I will answer there.
