### ISSUE TITLE
What module transpiles the "with" keyword?

### ISSUE THREAD

**Issue by binarykitchen** [zloirock/core-js#872]
Babel + core-js seem to transpile the `with` keyword into an IteratorConstructor:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with

This is breaking on IE11. How can I disable that?

**Comment by zloirock** [comment]
This issue is not related `core-js`. `core-js` does not transpile anything and `core-js` `IteratorConstructor` is not related `with` keyword.
