### ISSUE TITLE
I'm back

### ISSUE THREAD

**Issue by zloirock** [zloirock/core-js#874]
Wait for the news -)

**Comment by starzou** [comment]
### God bless you

**Comment by jzxznb** [comment]
好家伙，有你的

**Comment by r3nya** [comment]
Yay!

**Comment by Seminioni** [comment]
Пили пост

**Comment by joshmanders** [comment]
Welcome back!

**Comment by cepem** [comment]
Oh no

**Comment by Destaq** [comment]
When will we hear the news?

**Comment by joshxyzhimself** [comment]
Welcome back lol 🚀 🚀 🚀

**Comment by exposir** [comment]
Welcome back ！

**Comment by Eve-Sama** [comment]
cn: 好家伙, 我直接好家伙!
en: Awsome, really awsome!

**Comment by liwangyong** [comment]
cn: 好家伙, 我直接好家伙!
en: Awsome, really awsome!

**Comment by Nirongxu** [comment]
cn: 好家伙, 我直接好家伙!
en: Awsome, really awsome!

**Comment by IAALAI** [comment]
cn: 好家伙, 我直接好家伙!
en: Awsome, really awsome!

**Comment by Ryan2128** [comment]
cn: 好家伙, 我直接好家伙!
en: Awsome, really awsome!

**Comment by jehy** [comment]
Ещё нужна работа? Пиши : )

**Comment by ELI7VH** [comment]
welcome back. you still looking for a job? haha

**Comment by xjh22222228** [comment]
🚀🚀🚀

**Comment by phugodness** [comment]
where have you been? 🤔

**Comment by Attrash-Islam** [comment]
Welcome back!

**Comment by OtacilioN** [comment]
> where have you been? 🤔

In jail

**Comment by skyplaying** [comment]
大佬出来就有好工作了

**Comment by SagarBajpai** [comment]
Welcome bro! <3

**Comment by ysinsane** [comment]
You still looking for a job?
