### ISSUE TITLE
Internal dependency uses core-js 2. How to upgrade to core-js 3? 

### ISSUE THREAD

**Issue by sns45** [zloirock/core-js#878]
I am trying to upgrade my project from vue-cli-3 to vue-cli-4 which also upgrades my core-js from core-js@2 to core-js@3. But my internal dependencies are compiled using corejs-2 which I cannot upgrade from my end.
Which is why I get errors like:
`Module not found: Error: Can't resolve 'core-js/modules/es6.regexp.constructor'`

so what I can do to upgrade?

my `babel.config.js`:
```
module.exports = {
	presets: [
		'@vue/cli-plugin-babel/preset',
	],
	plugins: [
		[
			'component',
			{
				libraryName: 'elements-ui',
				styleLibraryName: 'theme-chalk',
			},
		],
	],
};

```

**Comment by zloirock** [comment]
Sorry, I cannot offer any panacea for cases like this. Your dependencies should also be updated to `core-js@3` if they use `core-js@2` as a peer dependency.

**Comment by takhello** [comment]
Module not found: Error: Can't resolve 'core-js/modules/es6.xxxxx
.....
.....
Can the causes of similar problems be added to the document to make it easier for users to understand
