### ISSUE TITLE
Preventing extensions on a string prototype causes an exception in core-js

### ISSUE THREAD

**Issue by dtychshenko** [zloirock/core-js#885]
We ran into a bit of an edge case when using a small object-freezing library [another-deep-freeze](https://www.npmjs.com/package/another-deep-freeze) together with core-js. 

`another-deep-freeze` simply recursively freezes a nested object through a prototype using [Object.preventExtensions()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) ([here](https://github.com/dsfx3d/another-deep-freeze/blob/develop/src/index.ts#L20) is their source code for reference)

What happens is if there is an object that has a string property that was frozen this way, then core-js throws an exception when attempting to extend a String.

Here is a simple repro case ([available here](https://dtychshenko.github.io/core-js-preventExtensions.html)):
```html
<html>
  <body>
    <script>
      const string = 'taxation is theft';
      string.__proto__ = Object.preventExtensions(string.__proto__);
    </script>
    <script src="https://unpkg.com/core-js-bundle@3.7.0/index.js"></script>
  </body>
</html>
```

Which results in the following core-js error:
```
index.js:1057 Uncaught TypeError: Cannot define property at, object is not extensible
    at Object.defineProperty [as f] (<anonymous>)
    at module.exports (index.js:1057)
    at module.exports (index.js:1142)
    at module.exports (index.js:812)
    at Object.<anonymous> (index.js:14861)
    at __webpack_require__ (index.js:26)
    at Object.<anonymous> (index.js:411)
    at __webpack_require__ (index.js:26)
    at index.js:90
    at index.js:93
```

I'm not sure if this is a core-js issue per-se because preventing extensions of a string prototype is not exactly a common use case, but the exception is still thrown within core-js nonetheless and I thought this could still be interesting to report here or for someone, who might run into this issue too. Thanks!

**Comment by zloirock** [comment]
Logically. `core-js` does not work in environments broken by users or other libraries. In this case, it just can't export itself. You could try the `pure` version.

**Comment by dtychshenko** [comment]
@zloirock In my repro case above, I'm not using other libraries though, nor is the environment broken. Again, although preventing extensions on a string prototype is not a common use case, there's nothing illegal or breaking about it in itself. What breaks is `core-js` when it encounters this condition.

To be clear, I'm not expecting `core-js` to work in this scenario. I do expect it to fail because it was not able to polyfill a string, but perhaps it could do so more gracefully. Should `core-js` check if object isExtensible before trying to extend it, or catch the exceptions and log a more descriptive error instead? It would really help others understand what failed and why, so they can adjust accordingly.

**Comment by zloirock** [comment]
@dtychshenko sorry, but a frozen built-in prototype is a kind of broken environment. By the spec, it should be extensible and if you freeze it - you break it. `core-js` should not check all possible scenarios how users could break their environments, moreover, it's impossible to make to work `core-js` properly in cases of broken environments like this.
