### ISSUE TITLE
Float32Array does not have Symbol.toStringTag, 

### ISSUE THREAD

**Issue by zba** [zloirock/core-js#890]
I got this issue on Chromium 46.0.2490.0, core-js ```core-js@3.7.0```

when used ```require('util').inherits;```

to reproduce:

```
> a=new Float32Array()
< []
> Symbol.toStringTag in a
< false
```

In modern browser there is ```true``` and ```a[Symbol.toStringTag]``` returns ```Float32Array```

**Comment by zloirock** [comment]
How do you use `core-js`? It's tested and should work fine.

**Comment by zba** [comment]
I use it with webpack 5, babel version ```core-js@3.7.0```

in babel I have 
```
'presets': [['@babel/preset-env', {
                                corejs: { version: 3, proposals: true },
...
```

**Comment by zba** [comment]
![Screenshot 2020-11-25 133836-2](https://user-images.githubusercontent.com/807956/100192017-bdd2c600-2f23-11eb-93cb-176e76cb3ecc.png)

**Comment by zba** [comment]
So I have above and somehow have no idea how to access to this Symbol descriptor

**Comment by zloirock** [comment]
Maybe `Symbol` is overwritten? I have no other ideas. Could you add a reproducible example?

**Comment by zba** [comment]
Yes, Symbol.toString tag was recreated, I described patch here. Don't know if need to be fixed anywhere in libs, but may be will be useful to somebody who got this problem again.

https://github.com/inspect-js/which-typed-array/issues/46#issuecomment-734084179

In short browser from start has this state:

**`Object.getOwnPropertySymbols(Float32Array.prototype)`**
`[Symbol(Symbol.toStringTag), Symbol(Symbol.iterator)]`
**`Object.getOwnPropertySymbols(Float32Array.prototype)[0]`**
`Symbol(Symbol.toStringTag)`
**`typeof Symbol`**
`"function"`
**`typeof Symbol.toStringTag`**
`"undefined"`

**Comment by ljharb** [comment]
OK, so it seems like core-js perhaps should, instead of blindly *creating* `Symbol.toStringTag`, detect if it exists as a non-well-known Symbol first, and then preserve that value?

**Comment by zba** [comment]
I don't know, because minimal example seems do this, so I can't reproduce it out of my prod code, I still not found which code sets `Symbol.toStringTag` to new symbol, may be one of the dependedants of some lib does so, however I tried to debug hard and not found one.

**Comment by zloirock** [comment]
Seems you just not load a `core-js/modules/es.symbol` module (most likely, try to load it manually) or overwrite `core-js` `Symbol` polyfill. It's not a `core-js` issue.

**Comment by zloirock** [comment]
@ljharb seems you don't understand how `core-js` implement well-known symbols logic and defines well-known symbols. `core-js` could use well-known symbols logic even without existent properties on `Symbol` and if those properties will be defied after that - they will be already used internally well-known symbols.

**Comment by ljharb** [comment]
I certainly don't understand it, which is why i said "seems".

What I mean is, if an engine provides a `Symbol.toStringTag` on objects, and its native `Object.prototype.toString` reads that, but it fails to provide a `toStringTag` property on `Symbol`, then unless core-js feature-detect for that exact case, you'd end up not using the native one and over-polyfilling. Indeed, though, if the over-polyfilling is aggressive enough, it should still Just Work. Given that this issue is occurring, the implication is that it's not "just working".

**Comment by zloirock** [comment]
@ljharb sorry, I don't understand how it's related to the `core-js` implementation - your assumptions are not correct, see the source code -)

**Comment by zba** [comment]
So, I found the call path where it happens:

at some moment ```Symbol.toStringTag``` does not exists,

so here in **`es.symbol.js`** call:

```
$forEach(objectKeys(WellKnownSymbolsStore), function (name) {
  defineWellKnownSymbol(name);
});
```

```WellKnownSymbolsStore``` contains: 

```
species: Symbol(Symbol.species)
toPrimitive: Symbol(Symbol.toPrimitive)
toStringTag: Symbol(Symbol.toStringTag)
```


**`define-well-known-symbol.js`**:

```
  if (!has(Symbol, NAME)) defineProperty(Symbol, NAME, {
    value: wrappedWellKnownSymbolModule.f(NAME)
  });
```

and finaly at **`object-define-property.js`**

``` if ('value' in Attributes) O[P] = Attributes.value;```

sets the symbol to new one.

so @zloirock `es.symbol` is loaded and do this job, idk if needed to fixed or not, but this is what I have, can make more debugging for you if you interested why `WellKnownSymbolsStore` has new created symbol, but this is this.

**Comment by zloirock** [comment]
@zba yep, in the first message I forgot to write about `es.symbol.to-string-tag` module - `Symbol.toStringTag` exposed here.

**Comment by zba** [comment]
@zloirock anyway, not helps, may be because es.symbol loads by babel, before this, so Symbol.toString tag defined in the ```well-known-symbol.js```:

`  if (!has(WellKnownSymbolsStore, name)) {`
`    if (NATIVE_SYMBOL && has(Symbol, name)) WellKnownSymbolsStore[name] = Symbol[name];`
**`    else WellKnownSymbolsStore[name] = createWellKnownSymbol('Symbol.' + name);`** `// here `
`  } return WellKnownSymbolsStore[name];`

**Comment by zloirock** [comment]
@zba it works in any order. Please, add a reproducible example.

**Comment by zba** [comment]
@zloirock 
is it count as minimal example the following ?


```
console.log(
Object.getOwnPropertySymbols(Float32Array.prototype)[0].toString() === 'Symbol(Symbol.toStringTag)',
Object.getOwnPropertySymbols(Float32Array.prototype)[0] === Symbol.toStringTag
)
```
`true false`

**Comment by zloirock** [comment]
> @zloirock 
> 
> is it count as minimal example one, which has this in the console ? 
> 
> 
> 
> 
> 
> ```
> 
> console.log(
> 
> Object.getOwnPropertySymbols(Float32Array.prototype)[0].toString() === 'Symbol(Symbol.toStringTag)',
> 
> Object.getOwnPropertySymbols(Float32Array.prototype)[0] === Symbol.toStringTag
> 
> )
> 
> ```
> 
> `true false`
> 
> 

No, since with proper 'core-js' usage it's tested and works even in this Chrome version as expected.

**Comment by zba** [comment]
Why no ? What is proper usage ? The Symbol.toStringTag() in global is not the same symbol as in Float32Array.prototype, which causes this error.

**Comment by zba** [comment]
So i need to reproduce:

*`console.log(Object.getOwnPropertySymbols(Float32Array.prototype)[0].toString() === Symbol.toStringTag.toString(), Object.getOwnPropertySymbols(Float32Array.prototype)[0] === Symbol.toStringTag, Float32Array.prototype[Symbol.toStringTag])`*
`true false undefined`

?

**Comment by zloirock** [comment]
You should reproduce how do you include `es.symbol.to-string-tag` without adding `Symbol.toStringTag` polyfill. Chrome 46:
![image](https://user-images.githubusercontent.com/2213682/100344352-3fede800-3013-11eb-8c48-14f923125eb0.png)

**Comment by ljharb** [comment]
It may be notable that the report is in Chromium 46, not Chrome 46?

**Comment by zloirock** [comment]
@ljharb I don't think so. Almost all issues like this are issues related incorrect `core-js` inclusion.

**Comment by zba** [comment]
Symbol.toStringTag here, but I see there is no Float32Array and other typed array polifills in sourcemaps, only symbol ones.
