### ISSUE TITLE
Security vulnerability: Insecure Randomness and Overly Permissive Message Posting Policy

### ISSUE THREAD

**Issue by tibabit** [zloirock/core-js#891]
Hi I using babel with react application. After building my application I am running Fortify tool to scan for security vulnerabilities. In which I am getting two reports in core-js module, 1st is "Insecure Randomness" and 2nd is "Overly Permissive Message Posting Policy"

Snapshot of the reports

**Overly Permissive Message Posting Policy-**

![image](https://user-images.githubusercontent.com/805631/100224077-56783e80-2f42-11eb-9bf7-900806d14e09.png)

**Insecure Randomness-**
![image](https://user-images.githubusercontent.com/805631/100224178-7f98cf00-2f42-11eb-9f8a-d22ceef002b4.png)

Can you please take a look at these and let me know when these will be fixed.

Babel:
@babel/core": "^7.4.3
@babel/plugin-proposal-class-properties": "^7.4.0
@babel/plugin-transform-runtime": "^7.4.4
@babel/polyfill": "^7.0.0
@babel/preset-env": "^7.4.3
@babel/preset-react": "^7.0.0
@babel/preset-typescript": "^7.3.3
@babel/runtime-corejs2": "^7.1.2
@babel/runtime-corejs3": "^7.4.0

Forityfy: 19.2
core-js: 2.6.11

**Comment by JakeChampion** [comment]
The randomness does not need to be secure for the Symbol polyfill

**Comment by zloirock** [comment]
It's not security vulnerabilities. If you don't think so - please, show how they could be used.

**Comment by tibabit** [comment]
@zloirock  Here is how fortify reported this - 

## Insecure Randomness
Insecure randomness errors occur when a function that can produce predictable values is used as a source of randomness in
security-sensitive context.
Computers are deterministic machines, and as such are unable to produce true randomness. Pseudorandom Number Generators
(PRNGs) approximate randomness algorithmically, starting with a seed from which subsequent values are calculated.
There are two types of PRNGs: statistical and cryptographic. Statistical PRNGs provide useful statistical properties, but their
output is highly predictable and forms an easy to reproduce numeric stream that is unsuitable for use in cases where security
depends on generated values being unpredictable. Cryptographic PRNGs address this problem by generating output that is more
difficult to predict. For a value to be cryptographically secure, it must be impossible or highly improbable for an attacker to
distinguish between it and a truly random value. In general, if a PRNG algorithm is not advertised as being cryptographically
secure, then it is probably a statistical PRNG and should not be used in security-sensitive contexts, where its use can lead to
serious vulnerabilities such as easy-to-guess temporary passwords, predictable cryptographic keys, session hijacking, and DNS
spoofing.
Example: The following code uses a statistical PRNG to create a URL for a receipt that remains active for some period of time
after a purchase.
function genReceiptURL (baseURL){
var randNum = Math.random();
var receiptURL = baseURL + randNum + ".html";
return receiptURL;
}
This code uses the Math.random() function to generate "unique" identifiers for the receipt pages it generates. Because
Math.random() is a statistical PRNG, it is easy for an attacker to guess the strings it generates. Although the underlying design of
the receipt system is also faulty, it would be more secure if it used a random number generator that did not produce predictable
receipt identifiers, such as a cryptographic PRNG.


## Overly Permissive Message Posting Policy
One of the new features of HTML5 is cross-document messaging. The feature allows scripts to post messages to other windows.
The corresponding API allows the user to specify the origin of the target window. However, caution should be taken when
specifying the target origin because an overly permissive target origin will allow a malicious script to communicate with the
victim window in an inappropriate way, leading to spoofing, data theft, relay and other attacks.
Example 1: Below is an example of using a wildcard to programmatically specify the target origin of the message to be sent.
o.contentWindow.postMessage(message, '*');
Using the * as the value of the target origin indicates that the script is sending a message to a window regardless of its origin.

**Comment by zloirock** [comment]
@tibabit I don’t care how `fortify` reported this - I don't see any real security vulnerabilities here. I asked about how it could be used. The report text absolutely is not related to those cases - `Math.random` in the `Symbol` polyfill is not something about security, `postMessage` in the microtask implementation used with empty messages - here is no data that could be theft, sending any messages to the listener also could not cause any problems.

**Comment by smile25896** [comment]
@tibabit  did you solve this problem?

**Comment by tibabit** [comment]
@smile25896 use specific window name instead of *
