### ISSUE TITLE
Will core-js supports `exports` ESM field?

### ISSUE THREAD

**Issue by JLHwung** [zloirock/core-js#893]
Node.js ESM introduces an [`"exports"`](https://nodejs.org/api/packages.html#packages_exports) field to instruct whether submodule imports like 
```js
import "core-js/modules/es6.array.copy-within"
```
is allowed.

`@babel/preset-env` generate imports of `core-js` as `import "core-js/modules/es6.array.copy-within"`. However `core-js` package does not specify `exports` in its `package.json`. Thus it throws on Node.js and Webpack 5: https://github.com/babel/babel/issues/12378

For such imports to work, `core-js` can specify `exports` like

```json
{
  "exports" : {
    "./modules/es6.array.copy-within" : "./modules/es6.array.copy-within.js"
  }
}
```
similar to what Babel did for `@babel/runtime-corejs3`: https://unpkg.com/@babel/runtime-corejs3@7.12.5/package.json

In https://github.com/babel/babel/pull/10862 Babel tries to workaround this issue by adding `.js` to such imports

```js
import "core-js/modules/es6.array.copy-within.js"
```

However it will break if `core-js` later adds `exports` but do not support exporting `./`, or `core-js` decides to ship the `.mjs` version. I feel it is better to coordinate here.

**Comment by zloirock** [comment]
I'm thinking about adding it to `core-js@4`.

**Comment by zloirock** [comment]
After adding all `core-js` entries to this field, CI randomly dies (2 / 3 chance) on MacOS https://github.com/zloirock/core-js/actions/runs/432880677 - seems 3k+ entries in this field is too much -/

**Comment by zloirock** [comment]
Removing some unnecessary entries allowed to reduce the number of lines to a reasonable number.

**Comment by zloirock** [comment]
Added in [`v4` branch](https://github.com/zloirock/core-js/pull/1310).
