### ISSUE TITLE
Promise.any is not a function

### ISSUE THREAD

**Issue by weiliang903** [zloirock/core-js#895]
macOS 10.15.5
safair 13.1.1 

entry file:
```javascript
import 'core-js/stable';
import 'regenerator-runtime/runtime';
```

babel config:
```javascript
      [
        require('@babel/preset-env'),
        {
          useBuiltIns: 'entry',
          corejs: 3.8,
          modules: false,
          exclude: ['transform-typeof-symbol']
        }
      ],
```

package.json
```json
    "core-js": "^3.8.1",
    "regenerator-runtime": "^0.13.7",
```

![截屏2020-12-07 20 15 00](https://user-images.githubusercontent.com/20644345/101350507-05fdcb00-38ca-11eb-8b68-b73b33d21499.png)

But, I found the file in the stable folder, What did I miss?

**Comment by zloirock** [comment]
I can't reproduce it. A reproducible example could be useful.

**Comment by zloirock** [comment]
As an option, you use an obsolete version of `@babel/preset-env`.

**Comment by weiliang903** [comment]
@zloirock Thanks reply. I manually imported the `es.promise.any.js` file, it's working. 
```javascript
import 'core-js/modules/es.promise.any';
```

This is a comparison of webpack analyzer.

<img width="487" alt="截屏2020-12-07 22 04 48" src="https://user-images.githubusercontent.com/20644345/101360829-25502480-38d9-11eb-96d0-a6d3c4f27c8c.png">

<img width="452" alt="截屏2020-12-07 22 04 40" src="https://user-images.githubusercontent.com/20644345/101360862-2e40f600-38d9-11eb-9a18-b970c35343c7.png">

**Comment by zloirock** [comment]
Most likely the issue in obsolete `@babel/preset-env` and / or `core-js-compat`, so the issue is closed.
