### ISSUE TITLE
Please, remove your ad from console messages

### ISSUE THREAD

**Issue by SaidMavlyan** [zloirock/core-js#897]
Please, remove your ad from console messages after installation. 
Console was and should stay pristine and sacral place without advertisements.
I would be happy to never use your package just because of your ads, 
but it comes with dependencies, and mars one of the rare pristine places left without ads.
Please, don't be a `${the_word_you_do_not_want_to_be_called_by}`, just because of that ad you get -100500 to your karma not just from me.

**Comment by zloirock** [comment]
Please, no longer use `core-js`, `${the_word_you_do_not_want_to_be_called_by}`.
