### ISSUE TITLE
What's the best practice of babel & core-js?

### ISSUE THREAD

**Issue by liugui** [zloirock/core-js#905]
When I use core-js with babel, I want to try my best to reduce the output file size. So I will configure babel to import only some polyfills. First, I use `@babel/preset-env` with `useBuiltIns: usage` like this:

```
"presets": [
        ["@babel/preset-env", {
            "modules": false,
            "useBuiltIns": "usage",
            "corejs": 3,
            "targets": "ie >= 8"
        }]
  ],
```

Thanks to core-js and @babel/preset-env, this works well. But I want to use `@babel/runtime` to import some common helper functions to save more output file size:

```
"presets": [
        ["@babel/preset-env", {
            "modules": false,
            "useBuiltIns": "usage",
            "corejs": 3,
            "targets": "ie >= 8",
            "debug": true
        }]
    ],
    "plugins": [
        ["@babel/plugin-transform-runtime", {
            "corejs": false
        }]
 ]
```

However, there is a problem: when I use `corejs: false` in `@babel/plugin-transform-runtime`, some helper functions may need polyfill which I don't import with `useBuiltIns: usage`. For example, when I import a helper function : `import '@babel/runtime/helpers/asyncToGenerator';` .  With the source code of asyncToGenerator, we can see that this helper needs a Promise polyfill:

```
 if (info.done) {
    resolve(value);
  } else {
   // Here is a Promise
    Promise.resolve(value).then(_next, _throw);
  }
}
```

However, If my source code doesn't have a Promise function,  then the promise polyfill won't be imported. So the runtime function will be broken is some old browsers. 

Another way, if I use core-js with @babel/runtime instead of preset-env:

```
{
    "presets": [
        ["@babel/preset-env", {
            "modules": false,
            "useBuiltIns": "usage",
            "corejs": false,
            "targets": "ie >= 8"
        }]
    ],
    "plugins": [
        ["@babel/plugin-transform-runtime", {
            "corejs": 3
        }]
    ]
}
```

As we know, @babel/runtime-corejs3 will not only polyfill runtime helpers, but also polyfill my source code. But there is also a big problem: @babel/runtime-corejs3 will ignore the target configure. So it will import all possible polyfills.

So, what's the best practice of babel and core-js? Any help will be appreciated!

**Comment by Talent30** [comment]
"presets": [
        ["@babel/preset-env", {
            "modules": false,
            "useBuiltIns": "entry",
            "corejs": 3,
            "targets": "ie >= 8",
            "debug": true
        }]
    ],
    "plugins": [
        ["@babel/plugin-transform-runtime", {
            "corejs": false
        }]
 ]

**Comment by zloirock** [comment]
It seems that you have got an answer for your case here https://github.com/babel/babel/discussions/12605.

**Comment by boycce** [comment]
@zloirock as of today an answer but not a solution..

**Comment by zloirock** [comment]
@boycce ...solution to what problem?

Now if you need a `Promise` polyfill in `regenerator-runtime` and if you use `preset-env` with `usage` mode - you should transpile `regenerator-runtime` or use `Promise` before `regenerator-runtime` or import `Promise` polyfill from `core-js` directly. It's a `preset-env` issue, a subset of [this](https://github.com/babel/babel/issues/13128) issue.
