### ISSUE TITLE
LegacyIteratorNext issue with iterators.

### ISSUE THREAD

**Issue by romainmenke** [zloirock/core-js#906]
https://github.com/zloirock/core-js/blob/cc5b386ecef9a4aef9321b4d5953afd9226b8e1e/packages/core-js/internals/array-from.js#L27

Run through babel + core-js.
Test in older firefox (43 has the error)

```js
const url = new URL(
	'https://u:p@example.com:8080/some/path?foo=true&bar=true#frag'
);

Array.from(url.searchParams.entries());
```

Result :

Page will freeze with an infinite loop.

--------

Caused by : https://github.com/mozilla/gecko-dev/blob/0f254a30d684796bcc8b6e2a102a0095d25842bb/js/src/builtin/Iterator.js#L14

Hacky way to circumvent :

```js
next = iterator.next;
var isLegacyIteratorNext = next.name === 'LegacyIteratorNext';
result = new C();
for (;!(step = (isLegacyIteratorNext ? next.call(iterator).value : next.call(iterator))).done; index++) {
  value = mapping ? callWithSafeIterationClosing(iterator, mapfn, [step.value, index], true) : step.value;
  createProperty(result, index, value);

  if (index > 150) { // how to detect the infinite loop
    throw new Error('panic');
  }
}
```

-----------

Unsure what changed.
We started seeing this error a couple of weeks ago but it might have always been there and maybe didn't get reported.

**Comment by zloirock** [comment]
`core-js` does not use native `URL` and `URLSearchParams` in FF43, they should overwritten in FF57-. Make sure that you load all required modules.

**Comment by romainmenke** [comment]
This is with the overwritten `URL` and `URLSearchParams`.

```
modules by path ../../../node_modules/core-js/internals/*.js 51.6 KiB 81 modules
modules by path ../../../node_modules/core-js/modules/*.js 48.9 KiB
  ../../../node_modules/core-js/modules/es.array.from.js 433 bytes [built] [code generated]
  ../../../node_modules/core-js/modules/es.array.iterator.js 2.1 KiB [built] [code generated]
  ../../../node_modules/core-js/modules/es.object.to-string.js 380 bytes [built] [code generated]
  ../../../node_modules/core-js/modules/es.string.iterator.js 1.01 KiB [built] [code generated]
  ../../../node_modules/core-js/modules/web.dom-collections.iterator.js 1.53 KiB [built] [code generated]
  ../../../node_modules/core-js/modules/web.url.js 31.9 KiB [built] [code generated]
  ../../../node_modules/core-js/modules/web.url-search-params.js 11.6 KiB [built] [code generated]
```

babel config :

```js
module: {
	rules: [
		{
			test: /\.js$/,
			exclude: /(node_modules)/,
			use: {
				loader: 'babel-loader',
				options: {
					comments: false,
					presets: [
						[
							'@babel/preset-env',
							{
								corejs: '^3.6.3',
								targets: {
									browsers: [ 'chrome >= 26', 'edge >= 12', 'firefox >= 26', 'opera >= 26', 'safari >= 6', 'ie >= 8' ],
								},
								useBuiltIns: 'usage'
							}
						]
					]
				}
			}
		}
	]
}
```

**Comment by romainmenke** [comment]
A minimal project that reproduces the issue :

https://github.com/romainmenke/legacy-iterator-next

When visiting the page in Firefox 43 :

<img width="963" alt="Screenshot 2021-01-09 at 23 02 43" src="https://user-images.githubusercontent.com/11521496/104109501-d2e69700-52ce-11eb-9e31-9e5eb1c39582.png">

**Comment by romainmenke** [comment]
Thank you @zloirock for taking the time to look into this and for having a fix so quickly!
Really appreciate all the hard work that goes into this project!
