### ISSUE TITLE
WeakMap error in IE11

### ISSUE THREAD

**Issue by ViggoV** [zloirock/core-js#907]
Hi. I am getting the following error in IE11 when running my Webpack/Babel app:

<img width="418" alt="Screen Shot 2021-01-27 at 09 18 10" src="https://user-images.githubusercontent.com/3153568/105962863-96fa5280-6080-11eb-9dff-c82e3fb41a8d.png">

IE's debugger points to line 37 of `core-js/internals/collection.js`. If I remove the `core-js/stable` import from my app, the next WeakMap occurence will throw the same error. It was my impression, however, that `core-js` was supposed polyfill WeakMap in IE

I am using:
- core-js 3.8.3
- webpack 5.9.0
- @babel/core 7.12.9 (with `/node_modules/` excluded)

I `import 'core-js/stable` as the first thing in my entry point.

I have tried the suggestion from [Issue 485](https://github.com/zloirock/core-js/issues/485) with no luck.

**Comment by zloirock** [comment]
I'm not sure that it's a `core-js` issue - `WeakMap#set` should throw an error on primitive as a key. Please, add a reproducible example.

**Comment by ViggoV** [comment]
I threw this repo together: https://github.com/ViggoV/weakmap-error-repro

The error thrown is different, but it does throw on a `core-js` file mentioning WeakMaps. In any case, it is the only import used.

Thanks for your time

**Comment by ViggoV** [comment]
I solved my issue by reverting to the deprecated `@babel/polyfill`. I have tried a bunch of different configurations for Babel and Core-JS, but I was unable to replicate the behavior. It's probably rather a `babel` or `webpack` issue.
