### ISSUE TITLE
Publish my codes using Promise.any() can't work on Chrome 85+ (with native Promise.any support)

### ISSUE THREAD

**Issue by qiulang** [zloirock/core-js#908]
I first asked the question at [SO](https://stackoverflow.com/questions/66088525/how-do-i-polyfill-promise-any-using-babel-7) , basically my codes use `Promise.any()` and I use webpack to publish my codes to the clients who use Chrome 80 that doesn't support Promise.any() natively. So I have been trying to polyfill `Promise.any()` for them. But now with Babel 7 my published code can't event work on Chrome 85 that supports `Promise.any()` natively. 

But because if I use Babel 6, the bundled code don't have any problem to work on Chrome85+, so I feel like it may be a bug.

My .bablerc

```
{
    "env": {
        "production": {
            "presets": [
                [
                    "@babel/preset-env",
                    {
                        "targets": {
                            "browsers": [
                                "last 5 Chrome versions",
                                "last 3 Firefox versions",
                            ]
                        },
                        "modules": "commonjs",
                        "debug": true,
                        "useBuiltIns": "usage"
                    }
                ]
            ],
            "plugins": [
                [
                    "@babel/plugin-transform-runtime",
                    {
                        "corejs": 2,
                        "regenerator": true
                    }
                ]
            ]
        }
    }
}
```

My webpack.config.js

```
module.exports = {
    entry: {
        index: './src/index.js'
        ui:'./src/ui/index.js'
    },
    output: {
        path: path.resolve(__dirname, './dist'),
        filename: '[name].js',
        libraryTarget: 'umd',
        libraryExport: 'default',
        umdNamedDefine: true,
        library: '[name]'
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader'
                }
            },
   ...
}
```

The bebel packages I used in package.json

```
    "devDependencies": {
        "@babel/core": "^7.0.0",
        "@babel/plugin-transform-runtime": "^7.0.0",
        "@babel/polyfill": "^7.12.1",
        "@babel/preset-env": "^7.0.0",
        "@babel/runtime-corejs2": "^7.12.13",
        "babel-eslint": "^10.0.1",
        "babel-loader": "^8.0.0",
```

With those settings, when I run my published codes on Chrome 85+ I got the error  **"Uncaught (in promise) rejected"**.
When I switch to Babel 6 I don't have the error, Promise.any() works.

**Comment by zloirock** [comment]
You use an obsolete version of `core-js`.

**Comment by zloirock** [comment]
Also (it's not related your issue), you should never use `useBuiltIns` of `preset-env` and `runtime` with `corejs` option together.

**Comment by qiulang** [comment]
I did tried to use  "core-js": "3.8.3" with

```
"@babel/plugin-transform-runtime",
                    {
                        "corejs": 3,
                        "regenerator": true
                    }
```

But then webpack complained a bunch of `Can't resolve 'core-js/modules/... ` I don't know how to fix. So you please tell how to set my .babelrc with corejs 3 correctly as you also said "I never use useBuiltIns of preset-env and runtime with corejs option together"?

**Comment by qiulang** [comment]
Hi with your input I finally fix it. Thanks! Following is my .babelrc

"production": {
            "presets": [
                [
                    "@babel/preset-env",
                    {
                        "targets": { ... },
                        "modules": "commonjs",
                        "debug": true,
                        "useBuiltIns": "usage",
                        "corejs": {
                            "version": 3, 
                            "proposals": true
                        }
                    }
                ]
            ],
            "plugins": [
                [
                    "@babel/plugin-transform-runtime",
                    {
                        "regenerator": true
                    }
                ]
            ]
        }

**Comment by zloirock** [comment]
I'd recommend to use `"corejs": { "version": "3.8" }` if you need `Promise.any`, but don't need unstable features.

**Comment by qiulang** [comment]
Thanks, with 3.8 do I need set `"proposals": true` too ?

**Comment by zloirock** [comment]
Nope, in this case `Promise.any` will be injected as a stable ES feature.

**Comment by qiulang** [comment]
I set `"proposals": false`, the bundled codes failed again. I changed back to `"proposals": true` then the bundled codes work. That is just one of examples babel drives me crazy.

**Comment by zloirock** [comment]
It seems that you use obsolete `core-js-compat`.

**Comment by qiulang** [comment]
I didn't use it myself. But I check yarn.lock and see core-js-compat is preset-env's dependency.

BTW,  setting babelrc right is always a daunting task to me. I never know which setting correct or necessary.

```
"@babel/preset-env@^7.0.0":
  version "7.12.13"
  resolved "https://registry.npmjs.org/@babel/preset-env/-/preset-env-7.12.13.tgz#3aa2d09cf7d255177538dff292ac9af29ad46525"
  integrity sha512-JUVlizG8SoFTz4LmVUL8++aVwzwxcvey3N0j1tRbMAXVEy95uQ/cnEkmEKHN00Bwq4voAV3imQGnQvpkLAxsrw==
  dependencies:
  ...
  core-js-compat "^3.8.0"
```

**Comment by zloirock** [comment]
In this case, I have no ideas - only NPM cache. Anyway, it's an issue with `babel`, not with `core-js`.

`useBuiltIns` option of `preset-env` makes sense for applications, `corejs` option of `runtime` - for libraries. They do the same thing, but for different use cases. Enabling both of the cause duplications of polyfills, increasing the size and possible conflicts.

**Comment by stepancar** [comment]
@zloirock , I faced with the same version. babel.compat.
My version of core-js is 3.9, core-js-compat: 3.9
I even set to .browserlistrc `last 20 Chrome versions`

with 
```
"corejs": {
            "version": "3.9"
 },
```
core-js does not apply promise.any polyfill

but if I pass

```
"corejs": {
            "version": "3.9",
            "proposals": true
 },
```
I see `esnext.promise.any { "android":"88", "chrome":"69", "edge":"88",....`

**Comment by zloirock** [comment]
@stepancar make sure that you use the latest `preset-env` and the output contains `es.promise.any` / `esnext.promise.any`. Anyway, it's not a `core-js` issue.
