### ISSUE TITLE
IE11 Incompatible receiver - @babel/env build from esm to amd

### ISSUE THREAD

**Issue by evromalarkey** [zloirock/core-js#909]
Hello,
I'm trying to build IE11 compatible output with rollup and @babel/env preset. Everything build ok and the output works in modern browsers. But not in IE11, here I get Incompatible receiver error in the console. 

Is this problem with corejs or did I do something wrong elsewhere in the config related to babel and corejs? Trying to figure out this for some time and creating rollup config with modern esm imports and dynamic imports, also with support for legacy browsers seems like an impossible task form me :sweat_smile:  and can't find any working example of this online.

Here is the demo repo
https://github.com/evromalarkey/esm-ie11

Any help appreciated :pray:

**Comment by sviat9440** [comment]
Same here +1

**Comment by zloirock** [comment]
You should not transpile `core-js`, exclude it from your transpiling options.
