### ISSUE TITLE
[Feature request] Bundle summary for core-js-builder

### ISSUE THREAD

**Issue by vforsh** [zloirock/core-js#910]
It would be useful if this utility could provide some summary along with the code. Something like the total bundle size and what percentage each polyfill has taken.

**Comment by zloirock** [comment]
I'm not sure that "percentage each polyfill has taken" is possible since `core-js` modules use shared internals. However, showing some bundle summary could be useful.

**Comment by zloirock** [comment]
Bundle summary for `core-js-builder` will be added in `core-js@4`.

**Comment by zloirock** [comment]
I backported it to `core-js@3`, it will be available in `3.16`.
