### ISSUE TITLE
TypeError: $ is not a function

### ISSUE THREAD

**Issue by Mikilll94** [zloirock/core-js#912]
I have the following project which is using webpack + babel + core.js

[vue-webpack-test.zip](https://github.com/zloirock/core-js/files/5984302/vue-webpack-test.zip)

It builds fine but when I open the browser, it throws the following error

![Screenshot 2021-02-15 at 22 59 19](https://user-images.githubusercontent.com/17653648/107996761-7408f180-6fe1-11eb-8244-c734cf7dec8a.png)

To run the project you need to execute:
```
npm install
npm run dev
```

**Comment by zloirock** [comment]
You should not transpile `core-js`, add it to the `exclude` option of `babel-loader`.

**Comment by BombCowpat** [comment]
I have the same problem, add `exclude: ['./node_modules']` in `babel.config.js` maybe work

**Comment by Ram4GB** [comment]
> I have the same problem, add `exclude: ['./node_modules']` in `babel.config.js` maybe work

I confirm that resolve my issue
