### ISSUE TITLE
core-js/features/symbol broken in IE11

### ISSUE THREAD

**Issue by mdix** [zloirock/core-js#916]
When adding 'core-js/features/symbol' to a bundle and executing the bundle in IE11, it fails with the error message triggered from here: https://github.com/zloirock/core-js/blob/master/packages/core-js/internals/internal-state.js#L21, "Incompatible receiver".

**Comment by mdix** [comment]
Might be related to https://github.com/zloirock/core-js/issues/909

**Comment by zloirock** [comment]
You should not transpile `core-js`. Exclude it from `babel` options.

**Comment by mdix** [comment]
Just a suggestions but... you could ask before closing issues. I already excluded core-js from transpiling via an exclude in my `babel-loader` configuration:

```
            {
                test: /\.js$/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        exclude: [
                            /node_modules[\\/]core-js/
                        ],
                    }
                },
            },
``` 

(which can be found in the `babel-loader` npm repo https://www.npmjs.com/package/babel-loader).

**Comment by zloirock** [comment]
99% that your issue in transpiling of `core-js` since it's a common user mistake and for `core-js/features/symbol` ends in this line. If you are pretty sure that it's another case - please, add a reproducible example.
