### ISSUE TITLE
core-js is too big

### ISSUE THREAD

**Issue by fireridlle** [zloirock/core-js#917]
I'm writing some npm package and also would like to provide cdn version of my package.

I use webpack with the following config

```
module.exports = env => ({
  entry: path.resolve(__dirname, './src/index.js'),
  mode: 'production',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'lib.js',
    library: 'lib',
    libraryTarget: 'umd',
    globalObject: 'this',
  },
  module: {
    rules: [
      {
        test: /\.m?js$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            envName: 'umd',
          },
        },
      },
    ],
  }
})
```
And .babelrc config
```
{
      "presets": [["@babel/preset-env", { 
        "modules": "umd",
        "useBuiltIns": "usage",
        "targets": {
          "browsers": "last 2 versions"
        },
        "bugfixes": true,
        "corejs": 3,
        "debug": true
      }]]
    }
```

Unfortunately it produce a huge bundle size (461kb) where 185kb is core-js
![image](https://user-images.githubusercontent.com/12122603/111429336-8cb01880-8701-11eb-9991-b564a569878e.png)

Is there any solution how to reduce it?

**Comment by zloirock** [comment]
Even with all proposals, with all modules, minified full `core-js` size is ~160kb, see `core-js-bundle` - and it's not a big size for features which `core-js` provide. Seems you have a problem with minification. Your browserslist target includes `last 2 versions` -> IE10, almost all `core-js` modules required for this target. Static analysis from `preset-env` detects features from your code that require polyfilling in the lower target and adds polyfills for them. You could raise the lower browser target and / or reduce the number of used features which require polyfilling.
