### ISSUE TITLE
Respect `npm-fund` and `fund` flag in npm config

### ISSUE THREAD

**Issue by kotx** [zloirock/core-js#922]
Currently with `fund` set to `false` in ~/.npmrc, I still see this message logged to stdout.
```
Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
```

**Comment by zloirock** [comment]
Hi @kotx! It's not related to `npm-fund` and `fund` flag. If you wanna disable this message - [you could find a way](https://github.com/zloirock/core-js/blob/master/packages/core-js/postinstall.js#L7-L11).
