### ISSUE TITLE
Support of AsyncFunction ?

### ISSUE THREAD

**Issue by bertho-zero** [zloirock/core-js#925]
I haven't seen any mention of `AsyncFunction` in core-js, are there any plans to create a polyfill or something like that?

https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/AsyncFunction

The following code works in the Chrome console but not with a babelified code, the result of `instanceof` is always true:

```js
const AsyncFunction = Object.getPrototypeOf(async () => {}).constructor;

async function asyncMethod() {}
function method() {}

asyncMethod instanceof AsyncFunction // true
method instanceof AsyncFunction // false, but true with babelified code

asyncMethod.constructor.name // should be "AsyncFunction", but "Function" with babelified code
```

I don't know if this is the role of core-js or babel, here is the corresponding issue on the babel repo: https://github.com/babel/babel/issues/8642

**Comment by zloirock** [comment]
It's not a work of `core-js`. It's a work of `babel` and / or `regenerator` and should be done on their side.

**Comment by zloirock** [comment]
Sorry, but I can't do anything here.
