### ISSUE TITLE
Improve documentation to show how to use newer "import" while on Node.JS 8

### ISSUE THREAD

**Issue by olignyf** [zloirock/core-js#927]
I want to use "import" in my Node.JS server-side programming but we are stuck with Node v8 which only supports "require". I presume it is possible to use **core-js** to write the newer style of import while using Node v8, without using experimental cmdline arguments and use core-js instead. However I couldn't figure it out from the documentation. Does what I am trying to achieve makes sense? If yes would it be possible to add how to do this in the documentation? Thanks!

**Comment by zloirock** [comment]
The actual `core-js` version is based on CommonJS, so you could use `require` instead of `import`. Documentations indicate that it's a CommonJS API. Feel free to add a PR that, you consider, could make the documentation better.

**Comment by olignyf** [comment]
Actually I want to use `import` instead of `require`. `import` is the newer statement only available more recent Node.JS versions.
I still don't know how to achieve this using `core-js`. Can you point to an example or external documentation, then I can figure it out and send a doc improvement PR if needed.

**Comment by zloirock** [comment]
`core-js` is about builtins, not about syntax. You should use a transpiler for that. `core-js` perfectly works with `babel` and you could find it in the readme.

**Comment by olignyf** [comment]
Is this the proper way https://github.com/olignyf/example-node-server
It seems babel/preset-env only uses `core-js-compat`.
The documention in core-js about babel seems to be axed toward browser target, not Node.JS and mention `import 'core-js/stable';` as the way to go. Not clear how to use it from an older Node.JS version. Would the example above `example-node-server` be the way you recommend?

**Comment by zloirock** [comment]
As an option.
