### ISSUE TITLE
can copyright be added only once? memory leaks occur when rendered on the server side

### ISSUE THREAD

**Issue by SSoLMan** [zloirock/core-js#929]
https://github.com/zloirock/core-js/blob/master/packages/core-js/internals/shared.js
![core-js](https://user-images.githubusercontent.com/10937432/116203636-78ceec00-a76e-11eb-97e9-0c0e568399aa.png)

**Comment by zloirock** [comment]
Nope, it can't be added only once. At first, it's not a copyright, it's a list of used `core-js` instances with versions and modes, it's required for debugging and indication cases like this. If you have a such number of loaded `core-js` instances, most likely you have memory leaks also in other cases, so you doing something wrong. If you are pretty sure that this array is the only problem - you could reduce the size of this array manually.
