### ISSUE TITLE
react-native app hangs on splash screen with v3.11.1

### ISSUE THREAD

**Issue by webyonet** [zloirock/core-js#931]
app hangs on the splash screen with V3.11.1 on IOS
but there is no such problem in v3.11.0

OS: macOS Big Sur v11.3
RN: v0.63.4
Xcode: v12.5
iOS: v14.5

**Comment by zloirock** [comment]
I don't see any 3.11.1 changes that could even theoretically cause it in iOS 14.5. Could you add a reproducible example?

**Comment by webyonet** [comment]
I did not encounter this problem when I tried it in a blank project.
The project has too many module dependencies. (@react-native-firebase, @sentry/react-native, react-native-iap, react-native-onesignal, react-native-version-check, smartlook-react-native-wrapper, etc)
I reopen this issue when I find which module it conflicts with.

**Comment by reinhardholl** [comment]
@zloirock @webyonet we had the same issue. Dropping down to 3.11.0 solved it for us

**Comment by zloirock** [comment]
As an option, see #932.

**Comment by zloirock** [comment]
Try 3.11.2.
