### ISSUE TITLE
It is necessary to tell me you're looking for a job three times in my own terminal?

### ISSUE THREAD

**Issue by mad-briller** [zloirock/core-js#936]
Repeating something does not make it hold more credence and this does not make you look employable, let your work speak for itself.

![2021-05-13-161913_907x550_scrot](https://user-images.githubusercontent.com/28307684/118146922-fbaaa480-b406-11eb-98e8-3221d1291018.png)

**Comment by zloirock** [comment]
Yes, it's necessary. My work is used on more than half of internet sites and works perfectly - it's one of the main reasons why you could use ES6+ in your development process already many years, it's hard work that takes some hours each day, but without this message, `core-js` had 50$ MRR donations. I worked on `core-js` project for too many years absolutely for free and this message was added only when it was really required, but this message did not help. Now donations are 700$ MRR, so this message works at least somehow. However, it's not enough for proper maintenance of this project, the future of `core-js` is in question. If someone thinks that I should remove this message, he can go fuck it.

If you see this message more than one time for installation - it's a problem on your side, for example, blocked temp directory.

**Comment by mad-briller** [comment]
> If someone thinks that I should remove this message, he can go fuck it.

incredible, i'm sure you will get many job offers with this attitude.

**Comment by zloirock** [comment]
This approach is much better than hypocrisy. I have enough job offers, but still not enough opportunity to accept them. Banned.
