### ISSUE TITLE
How to add URLSearchParams polyfill in core-js 2.6.5 version?

### ISSUE THREAD

**Issue by kishoreio** [zloirock/core-js#937]
When i loaded my react project in IE11, in the console i got an error that URLSearchParams is undefined. I am using core-js 2.6.5 version and i need polyfill forURLSearchParams. What import statement should i include?

**Comment by zloirock** [comment]
`core-js@2` haven't `URLSearchParams` polyfill. It's an obsolete version that is no longer maintained and could cause problems. I'd recommend updating to the actual version of `core-js@3`.

**Comment by kishoreio** [comment]
How do i add support for URLSearchParams in core-js@3 ?

**Comment by zloirock** [comment]
It's available in `feateres` and `stable` namespaces. For example,
```js
import 'core-js/stable/url-search-params';
```

**Comment by kishoreio** [comment]
Thanks, also since i am beginner i don't know how to add features. So if i wanted to add any polyfill say for example weakMap then i need to import 'core-js/stable/weak-map'; right?

**Comment by zloirock** [comment]
Yep. If you don't wanna import each feature individually, you could use `import 'core-js/stable'`.

**Comment by kishoreio** [comment]
Got it, also do core-js have polyfill for The Intl APIs must be available in the runtime, and do not appear to be built-in. An Intl polyfill should be loaded ? I couldn't find it.

**Comment by zloirock** [comment]
At this moment, `core-js` haven't `Intl` polyfill. You could try this https://formatjs.io/docs/polyfills/

**Comment by kishoreio** [comment]
Thanks for answering my questions.
