### ISSUE TITLE
Support DOMException constructor

### ISSUE THREAD

**Issue by mcalmus** [zloirock/core-js#938]
It would be nice to have the DOMException constructor polyfilled for IE.

Found an imlementation in fetch.js https://github.com/github/fetch/blob/master/fetch.js#L487

**Comment by zloirock** [comment]
At this moment, `DOMException` is not in the scope of `core-js`. `core-js` provide only polyfills for ECMAScript features and closely related cross-platform features from web standards.  However, in the future, this position can be changed.

**Comment by mcalmus** [comment]
I thought that might be the case, but I thought having an issue here in case someone Googled it might be useful.

**Comment by zloirock** [comment]
Thanks, it could be useful in the future.

**Comment by zloirock** [comment]
It's required for #969 / #984, so let's reopen it.

**Comment by zloirock** [comment]
https://github.com/nodejs/node/blob/e46c680bf2b211bbd52cf959ca17ee98c7f657f5/lib/internal/per_context/domexception.js
