### ISSUE TITLE
features/global-this - works only when I generate publish but doesn't work in debug mode

### ISSUE THREAD

**Issue by Hafez70** [zloirock/core-js#939]
Hi ! I have created React js app
I used   "core-js": "^3.13.1", in my dependencies scope in package.json
and imported in my index.js this line : 
import 'core-js/features/global-this';

(I had issue with globalThis in ios 11.4 and before that version)
when I generate  production Publish it works fine
but when I run my project in debug mode (VS.2019) with iis-Express, my ios Emulator still return the globalThis Error
"what is wrong with my usage of this package ?"
I want to use it in debug mode too.
Thank you

**Comment by zloirock** [comment]
I don't use VS and I don't know how works VS debug mode. However, it **SHOULD** work after `import 'core-js/features/global-this'`. It would be better to ask team VS or your building tools. It's definitely not a `core-js` issue.
