### ISSUE TITLE
[Feature request] Polyfill for Element#replaceChildren

### ISSUE THREAD

**Issue by pbadenski** [zloirock/core-js#940]
See here: https://github.com/whatwg/dom/issues/478

As far as I understand this is an equivalent of:
```
element.innerHTML = "";
element.append(...children)
```

**Comment by zloirock** [comment]
Thanks for the proposal, but at this moment, `Element#replaceChildren` is out of the scope of `core-js`. `core-js` provide only polyfills for ECMAScript features and closely related cross-platform features from web standards. However, in the future, this position can be changed.

**Comment by danieltroger** [comment]
`element.innerHTML` doesn't work on `Document` which also got `Document.prototype.replaceChildren`.

I wrote this polyfill because I couldn't find any. The throwing behavior probably isn't accurate and it relies on a polyfill for https://developer.mozilla.org/en-US/docs/web/api/element/append (or native support) but here it is:

```
Document.prototype.replaceChildren ||= replaceChildren;
DocumentFragment.prototype.replaceChildren ||= replaceChildren;
Element.prototype.replaceChildren ||= replaceChildren;

function replaceChildren(...new_children) {
  const { childNodes } = this;
  while (childNodes.length) {
    childNodes[0].remove();
  }
  this.append(...new_children);
}
```

**Comment by hardhub** [comment]
> `element.innerHTML` doesn't work on `Document` which also got `Document.prototype.replaceChildren`.
> 
> I wrote this polyfill because I couldn't find any. The throwing behavior probably isn't accurate and it relies on a polyfill for https://developer.mozilla.org/en-US/docs/web/api/element/append (or native support) but here it is:
> 
> ```
> Document.prototype.replaceChildren ||= replaceChildren;
> DocumentFragment.prototype.replaceChildren ||= replaceChildren;
> Element.prototype.replaceChildren ||= replaceChildren;
> 
> function replaceChildren(...new_children) {
>   const { childNodes } = this;
>   while (childNodes.length) {
>     childNodes[0].remove();
>   }
>   this.append(...new_children);
> }
> ```

It does not make sense to use modern syntax for polyfills, this one is useless.

**Comment by danieltroger** [comment]
@hardhub you have to transpile it
