### ISSUE TITLE
3.15.0 breaks @firebase/firestore on older Tizen TV's

### ISSUE THREAD

**Issue by bfanger** [zloirock/core-js#947]
Upgrading to core-js@3.0.15  broke firebase (which depends on core-js@3.6.5)

```
@firebase/firestore: Firestore (8.6.8): FIRESTORE (8.6.8) INTERNAL ASSERTION FAILED: Unexpected state
```
Tested on platform:  

Samsung Tizen 3.0  (Chromium 47): `Mozilla/5.0 (SMART-TV; LINUX; Tizen 3.0) AppleWebKit/538.1 (KHTML, like Gecko) Version/3.0 TV Safari/538.1`

**Comment by zloirock** [comment]
Could you add a reproducible example? All tests passed in Chromium 47.

**Comment by zloirock** [comment]
Maybe it was related to #948, try `core-js@3.15.1`.

**Comment by bfanger** [comment]
Yes, i retested with 3.15.1 and that seems to have fixed the issue. 👍

(Thanks for the tip, creating a reproducible example would have been quite a chore,)
