### ISSUE TITLE
In corejs 3.15.0 version, regexp polifill does not work properly.

### ISSUE THREAD

**Issue by rever-whale** [zloirock/core-js#948]
Hi. In corejs 3.15.0 version, regexp polifill does not work properly.
I am using corejs polyfill in ie11.

A sample script is as follows.
```js
regExp = new RegExp(/^https?:\/\//i)
url = 'http://github.com'

result = url.match(regExp)
console.log(result) // null
```

In version 3.14, the following matching values ​​were found for the same script. 
```js
console.log(result) // [object Array] ["http://"]
```

My project's babel.config.js looks like this:

```js
module.exports = {
  presets: [
    ['@vue/cli-plugin-babel/preset', {
      targets: {ie: '11'},
      modules: 'cjs',
    }],
  ],
  plugins: [
    ['@babel/plugin-transform-runtime', {
      corejs: 3,
    }],
  ],
  env: {
    production: {
      plugins: [['transform-remove-console', {exclude: ['error']}]],
    },
  },
};
```

Version 3.15.0

**Comment by zloirock** [comment]
`@babel/plugin-transform-runtime` does not inject `RegExp` polyfills, they are available only in the global version.

**Comment by zloirock** [comment]
Could you add a reproducible example?

**Comment by rever-whale** [comment]
Sorry. There was a typo in example.
This is correct example.

```js
const regExp = new RegExp(/^https?:\/\//i)
const url = 'http://github.com'

const result = url.match(regExp)
console.log(result)
``` 

Thx.

**Comment by zloirock** [comment]
Ok, I was able to reproduce it, thanks.
