### ISSUE TITLE
Polyfill for `HTMLFormElement.requestSubmit()`

### ISSUE THREAD

**Issue by AlexWayfer** [zloirock/core-js#949]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit

I'm not sure that this is correct issue (feature request), but while there is not too wide support — why not.
![image](https://user-images.githubusercontent.com/6510020/123221311-7e7b5080-d4d7-11eb-9e7f-afda6ac34cbf.png)

**Comment by zloirock** [comment]
Thanks for the proposal, but at this moment, `HTMLFormElement#requestSubmit` is out of the scope of `core-js`. `core-js` provide only polyfills for ECMAScript features and closely related cross-platform features from web standards. However, in the future, this position can be changed.

**Comment by AlexWayfer** [comment]
> Thanks for the proposal, but at this moment, `HTMLFormElement#requestSubmit` is out of the scope of `core-js`. `core-js` provide only polyfills for ECMAScript features and closely related cross-platform features from web standards. However, in the future, this position can be changed.

What about [existing in `core-js` web standards](https://github.com/zloirock/core-js#web-standards)? Do you have plans to drop it? I like `NodeList.forEach` polyfill.

**Comment by zloirock** [comment]
> ...and closely related cross-platform features from web standards

Like iterators on DOM collections, it's a full equal of the `Array` method.

**Comment by AlexWayfer** [comment]
Hm, OK, as you say, thank you.
