### ISSUE TITLE
Some minify plugins have a spacing bugs.

### ISSUE THREAD

**Issue by demonguyj** [zloirock/core-js#951]
I used to using new Set(), but some environment have remove spacing bug.

- internal-metadata.js
var setMetadata = function (it) {
  defineProperty(it, METADATA, { value: {
    objectID: 'O' + ++id, // object ID
    weakData: {}          // weak collections IDs
  } });
};

- to be
var setMetadata = function (it) {
  defineProperty(it, METADATA, { value: {
    objectID: 'O'+++id, // object ID.                           <----- plus spacing remove
    weakData: {}          // weak collections IDs
  } });
};

It's not normal environment, but I hope resolve this issue.

If I can't fixed remove spacing bugs, How can I do this?

Please help.

**Comment by zloirock** [comment]
What plugins and environments?

**Comment by demonguyj** [comment]
I think my company's custom minify tools.
It is remove all spacing.

**Comment by zloirock** [comment]
It should be fixed on the side of this tool - too many other cases will be broken if just remove all spaces. Operations like this should be done by modification AST.

**Comment by demonguyj** [comment]
I knew problem. I'll fix custom tools.
But 

-as is
objectID: 'O' + ++id, // object ID

-to be 
objectID: 'O' + id++, // object ID

will helpful for other case, I think... may be....

**Comment by zloirock** [comment]
Ok, I'll accept this PR.

**Comment by demonguyj** [comment]
Thank you!! :) 👍
