### ISSUE TITLE
An error occurs when use Promise

### ISSUE THREAD

**Issue by zedream** [zloirock/core-js#957]
![image](https://user-images.githubusercontent.com/45782249/124723224-6545bb80-df3d-11eb-9c7e-f171cfd914ed.png)
![image](https://user-images.githubusercontent.com/45782249/124723436-a4740c80-df3d-11eb-8130-c440680e9d83.png)

I'm sure I have core-js installed
node version： 12.17.0（32-bit）
npm version: 6.14.13

help me~ qaq

**Comment by zloirock** [comment]
It looks like a problem with your bundling process or with your `node_modules`. All modules unresolved in your project [exists](https://unpkg.com/core-js@3.15.2/internals/export.js). Try to reinstall your dependencies or check your bundler config.

**Comment by zedream** [comment]
I have reinstalled the dependencies, but it still doesn't work
This is my webpack.config
![image](https://user-images.githubusercontent.com/45782249/124732653-fb7ddf80-df45-11eb-90f1-f8e199fde5b8.png)
@zloirock
