### ISSUE TITLE
Using Symbol under PhantomJS results in 'RangeError: Maximum call stack size exceeded.' error

### ISSUE THREAD

**Issue by ilyaa1** [zloirock/core-js#96]
I'm trying to run Karma tests with Babel (browserify or webpack, doesn't make a difference). PhantomJS version 1.9.8, Windows 7.

Running the same test in Chrome works fine.

Here's the error:

```
RangeError: Maximum call stack size exceeded. in C:/Users/ilyaa/AppData/Local/Temp/d8979572628301f98da8ac1f2c880bdb.browserify (line 511)
	    at C:/Users/ilyaa/AppData/Local/Temp/d8979572628301f98da8ac1f2c880bdb.browserify:511:0 <- node_modules/babel-runtime/node_modules/core-js/library/modules/es6.symbol.js:56:0
```

Let me know if you'd like the full setup.

**Comment by sebmck** [comment]
What do you mean by "using Symbol"? Can you post some code that triggers it?

**Comment by zloirock** [comment]
I can't reproduce it. Test case [passed](https://travis-ci.org/zloirock/core-js/builds/73482419) in PhantomJS 1.9.8 + Karma w/o any problem. Please, add example of problem code.

**Comment by ilyaa1** [comment]
@zloirock I've debugged the issue further, and was able to get the tests running, but don't understand at the moment why.

Here's the culprit (simplified):

```js
export default (function (global) {
    return class Logger {
        constructor () { /* ... */ }

        static instance () { /* singleton impl */ }

        static log (data) {
            /* the problem was HERE */
            Logger.instance.emit('update', data);
        }
    }
}(this));
```

Apparently, I can't reference the class from inside itself when it's "anonymous" like this.

When I separated class definition from return statement, the tests ran flawlessly:

```js
/* other code here */
export default (function (global) {
    class Logger {}

    return Logger;
}(this));
```

So the questions then are:

* Why does the first version fail, while the second one works?
* Why did this work in Chrome?
* Why did this fail on core-js Symbol shim?..

Or more broadly, is this a valid edge case?

**Comment by zloirock** [comment]
Are you use `runtime` transformer? `babel` ignores `node_modules` in your config?

**Comment by ilyaa1** [comment]
karma.conf.js

```js
module.exports = function karmaConfig (config) {
    config.set({
        basePath: './',
        frameworks: ['jasmine', 'jasmine-matchers', 'browserify'],
        files: [
            'logger.spec.js'
        ],
        exclude: [],
        preprocessors: {
            'logger.spec.js': ['browserify']
        },
        reporters: ['spec'],
        port: 9876,
        colors: true,
        logLevel: config.LOG_DEBUG,
        autoWatch: false,
        singleRun: true,
        browsers: ['PhantomJS'],
        browserify: {
            debug: true,
            watch: true,
            transform: [['babelify', { 'stage': 0, optional: ['runtime'] }]]
        }
    });
};
```

**Comment by zloirock** [comment]
Try add `ignore: /node_modules/` to `babelify` config.
