### ISSUE TITLE
Cannot find module core-js-compat/data.json

### ISSUE THREAD

**Issue by ofiron01** [zloirock/core-js#962]
When using ^3.15.0 ( having this as a dependency of @babel/preset-env)
Getting this error:
Error: [BABEL]: Cannot find module 'core-js-compat/data.json' (While processing: ....../node_modules/@babel/preset-env/lib/index.js

Looks like data.json is not part of the package. If I roll back to 3.14.0 there's no issue.

**Comment by zloirock** [comment]
[It's available on NPM](https://unpkg.com/core-js-compat@3.15.2/data.json), so it's not a `core-js` issue. Try to reinstall your dependencies or clean the NPM cache.
