### ISSUE TITLE
`URLSearchParams` passed to `Request` does not set the correct body and headers

### ISSUE THREAD

**Issue by romainmenke** [zloirock/core-js#965]
This is essentially the same issue as : https://github.com/zloirock/core-js/issues/674

A similar wrapper for `Request` might resolve this.
`Request` being a constructor whereas `fetch` is just a function might complicate things :/

see : https://github.com/mrhenry/web-tests/issues/171

(maybe this should not be fixed here, that is also fine!)

**Comment by zloirock** [comment]
Could you add a PR?

**Comment by romainmenke** [comment]
I have some time this weekend and will give it a shot!
Thank you for the quick response :)

**Comment by romainmenke** [comment]
Still not sure about patching `Request` in `core-js`.
Having some non-ecma features in `core-js` complicates things and don't really want to expand that surface.

Hoping to resolve this through : https://github.com/Financial-Times/polyfill-library/pull/1077

**Comment by zloirock** [comment]
It should be solved by patching of `Request` since it should work with any implementation and bad support of `URLSearchParams` is not a reason to polyfill `fetch` / `Request`.

**Comment by romainmenke** [comment]
Thank you @zloirock 

Seeing the final code I don't think I would have gotten there smoothly :)
You are also right that this should be fixed for any fetch implementation.

**Comment by romainmenke** [comment]
Thank you fo the quick release.
First test results indicate that this is now working for a lot more browsers!
