### ISSUE TITLE
structuredClone

### ISSUE THREAD

**Issue by zloirock** [zloirock/core-js#969]
[`structuredClone` method now exposed in the HTML spec.](https://github.com/whatwg/html/pull/3414) It's not a part of ECMAScript, but it's a very useful cross-platform feature, so makes sense to add it to `core-js`. If someone wanna contribute something significant to `core-js` - it's a good chance.

**Comment by BasixKOR** [comment]
FYI, This is the algorithm used for structured clone [serialization](https://html.spec.whatwg.org/multipage/structured-data.html#structuredserializeinternal) and [deserialization](https://html.spec.whatwg.org/multipage/structured-data.html#structureddeserialize).

And can I get a chance to implement this? Not very familar with core-js codebase but I really wanna give it a try :)

**Comment by zloirock** [comment]
@BasixKOR sure. Ask me if you will have any questions.

**Comment by petamoriken** [comment]
I made a list of `Serializable`s and `Transferable`s from WebIDL. I hope this helps :)

https://gist.github.com/petamoriken/3802602b8e93d89e5b4c21e36683cadb#gistcomment-3899514

**Comment by petamoriken** [comment]
The next release of Node.js (v17.0.0) will include `structuredClone` and `DOMException`.
https://github.com/nodejs/node/pull/40119

I think it would be nice to add support for `DOMException`.
related: https://github.com/zloirock/core-js/issues/938

**Comment by zloirock** [comment]
@petamoriken thanks! However, I'm not sure that the implementation of the transferable behavior is possible in most cases.

**Comment by BasixKOR** [comment]
The ongoing implementation of `structuredClone` uses DOMException if it's available, and fallbacks to plain Error if there isn't. I guess the support table should be updated to reflect the support status of Deno and Node.js.

**Comment by zloirock** [comment]
https://github.com/whatwg/html/pull/5749
