### ISSUE TITLE
es6 promise + facebook sdk

### ISSUE THREAD

**Issue by yonatanmn** [zloirock/core-js#97]
When using `Promise.then()` (I think that's what triggers the error), fb sdk starts spamming my console.
I think  ([according to this](http://stackoverflow.com/a/17930587/4391952)) that the problem is with this code:

```javascript
//$.task.js
...else if(global.addEventListener && isFunction(global.postMessage) && !global.importScripts){
    defer = function(id){
      global.postMessage(id, '*');
    };
    global.addEventListener('message', listner, false);
...
```
fb sdk is  listening to this, and warns:
`received message of type number from http://localhost:8000, expected a string`
(note: this is not due to localhost, and happens also with my real server)

According to MDN reference first argument of the postMessage method can be of any type. Still, Prior to Gecko 6.0 (Firefox 6.0 / Thunderbird 6.0 / SeaMonkey 2.3), the message parameter **must be a string**. ([that's what he says](http://stackoverflow.com/a/17930587/4391952))

I not sure if this is actually a FB bug or not, but since they haven't fixed it ([since 2012](http://stackoverflow.com/q/11675944/4391952)), and their widely usage, I guess it might be a good idea to fix this here.

**Comment by zloirock** [comment]
Looks like it was fixed after #95 (includes conversion key to string for `postMessage`). I'll publish new version in near time.
