### ISSUE TITLE
WSH + core-js@3.16.1 : String.prototype.split cannot expect accurate works.

### ISSUE THREAD

**Issue by gnh1201** [zloirock/core-js#971]
This happens sometimes. This occurs when split() has been run before (For example, in the loop).

```javascript
var s = "monkey:red:apple:delicious:banana:long:train:fast:airplane:high:everest:sharp:seringue:painful";
s.split(':');
["red", "apple", "delicious", "banana", "long", "train", "fast", "airplane", "high", "everest", "sharp", "seringue", "painful"]
// Loss of the first element ​"monkey"
```

```javascript
var s = "a=1=b=2=c=3";
s.split('=');
["a=1=b=2=c=3"]
// Array returned but not split.
```

WSH is based on JScript, so it may be related to the issue. #741 #751

Only core-js were used without any other polyfill libraries.

**Comment by zloirock** [comment]
Now I haven't a Windows machine to check it, feel free to propose a fix. #741 / #751 were fixed.

**Comment by zloirock** [comment]
Also, could you provide info about a version of Windows / WSH?

**Comment by gnh1201** [comment]
Version: Windows 10, WSH 5.812

There is no problem at this time. If the same problem occurs again, I will reopen the issue.
