### ISSUE TITLE
RegExp syntax error in IE when using Google Closure Compiler

### ISSUE THREAD

**Issue by Grundik** [zloirock/core-js#972]
There are several places in code, where are workarounds for IE misunderstanding of some regexp flags:
* internals/regexp-sticky-helpers.js for flag 'y';
* internals/regexp-unsupported-dot-all.js for flag 's';
* internals/regexp-unsupported-ncg.js for flag 'g'.

Workarounds are like:
```javascript
// babel-minify transpiles RegExp('a', 'y') -> /a/y and it causes SyntaxError,
var RE = function (s, f) {
  return RegExp(s, f);
};

exports.UNSUPPORTED_Y = fails(function () {
  var re = RE('a', 'y');
  re.lastIndex = 2;
  return re.exec('abcd') != null;
});
```

and
```javascript
module.exports = fails(function () {
  // babel-minify transpiles RegExp('.', 's') -> /./s and it causes SyntaxError
  var re = RegExp('.', (typeof '').charAt(0));
  return !(re.dotAll && re.exec('\n') && re.flags === 's');
});
```

That could work fine with Babel, but Google Closure Compiler cannot be fooled like that. It understands such tricks, and still compiles code into failing regexps.

That could be prevented by using "@noinline" flag, like this:
```javascript
// babel-minify transpiles RegExp('a', 'y') -> /a/y and it causes SyntaxError,
/** @noinline */
var RE = function (s, f) {
  return RegExp(s, f);
};
```
in all 3 places.

**Comment by zloirock** [comment]
Thanks for the issue. However, such directives-comments will not work if you will pass already minified `core-js` with removed comments to Closure Compiler - that confuses me.

**Comment by Grundik** [comment]
Yes, thats a small problem. But if one uses google closure compiler, there are no point to compile minified files. Its better to use source files, to get useful source maps.

**Comment by zloirock** [comment]
Could you try to add
```js
var RegExp = require('../internals/global').RegExp;
```
at the top of those files?

**Comment by Grundik** [comment]
Yes, that works too, compiles into
```javascript
var d=a(17).RegExp;b.UNSUPPORTED_Y=c(function(){var e=d("a","y"); .... }
```
with SIMPLE compilation level.

**Comment by moronesyesenia** [comment]
var RegExp = require('../internals/global').RegExp;
