### ISSUE TITLE
this is a bug? 

### ISSUE THREAD

**Issue by richchen** [zloirock/core-js#974]
when i define a 'finally' function on other function's prototype, why dist code includes "core-js/modules/es.promise.finally.js",
"core-js/modules/es.promise.js". 

ex:

![image](https://user-images.githubusercontent.com/20663807/130170729-0a1f1ce6-a651-46a1-896b-ec37fe71f100.png)

**Comment by zloirock** [comment]
It's not the correct place for this issue. Please, open it here: https://github.com/babel/babel-polyfills. I think - yes, plugins could be improved for ignoring this case, but it's not a very simple task since `Promise.prototype.finally = something` can't be ignored.
