### ISSUE TITLE
Uncaught TypeError: (0 , j.__extends) is not a function at main.js:1

### ISSUE THREAD

**Issue by adhivenkatesh** [zloirock/core-js#977]
i was getting error for uncaught could not find module error for the TSLIB after adding ("paths": {
      "tslib" : ["node_modules/tslib/tslib.d.ts"]
    },)
 in tsconfig.json getting below error  **solution required.**

Uncaught TypeError: (0 , j.__extends) is not a function
    at main.js:1
    at Object.39643 (main.js:1)
    at r (runtime.js:1)
    at Object.27458 (main.js:1)
    at r (runtime.js:1)
    at Object.53604 (main.js:1)
    at r (runtime.js:1)
    at Module.70907 (main.js:1)
    at r (runtime.js:1)
    at Module.61116 (main.js:1)

**Comment by zloirock** [comment]
How it's related to `core-js`?

**Comment by adhivenkatesh** [comment]
Thanks Zloirock  for your response , how to solve this any idea its runetime error while running angular (versiion 12 ) application

**Comment by adhivenkatesh** [comment]
> How it's related to `core-js`?

how your pointing its related to core-js ? if you get any idea or solution please share ASAP. i have googled not getting solution.
Thanks.

**Comment by zloirock** [comment]
It's a `core-js` repo for issues with `core-js` package. I don't see here anything related to `core-js` and I have no ideas about the reason of this issue.

**Comment by adhivenkatesh** [comment]
ok Thanks    zloirock
