### ISSUE TITLE
`es.string.replace-all` not being polyfilled in Node v14 LTS

### ISSUE THREAD

**Issue by joealden** [zloirock/core-js#978]
From looking at https://node.green/#ES2021-features--String-prototype-replaceAll, `string.prototype.replaceAll` is not supported in the latest version of the current LTS release (`14.17.x`), meaning that I believe `core-js` should polyfill this when using `@babel/preset-env` with a `targets` option of `{ node: "14.15.0" }` and a `corejs` option of `3.16.2`? From my testing, this is currently not the case. Please let me know if you cannot reproduce this yourself, and I'll try to provide a minimal case.

I believe these two sections of code are relevant to this problem:

https://github.com/zloirock/core-js/blob/4e72728fa1d8d23c97e6fe015078a4ba71617f04/packages/core-js-compat/src/data.mjs#L1047-L1051

https://github.com/zloirock/core-js/blob/4e72728fa1d8d23c97e6fe015078a4ba71617f04/packages/core-js-compat/src/mapping.mjs#L54-L55

As `85` isn't defined in the `ChromeToNode` mapping, I'm wondering what happens in this case? Does it (or is it supposed to) interpolate between the values that are defined for values that are not defined, meaning that `85` should map to `15.0` in this case? If not, then I guess to resolve this problem, we'd need to define an `85` mapping?

**Comment by zloirock** [comment]
On `core-js` side all fine. It's a `babel` issue. Seems they should update built-ins definitions. They find the same problem an hour ago https://github.com/babel/website/pull/2569#issuecomment-904788037, https://github.com/babel/babel/issues/13701.

Please, report it to https://github.com/babel/babel-polyfills.

You could try to set `proposals: true` option as a temporal fix - most likely it will help.
