### ISSUE TITLE
Function.prototype.name polyfill fails on minified code

### ISSUE THREAD

**Issue by amok** [zloirock/core-js#979]
If function body is minified (so `Function.prototype.toString` returns it as is), `nameRE` regexp match specified in [es.function.name.js](https://github.com/zloirock/core-js/blob/ce52fdc735c5c809c9e85b2072f92d41b5a3885a/packages/core-js/modules/es.function.name.js) returns null, so the polyfill throws trying to access 1 element of the regexp match result.

https://github.com/zloirock/core-js/blob/ce52fdc735c5c809c9e85b2072f92d41b5a3885a/packages/core-js/modules/es.function.name.js#L5-L22

Example of a function:

```js
function(e,t){return e+t;}
```

![image](https://user-images.githubusercontent.com/1369559/131661751-e86aa576-90f6-4343-832a-64704e6a8c3c.png)

**Comment by zloirock** [comment]
Yes, but I can't understand what confuses you. When the regex throws, the returned result is an empty string and it's the correct name for this function.
