### ISSUE TITLE
library/modules/es6.object.to-string.js is empty

### ISSUE THREAD

**Issue by miherlosev** [zloirock/core-js#98]
I'm using babel-runtime and webmake.
My code contains Promise calls.
When bundling client scripts, webmake is getting the required javascript files from babel-runtime\node_modules\core-js.

The result code:
"promise.js": function (exports, module, require) {
     
    require('../modules/es6.object.to-string');
     
    require('../modules/es6.string.iterator');
     
    require('../modules/web.dom.iterable');
     
    require('../modules/es6.promise');
     
    module.exports = require('../modules/$.core').Promise;
    }
}

The instruction 'require('../modules/es6.object.to-string')' performs loading of the core-js\library\modules\es6.object.to-string.js module. However this file is empty. 
So, I get a javascript runtime error when executing the bundled file.
I see that the file https://github.com/zloirock/core-js/blob/master/library/modules/es6.object.to-string.js is really empty

**Comment by zloirock** [comment]
Yes, it should be empty in `library` version for prevent global pollution and should not cause error. I don't see any way how to polyfill `Object#toString` in `library` version. If you have an error - it have another reason.

**Comment by miherlosev** [comment]
1)Download sample - http://content.screencast.com/users/miherlosev/folders/TestCafe/media/3b62fe51-160b-4013-ad29-fadc059e6252/babel-runtime-core-js.zip?downloadOnly=true
2)Install node modules and run gulp task
3)inspect /processed/index.js
4)It contains strange code:
`"es6.object.to-string.js": function (exports, module, require) {
					[object Object]
				},`

5)Please check and say me if it is bug of babel transformer

**Comment by zloirock** [comment]
1. If you uses `babel-runtime` - add `"ignore": "node_modules"` to `.babelrc`, otherwise you will have circular dependencies.
2. Looks `modules-webmake` has a bug with empty modules, it's not  a `core-js` issue.

**Comment by medikoo** [comment]
> Looks like modules-webmake has a bug with empty modules, it's not an core-js issue.

I'm not aware of such issue. Requiring empty modules works fine. Still @miherlosev if you feel it's otherwise please prepare a simplest possible test case, and open issue in webmake project

**Comment by zloirock** [comment]
@medikoo simple add `"ignore": "node_modules"` to `.babelrc` in @miherlosev example and you will have only this problem.

**Comment by miherlosev** [comment]
Create issue - https://github.com/medikoo/modules-webmake/issues/52

**Comment by medikoo** [comment]
Thanks @miherlosev indeed there was an issue when also source maps were generated. It's fixed now and published as v0.3.40

**Comment by miherlosev** [comment]
Thanks
