### ISSUE TITLE
ignore reserved word in es3 ?

### ISSUE THREAD

**Issue by yukinotech** [zloirock/core-js#980]
in `/packages/core-js/modules/web.url.js` There is  a `char` . 

```
var parseIPv6 = function (input) {
  var address = [0, 0, 0, 0, 0, 0, 0, 0];
  var pieceIndex = 0;
  var compress = null;
  var pointer = 0;
  var value, length, numbersSeen, ipv4Piece, number, swaps, swap;

  // here , char
  var char = function () {
    return input.charAt(pointer);
  };

  if (char() == ':') {
    if (input.charAt(1) != ':') return;
    pointer += 2;
    pieceIndex++;
    compress = pieceIndex;
  }
  while (char()) {
    if (pieceIndex == 8) return;
    if (char() == ':') {
      if (compress !== null) return;
      pointer++;
```
However in  ES3 , `char` is  a  reserved word . 

And in cdn `https://unpkg.com/core-js-bundle@3.16.4/index.js` or `https://unpkg.com/core-js-bundle@3.16.4/minified.js`,
`char` is not be transformed to `_char` or other indetifer , which means the cdn polyfill might not work in ie6/ie7.

**Comment by zloirock** [comment]
It seems you are right, thanks.

**Comment by zloirock** [comment]
Strangely that ESLint does not see it, https://github.com/zloirock/core-js/blob/master/.eslintrc.js#L993 (till this week was used the default parser).

**Comment by zloirock** [comment]
The same https://github.com/zloirock/core-js/commit/4f4d95ee737372f2aa26ce2d10273a088f3d57f9
