### ISSUE TITLE
use corejs Reflect metadata in typescript

### ISSUE THREAD

**Issue by 2239559319** [zloirock/core-js#982]
I try to use reflect metadata in ts and corejs as polyfill, but there will be a type error: "Property'defineMetadata' does not exist on type'typeof Reflect'". How should I solve this problem

**Comment by zloirock** [comment]
How do you use `core-js`?

**Comment by 2239559319** [comment]
> How do you use `core-js`?

`import 'core-js/proposals/reflect-metadata';` In the entry file

**Comment by zloirock** [comment]
`core-js` does not contain type definitions, https://github.com/zloirock/core-js/issues/568, you could try to use something like https://www.npmjs.com/package/@types/core-js, however, it's outdated.

**Comment by 2239559319** [comment]
> `core-js` does not contain types definitions, #568, you could try to use something like https://www.npmjs.com/package/@types/core-js, however, it's outdated.

I get it, the types file is for corejs2, thanks
