### ISSUE TITLE
Promise.finally is undefined

### ISSUE THREAD

**Issue by luhc228** [zloirock/core-js#983]
When I set the `"useBuiltIns": "entry"`, the Promise.prototype.finally is undefined. When I set the `"useBuiltIns": "usage"`，I can use the promise.prototype.finally. 

how to solve this problem.

related issues:
- https://github.com/storybookjs/react-native/issues/20

**Comment by zloirock** [comment]
When you use `"useBuiltIns": "entry"`, you should import required modules by yourself, for example, use `import 'core-js/stable'`, and `preset-env` will optimize it.

**Comment by zloirock** [comment]
In this case, it's a Babel issue, you could report it here https://github.com/babel/babel-polyfills/

**Comment by luhc228** [comment]
It's my problem. Thank you.
