### ISSUE TITLE
`forEach` is applied to all DOM Iterators

### ISSUE THREAD

**Issue by moorejs** [zloirock/core-js#988]
The [README](https://github.com/zloirock/core-js#iterable-dom-collections) and [compatibility test](https://github.com/zloirock/core-js/blob/master/tests/compat/tests.js#L1513-L1516) say that `'web.dom-collections.for-each'` is only for `NodeList` and `DOMTokenList`.

The [implementation](https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/web.dom-collections.for-each.js#L16) applies it to all [`dom-iterables`](https://github.com/zloirock/core-js/blob/master/packages/core-js/internals/dom-iterables.js) which includes much more than just those two.

**Comment by zloirock** [comment]
Yes, you are right, thanks.
