### ISSUE TITLE
SIMD Polyfill

### ISSUE THREAD

**Issue by thomasfoster96** [zloirock/core-js#99]
Obviously the performance benefits of SIMD can't be replicated in this library, but there is a fairly good polyfill available at [ecmascript_simd](https://github.com/tc39/ecmascript_simd/blob/master/src/ecmascript_simd.js). 

I completely understand if this isn't worth doing, but this would save a lot of feature detection at the cost of performance when SIMD isn't available (it is in Firefox nightly only at the moment). A bit like how `TypedArray`s used to be polyfilled with plain old `Array`s.

**Comment by zloirock** [comment]
I think, it will be added in the future, but now we have some problems. It was already mentioned [here](https://github.com/zloirock/core-js#missing-polyfills).
* Typed arrays not available in old browsers, [need add typed arrays polyfill before](https://github.com/zloirock/core-js/issues/90).
* It will add ~half of `core-js` size. Possible add it as optional feature.

**Comment by thomasfoster96** [comment]
*~half?* Wowsers. Sorry, I didn't see that in the README. 

Optional feature sounds like a good idea. Making ES3 support (which I gather is the reason for no TypedArrays polyfill?) optional is another option.

**Comment by zloirock** [comment]
[`SIMD` was moved to inactive proposals list](https://github.com/tc39/proposals/commit/35e0032d8b1cb5249a80629eabdd2c444acdea6a#diff-127dbd58d270d0e11d139253362f545c), so I'm closing it before the resumption of work on this proposal.
