### ISSUE TITLE
core-js/es/symbol/to-primitive doesn't work as expected

### ISSUE THREAD

**Issue by danieltroger** [zloirock/core-js#994]
Input code:
```
const my_obj = {
  [Symbol.toPrimitive](hint) {
    if (hint === "number") {
      return 5;
    } else {
      return "five";
    }
  },
};

console.log(`10 = ${my_obj * 2}, "five" = "${my_obj}"`);
```

Expected output: `10 = 10, "five" = "five"`
Actual output in IE11: `10 = NaN, "five" = "[object Object]"`

I have tried including `import "core-js/es/symbol/to-primitive";` as well as including whole core-js `import "core-js";`

I'm using babel with target set to `ie 11`.
Is this a babel issue? What's the point of core-js's to-primitive polyfill if this example isn't supported?

**Comment by zloirock** [comment]
Yes, now it does not work. This case is at first a Babel issue - that requires an extra transform that should wrap almost all operators. But this transform will cause a HUGE slowdown. 5-7 years ago I proposed to add such transform to Babel and make it optional, but it's still not implemented. `core-js` provide a well-known symbol for this transform - each transpiler could choose to implement this behavior or not. Also, some `core-js` polyfills support `@@toPrimitive` behavior.
