### ISSUE TITLE
Cross-realm well-known symbols

### ISSUE THREAD

**Issue by anilanar** [zloirock/core-js#998]
`WellKnownSymbolsStore` is not shared across realms, but `Symbol.for` is shared:

https://jakearchibald.com/2017/arrays-symbols-realms/

Reproduction:

1) Load Symbol.observable polyfill in a modern/recent browser.
2) Create same domain iframe and load another copy of Symbol.observable polyfill in the iframe.
3) Compare `Symbol.observable` against `Symbol.observable` from the iframe, they won't be equal.

On the other hand, `window.Symbol.for('observable') === iframe.window.Symbol.for('observable')` so `Symbol.for` works across realms.

**Comment by zloirock** [comment]
Thanks for the issue. I thought about it. But someone could use `Symbol.for('observable')` for anything else and it will unexpectedly make objects with this property observable. However, sure, it could be solved by using something like prefixes.
